#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_GRAPH_ELEMENT_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_GRAPH_ELEMENT_UTILS_EXPORT_H

#include "googlesql/common/graph_element_utils.h"
// include sources
#include "googlesql/common/graph_element_utils.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/json_value/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/json/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#endif
