#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_DIAGNOSTIC_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_DIAGNOSTIC_EXPORT_H

#include "googlesql/legacy_zetasql/parser/macros/diagnostic.h"
// include sources
#include "googlesql/legacy_zetasql/parser/macros/diagnostic.cc"
// include dependencies
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
