#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_MATCH_RECOGNIZE_COMPILED_PATTERN_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_MATCH_RECOGNIZE_COMPILED_PATTERN_EXPORT_H

#include "googlesql/public/functions/match_recognize/compiled_pattern.h"
// include sources
#include "googlesql/public/functions/match_recognize/compiled_pattern.cc"
// include dependencies
#include "go-googlesql/public/functions/match_recognize/compiled_pattern_cc_proto/export.inc"
#include "go-googlesql/public/functions/match_recognize/match_partition/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/match_recognize/compiled_nfa/export.inc"
#include "go-googlesql/common/match_recognize/nfa/export.inc"
#include "go-googlesql/common/match_recognize/nfa_builder/export.inc"
#include "go-googlesql/common/match_recognize/nfa_match_partition/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
