#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_CONDITIONS_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_CONDITIONS_EXPORT_H

#include "absl/log/internal/conditions.h"
// include sources
#include "absl/log/internal/conditions.cc"
// include dependencies
#include "go-absl/log/go_internal/voidify/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
