#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PARSER_MACROS_TOKEN_PROVIDER_BASE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PARSER_MACROS_TOKEN_PROVIDER_BASE_EXPORT_H

#include "googlesql/legacy_zetasql/parser/macros/token_provider_base.h"
// include sources
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/parser/token_with_location/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
