#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_STRING_NUMBERS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_STRING_NUMBERS_EXPORT_H

#include "zetasql/base/string_numbers.h"
// include sources
#include "zetasql/base/string_numbers.cc"
// include dependencies
#include "go-zetasql/base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
