#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_NET_PUBLIC_SUFFIX_OSS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_NET_PUBLIC_SUFFIX_OSS_EXPORT_H

#include "googlesql/legacy_zetasql/base/net/public_suffix_oss.h"
// include sources
#include "googlesql/legacy_zetasql/base/net/public_suffix_list_data.h"
#include "googlesql/legacy_zetasql/base/net/public_suffix_oss.cc"
// include dependencies
#include "go-zetasql/base/logging/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-icu/icu/export.inc"

#endif
