#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TM_LEXER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TM_LEXER_EXPORT_H

#include "googlesql/parser/tm_lexer.h"
#include "googlesql/parser/tm_token.h"
// include sources
#include "googlesql/parser/tm_lexer.cc"
// include dependencies
#include "go-googlesql/parser/parser_mode/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
