#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_MULTIWAY_UNNEST_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_MULTIWAY_UNNEST_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/multiway_unnest_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/multiway_unnest_rewriter.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/function_headers/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/array_zip_mode_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/column_factory/export.inc"
#include "go-zetasql/resolved_ast/make_node_vector/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-zetasql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
