#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SQL_TVF_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SQL_TVF_EXPORT_H

#include "googlesql/public/sql_tvf.h"
// include sources
#include "googlesql/public/sql_tvf.cc"
// include dependencies
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"

#endif
