#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_DEIDENTIFY_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_DEIDENTIFY_EXPORT_H

#include "zetasql/parser/deidentify.h"
// include sources
#include "zetasql/parser/deidentify.cc"
// include dependencies
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/builtin_function_options/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_resume_location/export.inc"
#include "go-zetasql/public/simple_catalog/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
