#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_BUILTIN_FUNCTION_INLINER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_BUILTIN_FUNCTION_INLINER_EXPORT_H

#include "googlesql/analyzer/rewriters/builtin_function_inliner.h"
// include sources
#include "googlesql/analyzer/rewriters/builtin_function_inliner.cc"
// include dependencies
#include "go-googlesql/analyzer/builtin_only_catalog/export.inc"
#include "go-googlesql/analyzer/substitute/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
