
#ifndef algorithms_algorithm_bind_cc
#define algorithms_algorithm_bind_cc

// switch namespace
#define differential_privacy algorithms_algorithm_differential_privacy
#define googlesql algorithms_algorithm_googlesql
#define googlesql_base algorithms_algorithm_googlesql_base
#define googlesql_bison_parser algorithms_algorithm_googlesql_bison_parser
#define re2 algorithms_algorithm_re2
#define AbslInternalSleepFor algorithms_algorithm_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_algorithm_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_algorithm_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_algorithm_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_algorithm_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_algorithm_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_algorithm_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_algorithm_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_algorithm_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_algorithm_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_algorithm_AbslInternalGetFileMappingHint
#define GoogleSqlalloc algorithms_algorithm_GoogleSqlalloc
#define GoogleSqlfree algorithms_algorithm_GoogleSqlfree
#define GoogleSqlrealloc algorithms_algorithm_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_algorithm_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream algorithms_algorithm_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_algorithm_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream algorithms_algorithm_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit algorithms_algorithm_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path algorithms_algorithm_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width algorithms_algorithm_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance algorithms_algorithm_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period algorithms_algorithm_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit algorithms_algorithm_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path algorithms_algorithm_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width algorithms_algorithm_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance algorithms_algorithm_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period algorithms_algorithm_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes algorithms_algorithm_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes algorithms_algorithm_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string algorithms_algorithm_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string algorithms_algorithm_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability algorithms_algorithm_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability algorithms_algorithm_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests algorithms_algorithm_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests algorithms_algorithm_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase algorithms_algorithm_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer algorithms_algorithm_GoogleSqlFlexLexer
#define UCaseMap algorithms_algorithm_UCaseMap

#define GO_EXPORT(def) export_algorithms_algorithm_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "algorithms/algorithm.h"
//#undef private

// include sources

// include dependencies
#include "go-algorithms/numerical-mechanisms/export.inc"
#include "go-algorithms/util/export.inc"
#include "go-base/logging/export.inc"
#include "go-proto/util-lib/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-base/status/export.inc"
#include "go-proto/confidence_interval_cc_proto/export.inc"
#include "go-proto/data_cc_proto/export.inc"
#include "go-proto/summary_cc_proto/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_algorithm_bind_cc */
