#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_CORD_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_CORD_EXPORT_H

#include "absl/strings/cord.h"
#include "absl/strings/cord_buffer.h"
// include sources
#include "absl/strings/cord.cc"
#include "absl/strings/cord_analysis.cc"
#include "absl/strings/cord_analysis.h"
#include "absl/strings/cord_buffer.cc"
// include dependencies
#include "go-absl/strings/cord_internal/export.inc"
#include "go-absl/strings/cordz_functions/export.inc"
#include "go-absl/strings/cordz_info/export.inc"
#include "go-absl/strings/cordz_statistics/export.inc"
#include "go-absl/strings/cordz_update_scope/export.inc"
#include "go-absl/strings/cordz_update_tracker/export.inc"
#include "go-absl/strings/internal/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/endian/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/container/fixed_array/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/crc/crc_cord_state/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/span/export.inc"

#endif
