#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_ERRORS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_ERRORS_EXPORT_H

#include "googlesql/legacy_zetasql/common/errors.h"
// include sources
#include "googlesql/legacy_zetasql/common/errors.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/proto/internal_error_location_cc_proto/export.inc"
#include "go-zetasql/public/deprecation_warning_cc_proto/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/error_location_cc_proto/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/span/export.inc"

#endif
