#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_JSON_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_JSON_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/functions/json.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/functions/json.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/internal_value/export.inc"
#include "go-googlesql/public/json_value/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/json/export.inc"
#include "go-googlesql/public/functions/json_format/export.inc"
#include "go-googlesql/public/functions/json_internal/export.inc"
#include "go-googlesql/public/functions/to_json/export.inc"
#include "go-googlesql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/reference_impl/evaluation/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
