#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_UNARY_FUNCTION_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_UNARY_FUNCTION_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/unary_function_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/unary_function_rewriter.cc"
// include dependencies
#include "go-googlesql/analyzer/rewriters/rewriter_interface/export.inc"
#include "go-googlesql/analyzer/substitute/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/builtin_function/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
