#ifndef INTERNAL_CCALL_GO_ABSL_BASE_MALLOC_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_BASE_MALLOC_INTERNAL_EXPORT_H

#include "absl/base/internal/direct_mmap.h"
#include "absl/base/internal/low_level_alloc.h"
// include sources
#include "absl/base/internal/low_level_alloc.cc"
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/dynamic_annotations/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#endif
