#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_FUNCTION_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_FUNCTION_UTILS_EXPORT_H

#include "googlesql/common/function_utils.h"
// include sources
#include "googlesql/common/function_utils.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
