#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_STRING_FORMAT_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_STRING_FORMAT_EXPORT_H

#include "googlesql/public/functions/string_format.h"
// include sources
#include "googlesql/public/functions/string_format.cc"
// include dependencies
#include "go-googlesql/public/functions/convert_proto/export.inc"
#include "go-googlesql/public/functions/format_max_output_width/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/utf_util/export.inc"
#include "go-googlesql/public/json_value/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-re2/re2/export.inc"
#include "go-icu/icu/export.inc"

#endif
