#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_CHECK_IMPL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_CHECK_IMPL_EXPORT_H

#include "absl/log/internal/check_impl.h"
// include sources
// include dependencies
#include "go-absl/log/go_internal/check_op/export.inc"
#include "go-absl/log/go_internal/conditions/export.inc"
#include "go-absl/log/go_internal/log_message/export.inc"
#include "go-absl/log/go_internal/strip/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
