#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_AST_NODE_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_AST_NODE_UTIL_EXPORT_H

#include "googlesql/parser/ast_node_util.h"
// include sources
#include "googlesql/parser/ast_node_util.cc"
// include dependencies
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
