#ifndef INTERNAL_CCALL_GO_ABSL_FUNCTIONAL_ANY_INVOCABLE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FUNCTIONAL_ANY_INVOCABLE_EXPORT_H

#include "absl/functional/any_invocable.h"
// include sources
#include "absl/functional/internal/any_invocable.h"
// include dependencies
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
