#ifndef INTERNAL_CCALL_GO_GOOGLESQL_SCRIPTING_ERROR_HELPERS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_SCRIPTING_ERROR_HELPERS_EXPORT_H

#include "googlesql/scripting/error_helpers.h"
// include sources
#include "googlesql/scripting/error_helpers.cc"
// include dependencies
#include "go-googlesql/scripting/script_segment/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/status_payload_utils/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/proto/script_exception_cc_proto/export.inc"
#include "go-googlesql/public/error_location_cc_proto/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
