#ifndef INTERNAL_CCALL_GO_GOOGLESQL_SCRIPTING_CONTROL_FLOW_GRAPH_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_SCRIPTING_CONTROL_FLOW_GRAPH_EXPORT_H

#include "googlesql/scripting/control_flow_graph.h"
// include sources
#include "googlesql/scripting/control_flow_graph.cc"
// include dependencies
#include "go-googlesql/scripting/script_segment/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
