#ifndef INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_CONTROL_FLOW_GRAPH_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_CONTROL_FLOW_GRAPH_EXPORT_H

#include "googlesql/scripting/control_flow_graph.h"
// include sources
#include "googlesql/scripting/control_flow_graph.cc"
// include dependencies
#include "go-zetasql/scripting/script_segment/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
