#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_TYPE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_TYPE_EXPORT_H

#include "zetasql/public/convert_type_to_proto.h"
#include "zetasql/public/type.h"
// Wire format proto defines google.protobuf extensions used by convert_type_to_proto.cc.
#include "go-zetasql/public/proto/wire_format_annotation_cc_proto/export.inc"
// include sources
#include "zetasql/public/convert_type_to_proto.cc"
// include dependencies
#include "go-zetasql/public/type_annotation_cc_proto/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-protobuf/protobuf/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
