#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_UPDATE_SCOPE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_UPDATE_SCOPE_EXPORT_H

#include "absl/strings/internal/cordz_update_scope.h"
// include sources
// include dependencies
#include "go-absl/strings/cord_internal/export.inc"
#include "go-absl/strings/cordz_info/export.inc"
#include "go-absl/strings/cordz_update_tracker/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
