#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PARSER_TOKEN_WITH_LOCATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PARSER_TOKEN_WITH_LOCATION_EXPORT_H

#include "googlesql/legacy_zetasql/parser/token_with_location.h"
// include sources
#include "googlesql/legacy_zetasql/parser/token_with_location.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/parser/token_codes/export.inc"
#include "go-zetasql/public/error_location_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
