#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_MATCH_RECOGNIZE_MATCH_PARTITION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_MATCH_RECOGNIZE_MATCH_PARTITION_EXPORT_H

#include "googlesql/public/functions/match_recognize/match_partition.h"
// include sources
// include dependencies
#include "go-zetasql/public/value/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
