
#ifndef zetasql_parser_tm_parser_bind_cc
#define zetasql_parser_tm_parser_bind_cc

// switch namespace
#define absl zetasql_parser_tm_parser_absl
#define differential_privacy zetasql_parser_tm_parser_differential_privacy
#define google zetasql_parser_tm_parser_google
#define zetasql zetasql_parser_tm_parser_zetasql
#define zetasql_base zetasql_parser_tm_parser_zetasql_base
#define zetasql_bison_parser zetasql_parser_tm_parser_zetasql_bison_parser
#define re2 zetasql_parser_tm_parser_re2
#define AbslInternalSleepFor zetasql_parser_tm_parser_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError zetasql_parser_tm_parser_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield zetasql_parser_tm_parser_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost zetasql_parser_tm_parser_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait zetasql_parser_tm_parser_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything zetasql_parser_tm_parser_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay zetasql_parser_tm_parser_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake zetasql_parser_tm_parser_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin zetasql_parser_tm_parser_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd zetasql_parser_tm_parser_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint zetasql_parser_tm_parser_AbslInternalGetFileMappingHint
#define ZetaSqlalloc zetasql_parser_tm_parser_ZetaSqlalloc
#define ZetaSqlfree zetasql_parser_tm_parser_ZetaSqlfree
#define ZetaSqlrealloc zetasql_parser_tm_parser_ZetaSqlrealloc
#define FLAGS_nooutput_asc_explicitly zetasql_parser_tm_parser_FLAGS_nooutput_asc_explicitly
#define FLAGS_nozetasql_use_customized_flex_istream zetasql_parser_tm_parser_FLAGS_nozetasql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly zetasql_parser_tm_parser_FLAGS_output_asc_explicitly
#define FLAGS_zetasql_use_customized_flex_istream zetasql_parser_tm_parser_FLAGS_zetasql_use_customized_flex_istream
#define FLAGS_zetasql_type_factory_nesting_depth_limit zetasql_parser_tm_parser_FLAGS_zetasql_type_factory_nesting_depth_limit
#define FLAGS_zetasql_read_proto_field_optimized_path zetasql_parser_tm_parser_FLAGS_zetasql_read_proto_field_optimized_path
#define FLAGS_zetasql_format_max_output_width zetasql_parser_tm_parser_FLAGS_zetasql_format_max_output_width
#define FLAGS_zetasql_min_length_required_for_edit_distance zetasql_parser_tm_parser_FLAGS_zetasql_min_length_required_for_edit_distance
#define FLAGS_zetasql_simple_iterator_call_time_now_rows_period zetasql_parser_tm_parser_FLAGS_zetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_nozetasql_type_factory_nesting_depth_limit zetasql_parser_tm_parser_FLAGS_nozetasql_type_factory_nesting_depth_limit
#define FLAGS_nozetasql_read_proto_field_optimized_path zetasql_parser_tm_parser_FLAGS_nozetasql_read_proto_field_optimized_path
#define FLAGS_nozetasql_format_max_output_width zetasql_parser_tm_parser_FLAGS_nozetasql_format_max_output_width
#define FLAGS_nozetasql_min_length_required_for_edit_distance zetasql_parser_tm_parser_FLAGS_nozetasql_min_length_required_for_edit_distance
#define FLAGS_nozetasql_simple_iterator_call_time_now_rows_period zetasql_parser_tm_parser_FLAGS_nozetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_zetasql_enough_stack_bytes zetasql_parser_tm_parser_FLAGS_zetasql_enough_stack_bytes
#define FLAGS_nozetasql_enough_stack_bytes zetasql_parser_tm_parser_FLAGS_nozetasql_enough_stack_bytes
#define FLAGS_zetasql_canonicalize_signed_zero_to_string zetasql_parser_tm_parser_FLAGS_zetasql_canonicalize_signed_zero_to_string
#define FLAGS_nozetasql_canonicalize_signed_zero_to_string zetasql_parser_tm_parser_FLAGS_nozetasql_canonicalize_signed_zero_to_string
#define FLAGS_zetasql_default_error_message_stability zetasql_parser_tm_parser_FLAGS_zetasql_default_error_message_stability
#define FLAGS_nozetasql_default_error_message_stability zetasql_parser_tm_parser_FLAGS_nozetasql_default_error_message_stability
#define FLAGS_zetasql_redact_error_messages_for_tests zetasql_parser_tm_parser_FLAGS_zetasql_redact_error_messages_for_tests
#define FLAGS_nozetasql_redact_error_messages_for_tests zetasql_parser_tm_parser_FLAGS_nozetasql_redact_error_messages_for_tests
#define ZetaSqlFlexTokenizerBase zetasql_parser_tm_parser_ZetaSqlFlexTokenizerBase
#define ZetaSqlFlexLexer zetasql_parser_tm_parser_ZetaSqlFlexLexer
#define UCaseMap zetasql_parser_tm_parser_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto zetasql_parser_tm_parser_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto zetasql_parser_tm_parser_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto zetasql_parser_tm_parser_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto zetasql_parser_tm_parser_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto zetasql_parser_tm_parser_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto zetasql_parser_tm_parser_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto zetasql_parser_tm_parser_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto zetasql_parser_tm_parser_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto zetasql_parser_tm_parser_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto zetasql_parser_tm_parser_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto zetasql_parser_tm_parser_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto zetasql_parser_tm_parser_TableStruct_google_2ftype_2ftimeofday_2eproto
#define google_2frpc_2fstatus_2eproto zetasql_parser_tm_parser_google_2frpc_2fstatus_2eproto
#define descriptor_table_google_2frpc_2fstatus_2eproto zetasql_parser_tm_parser_descriptor_table_google_2frpc_2fstatus_2eproto
#define TableStruct_google_2frpc_2fstatus_2eproto zetasql_parser_tm_parser_TableStruct_google_2frpc_2fstatus_2eproto
#define zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define zetasql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto zetasql_parser_tm_parser_zetasql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define descriptor_table_zetasql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define TableStruct_zetasql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define zetasql_2fparser_2fparse_5ftree_2eproto zetasql_parser_tm_parser_zetasql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto
#define zetasql_2fparser_2fast_5fenums_2eproto zetasql_parser_tm_parser_zetasql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto
#define TableStruct_zetasql_2fparser_2fast_5fenums_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fparser_2fast_5fenums_2eproto
#define zetasql_2fproto_2foptions_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2foptions_2eproto
#define descriptor_table_zetasql_2fproto_2foptions_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2foptions_2eproto
#define TableStruct_zetasql_2fproto_2foptions_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2foptions_2eproto
#define zetasql_2fproto_2fsimple_5fcatalog_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define zetasql_2fproto_2ffunction_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2ffunction_2eproto
#define descriptor_table_zetasql_2fproto_2ffunction_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2ffunction_2eproto
#define TableStruct_zetasql_2fproto_2ffunction_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2ffunction_2eproto
#define zetasql_2fproto_2finternal_5ferror_5flocation_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define zetasql_2fproto_2fscript_5fexception_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2fscript_5fexception_2eproto
#define descriptor_table_zetasql_2fproto_2fscript_5fexception_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2fscript_5fexception_2eproto
#define TableStruct_zetasql_2fproto_2fscript_5fexception_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2fscript_5fexception_2eproto
#define zetasql_2fproto_2fsimple_5fproperty_5fgraph_2eproto zetasql_parser_tm_parser_zetasql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define descriptor_table_zetasql_2fproto_2fsimple_5fproperty_5fgraph_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define TableStruct_zetasql_2fproto_2fsimple_5fproperty_5fgraph_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define zetasql_2fpublic_2fbuiltin_5ffunction_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define zetasql_2fpublic_2fdeprecation_5fwarning_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define zetasql_2fpublic_2ffunction_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunction_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2ffunction_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunction_2eproto
#define zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define zetasql_2fpublic_2foptions_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2foptions_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2foptions_2eproto
#define TableStruct_zetasql_2fpublic_2foptions_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2foptions_2eproto
#define zetasql_2fpublic_2fsimple_5ftable_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define zetasql_2fpublic_2fsimple_5fconstant_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define zetasql_2fpublic_2fsimple_5fconnection_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconnection_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconnection_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define zetasql_2fpublic_2fsimple_5fmodel_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fmodel_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fmodel_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define zetasql_2fpublic_2fparse_5flocation_5frange_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define zetasql_2fpublic_2ftype_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ftype_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ftype_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ftype_2eproto
#define zetasql_2fpublic_2ftype_5fannotation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define zetasql_2fpublic_2fvalue_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fvalue_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fvalue_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fvalue_2eproto
#define zetasql_2fpublic_2ftype_5fparameters_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define zetasql_2fpublic_2fcollation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fcollation_2eproto
#define descriptor_table_zetasql_2fpublic_2fcollation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fcollation_2eproto
#define TableStruct_zetasql_2fpublic_2fcollation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fcollation_2eproto
#define zetasql_2fpublic_2ftype_5fmodifiers_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define zetasql_2fpublic_2fformatter_5foptions_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define zetasql_2fpublic_2ferror_5flocation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto
#define zetasql_2fpublic_2fannotation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fannotation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fannotation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fannotation_2eproto
#define zetasql_2fpublic_2fsimple_5fvalue_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define zetasql_2fpublic_2ffunctions_2fdatetime_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define zetasql_2fpublic_2fproto_2flogging_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto
#define zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto zetasql_parser_tm_parser_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto zetasql_parser_tm_parser_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto zetasql_parser_tm_parser_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto zetasql_parser_tm_parser_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_2eproto zetasql_parser_tm_parser_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define zetasql_2fresolved_5fast_2fserialization_2eproto zetasql_parser_tm_parser_zetasql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto
#define zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto zetasql_parser_tm_parser_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define zetasql_2fscripting_2fprocedure_5fextension_2eproto zetasql_parser_tm_parser_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define zetasql_2fscripting_2fvariable_2eproto zetasql_parser_tm_parser_zetasql_2fscripting_2fvariable_2eproto
#define descriptor_table_zetasql_2fscripting_2fvariable_2eproto zetasql_parser_tm_parser_descriptor_table_zetasql_2fscripting_2fvariable_2eproto
#define TableStruct_zetasql_2fscripting_2fvariable_2eproto zetasql_parser_tm_parser_TableStruct_zetasql_2fscripting_2fvariable_2eproto
#define proto_2fconfidence_2dinterval_2eproto zetasql_parser_tm_parser_proto_2fconfidence_2dinterval_2eproto
#define descriptor_table_proto_2fconfidence_2dinterval_2eproto zetasql_parser_tm_parser_descriptor_table_proto_2fconfidence_2dinterval_2eproto
#define TableStruct_proto_2fconfidence_2dinterval_2eproto zetasql_parser_tm_parser_TableStruct_proto_2fconfidence_2dinterval_2eproto
#define proto_2fdata_2eproto zetasql_parser_tm_parser_proto_2fdata_2eproto
#define descriptor_table_proto_2fdata_2eproto zetasql_parser_tm_parser_descriptor_table_proto_2fdata_2eproto
#define TableStruct_proto_2fdata_2eproto zetasql_parser_tm_parser_TableStruct_proto_2fdata_2eproto
#define proto_2fnumerical_2dmechanism_2eproto zetasql_parser_tm_parser_proto_2fnumerical_2dmechanism_2eproto
#define descriptor_table_proto_2fnumerical_2dmechanism_2eproto zetasql_parser_tm_parser_descriptor_table_proto_2fnumerical_2dmechanism_2eproto
#define TableStruct_proto_2fnumerical_2dmechanism_2eproto zetasql_parser_tm_parser_TableStruct_proto_2fnumerical_2dmechanism_2eproto
#define proto_2fsummary_2eproto zetasql_parser_tm_parser_proto_2fsummary_2eproto
#define descriptor_table_proto_2fsummary_2eproto zetasql_parser_tm_parser_descriptor_table_proto_2fsummary_2eproto
#define TableStruct_proto_2fsummary_2eproto zetasql_parser_tm_parser_TableStruct_proto_2fsummary_2eproto

#define GO_EXPORT(def) export_zetasql_parser_tm_parser_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "zetasql/parser/bison_parser.h"
#include "zetasql/parser/join_processor.h"
#include "zetasql/parser/parse_tree.h"
#include "zetasql/parser/parse_tree_decls.h"
#include "zetasql/parser/parse_tree_generated.h"
#include "zetasql/parser/parser_internal.h"
#include "zetasql/parser/parser_runtime_info.h"
#include "zetasql/parser/statement_properties.h"
#include "zetasql/parser/textmapper_lexer_adapter.h"
#include "zetasql/parser/tm_parser.h"
//#undef private

// include sources
#include "zetasql/parser/textmapper_lexer_adapter.cc"
#include "zetasql/parser/tm_parser.cc"

// include dependencies
#include "go-zetasql/parser/ast_enums_cc_proto/export.inc"
#include "go-zetasql/parser/bison_parser_generated_lib/export.inc"
#include "go-zetasql/parser/bison_parser_mode/export.inc"
#include "go-zetasql/parser/keywords/export.inc"
#include "go-zetasql/parser/lookahead_transformer/export.inc"
#include "go-zetasql/parser/parse_tree/export.inc"
#include "go-zetasql/parser/token/export.inc"
#include "go-zetasql/parser/token_codes/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/arena/export.inc"
#include "go-zetasql/base/arena_allocator/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/timer_util/export.inc"
#include "go-zetasql/parser/macros/macro_catalog/export.inc"
#include "go-zetasql/parser/macros/macro_expander/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/proto/logging_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* zetasql_parser_tm_parser_bind_cc */
