#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_FLAG_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_FLAG_INTERNAL_EXPORT_H

#include "absl/flags/internal/flag.h"
#include "absl/flags/internal/sequence_lock.h"
// include sources
#include "absl/flags/internal/flag.cc"
// include dependencies
#include "go-absl/flags/commandlineflag/export.inc"
#include "go-absl/flags/commandlineflag_internal/export.inc"
#include "go-absl/flags/config/export.inc"
#include "go-absl/flags/marshalling/export.inc"
#include "go-absl/flags/reflection/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/dynamic_annotations/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
