#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_CHECK_OP_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_CHECK_OP_EXPORT_H

#include "absl/log/internal/check_op.h"
// include sources
// include dependencies
#include "go-absl/log/go_internal/nullguard/export.inc"
#include "go-absl/log/go_internal/nullstream/export.inc"
#include "go-absl/log/go_internal/strip/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
