#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_RESOLVER_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_RESOLVER_UTIL_EXPORT_H

#include "googlesql/analyzer/resolver_util.h"
// include sources
#include "googlesql/analyzer/resolver_util.cc"
// include dependencies
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/types/type/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/types/span/export.inc"

#endif
