#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_COLLATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_COLLATOR_EXPORT_H

#include "googlesql/legacy_zetasql/public/collator.h"
// include sources
#include "googlesql/legacy_zetasql/public/collator.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/collator_lite/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-icu/icu/export.inc"
#include "go-icu/icu/export.inc"

#endif
