#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_GRAPH_ELEMENT_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_GRAPH_ELEMENT_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/common/graph_element_utils.h"
// include sources
#include "googlesql/legacy_zetasql/common/graph_element_utils.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/json_value/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/json/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#endif
