#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_EVALUATOR_REGISTRATION_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_EVALUATOR_REGISTRATION_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/common/evaluator_registration_utils.h"
// include sources
#include "googlesql/legacy_zetasql/common/evaluator_registration_utils.cc"
// include dependencies
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/collator/export.inc"
#include "go-googlesql/reference_impl/functions/register_all/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
