#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_NET_IPADDRESS_OSS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_NET_IPADDRESS_OSS_EXPORT_H

#include "googlesql/legacy_zetasql/base/net/ipaddress_oss.h"
// include sources
#include "googlesql/legacy_zetasql/base/net/ipaddress_oss.cc"
// include dependencies
#include "go-googlesql/base/endian/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
