#ifndef INTERNAL_CCALL_GO_ALGORITHMS_NUMERICAL_MECHANISMS_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_NUMERICAL_MECHANISMS_EXPORT_H

#include "algorithms/numerical-mechanisms.h"
// include sources
#include "algorithms/numerical-mechanisms.cc"
// include dependencies
#include "go-algorithms/distributions/export.inc"
#include "go-algorithms/rand/export.inc"
#include "go-algorithms/util/export.inc"
#include "go-algorithms/go_internal/gaussian-stddev-calculator/export.inc"
#include "go-base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-base/status/export.inc"
#include "go-proto/confidence_interval_cc_proto/export.inc"
#include "go-proto/numerical_mechanism_cc_proto/export.inc"

#endif
