#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PARSE_RESUME_LOCATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PARSE_RESUME_LOCATION_EXPORT_H

#include "googlesql/public/parse_resume_location.h"
// include sources
// include dependencies
#include "go-zetasql/public/parse_resume_location_cc_proto/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
