
#ifndef googlesql_parser_macros_flex_token_provider_bind_cc
#define googlesql_parser_macros_flex_token_provider_bind_cc

// Link-only bind.cc (no amalgamated .cc includes). Native implementations must come from prebuilt
// archives (e.g. libgooglesql.a) and match this package's exported bridge symbols.
// Enable per package via cclib.link_only_bind_packages in internal/cmd/generator/config.yaml.
// See docs/link-only-cgo-migration.md.
#define AbslInternalSleepFor googlesql_parser_macros_flex_token_provider_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_parser_macros_flex_token_provider_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_parser_macros_flex_token_provider_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_parser_macros_flex_token_provider_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_parser_macros_flex_token_provider_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_parser_macros_flex_token_provider_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_parser_macros_flex_token_provider_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_parser_macros_flex_token_provider_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_parser_macros_flex_token_provider_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_parser_macros_flex_token_provider_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_parser_macros_flex_token_provider_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_parser_macros_flex_token_provider_GoogleSqlalloc
#define GoogleSqlfree googlesql_parser_macros_flex_token_provider_GoogleSqlfree
#define GoogleSqlrealloc googlesql_parser_macros_flex_token_provider_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_parser_macros_flex_token_provider_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_parser_macros_flex_token_provider_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_parser_macros_flex_token_provider_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_parser_macros_flex_token_provider_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_parser_macros_flex_token_provider_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_parser_macros_flex_token_provider_GoogleSqlFlexLexer
#define UCaseMap googlesql_parser_macros_flex_token_provider_UCaseMap

#define GO_EXPORT(def) export_googlesql_parser_macros_flex_token_provider_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers (types only; no .cc bodies)
#include "googlesql/parser/macros/flex_token_provider.h"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_parser_macros_flex_token_provider_bind_cc */
