#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_FAILURE_SIGNAL_HANDLER_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_FAILURE_SIGNAL_HANDLER_EXPORT_H

#include "absl/debugging/failure_signal_handler.h"
// include sources
#include "absl/debugging/failure_signal_handler.cc"
// include dependencies
#include "go-absl/debugging/examine_stack/export.inc"
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#endif
