
#ifndef base_logging_bind_cc
#define base_logging_bind_cc

// Link-only bind.cc (no amalgamated .cc includes). Native implementations must come from prebuilt
// archives (e.g. libgooglesql.a) and match this package's exported bridge symbols.
// Enable per package via cclib.link_only_bind_packages in internal/cmd/generator/config.yaml.
// See docs/link-only-cgo-migration.md.
#define differential_privacy base_logging_differential_privacy
#define googlesql base_logging_googlesql
#define googlesql_base base_logging_googlesql_base
#define googlesql_bison_parser base_logging_googlesql_bison_parser
#define re2 base_logging_re2
#define AbslInternalSleepFor base_logging_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError base_logging_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield base_logging_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost base_logging_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait base_logging_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything base_logging_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay base_logging_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake base_logging_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin base_logging_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd base_logging_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint base_logging_AbslInternalGetFileMappingHint
#define GoogleSqlalloc base_logging_GoogleSqlalloc
#define GoogleSqlfree base_logging_GoogleSqlfree
#define GoogleSqlrealloc base_logging_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly base_logging_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream base_logging_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly base_logging_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream base_logging_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit base_logging_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path base_logging_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width base_logging_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance base_logging_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period base_logging_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit base_logging_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path base_logging_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width base_logging_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance base_logging_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period base_logging_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes base_logging_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes base_logging_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string base_logging_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string base_logging_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability base_logging_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability base_logging_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests base_logging_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests base_logging_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase base_logging_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer base_logging_GoogleSqlFlexLexer
#define UCaseMap base_logging_UCaseMap

#define GO_EXPORT(def) export_base_logging_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

#include "_cgo_export.h"

// include headers (types only; no .cc bodies)
#include "base/logging.h"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* base_logging_bind_cc */
