
#ifndef proto_confidence_interval_cc_proto_bind_cc
#define proto_confidence_interval_cc_proto_bind_cc

// Link-only bind.cc (no amalgamated .cc includes). Native implementations must come from prebuilt
// archives (e.g. libgooglesql.a) and match this package's exported bridge symbols.
// Enable per package via cclib.link_only_bind_packages in internal/cmd/generator/config.yaml.
// See docs/link-only-cgo-migration.md.
#define AbslInternalSleepFor proto_confidence_interval_cc_proto_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError proto_confidence_interval_cc_proto_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield proto_confidence_interval_cc_proto_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost proto_confidence_interval_cc_proto_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait proto_confidence_interval_cc_proto_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything proto_confidence_interval_cc_proto_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay proto_confidence_interval_cc_proto_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake proto_confidence_interval_cc_proto_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin proto_confidence_interval_cc_proto_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd proto_confidence_interval_cc_proto_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint proto_confidence_interval_cc_proto_AbslInternalGetFileMappingHint
#define GoogleSqlalloc proto_confidence_interval_cc_proto_GoogleSqlalloc
#define GoogleSqlfree proto_confidence_interval_cc_proto_GoogleSqlfree
#define GoogleSqlrealloc proto_confidence_interval_cc_proto_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly proto_confidence_interval_cc_proto_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream proto_confidence_interval_cc_proto_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly proto_confidence_interval_cc_proto_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream proto_confidence_interval_cc_proto_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit proto_confidence_interval_cc_proto_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path proto_confidence_interval_cc_proto_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width proto_confidence_interval_cc_proto_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance proto_confidence_interval_cc_proto_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period proto_confidence_interval_cc_proto_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit proto_confidence_interval_cc_proto_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path proto_confidence_interval_cc_proto_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width proto_confidence_interval_cc_proto_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance proto_confidence_interval_cc_proto_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period proto_confidence_interval_cc_proto_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes proto_confidence_interval_cc_proto_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes proto_confidence_interval_cc_proto_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string proto_confidence_interval_cc_proto_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string proto_confidence_interval_cc_proto_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability proto_confidence_interval_cc_proto_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability proto_confidence_interval_cc_proto_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests proto_confidence_interval_cc_proto_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests proto_confidence_interval_cc_proto_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase proto_confidence_interval_cc_proto_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer proto_confidence_interval_cc_proto_GoogleSqlFlexLexer
#define UCaseMap proto_confidence_interval_cc_proto_UCaseMap

#define GO_EXPORT(def) export_proto_confidence_interval_cc_proto_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

#include "_cgo_export.h"

// include headers (types only; no .cc bodies)
#include "proto/confidence-interval.pb.h"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* proto_confidence_interval_cc_proto_bind_cc */
