#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_TOKEN_PROVIDER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_TOKEN_PROVIDER_EXPORT_H

#include "googlesql/parser/macros/token_provider.h"
// include sources
#include "googlesql/parser/macros/token_provider.cc"
// include dependencies
#include "go-zetasql/parser/macros/token_provider_base/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/parser/token/export.inc"
#include "go-zetasql/parser/token_with_location/export.inc"
#include "go-zetasql/parser/tokenizer/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
