#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_NUMERIC_PARSER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_NUMERIC_PARSER_EXPORT_H

#include "googlesql/legacy_zetasql/public/numeric_parser.h"
// include sources
#include "googlesql/legacy_zetasql/public/numeric_parser.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/numeric_constants/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/multiprecision_int/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
