#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_RESOLVED_AST_COLUMN_FACTORY_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_RESOLVED_AST_COLUMN_FACTORY_EXPORT_H

#include "googlesql/legacy_zetasql/resolved_ast/column_factory.h"
// include sources
#include "googlesql/legacy_zetasql/resolved_ast/column_factory.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
