#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_MATCH_PARTITION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_MATCH_PARTITION_EXPORT_H

#include "zetasql/common/match_recognize/nfa_match_partition.h"
// include sources
#include "zetasql/common/match_recognize/nfa_match_partition.cc"
// include dependencies
#include "go-zetasql/common/match_recognize/compiled_nfa/export.inc"
#include "go-zetasql/common/match_recognize/edge_tracker/export.inc"
#include "go-zetasql/common/match_recognize/nfa/export.inc"
#include "go-zetasql/common/match_recognize/row_edge_list/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/functions/match_recognize/match_partition/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
