#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_DISTANCE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_DISTANCE_EXPORT_H

#include "googlesql/public/functions/distance.h"
// include sources
#include "googlesql/public/functions/distance.cc"
// include dependencies
#include "go-googlesql/public/functions/arithmetics/export.inc"
#include "go-googlesql/public/functions/math/export.inc"
#include "go-googlesql/base/edit_distance/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-icu/icu/export.inc"

#endif
