#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_INTERNAL_EXPORT_H

#include "absl/strings/internal/escaping.h"
#include "absl/strings/internal/ostringstream.h"
#include "absl/strings/internal/resize_uninitialized.h"
#include "absl/strings/internal/utf8.h"
// include sources
#include "absl/strings/internal/escaping.cc"
#include "absl/strings/internal/ostringstream.cc"
#include "absl/strings/internal/utf8.cc"
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/endian/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#endif
