#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_REWRITE_FLAGS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_REWRITE_FLAGS_EXPORT_H

#include "googlesql/reference_impl/rewrite_flags.h"
// include sources
#include "googlesql/reference_impl/rewrite_flags.cc"
// include dependencies
#include "go-googlesql/common/options_utils/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
