#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SQL_PROCEDURE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SQL_PROCEDURE_EXPORT_H

#include "googlesql/public/sql_procedure.h"
// include sources
// include dependencies
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/module_details/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
