
#ifndef googlesql_parser_lookahead_transformer_bind_cc
#define googlesql_parser_lookahead_transformer_bind_cc

// switch namespace
#define differential_privacy googlesql_parser_lookahead_transformer_differential_privacy
#define googlesql googlesql_parser_lookahead_transformer_googlesql
#define googlesql_base googlesql_parser_lookahead_transformer_googlesql_base
#define googlesql_bison_parser googlesql_parser_lookahead_transformer_googlesql_bison_parser
#define re2 googlesql_parser_lookahead_transformer_re2
#define AbslInternalSleepFor googlesql_parser_lookahead_transformer_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_parser_lookahead_transformer_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_parser_lookahead_transformer_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_parser_lookahead_transformer_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_parser_lookahead_transformer_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_parser_lookahead_transformer_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_parser_lookahead_transformer_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_parser_lookahead_transformer_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_parser_lookahead_transformer_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_parser_lookahead_transformer_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_parser_lookahead_transformer_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_parser_lookahead_transformer_GoogleSqlalloc
#define GoogleSqlfree googlesql_parser_lookahead_transformer_GoogleSqlfree
#define GoogleSqlrealloc googlesql_parser_lookahead_transformer_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_parser_lookahead_transformer_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_parser_lookahead_transformer_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_parser_lookahead_transformer_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_parser_lookahead_transformer_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_parser_lookahead_transformer_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_parser_lookahead_transformer_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_parser_lookahead_transformer_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_parser_lookahead_transformer_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_parser_lookahead_transformer_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_parser_lookahead_transformer_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_parser_lookahead_transformer_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_parser_lookahead_transformer_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_parser_lookahead_transformer_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_parser_lookahead_transformer_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_parser_lookahead_transformer_GoogleSqlFlexLexer
#define UCaseMap googlesql_parser_lookahead_transformer_UCaseMap

#define GO_EXPORT(def) export_googlesql_parser_lookahead_transformer_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/parser/lookahead_transformer.h"
//#undef private

// include sources
#include "googlesql/parser/lookahead_transformer.cc"

// include dependencies
#include "go-googlesql/parser/parser_mode/export.inc"
#include "go-googlesql/parser/token/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/parser/macros/macro_catalog/export.inc"
#include "go-googlesql/parser/macros/macro_expander/export.inc"
#include "go-googlesql/parser/macros/token_provider/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_parser_lookahead_transformer_bind_cc */
