#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_KEYWORDS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_KEYWORDS_EXPORT_H

#include "googlesql/parser/keywords.h"
// include sources
#include "googlesql/parser/keywords.cc"
// include dependencies
#include "go-zetasql/parser/token/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/variant/export.inc"

#endif
