#ifndef INTERNAL_CCALL_GO_ZETASQL_RESOLVED_AST_RESOLVED_AST_REWRITE_VISITOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_RESOLVED_AST_RESOLVED_AST_REWRITE_VISITOR_EXPORT_H

#include "zetasql/resolved_ast/resolved_ast_rewrite_visitor.h"
// include sources
#include "zetasql/resolved_ast/resolved_ast_rewrite_visitor.cc"
// include dependencies
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
