#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_GRAPH_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_GRAPH_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/functions/graph.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/functions/graph.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/json_value/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/json/export.inc"
#include "go-zetasql/public/functions/json_format/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
