#ifndef INTERNAL_CCALL_GO_ABSL_CRC_CRC_CORD_STATE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_CRC_CRC_CORD_STATE_EXPORT_H

#include "absl/crc/internal/crc_cord_state.h"
// include sources
#include "absl/crc/internal/crc_cord_state.cc"
// include dependencies
#include "go-absl/crc/crc32c/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/numeric/bits/export.inc"

#endif
