
#ifndef algorithms_bounded_variance_bind_cc
#define algorithms_bounded_variance_bind_cc

// switch namespace
#define absl algorithms_bounded_variance_absl
#define differential_privacy algorithms_bounded_variance_differential_privacy
#define google algorithms_bounded_variance_google
#define zetasql algorithms_bounded_variance_zetasql
#define zetasql_base algorithms_bounded_variance_zetasql_base
#define zetasql_bison_parser algorithms_bounded_variance_zetasql_bison_parser
#define re2 algorithms_bounded_variance_re2
#define AbslInternalSleepFor algorithms_bounded_variance_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_bounded_variance_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_bounded_variance_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_bounded_variance_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_bounded_variance_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_bounded_variance_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_bounded_variance_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_bounded_variance_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_bounded_variance_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_bounded_variance_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_bounded_variance_AbslInternalGetFileMappingHint
#define ZetaSqlalloc algorithms_bounded_variance_ZetaSqlalloc
#define ZetaSqlfree algorithms_bounded_variance_ZetaSqlfree
#define ZetaSqlrealloc algorithms_bounded_variance_ZetaSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_bounded_variance_FLAGS_nooutput_asc_explicitly
#define FLAGS_nozetasql_use_customized_flex_istream algorithms_bounded_variance_FLAGS_nozetasql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_bounded_variance_FLAGS_output_asc_explicitly
#define FLAGS_zetasql_use_customized_flex_istream algorithms_bounded_variance_FLAGS_zetasql_use_customized_flex_istream
#define FLAGS_zetasql_type_factory_nesting_depth_limit algorithms_bounded_variance_FLAGS_zetasql_type_factory_nesting_depth_limit
#define FLAGS_zetasql_read_proto_field_optimized_path algorithms_bounded_variance_FLAGS_zetasql_read_proto_field_optimized_path
#define FLAGS_zetasql_format_max_output_width algorithms_bounded_variance_FLAGS_zetasql_format_max_output_width
#define FLAGS_zetasql_min_length_required_for_edit_distance algorithms_bounded_variance_FLAGS_zetasql_min_length_required_for_edit_distance
#define FLAGS_zetasql_simple_iterator_call_time_now_rows_period algorithms_bounded_variance_FLAGS_zetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_nozetasql_type_factory_nesting_depth_limit algorithms_bounded_variance_FLAGS_nozetasql_type_factory_nesting_depth_limit
#define FLAGS_nozetasql_read_proto_field_optimized_path algorithms_bounded_variance_FLAGS_nozetasql_read_proto_field_optimized_path
#define FLAGS_nozetasql_format_max_output_width algorithms_bounded_variance_FLAGS_nozetasql_format_max_output_width
#define FLAGS_nozetasql_min_length_required_for_edit_distance algorithms_bounded_variance_FLAGS_nozetasql_min_length_required_for_edit_distance
#define FLAGS_nozetasql_simple_iterator_call_time_now_rows_period algorithms_bounded_variance_FLAGS_nozetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_zetasql_enough_stack_bytes algorithms_bounded_variance_FLAGS_zetasql_enough_stack_bytes
#define FLAGS_nozetasql_enough_stack_bytes algorithms_bounded_variance_FLAGS_nozetasql_enough_stack_bytes
#define FLAGS_zetasql_canonicalize_signed_zero_to_string algorithms_bounded_variance_FLAGS_zetasql_canonicalize_signed_zero_to_string
#define FLAGS_nozetasql_canonicalize_signed_zero_to_string algorithms_bounded_variance_FLAGS_nozetasql_canonicalize_signed_zero_to_string
#define FLAGS_zetasql_default_error_message_stability algorithms_bounded_variance_FLAGS_zetasql_default_error_message_stability
#define FLAGS_nozetasql_default_error_message_stability algorithms_bounded_variance_FLAGS_nozetasql_default_error_message_stability
#define FLAGS_zetasql_redact_error_messages_for_tests algorithms_bounded_variance_FLAGS_zetasql_redact_error_messages_for_tests
#define FLAGS_nozetasql_redact_error_messages_for_tests algorithms_bounded_variance_FLAGS_nozetasql_redact_error_messages_for_tests
#define ZetaSqlFlexTokenizerBase algorithms_bounded_variance_ZetaSqlFlexTokenizerBase
#define ZetaSqlFlexLexer algorithms_bounded_variance_ZetaSqlFlexLexer
#define UCaseMap algorithms_bounded_variance_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto algorithms_bounded_variance_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto algorithms_bounded_variance_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto algorithms_bounded_variance_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto algorithms_bounded_variance_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto algorithms_bounded_variance_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto algorithms_bounded_variance_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto algorithms_bounded_variance_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto algorithms_bounded_variance_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto algorithms_bounded_variance_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto algorithms_bounded_variance_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto algorithms_bounded_variance_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto algorithms_bounded_variance_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto algorithms_bounded_variance_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto algorithms_bounded_variance_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto algorithms_bounded_variance_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto algorithms_bounded_variance_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto algorithms_bounded_variance_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto algorithms_bounded_variance_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto algorithms_bounded_variance_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto algorithms_bounded_variance_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto algorithms_bounded_variance_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto algorithms_bounded_variance_TableStruct_google_2ftype_2ftimeofday_2eproto
#define google_2frpc_2fstatus_2eproto algorithms_bounded_variance_google_2frpc_2fstatus_2eproto
#define descriptor_table_google_2frpc_2fstatus_2eproto algorithms_bounded_variance_descriptor_table_google_2frpc_2fstatus_2eproto
#define TableStruct_google_2frpc_2fstatus_2eproto algorithms_bounded_variance_TableStruct_google_2frpc_2fstatus_2eproto
#define zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define zetasql_2fparser_2fparse_5ftree_2eproto algorithms_bounded_variance_zetasql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto
#define zetasql_2fparser_2fast_5fenums_2eproto algorithms_bounded_variance_zetasql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto
#define TableStruct_zetasql_2fparser_2fast_5fenums_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fparser_2fast_5fenums_2eproto
#define zetasql_2fproto_2foptions_2eproto algorithms_bounded_variance_zetasql_2fproto_2foptions_2eproto
#define descriptor_table_zetasql_2fproto_2foptions_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2foptions_2eproto
#define TableStruct_zetasql_2fproto_2foptions_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2foptions_2eproto
#define zetasql_2fproto_2fsimple_5fcatalog_2eproto algorithms_bounded_variance_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define zetasql_2fproto_2ffunction_2eproto algorithms_bounded_variance_zetasql_2fproto_2ffunction_2eproto
#define descriptor_table_zetasql_2fproto_2ffunction_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2ffunction_2eproto
#define TableStruct_zetasql_2fproto_2ffunction_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2ffunction_2eproto
#define zetasql_2fproto_2finternal_5ferror_5flocation_2eproto algorithms_bounded_variance_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto algorithms_bounded_variance_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto algorithms_bounded_variance_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define zetasql_2fproto_2fscript_5fexception_2eproto algorithms_bounded_variance_zetasql_2fproto_2fscript_5fexception_2eproto
#define descriptor_table_zetasql_2fproto_2fscript_5fexception_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fproto_2fscript_5fexception_2eproto
#define TableStruct_zetasql_2fproto_2fscript_5fexception_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fproto_2fscript_5fexception_2eproto
#define zetasql_2fpublic_2fbuiltin_5ffunction_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define zetasql_2fpublic_2fdeprecation_5fwarning_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define zetasql_2fpublic_2ffunction_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunction_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2ffunction_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunction_2eproto
#define zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define zetasql_2fpublic_2foptions_2eproto algorithms_bounded_variance_zetasql_2fpublic_2foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2foptions_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2foptions_2eproto
#define TableStruct_zetasql_2fpublic_2foptions_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2foptions_2eproto
#define zetasql_2fpublic_2fsimple_5ftable_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define zetasql_2fpublic_2fsimple_5fconstant_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define zetasql_2fpublic_2fsimple_5fconnection_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconnection_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconnection_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define zetasql_2fpublic_2fsimple_5fmodel_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fmodel_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fmodel_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define zetasql_2fpublic_2fparse_5flocation_5frange_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define zetasql_2fpublic_2ftype_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ftype_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ftype_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ftype_2eproto
#define zetasql_2fpublic_2ftype_5fannotation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define zetasql_2fpublic_2fvalue_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fvalue_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fvalue_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fvalue_2eproto
#define zetasql_2fpublic_2ftype_5fparameters_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define zetasql_2fpublic_2fcollation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fcollation_2eproto
#define descriptor_table_zetasql_2fpublic_2fcollation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fcollation_2eproto
#define TableStruct_zetasql_2fpublic_2fcollation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fcollation_2eproto
#define zetasql_2fpublic_2ftype_5fmodifiers_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define zetasql_2fpublic_2fformatter_5foptions_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define zetasql_2fpublic_2ferror_5flocation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto
#define zetasql_2fpublic_2fannotation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fannotation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fannotation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fannotation_2eproto
#define zetasql_2fpublic_2fsimple_5fvalue_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define zetasql_2fpublic_2ffunctions_2fdatetime_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto algorithms_bounded_variance_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define zetasql_2fpublic_2fproto_2flogging_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto
#define zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto algorithms_bounded_variance_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto algorithms_bounded_variance_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto algorithms_bounded_variance_TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto algorithms_bounded_variance_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto algorithms_bounded_variance_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_2eproto algorithms_bounded_variance_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define zetasql_2fresolved_5fast_2fserialization_2eproto algorithms_bounded_variance_zetasql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto
#define zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto algorithms_bounded_variance_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define zetasql_2fscripting_2fprocedure_5fextension_2eproto algorithms_bounded_variance_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define zetasql_2fscripting_2fvariable_2eproto algorithms_bounded_variance_zetasql_2fscripting_2fvariable_2eproto
#define descriptor_table_zetasql_2fscripting_2fvariable_2eproto algorithms_bounded_variance_descriptor_table_zetasql_2fscripting_2fvariable_2eproto
#define TableStruct_zetasql_2fscripting_2fvariable_2eproto algorithms_bounded_variance_TableStruct_zetasql_2fscripting_2fvariable_2eproto
#define proto_2fconfidence_2dinterval_2eproto algorithms_bounded_variance_proto_2fconfidence_2dinterval_2eproto
#define descriptor_table_proto_2fconfidence_2dinterval_2eproto algorithms_bounded_variance_descriptor_table_proto_2fconfidence_2dinterval_2eproto
#define TableStruct_proto_2fconfidence_2dinterval_2eproto algorithms_bounded_variance_TableStruct_proto_2fconfidence_2dinterval_2eproto
#define proto_2fdata_2eproto algorithms_bounded_variance_proto_2fdata_2eproto
#define descriptor_table_proto_2fdata_2eproto algorithms_bounded_variance_descriptor_table_proto_2fdata_2eproto
#define TableStruct_proto_2fdata_2eproto algorithms_bounded_variance_TableStruct_proto_2fdata_2eproto
#define proto_2fnumerical_2dmechanism_2eproto algorithms_bounded_variance_proto_2fnumerical_2dmechanism_2eproto
#define descriptor_table_proto_2fnumerical_2dmechanism_2eproto algorithms_bounded_variance_descriptor_table_proto_2fnumerical_2dmechanism_2eproto
#define TableStruct_proto_2fnumerical_2dmechanism_2eproto algorithms_bounded_variance_TableStruct_proto_2fnumerical_2dmechanism_2eproto
#define proto_2fsummary_2eproto algorithms_bounded_variance_proto_2fsummary_2eproto
#define descriptor_table_proto_2fsummary_2eproto algorithms_bounded_variance_descriptor_table_proto_2fsummary_2eproto
#define TableStruct_proto_2fsummary_2eproto algorithms_bounded_variance_TableStruct_proto_2fsummary_2eproto

#define GO_EXPORT(def) export_algorithms_bounded_variance_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "algorithms/bounded-variance.h"
//#undef private

// include sources

// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/approx-bounds/export.inc"
#include "go-algorithms/bounded-algorithm/export.inc"
#include "go-algorithms/numerical-mechanisms/export.inc"
#include "go-algorithms/util/export.inc"
#include "go-base/logging/export.inc"
#include "go-proto/util-lib/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-base/status/export.inc"
#include "go-proto/data_cc_proto/export.inc"
#include "go-proto/summary_cc_proto/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_bounded_variance_bind_cc */
