#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_PROTO_TYPE_ANNOTATION_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_PROTO_TYPE_ANNOTATION_CC_PROTO_EXPORT_H

#include "googlesql/legacy_zetasql/public/proto/type_annotation.pb.h"
#include "googlesql/legacy_zetasql/public/proto/wire_format_annotation.pb.h"
// include sources
#include "googlesql/legacy_zetasql/public/proto/type_annotation.pb.cc"
#include "googlesql/legacy_zetasql/public/proto/wire_format_annotation.pb.cc"
// include dependencies

#endif
