#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_CONSTANT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_CONSTANT_EXPORT_H

#include "zetasql/public/constant.h"
// include sources
// include dependencies
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
