#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_TEMPLATED_FUNCTION_CALL_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_TEMPLATED_FUNCTION_CALL_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/templated_function_call_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/templated_function_call_rewriter.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/analyzer/rewriters/rewriter_relevance_checker/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/templated_sql_function/export.inc"
#include "go-zetasql/public/templated_sql_tvf_no_resolver/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
