#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_PARSE_LOCATION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_PARSE_LOCATION_EXPORT_H

#include "googlesql/legacy_zetasql/public/parse_location.h"
// include sources
#include "googlesql/legacy_zetasql/public/parse_location.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/parse_location_range_cc_proto/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/mathutil/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/proto/internal_error_location_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-icu/icu/export.inc"

#endif
