// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/reference_impl/evaluator_table_iterator.proto

#include "zetasql/reference_impl/evaluator_table_iterator.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace zetasql {
constexpr EvaluatorTableIteratorProto::EvaluatorTableIteratorProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : next_row_count_(int64_t{0})
  , location_byte_offset_(0){}
struct EvaluatorTableIteratorProtoDefaultTypeInternal {
  constexpr EvaluatorTableIteratorProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~EvaluatorTableIteratorProtoDefaultTypeInternal() {}
  union {
    EvaluatorTableIteratorProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT EvaluatorTableIteratorProtoDefaultTypeInternal _EvaluatorTableIteratorProto_default_instance_;
}  // namespace zetasql
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto = nullptr;

const uint32_t TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::zetasql::EvaluatorTableIteratorProto, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::zetasql::EvaluatorTableIteratorProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::zetasql::EvaluatorTableIteratorProto, location_byte_offset_),
  PROTOBUF_FIELD_OFFSET(::zetasql::EvaluatorTableIteratorProto, next_row_count_),
  1,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::zetasql::EvaluatorTableIteratorProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::zetasql::_EvaluatorTableIteratorProto_default_instance_),
};

const char descriptor_table_protodef_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n5zetasql/reference_impl/evaluator_table"
  "_iterator.proto\022\007zetasql\"S\n\033EvaluatorTab"
  "leIteratorProto\022\034\n\024location_byte_offset\030"
  "\001 \001(\005\022\026\n\016next_row_count\030\002 \001(\003"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto = {
  false, false, 149, descriptor_table_protodef_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto, "zetasql/reference_impl/evaluator_table_iterator.proto", 
  &descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto::offsets,
  file_level_metadata_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto, file_level_enum_descriptors_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto, file_level_service_descriptors_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto_getter() {
  return &descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto(&descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto);
namespace zetasql {

// ===================================================================

class EvaluatorTableIteratorProto::_Internal {
 public:
  using HasBits = decltype(std::declval<EvaluatorTableIteratorProto>()._has_bits_);
  static void set_has_location_byte_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_next_row_count(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

EvaluatorTableIteratorProto::EvaluatorTableIteratorProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:zetasql.EvaluatorTableIteratorProto)
}
EvaluatorTableIteratorProto::EvaluatorTableIteratorProto(const EvaluatorTableIteratorProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&next_row_count_, &from.next_row_count_,
    static_cast<size_t>(reinterpret_cast<char*>(&location_byte_offset_) -
    reinterpret_cast<char*>(&next_row_count_)) + sizeof(location_byte_offset_));
  // @@protoc_insertion_point(copy_constructor:zetasql.EvaluatorTableIteratorProto)
}

inline void EvaluatorTableIteratorProto::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&next_row_count_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&location_byte_offset_) -
    reinterpret_cast<char*>(&next_row_count_)) + sizeof(location_byte_offset_));
}

EvaluatorTableIteratorProto::~EvaluatorTableIteratorProto() {
  // @@protoc_insertion_point(destructor:zetasql.EvaluatorTableIteratorProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void EvaluatorTableIteratorProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void EvaluatorTableIteratorProto::ArenaDtor(void* object) {
  EvaluatorTableIteratorProto* _this = reinterpret_cast< EvaluatorTableIteratorProto* >(object);
  (void)_this;
}
void EvaluatorTableIteratorProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EvaluatorTableIteratorProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EvaluatorTableIteratorProto::Clear() {
// @@protoc_insertion_point(message_clear_start:zetasql.EvaluatorTableIteratorProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&next_row_count_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&location_byte_offset_) -
        reinterpret_cast<char*>(&next_row_count_)) + sizeof(location_byte_offset_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EvaluatorTableIteratorProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 location_byte_offset = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_location_byte_offset(&has_bits);
          location_byte_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int64 next_row_count = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_next_row_count(&has_bits);
          next_row_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EvaluatorTableIteratorProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zetasql.EvaluatorTableIteratorProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 location_byte_offset = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_location_byte_offset(), target);
  }

  // optional int64 next_row_count = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_next_row_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zetasql.EvaluatorTableIteratorProto)
  return target;
}

size_t EvaluatorTableIteratorProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zetasql.EvaluatorTableIteratorProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int64 next_row_count = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_next_row_count());
    }

    // optional int32 location_byte_offset = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_location_byte_offset());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EvaluatorTableIteratorProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    EvaluatorTableIteratorProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EvaluatorTableIteratorProto::GetClassData() const { return &_class_data_; }

void EvaluatorTableIteratorProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<EvaluatorTableIteratorProto *>(to)->MergeFrom(
      static_cast<const EvaluatorTableIteratorProto &>(from));
}


void EvaluatorTableIteratorProto::MergeFrom(const EvaluatorTableIteratorProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:zetasql.EvaluatorTableIteratorProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      next_row_count_ = from.next_row_count_;
    }
    if (cached_has_bits & 0x00000002u) {
      location_byte_offset_ = from.location_byte_offset_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EvaluatorTableIteratorProto::CopyFrom(const EvaluatorTableIteratorProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zetasql.EvaluatorTableIteratorProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EvaluatorTableIteratorProto::IsInitialized() const {
  return true;
}

void EvaluatorTableIteratorProto::InternalSwap(EvaluatorTableIteratorProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EvaluatorTableIteratorProto, location_byte_offset_)
      + sizeof(EvaluatorTableIteratorProto::location_byte_offset_)
      - PROTOBUF_FIELD_OFFSET(EvaluatorTableIteratorProto, next_row_count_)>(
          reinterpret_cast<char*>(&next_row_count_),
          reinterpret_cast<char*>(&other->next_row_count_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EvaluatorTableIteratorProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto_getter, &descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto_once,
      file_level_metadata_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zetasql::EvaluatorTableIteratorProto* Arena::CreateMaybeMessage< ::zetasql::EvaluatorTableIteratorProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zetasql::EvaluatorTableIteratorProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
