#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_JSON_PARSER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_JSON_PARSER_EXPORT_H

#include "zetasql/common/json_parser.h"
// include sources
#include "zetasql/common/json_parser.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-re2/re2/export.inc"
#include "go-icu/icu/export.inc"

#endif
