#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_AST_NODE_FACTORY_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_AST_NODE_FACTORY_EXPORT_H

#include "googlesql/parser/ast_node_factory.h"
// include sources
#include "googlesql/parser/ast_node_factory.cc"
// include dependencies
#include "go-googlesql/parser/parse_tree/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/arena_allocator/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/proto/logging_cc_proto/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#endif
