#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_MATHUTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_MATHUTIL_EXPORT_H

#include "googlesql/legacy_zetasql/base/mathutil.h"
// include sources
#include "googlesql/legacy_zetasql/base/mathutil.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/base/bits/export.inc"
#include "go-zetasql/legacy_zetasql/base/check/export.inc"
#include "go-absl/base/base/export.inc"

#endif
