#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ID_STRING_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ID_STRING_EXPORT_H

#include "googlesql/legacy_zetasql/public/id_string.h"
// include sources
#include "googlesql/legacy_zetasql/public/id_string.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/endian/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/common/unicode_utils/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
