#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_VARIABLE_GENERATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_VARIABLE_GENERATOR_EXPORT_H

#include "googlesql/reference_impl/variable_generator.h"
// include sources
#include "googlesql/reference_impl/variable_generator.cc"
// include dependencies
#include "go-googlesql/reference_impl/common/export.inc"
#include "go-googlesql/reference_impl/parameters/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
