#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_LOGGING_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_LOGGING_EXPORT_H

#include "googlesql/legacy_zetasql/base/logging.h"
// include sources
#include "googlesql/legacy_zetasql/base/logging.cc"
// include dependencies
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/log/absl_check/export.inc"
#include "go-absl/log/absl_log/export.inc"

#endif
