#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_REGEXP_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_REGEXP_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/regexp.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/regexp.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/functions/string/export.inc"
#include "go-googlesql/legacy_zetasql/public/functions/util/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/utf_util/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-re2/re2/export.inc"
#include "go-icu/icu/export.inc"

#endif
