#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PARSE_RESUME_LOCATION_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PARSE_RESUME_LOCATION_CC_PROTO_EXPORT_H

#include "zetasql/public/parse_resume_location.pb.h"
// include sources
#define schemas zetasql_public_parse_resume_location_cc_proto_schemas
#define file_default_instances zetasql_public_parse_resume_location_cc_proto_file_default_instances
#include "zetasql/public/parse_resume_location.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies
#include "go-protobuf/protobuf/export.inc"

#endif
