#ifndef INTERNAL_CCALL_GO_ABSL_BASE_RAW_LOGGING_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_BASE_RAW_LOGGING_INTERNAL_EXPORT_H

#include "absl/base/internal/raw_logging.h"
// include sources
// include dependencies
#include "go-absl/base/atomic_hook/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/errno_saver/export.inc"
#include "go-absl/base/log_severity/export.inc"

#endif
