#ifndef INTERNAL_CCALL_GO_ABSL_SYNCHRONIZATION_KERNEL_TIMEOUT_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_SYNCHRONIZATION_KERNEL_TIMEOUT_INTERNAL_EXPORT_H

#include "absl/synchronization/internal/kernel_timeout.h"
// include sources
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/time/time/export.inc"

#endif
