
#ifndef googlesql_legacy_zetasql_parser_bison_parser_generated_lib_bind_cc
#define googlesql_legacy_zetasql_parser_bison_parser_generated_lib_bind_cc

// switch namespace
#define differential_privacy googlesql_legacy_zetasql_parser_bison_parser_generated_lib_differential_privacy
#define googlesql googlesql_legacy_zetasql_parser_bison_parser_generated_lib_googlesql
#define googlesql_base googlesql_legacy_zetasql_parser_bison_parser_generated_lib_googlesql_base
#define googlesql_bison_parser googlesql_legacy_zetasql_parser_bison_parser_generated_lib_googlesql_bison_parser
#define re2 googlesql_legacy_zetasql_parser_bison_parser_generated_lib_re2
#define AbslInternalSleepFor googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_legacy_zetasql_parser_bison_parser_generated_lib_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_legacy_zetasql_parser_bison_parser_generated_lib_GoogleSqlalloc
#define GoogleSqlfree googlesql_legacy_zetasql_parser_bison_parser_generated_lib_GoogleSqlfree
#define GoogleSqlrealloc googlesql_legacy_zetasql_parser_bison_parser_generated_lib_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_legacy_zetasql_parser_bison_parser_generated_lib_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_legacy_zetasql_parser_bison_parser_generated_lib_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_legacy_zetasql_parser_bison_parser_generated_lib_GoogleSqlFlexLexer
#define UCaseMap googlesql_legacy_zetasql_parser_bison_parser_generated_lib_UCaseMap

#define GO_EXPORT(def) export_googlesql_legacy_zetasql_parser_bison_parser_generated_lib_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/legacy_zetasql/parser/bison_parser.h"
#include "googlesql/legacy_zetasql/parser/join_processor.h"
#include "googlesql/legacy_zetasql/parser/parser_internal.h"
#include "googlesql/legacy_zetasql/parser/parser_runtime_info.h"
#include "googlesql/legacy_zetasql/parser/statement_properties.h"
//#undef private

// include sources
#include "googlesql/legacy_zetasql/parser/join_processor.cc"

// include dependencies
#include "go-googlesql/legacy_zetasql/parser/bison_parser_mode/export.inc"
#include "go-googlesql/legacy_zetasql/parser/keywords/export.inc"
#include "go-googlesql/legacy_zetasql/parser/parse_tree/export.inc"
#include "go-googlesql/legacy_zetasql/parser/token/export.inc"
#include "go-googlesql/legacy_zetasql/parser/token_codes/export.inc"
#include "go-googlesql/legacy_zetasql/parser/token_with_location/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/arena_allocator/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/strings/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/timer_util/export.inc"
#include "go-googlesql/parser/macros/macro_catalog/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/proto/logging_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_legacy_zetasql_parser_bison_parser_generated_lib_bind_cc */
