#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_WARNING_SINK_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_WARNING_SINK_EXPORT_H

#include "googlesql/legacy_zetasql/common/warning_sink.h"
// include sources
#include "googlesql/legacy_zetasql/common/warning_sink.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/common/status_payload_utils/export.inc"
#include "go-googlesql/public/deprecation_warning_cc_proto/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/types/span/export.inc"

#endif
