#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_SUBSTITUTE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_SUBSTITUTE_EXPORT_H

#include "googlesql/analyzer/substitute.h"
// include sources
#include "googlesql/analyzer/substitute.cc"
// include dependencies
#include "go-googlesql/analyzer/analyzer_impl/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/internal_analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/multi_catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/simple_catalog/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
