#ifndef INTERNAL_CCALL_GO_GOOGLESQL_BASE_RET_CHECK_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_BASE_RET_CHECK_EXPORT_H

#include "googlesql/base/ret_check.h"
// include sources
#include "googlesql/base/ret_check.cc"
// include dependencies
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/status/status/export.inc"

#endif
