#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_ENDIAN_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_ENDIAN_EXPORT_H

#include "googlesql/legacy_zetasql/base/endian.h"
#include "googlesql/legacy_zetasql/base/unaligned_access.h"
// include sources
// include dependencies
#include "go-zetasql/legacy_zetasql/base/logging/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/int128/export.inc"

#endif
