#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_INTERNAL_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_INTERNAL_VALUE_EXPORT_H

#include "googlesql/legacy_zetasql/common/internal_value.h"
// include sources
#include "googlesql/legacy_zetasql/common/internal_value.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/common/float_margin/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
