#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_AGGREGATION_THRESHOLD_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_AGGREGATION_THRESHOLD_UTILS_EXPORT_H

#include "zetasql/public/aggregation_threshold_utils.h"
// include sources
#include "zetasql/public/aggregation_threshold_utils.cc"
// include dependencies
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/no_destructor/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"

#endif
