#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_TIME_PROTO_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_TIME_PROTO_UTIL_EXPORT_H

#include "zetasql/base/time_proto_util.h"
// include sources
#include "zetasql/base/time_proto_util.cc"
// include dependencies
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
