#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_ANNOTATION_DEFAULT_ANNOTATION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_ANNOTATION_DEFAULT_ANNOTATION_EXPORT_H

#include "googlesql/public/annotation/default_annotation_spec.h"
// include sources
#include "googlesql/public/annotation/default_annotation_spec.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/type_and_argument_kind_visitor/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
