
#ifndef algorithms_bounded_algorithm_bind_cc
#define algorithms_bounded_algorithm_bind_cc

// switch namespace
#define differential_privacy algorithms_bounded_algorithm_differential_privacy
#define googlesql algorithms_bounded_algorithm_googlesql
#define googlesql_base algorithms_bounded_algorithm_googlesql_base
#define googlesql_bison_parser algorithms_bounded_algorithm_googlesql_bison_parser
#define re2 algorithms_bounded_algorithm_re2
#define AbslInternalSleepFor algorithms_bounded_algorithm_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_bounded_algorithm_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_bounded_algorithm_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_bounded_algorithm_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_bounded_algorithm_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_bounded_algorithm_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_bounded_algorithm_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_bounded_algorithm_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_bounded_algorithm_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_bounded_algorithm_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_bounded_algorithm_AbslInternalGetFileMappingHint
#define GoogleSqlalloc algorithms_bounded_algorithm_GoogleSqlalloc
#define GoogleSqlfree algorithms_bounded_algorithm_GoogleSqlfree
#define GoogleSqlrealloc algorithms_bounded_algorithm_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_bounded_algorithm_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream algorithms_bounded_algorithm_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_bounded_algorithm_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream algorithms_bounded_algorithm_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit algorithms_bounded_algorithm_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path algorithms_bounded_algorithm_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width algorithms_bounded_algorithm_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance algorithms_bounded_algorithm_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period algorithms_bounded_algorithm_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit algorithms_bounded_algorithm_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path algorithms_bounded_algorithm_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width algorithms_bounded_algorithm_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance algorithms_bounded_algorithm_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period algorithms_bounded_algorithm_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes algorithms_bounded_algorithm_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes algorithms_bounded_algorithm_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string algorithms_bounded_algorithm_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string algorithms_bounded_algorithm_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability algorithms_bounded_algorithm_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability algorithms_bounded_algorithm_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests algorithms_bounded_algorithm_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests algorithms_bounded_algorithm_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase algorithms_bounded_algorithm_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer algorithms_bounded_algorithm_GoogleSqlFlexLexer
#define UCaseMap algorithms_bounded_algorithm_UCaseMap

#define GO_EXPORT(def) export_algorithms_bounded_algorithm_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "algorithms/bounded-algorithm.h"
//#undef private

// include sources

// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/approx-bounds/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-base/status/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_bounded_algorithm_bind_cc */
