#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_COMMON_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_COMMON_PROTO_EXPORT_H

#include "zetasql/public/functions/common_proto.h"
// include sources
#include "zetasql/public/functions/common_proto.cc"
// include dependencies
#include "go-zetasql/public/functions/date_time_util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/utf_util/export.inc"
#include "go-zetasql/public/civil_time/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-google/type/latlng_cc_proto/export.inc"
#include "go-google/type/timeofday_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
