#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_REWRITER_RELEVANCE_CHECKER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_REWRITER_RELEVANCE_CHECKER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/rewriter_relevance_checker.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/rewriter_relevance_checker.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/sql_function/export.inc"
#include "go-googlesql/public/sql_tvf/export.inc"
#include "go-googlesql/public/sql_view/export.inc"
#include "go-googlesql/public/templated_sql_function/export.inc"
#include "go-googlesql/public/templated_sql_tvf/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
