#ifndef INTERNAL_CCALL_GO_ALGORITHMS_ORDER_STATISTICS_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_ORDER_STATISTICS_EXPORT_H

#include "algorithms/order-statistics.h"
// include sources
// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/binary-search/export.inc"
#include "go-algorithms/bounded-algorithm/export.inc"
#include "go-algorithms/numerical-mechanisms/export.inc"
#include "go-base/percentile/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
