
#ifndef googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_bind_cc
#define googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_bind_cc

// switch namespace
#define differential_privacy googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_differential_privacy
#define googlesql googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_googlesql
#define googlesql_base googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_googlesql_base
#define googlesql_bison_parser googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_googlesql_bison_parser
#define re2 googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_re2
#define AbslInternalSleepFor googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_GoogleSqlalloc
#define GoogleSqlfree googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_GoogleSqlfree
#define GoogleSqlrealloc googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_GoogleSqlFlexLexer
#define UCaseMap googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_UCaseMap

#define GO_EXPORT(def) export_googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/analyzer/rewriters/privacy/approx_count_distinct_utility.h"
//#undef private

// include sources
#include "googlesql/analyzer/rewriters/privacy/approx_count_distinct_utility.cc"

// include dependencies
#include "go-googlesql/analyzer/rewriters/privacy/privacy_utility/export.inc"
#include "go-googlesql/analyzer/resolver/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/parser/parse_tree/export.inc"
#include "go-googlesql/proto/anon_output_with_report_cc_proto/export.inc"
#include "go-googlesql/proto/internal_error_location_cc_proto/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/resolved_ast/comparator/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_analyzer_rewriters_privacy_approx_count_distinct_utility_bind_cc */
