#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_BUILTINS_OUTPUT_PROPERTIES_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_BUILTINS_OUTPUT_PROPERTIES_EXPORT_H

#include "googlesql/common/builtins_output_properties.h"
// include sources
// include dependencies
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"

#endif
