#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_SIMPLE_EVALUATOR_TABLE_ITERATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_SIMPLE_EVALUATOR_TABLE_ITERATOR_EXPORT_H

#include "zetasql/common/simple_evaluator_table_iterator.h"
// include sources
#include "zetasql/common/simple_evaluator_table_iterator.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/clock/export.inc"
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/evaluator_table_iterator/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
