#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_LAMBDA_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_LAMBDA_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/lambda_util.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/lambda_util.cc"
// include dependencies
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
