#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_PARSED_TEMPLATED_SQL_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_PARSED_TEMPLATED_SQL_FUNCTION_EXPORT_H

#include "googlesql/common/parsed_templated_sql_function.h"
// include sources
// include dependencies
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/templated_sql_function/export.inc"

#endif
