#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_THREAD_STACK_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_THREAD_STACK_EXPORT_H

#include "zetasql/common/thread_stack.h"
// include sources
#include "zetasql/common/thread_stack.cc"
// include dependencies
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"

#endif
