#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_FUNCTIONS_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_FUNCTIONS_EXPORT_H

#include "absl/strings/internal/cordz_functions.h"
// include sources
#include "absl/strings/internal/cordz_functions.cc"
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/profiling/exponential_biased/export.inc"

#endif
