#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FILE_MODULE_CONTENTS_FETCHER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FILE_MODULE_CONTENTS_FETCHER_EXPORT_H

#include "googlesql/public/file_module_contents_fetcher.h"
// include sources
#include "googlesql/public/file_module_contents_fetcher.cc"
// include dependencies
#include "go-googlesql/public/module_contents_fetcher/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/base/file_util/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/path/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/proto_helper/export.inc"
#include "go-googlesql/common/status_payload_utils/export.inc"
#include "go-googlesql/proto/module_options_cc_proto/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
