#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_INTERNAL_PROPERTY_GRAPH_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_INTERNAL_PROPERTY_GRAPH_EXPORT_H

#include "googlesql/legacy_zetasql/common/internal_property_graph.h"
// include sources
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"

#endif
