#ifndef INTERNAL_CCALL_GO_ZETASQL_RESOLVED_AST_REWRITE_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_RESOLVED_AST_REWRITE_UTILS_EXPORT_H

#include "zetasql/resolved_ast/rewrite_utils.h"
// include sources
#include "zetasql/resolved_ast/rewrite_utils.cc"
// include dependencies
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
