#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_CONSTANT_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_CONSTANT_UTILS_EXPORT_H

#include "zetasql/common/constant_utils.h"
// include sources
#include "zetasql/common/constant_utils.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/types/type/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
