
#ifndef googlesql_legacy_zetasql_reference_impl_algebrizer_bind_cc
#define googlesql_legacy_zetasql_reference_impl_algebrizer_bind_cc

// switch namespace
#define differential_privacy googlesql_legacy_zetasql_reference_impl_algebrizer_differential_privacy
#define googlesql googlesql_legacy_zetasql_reference_impl_algebrizer_googlesql
#define googlesql_base googlesql_legacy_zetasql_reference_impl_algebrizer_googlesql_base
#define googlesql_bison_parser googlesql_legacy_zetasql_reference_impl_algebrizer_googlesql_bison_parser
#define re2 googlesql_legacy_zetasql_reference_impl_algebrizer_re2
#define AbslInternalSleepFor googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_legacy_zetasql_reference_impl_algebrizer_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_legacy_zetasql_reference_impl_algebrizer_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_legacy_zetasql_reference_impl_algebrizer_GoogleSqlalloc
#define GoogleSqlfree googlesql_legacy_zetasql_reference_impl_algebrizer_GoogleSqlfree
#define GoogleSqlrealloc googlesql_legacy_zetasql_reference_impl_algebrizer_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_legacy_zetasql_reference_impl_algebrizer_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_legacy_zetasql_reference_impl_algebrizer_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_legacy_zetasql_reference_impl_algebrizer_GoogleSqlFlexLexer
#define UCaseMap googlesql_legacy_zetasql_reference_impl_algebrizer_UCaseMap

#define GO_EXPORT(def) export_googlesql_legacy_zetasql_reference_impl_algebrizer_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/legacy_zetasql/reference_impl/algebrizer.h"
#include "googlesql/legacy_zetasql/reference_impl/function.h"
#include "googlesql/legacy_zetasql/reference_impl/operator.h"
#include "googlesql/legacy_zetasql/reference_impl/tuple.h"
//#undef private

// include sources
#include "googlesql/legacy_zetasql/reference_impl/algebrizer.cc"
#include "googlesql/legacy_zetasql/reference_impl/algebrizer_graph.cc"

// include dependencies
#include "go-googlesql/legacy_zetasql/reference_impl/common/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/evaluation/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/parameters/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/proto_util/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/tvf_evaluation/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/type_helpers/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/uda_evaluation/export.inc"
#include "go-googlesql/legacy_zetasql/reference_impl/variable_generator/export.inc"
#include "go-googlesql/analyzer/resolver/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/flat_set/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/no_destructor/export.inc"
#include "go-googlesql/base/optional_ref/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/stl_util/export.inc"
#include "go-googlesql/common/aggregate_null_handling/export.inc"
#include "go-googlesql/common/internal_value/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/public/anonymization_utils/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/coercer/export.inc"
#include "go-googlesql/public/collator_lite/export.inc"
#include "go-googlesql/public/evaluator_table_iterator/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/interval_value/export.inc"
#include "go-googlesql/public/json_value/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-googlesql/public/simple_catalog/export.inc"
#include "go-googlesql/public/sql_function/export.inc"
#include "go-googlesql/public/sql_tvf/export.inc"
#include "go-googlesql/public/templated_sql_function/export.inc"
#include "go-googlesql/public/templated_sql_tvf_no_resolver/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/array_zip_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/date_time_util/export.inc"
#include "go-googlesql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-googlesql/public/functions/json/export.inc"
#include "go-googlesql/public/functions/match_recognize/compiled_pattern/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/serialization_cc_proto/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/functional/bind_front/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-googletest/googletest/export.inc"
#include "go-re2/re2/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_legacy_zetasql_reference_impl_algebrizer_bind_cc */
