#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SIMPLE_TABLE_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SIMPLE_TABLE_CC_PROTO_EXPORT_H

#include "zetasql/public/simple_table.pb.h"
// include sources
#include "zetasql/public/simple_table.pb.cc"
// include dependencies
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/annotation_cc_proto/export.inc"
#include "go-zetasql/public/simple_value_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
