
#ifndef googlesql_resolved_ast_rewrite_utils_bind_cc
#define googlesql_resolved_ast_rewrite_utils_bind_cc

// switch namespace
#define differential_privacy googlesql_resolved_ast_rewrite_utils_differential_privacy
#define googlesql googlesql_resolved_ast_rewrite_utils_googlesql
#define googlesql_base googlesql_resolved_ast_rewrite_utils_googlesql_base
#define googlesql_bison_parser googlesql_resolved_ast_rewrite_utils_googlesql_bison_parser
#define re2 googlesql_resolved_ast_rewrite_utils_re2
#define AbslInternalSleepFor googlesql_resolved_ast_rewrite_utils_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_resolved_ast_rewrite_utils_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_resolved_ast_rewrite_utils_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_resolved_ast_rewrite_utils_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_resolved_ast_rewrite_utils_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_resolved_ast_rewrite_utils_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_resolved_ast_rewrite_utils_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_resolved_ast_rewrite_utils_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_resolved_ast_rewrite_utils_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_resolved_ast_rewrite_utils_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_resolved_ast_rewrite_utils_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_resolved_ast_rewrite_utils_GoogleSqlalloc
#define GoogleSqlfree googlesql_resolved_ast_rewrite_utils_GoogleSqlfree
#define GoogleSqlrealloc googlesql_resolved_ast_rewrite_utils_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_resolved_ast_rewrite_utils_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_resolved_ast_rewrite_utils_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_resolved_ast_rewrite_utils_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_resolved_ast_rewrite_utils_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_resolved_ast_rewrite_utils_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_resolved_ast_rewrite_utils_GoogleSqlFlexLexer
#define UCaseMap googlesql_resolved_ast_rewrite_utils_UCaseMap

#define GO_EXPORT(def) export_googlesql_resolved_ast_rewrite_utils_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/resolved_ast/rewrite_utils.h"
//#undef private

// include sources
#include "googlesql/resolved_ast/rewrite_utils.cc"

// include dependencies
#include "go-zetasql/resolved_ast/column_factory/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-zetasql/analyzer/annotation_propagator/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/annotation/collation/export.inc"
#include "go-zetasql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_resolved_ast_rewrite_utils_bind_cc */
