#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_EVALUATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_EVALUATOR_EXPORT_H

#include "googlesql/public/evaluator.h"
// include sources
#include "googlesql/public/evaluator.cc"
// include dependencies
#include "go-zetasql/public/evaluator_base/export.inc"
#include "go-zetasql/common/evaluator_registration_utils/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
