#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_EVALUATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_EVALUATOR_EXPORT_H

#include "googlesql/public/evaluator.h"
// include sources
#include "googlesql/public/evaluator.cc"
// include dependencies
#include "go-googlesql/public/evaluator_base/export.inc"
#include "go-googlesql/common/evaluator_registration_utils/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
