#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_UNSUPPORTED_FIELDS_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_UNSUPPORTED_FIELDS_CC_PROTO_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/unsupported_fields.pb.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/unsupported_fields.pb.cc"
// include dependencies

#endif
