#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_MAP_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_MAP_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/base/map_traits.h"
#include "googlesql/legacy_zetasql/base/map_util.h"
// include sources
// include dependencies
#include "go-googlesql/legacy_zetasql/base/logging/export.inc"
#include "go-googlesql/legacy_zetasql/base/no_destructor/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#endif
