#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_GENERATE_ARRAY_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_GENERATE_ARRAY_EXPORT_H

#include "zetasql/public/functions/generate_array.h"
// include sources
// include dependencies
#include "go-zetasql/public/functions/arithmetics/export.inc"
#include "go-zetasql/public/functions/date_time_util/export.inc"
#include "go-zetasql/public/functions/datetime_cc_proto/export.inc"
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/time/time/export.inc"

#endif
