#ifndef INTERNAL_CCALL_GO_ABSL_CONTAINER_HASHTABLEZ_SAMPLER_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_CONTAINER_HASHTABLEZ_SAMPLER_EXPORT_H

#include "absl/container/internal/hashtablez_sampler.h"
// include sources
#include "absl/container/internal/hashtablez_sampler.cc"
#include "absl/container/internal/hashtablez_sampler_force_weak_definition.cc"
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/profiling/exponential_biased/export.inc"
#include "go-absl/profiling/sample_recorder/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
