
#ifndef googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_bind_cc
#define googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_bind_cc

// switch namespace
#define differential_privacy googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_differential_privacy
#define googlesql googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_googlesql
#define googlesql_base googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_googlesql_base
#define googlesql_bison_parser googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_googlesql_bison_parser
#define re2 googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_re2
#define AbslInternalSleepFor googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_GoogleSqlalloc
#define GoogleSqlfree googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_GoogleSqlfree
#define GoogleSqlrealloc googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_GoogleSqlFlexLexer
#define UCaseMap googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_UCaseMap

#define GO_EXPORT(def) export_googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/legacy_zetasql/analyzer/rewriters/order_by_and_limit_in_aggregate_rewriter.h"
//#undef private

// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/order_by_and_limit_in_aggregate_rewriter.cc"

// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_legacy_zetasql_analyzer_rewriters_order_by_and_limit_in_aggregate_rewriter_bind_cc */
