
#ifndef absl_status_status_bind_cc
#define absl_status_status_bind_cc

// switch namespace
#define differential_privacy absl_status_status_differential_privacy
#define googlesql absl_status_status_googlesql
#define googlesql_base absl_status_status_googlesql_base
#define googlesql_bison_parser absl_status_status_googlesql_bison_parser
#define re2 absl_status_status_re2
#define AbslInternalSleepFor absl_status_status_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_status_status_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_status_status_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_status_status_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_status_status_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_status_status_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_status_status_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_status_status_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_status_status_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_status_status_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_status_status_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_status_status_GoogleSqlalloc
#define GoogleSqlfree absl_status_status_GoogleSqlfree
#define GoogleSqlrealloc absl_status_status_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_status_status_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_status_status_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_status_status_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_status_status_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_status_status_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_status_status_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_status_status_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_status_status_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_status_status_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_status_status_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_status_status_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_status_status_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_status_status_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_status_status_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_status_status_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_status_status_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_status_status_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_status_status_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_status_status_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_status_status_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_status_status_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_status_status_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_status_status_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_status_status_GoogleSqlFlexLexer
#define UCaseMap absl_status_status_UCaseMap

#define GO_EXPORT(def) export_absl_status_status_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/status/status.h"
#include "absl/status/status_payload_printer.h"
//#undef private

// include sources
#include "absl/status/internal/status_internal.h"

// include dependencies
#include "go-absl/base/atomic_hook/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/base/strerror/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/debugging/symbolize/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_status_status_bind_cc */
