#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_CYCLE_DETECTOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_CYCLE_DETECTOR_EXPORT_H

#include "googlesql/legacy_zetasql/public/cycle_detector.h"
// include sources
#include "googlesql/legacy_zetasql/public/cycle_detector.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
