#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_LOG_IMPL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_LOG_IMPL_EXPORT_H

#include "absl/log/internal/log_impl.h"
// include sources
// include dependencies
#include "go-absl/log/go_internal/conditions/export.inc"
#include "go-absl/log/go_internal/log_message/export.inc"
#include "go-absl/log/go_internal/strip/export.inc"
#include "go-absl/log/absl_vlog_is_on/export.inc"

#endif
