
#ifndef absl_flags_usage_internal_bind_cc
#define absl_flags_usage_internal_bind_cc

// switch namespace
#define differential_privacy absl_flags_usage_internal_differential_privacy
#define googlesql absl_flags_usage_internal_googlesql
#define googlesql_base absl_flags_usage_internal_googlesql_base
#define googlesql_bison_parser absl_flags_usage_internal_googlesql_bison_parser
#define re2 absl_flags_usage_internal_re2
#define AbslInternalSleepFor absl_flags_usage_internal_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_flags_usage_internal_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_flags_usage_internal_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_flags_usage_internal_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_flags_usage_internal_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_flags_usage_internal_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_flags_usage_internal_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_flags_usage_internal_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_flags_usage_internal_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_flags_usage_internal_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_flags_usage_internal_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_flags_usage_internal_GoogleSqlalloc
#define GoogleSqlfree absl_flags_usage_internal_GoogleSqlfree
#define GoogleSqlrealloc absl_flags_usage_internal_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_flags_usage_internal_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_flags_usage_internal_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_flags_usage_internal_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_flags_usage_internal_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_flags_usage_internal_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_flags_usage_internal_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_flags_usage_internal_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_flags_usage_internal_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_flags_usage_internal_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_flags_usage_internal_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_flags_usage_internal_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_flags_usage_internal_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_flags_usage_internal_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_flags_usage_internal_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_flags_usage_internal_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_flags_usage_internal_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_flags_usage_internal_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_flags_usage_internal_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_flags_usage_internal_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_flags_usage_internal_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_flags_usage_internal_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_flags_usage_internal_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_flags_usage_internal_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_flags_usage_internal_GoogleSqlFlexLexer
#define UCaseMap absl_flags_usage_internal_UCaseMap

#define GO_EXPORT(def) export_absl_flags_usage_internal_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/flags/internal/usage.h"
//#undef private

// include sources
#include "absl/flags/internal/usage.cc"

// include dependencies
#include "go-absl/flags/commandlineflag/export.inc"
#include "go-absl/flags/config/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/flags/flag_internal/export.inc"
#include "go-absl/flags/path_util/export.inc"
#include "go-absl/flags/private_handle_accessor/export.inc"
#include "go-absl/flags/program_name/export.inc"
#include "go-absl/flags/reflection/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_flags_usage_internal_bind_cc */
