#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_PERCENTILE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_PERCENTILE_EXPORT_H

#include "zetasql/public/functions/percentile.h"
// include sources
#include "zetasql/public/functions/percentile.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/mathutil/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/multiprecision_int/export.inc"
#include "go-zetasql/public/collator/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
