#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_PROGRAM_NAME_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_PROGRAM_NAME_EXPORT_H

#include "absl/flags/internal/program_name.h"
// include sources
#include "absl/flags/internal/program_name.cc"
// include dependencies
#include "go-absl/flags/path_util/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
