#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_LAMBDA_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_LAMBDA_UTIL_EXPORT_H

#include "zetasql/analyzer/lambda_util.h"
// include sources
#include "zetasql/analyzer/lambda_util.cc"
// include dependencies
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
