#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ANNOTATION_DEFAULT_ANNOTATION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ANNOTATION_DEFAULT_ANNOTATION_EXPORT_H

#include "googlesql/legacy_zetasql/public/annotation/default_annotation_spec.h"
// include sources
#include "googlesql/legacy_zetasql/public/annotation/default_annotation_spec.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
