#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_TIMER_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_TIMER_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/common/timer_util.h"
// include sources
// include dependencies
#include "go-zetasql/legacy_zetasql/common/thread_stack/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/public/proto/logging_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/time/time/export.inc"

#endif
