
#ifndef absl_algorithm_container_bind_cc
#define absl_algorithm_container_bind_cc

// switch namespace
#define differential_privacy absl_algorithm_container_differential_privacy
#define googlesql absl_algorithm_container_googlesql
#define googlesql_base absl_algorithm_container_googlesql_base
#define googlesql_bison_parser absl_algorithm_container_googlesql_bison_parser
#define re2 absl_algorithm_container_re2
#define AbslInternalSleepFor absl_algorithm_container_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_algorithm_container_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_algorithm_container_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_algorithm_container_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_algorithm_container_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_algorithm_container_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_algorithm_container_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_algorithm_container_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_algorithm_container_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_algorithm_container_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_algorithm_container_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_algorithm_container_GoogleSqlalloc
#define GoogleSqlfree absl_algorithm_container_GoogleSqlfree
#define GoogleSqlrealloc absl_algorithm_container_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_algorithm_container_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_algorithm_container_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_algorithm_container_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_algorithm_container_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_algorithm_container_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_algorithm_container_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_algorithm_container_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_algorithm_container_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_algorithm_container_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_algorithm_container_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_algorithm_container_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_algorithm_container_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_algorithm_container_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_algorithm_container_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_algorithm_container_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_algorithm_container_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_algorithm_container_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_algorithm_container_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_algorithm_container_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_algorithm_container_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_algorithm_container_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_algorithm_container_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_algorithm_container_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_algorithm_container_GoogleSqlFlexLexer
#define UCaseMap absl_algorithm_container_UCaseMap

#define GO_EXPORT(def) export_absl_algorithm_container_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/algorithm/container.h"
//#undef private

// include sources

// include dependencies
#include "go-absl/algorithm/algorithm/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_algorithm_container_bind_cc */
