#ifndef INTERNAL_CCALL_GO_ALGORITHMS_RAND_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_RAND_EXPORT_H

#include "algorithms/rand.h"
// include sources
// include dependencies
#include "go-base/logging/export.inc"
#include "go-boringssl/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
