#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_STRING_NUMBERS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_STRING_NUMBERS_EXPORT_H

#include "googlesql/legacy_zetasql/base/string_numbers.h"
// include sources
#include "googlesql/legacy_zetasql/base/string_numbers.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/base/check/export.inc"
#include "go-googlesql/legacy_zetasql/base/logging/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
