#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_PROTO_HELPER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_PROTO_HELPER_EXPORT_H

#include "googlesql/common/proto_helper.h"
// include sources
#include "googlesql/common/proto_helper.cc"
// include dependencies
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
