#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_JSON_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_JSON_VALUE_EXPORT_H

#include "googlesql/public/json_value.h"
// include sources
#include "googlesql/public/json_value.cc"
// include dependencies
#include "go-zetasql/public/numeric_parser/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/multiprecision_int/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/compare/export.inc"

#endif
