#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_COMMON_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_COMMON_EXPORT_H

#include "zetasql/reference_impl/common.h"
#include "zetasql/reference_impl/variable_id.h"
// include sources
#include "zetasql/reference_impl/common.cc"
#include "zetasql/reference_impl/variable_id.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/collator_lite/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
