#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SQL_CONSTANT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SQL_CONSTANT_EXPORT_H

#include "zetasql/public/sql_constant.h"
// include sources
#include "zetasql/public/sql_constant.cc"
// include dependencies
#include "go-zetasql/public/constant/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
