#ifndef INTERNAL_CCALL_GO_GOOGLESQL_BASE_ENDIAN_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_BASE_ENDIAN_EXPORT_H

#include "googlesql/base/endian.h"
#include "googlesql/base/unaligned_access.h"
// include sources
// include dependencies
#include "go-googlesql/base/logging/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/int128/export.inc"

#endif
