#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_MATCHERS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_MATCHERS_EXPORT_H

#include "googlesql/common/match_recognize/nfa_matchers.h"
// include sources
#include "googlesql/common/match_recognize/nfa_matchers.cc"
// include dependencies
#include "go-zetasql/common/match_recognize/nfa/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
