#ifndef INTERNAL_CCALL_GO_ABSL_CONTAINER_BTREE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_CONTAINER_BTREE_EXPORT_H

#include "absl/container/btree_map.h"
#include "absl/container/btree_set.h"
// include sources
#include "absl/container/internal/btree.h"
#include "absl/container/internal/btree_container.h"
// include dependencies
#include "go-absl/container/common/export.inc"
#include "go-absl/container/common_policy_traits/export.inc"
#include "go-absl/container/compressed_tuple/export.inc"
#include "go-absl/container/container_memory/export.inc"
#include "go-absl/container/layout/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/base/throw_delegate/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/types/compare/export.inc"

#endif
