#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_REFLECTION_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_REFLECTION_EXPORT_H

#include "absl/flags/internal/registry.h"
#include "absl/flags/reflection.h"
// include sources
#include "absl/flags/reflection.cc"
// include dependencies
#include "go-absl/flags/commandlineflag/export.inc"
#include "go-absl/flags/commandlineflag_internal/export.inc"
#include "go-absl/flags/config/export.inc"
#include "go-absl/flags/private_handle_accessor/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
