#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_UPDATE_CONSTRUCTOR_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_UPDATE_CONSTRUCTOR_REWRITER_EXPORT_H

#include "zetasql/analyzer/rewriters/update_constructor_rewriter.h"
// include sources
#include "zetasql/analyzer/rewriters/update_constructor_rewriter.cc"
// include dependencies
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output_properties/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
