#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_LANGUAGE_OPTIONS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_LANGUAGE_OPTIONS_EXPORT_H

#include "googlesql/public/language_options.h"
// include sources
#include "googlesql/public/language_options.cc"
// include dependencies
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/parser/keywords/export.inc"
#include "go-zetasql/proto/options_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-googletest/googletest/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
