#ifndef INTERNAL_CCALL_GO_ABSL_CONTAINER_CONTAINER_MEMORY_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_CONTAINER_CONTAINER_MEMORY_EXPORT_H

#include "absl/container/internal/container_memory.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
