#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_TOKEN_SPLICING_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_TOKEN_SPLICING_UTILS_EXPORT_H

#include "zetasql/parser/macros/token_splicing_utils.h"
// include sources
#include "zetasql/parser/macros/token_splicing_utils.cc"
// include dependencies
#include "go-zetasql/parser/keywords/export.inc"
#include "go-zetasql/parser/token/export.inc"
#include "go-zetasql/parser/token_codes/export.inc"
#include "go-zetasql/parser/token_with_location/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
