#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_CANONICALIZE_SIGNED_ZERO_TO_STRING_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_CANONICALIZE_SIGNED_ZERO_TO_STRING_EXPORT_H

#include "googlesql/legacy_zetasql/common/canonicalize_signed_zero_to_string.h"
// include sources
#include "googlesql/legacy_zetasql/common/canonicalize_signed_zero_to_string.cc"
// include dependencies
#include "go-absl/flags/flag/export.inc"

#endif
