#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_DECODE_RUST_PUNYCODE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_DECODE_RUST_PUNYCODE_EXPORT_H

#include "absl/debugging/internal/decode_rust_punycode.h"
// include sources
// include dependencies
#include "go-absl/debugging/bounded_utf8_length_sequence/export.inc"
#include "go-absl/debugging/utf8_for_code_point/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/nullability/export.inc"

#endif
