#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_INTERNAL_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_INTERNAL_VALUE_EXPORT_H

#include "googlesql/common/internal_value.h"
// include sources
#include "googlesql/common/internal_value.cc"
// include dependencies
#include "go-googlesql/common/float_margin/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/public/types/value_representations/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
