#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_SCRIPTING_PARSED_SCRIPT_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_SCRIPTING_PARSED_SCRIPT_EXPORT_H

#include "googlesql/legacy_zetasql/scripting/parsed_script.h"
// include sources
#include "googlesql/legacy_zetasql/scripting/parsed_script.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/scripting/control_flow_graph/export.inc"
#include "go-googlesql/legacy_zetasql/scripting/error_helpers/export.inc"
#include "go-googlesql/legacy_zetasql/scripting/type_aliases/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/strings/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/variant/export.inc"

#endif
