#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_STR_FORMAT_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_STR_FORMAT_INTERNAL_EXPORT_H

#include "absl/strings/internal/str_format/arg.h"
#include "absl/strings/internal/str_format/bind.h"
#include "absl/strings/internal/str_format/checker.h"
#include "absl/strings/internal/str_format/constexpr_parser.h"
#include "absl/strings/internal/str_format/extension.h"
#include "absl/strings/internal/str_format/float_conversion.h"
#include "absl/strings/internal/str_format/output.h"
#include "absl/strings/internal/str_format/parser.h"
// include sources
#include "absl/strings/internal/str_format/arg.cc"
#include "absl/strings/internal/str_format/bind.cc"
#include "absl/strings/internal/str_format/extension.cc"
#include "absl/strings/internal/str_format/float_conversion.cc"
#include "absl/strings/internal/str_format/output.cc"
#include "absl/strings/internal/str_format/parser.cc"
// include dependencies
#include "go-absl/strings/strings/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/fixed_array/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/numeric/representation/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
