#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_MARSHALLING_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_MARSHALLING_EXPORT_H

#include "absl/flags/marshalling.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
