#ifndef INTERNAL_CCALL_GO_ABSL_STATUS_STATUSOR_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STATUS_STATUSOR_EXPORT_H

#include "absl/status/statusor.h"
// include sources
#include "absl/status/internal/statusor_internal.h"
// include dependencies
#include "go-absl/status/status/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/has_ostream_operator/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/variant/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
