#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_REGISTRATION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_REGISTRATION_EXPORT_H

#include "googlesql/analyzer/rewriters/registration.h"
// include sources
#include "googlesql/analyzer/rewriters/registration.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
