#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_RANGE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_RANGE_EXPORT_H

#include "zetasql/public/functions/range.h"
// include sources
#include "zetasql/public/functions/range.cc"
// include dependencies
#include "go-zetasql/public/functions/date_time_util/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/endian/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/public/interval_value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"

#endif
