#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_MAP_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_MAP_EXPORT_H

#include "googlesql/reference_impl/functions/map.h"
// include sources
#include "googlesql/reference_impl/functions/map.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/optional_ref/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/internal_value/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
