#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_COLLATOR_LITE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_COLLATOR_LITE_EXPORT_H

#include "googlesql/public/collator.h"
// include sources
#include "googlesql/public/collator_lite.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-icu/icu/export.inc"

#endif
