#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_AGGREGATION_THRESHOLD_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_AGGREGATION_THRESHOLD_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/aggregation_threshold_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/aggregation_threshold_rewriter.cc"
// include dependencies
#include "go-googlesql/analyzer/rewriters/anonymization_helper/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
