#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_INFO_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_INFO_EXPORT_H

#include "absl/strings/internal/cordz_info.h"
// include sources
#include "absl/strings/internal/cordz_info.cc"
// include dependencies
#include "go-absl/strings/cord_internal/export.inc"
#include "go-absl/strings/cordz_functions/export.inc"
#include "go-absl/strings/cordz_handle/export.inc"
#include "go-absl/strings/cordz_statistics/export.inc"
#include "go-absl/strings/cordz_update_tracker/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
