#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_UUID_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_UUID_VALUE_EXPORT_H

#include "zetasql/public/uuid_value.h"
// include sources
#include "zetasql/public/uuid_value.cc"
// include dependencies
#include "go-zetasql/base/endian/export.inc"
#include "go-zetasql/base/no_destructor/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
