#ifndef INTERNAL_CCALL_GO_GOOGLESQL_BASE_NET_IDN_OSS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_BASE_NET_IDN_OSS_EXPORT_H

#include "googlesql/base/net/idn_oss.h"
// include sources
#include "googlesql/base/net/idn_oss.cc"
// include dependencies
#include "go-googlesql/base/logging/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-icu/icu/export.inc"

#endif
