#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_CONVERT_STRING_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_CONVERT_STRING_EXPORT_H

#include "zetasql/public/functions/convert_string.h"
// include sources
#include "zetasql/public/functions/convert_string.cc"
// include dependencies
#include "go-zetasql/public/functions/util/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/string_util/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
