#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_SUBPIPELINE_STMT_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_SUBPIPELINE_STMT_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/subpipeline_stmt_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/subpipeline_stmt_rewriter.cc"
// include dependencies
#include "go-zetasql/analyzer/rewriters/rewrite_subpipeline/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
