#ifndef INTERNAL_CCALL_GO_ABSL_CONTAINER_LAYOUT_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_CONTAINER_LAYOUT_EXPORT_H

#include "absl/container/internal/layout.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
