#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_RANK_TYPE_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_RANK_TYPE_CC_PROTO_EXPORT_H

#include "googlesql/public/functions/rank_type.pb.h"
// include sources
#define schemas googlesql_public_functions_rank_type_schemas
#define file_default_instances googlesql_public_functions_rank_type_file_default_instances
#include "googlesql/public/functions/rank_type.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies

#endif
