#ifndef ZETASQL_PROTO_ANON_OUTPUT_WITH_REPORT_CC_PROTO_EXPORT_H
#define ZETASQL_PROTO_ANON_OUTPUT_WITH_REPORT_CC_PROTO_EXPORT_H

#include "zetasql/proto/anon_output_with_report.pb.h"
#define schemas go_zetasql_proto_anon_output_with_report_cc_proto_schemas
#define file_default_instances go_zetasql_proto_anon_output_with_report_cc_proto_file_default_instances
#include "zetasql/proto/anon_output_with_report.pb.cc"
#undef file_default_instances
#undef schemas

#include "go-protobuf/protobuf/export.inc"

#endif
