// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/functions/match_recognize/compiled_pattern.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/functions/match_recognize/compiled_pattern.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {
namespace functions {
namespace match_recognize {

inline constexpr StateMachineProto_CompiledNFAProto_EdgeProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        to_state_{0},
        pattern_variable_{0},
        is_head_anchored_{false},
        is_tail_anchored_{false} {}

template <typename>
PROTOBUF_CONSTEXPR StateMachineProto_CompiledNFAProto_EdgeProto::StateMachineProto_CompiledNFAProto_EdgeProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StateMachineProto_CompiledNFAProto_EdgeProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateMachineProto_CompiledNFAProto_EdgeProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateMachineProto_CompiledNFAProto_EdgeProtoDefaultTypeInternal() {}
  union {
    StateMachineProto_CompiledNFAProto_EdgeProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateMachineProto_CompiledNFAProto_EdgeProtoDefaultTypeInternal _StateMachineProto_CompiledNFAProto_EdgeProto_default_instance_;

inline constexpr StateMachineProto_CompiledNFAProto_StateProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : edges_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StateMachineProto_CompiledNFAProto_StateProto::StateMachineProto_CompiledNFAProto_StateProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StateMachineProto_CompiledNFAProto_StateProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateMachineProto_CompiledNFAProto_StateProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateMachineProto_CompiledNFAProto_StateProtoDefaultTypeInternal() {}
  union {
    StateMachineProto_CompiledNFAProto_StateProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateMachineProto_CompiledNFAProto_StateProtoDefaultTypeInternal _StateMachineProto_CompiledNFAProto_StateProto_default_instance_;

inline constexpr StateMachineProto_CompiledNFAProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        states_{},
        start_state_{0},
        final_state_{0},
        num_pattern_variables_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StateMachineProto_CompiledNFAProto::StateMachineProto_CompiledNFAProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StateMachineProto_CompiledNFAProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateMachineProto_CompiledNFAProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateMachineProto_CompiledNFAProtoDefaultTypeInternal() {}
  union {
    StateMachineProto_CompiledNFAProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateMachineProto_CompiledNFAProtoDefaultTypeInternal _StateMachineProto_CompiledNFAProto_default_instance_;

inline constexpr StateMachineProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nfa_{nullptr},
        after_match_skip_mode_{static_cast< ::googlesql::ResolvedMatchRecognizeScanEnums_AfterMatchSkipMode >(0)},
        longest_match_mode_{false} {}

template <typename>
PROTOBUF_CONSTEXPR StateMachineProto::StateMachineProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StateMachineProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StateMachineProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StateMachineProtoDefaultTypeInternal() {}
  union {
    StateMachineProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StateMachineProtoDefaultTypeInternal _StateMachineProto_default_instance_;

inline constexpr CompiledPatternProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : variant_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR CompiledPatternProto::CompiledPatternProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CompiledPatternProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompiledPatternProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompiledPatternProtoDefaultTypeInternal() {}
  union {
    CompiledPatternProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompiledPatternProtoDefaultTypeInternal _CompiledPatternProto_default_instance_;
}  // namespace match_recognize
}  // namespace functions
}  // namespace googlesql
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.to_state_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.pattern_variable_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_head_anchored_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_tail_anchored_),
        0,
        1,
        2,
        3,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_StateProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_StateProto, _impl_.edges_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto, _impl_.states_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto, _impl_.start_state_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto, _impl_.final_state_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto, _impl_.num_pattern_variables_),
        ~0u,
        0,
        1,
        2,
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto, _impl_.nfa_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto, _impl_.after_match_skip_mode_),
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::StateMachineProto, _impl_.longest_match_mode_),
        0,
        1,
        2,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::CompiledPatternProto, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::CompiledPatternProto, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::CompiledPatternProto, _impl_.variant_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto)},
        {16, -1, -1, sizeof(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_StateProto)},
        {25, 37, -1, sizeof(::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto)},
        {41, 52, -1, sizeof(::googlesql::functions::match_recognize::StateMachineProto)},
        {55, -1, -1, sizeof(::googlesql::functions::match_recognize::CompiledPatternProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::functions::match_recognize::_StateMachineProto_CompiledNFAProto_EdgeProto_default_instance_._instance,
    &::googlesql::functions::match_recognize::_StateMachineProto_CompiledNFAProto_StateProto_default_instance_._instance,
    &::googlesql::functions::match_recognize::_StateMachineProto_CompiledNFAProto_default_instance_._instance,
    &::googlesql::functions::match_recognize::_StateMachineProto_default_instance_._instance,
    &::googlesql::functions::match_recognize::_CompiledPatternProto_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\nAgooglesql/public/functions/match_recog"
    "nize/compiled_pattern.proto\022#googlesql.f"
    "unctions.match_recognize\032/googlesql/reso"
    "lved_ast/resolved_ast_enums.proto\"\202\005\n\021St"
    "ateMachineProto\022T\n\003nfa\030\001 \001(\0132G.googlesql"
    ".functions.match_recognize.StateMachineP"
    "roto.CompiledNFAProto\022\\\n\025after_match_ski"
    "p_mode\030\002 \001(\0162=.googlesql.ResolvedMatchRe"
    "cognizeScanEnums.AfterMatchSkipMode\022\032\n\022l"
    "ongest_match_mode\030\003 \001(\010\032\234\003\n\020CompiledNFAP"
    "roto\022b\n\006states\030\001 \003(\0132R.googlesql.functio"
    "ns.match_recognize.StateMachineProto.Com"
    "piledNFAProto.StateProto\022\023\n\013start_state\030"
    "\002 \001(\005\022\023\n\013final_state\030\003 \001(\005\022\035\n\025num_patter"
    "n_variables\030\004 \001(\005\032k\n\tEdgeProto\022\020\n\010to_sta"
    "te\030\003 \001(\005\022\030\n\020pattern_variable\030\004 \001(\005\022\030\n\020is"
    "_head_anchored\030\005 \001(\010\022\030\n\020is_tail_anchored"
    "\030\006 \001(\010\032n\n\nStateProto\022`\n\005edges\030\001 \003(\0132Q.go"
    "oglesql.functions.match_recognize.StateM"
    "achineProto.CompiledNFAProto.EdgeProto\"r"
    "\n\024CompiledPatternProto\022O\n\rstate_machine\030"
    "\001 \001(\01326.googlesql.functions.match_recogn"
    "ize.StateMachineProtoH\000B\t\n\007variant"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto_deps[1] =
    {
        &::descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto = {
    false,
    false,
    914,
    descriptor_table_protodef_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    "googlesql/public/functions/match_recognize/compiled_pattern.proto",
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto_once,
    descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
};
namespace googlesql {
namespace functions {
namespace match_recognize {
// ===================================================================

class StateMachineProto_CompiledNFAProto_EdgeProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<StateMachineProto_CompiledNFAProto_EdgeProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_._has_bits_);
};

StateMachineProto_CompiledNFAProto_EdgeProto::StateMachineProto_CompiledNFAProto_EdgeProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
}
StateMachineProto_CompiledNFAProto_EdgeProto::StateMachineProto_CompiledNFAProto_EdgeProto(
    ::google::protobuf::Arena* arena, const StateMachineProto_CompiledNFAProto_EdgeProto& from)
    : StateMachineProto_CompiledNFAProto_EdgeProto(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto_CompiledNFAProto_EdgeProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void StateMachineProto_CompiledNFAProto_EdgeProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, to_state_),
           0,
           offsetof(Impl_, is_tail_anchored_) -
               offsetof(Impl_, to_state_) +
               sizeof(Impl_::is_tail_anchored_));
}
StateMachineProto_CompiledNFAProto_EdgeProto::~StateMachineProto_CompiledNFAProto_EdgeProto() {
  // @@protoc_insertion_point(destructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
  SharedDtor(*this);
}
inline void StateMachineProto_CompiledNFAProto_EdgeProto::SharedDtor(MessageLite& self) {
  StateMachineProto_CompiledNFAProto_EdgeProto& this_ = static_cast<StateMachineProto_CompiledNFAProto_EdgeProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* StateMachineProto_CompiledNFAProto_EdgeProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StateMachineProto_CompiledNFAProto_EdgeProto(arena);
}
constexpr auto StateMachineProto_CompiledNFAProto_EdgeProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StateMachineProto_CompiledNFAProto_EdgeProto),
                                            alignof(StateMachineProto_CompiledNFAProto_EdgeProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StateMachineProto_CompiledNFAProto_EdgeProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StateMachineProto_CompiledNFAProto_EdgeProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StateMachineProto_CompiledNFAProto_EdgeProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StateMachineProto_CompiledNFAProto_EdgeProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StateMachineProto_CompiledNFAProto_EdgeProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StateMachineProto_CompiledNFAProto_EdgeProto>(), &StateMachineProto_CompiledNFAProto_EdgeProto::ByteSizeLong,
            &StateMachineProto_CompiledNFAProto_EdgeProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_._cached_size_),
        false,
    },
    &StateMachineProto_CompiledNFAProto_EdgeProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StateMachineProto_CompiledNFAProto_EdgeProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> StateMachineProto_CompiledNFAProto_EdgeProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_._has_bits_),
    0, // no _extensions_
    6, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967235,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 pattern_variable = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.pattern_variable_), 1>(),
     {32, 1, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.pattern_variable_)}},
    // optional bool is_head_anchored = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_head_anchored_), 2>(),
     {40, 2, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_head_anchored_)}},
    // optional bool is_tail_anchored = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_tail_anchored_), 3>(),
     {48, 3, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_tail_anchored_)}},
    // optional int32 to_state = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.to_state_), 0>(),
     {24, 0, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.to_state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 to_state = 3;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.to_state_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 pattern_variable = 4;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.pattern_variable_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bool is_head_anchored = 5;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_head_anchored_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool is_tail_anchored = 6;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_tail_anchored_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void StateMachineProto_CompiledNFAProto_EdgeProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.to_state_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_tail_anchored_) -
        reinterpret_cast<char*>(&_impl_.to_state_)) + sizeof(_impl_.is_tail_anchored_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StateMachineProto_CompiledNFAProto_EdgeProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StateMachineProto_CompiledNFAProto_EdgeProto& this_ = static_cast<const StateMachineProto_CompiledNFAProto_EdgeProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StateMachineProto_CompiledNFAProto_EdgeProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StateMachineProto_CompiledNFAProto_EdgeProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 to_state = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_to_state(), target);
          }

          // optional int32 pattern_variable = 4;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_pattern_variable(), target);
          }

          // optional bool is_head_anchored = 5;
          if (cached_has_bits & 0x00000004u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_is_head_anchored(), target);
          }

          // optional bool is_tail_anchored = 6;
          if (cached_has_bits & 0x00000008u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_is_tail_anchored(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StateMachineProto_CompiledNFAProto_EdgeProto::ByteSizeLong(const MessageLite& base) {
          const StateMachineProto_CompiledNFAProto_EdgeProto& this_ = static_cast<const StateMachineProto_CompiledNFAProto_EdgeProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StateMachineProto_CompiledNFAProto_EdgeProto::ByteSizeLong() const {
          const StateMachineProto_CompiledNFAProto_EdgeProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000000fu) {
            // optional int32 to_state = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_to_state());
            }
            // optional int32 pattern_variable = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_pattern_variable());
            }
            // optional bool is_head_anchored = 5;
            if (cached_has_bits & 0x00000004u) {
              total_size += 2;
            }
            // optional bool is_tail_anchored = 6;
            if (cached_has_bits & 0x00000008u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StateMachineProto_CompiledNFAProto_EdgeProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StateMachineProto_CompiledNFAProto_EdgeProto*>(&to_msg);
  auto& from = static_cast<const StateMachineProto_CompiledNFAProto_EdgeProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.to_state_ = from._impl_.to_state_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.pattern_variable_ = from._impl_.pattern_variable_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.is_head_anchored_ = from._impl_.is_head_anchored_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.is_tail_anchored_ = from._impl_.is_tail_anchored_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StateMachineProto_CompiledNFAProto_EdgeProto::CopyFrom(const StateMachineProto_CompiledNFAProto_EdgeProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StateMachineProto_CompiledNFAProto_EdgeProto::InternalSwap(StateMachineProto_CompiledNFAProto_EdgeProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.is_tail_anchored_)
      + sizeof(StateMachineProto_CompiledNFAProto_EdgeProto::_impl_.is_tail_anchored_)
      - PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_EdgeProto, _impl_.to_state_)>(
          reinterpret_cast<char*>(&_impl_.to_state_),
          reinterpret_cast<char*>(&other->_impl_.to_state_));
}

::google::protobuf::Metadata StateMachineProto_CompiledNFAProto_EdgeProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StateMachineProto_CompiledNFAProto_StateProto::_Internal {
 public:
};

StateMachineProto_CompiledNFAProto_StateProto::StateMachineProto_CompiledNFAProto_StateProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto_CompiledNFAProto_StateProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_StateProto& from_msg)
      : edges_{visibility, arena, from.edges_},
        _cached_size_{0} {}

StateMachineProto_CompiledNFAProto_StateProto::StateMachineProto_CompiledNFAProto_StateProto(
    ::google::protobuf::Arena* arena,
    const StateMachineProto_CompiledNFAProto_StateProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StateMachineProto_CompiledNFAProto_StateProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto_CompiledNFAProto_StateProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : edges_{visibility, arena},
        _cached_size_{0} {}

inline void StateMachineProto_CompiledNFAProto_StateProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
StateMachineProto_CompiledNFAProto_StateProto::~StateMachineProto_CompiledNFAProto_StateProto() {
  // @@protoc_insertion_point(destructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
  SharedDtor(*this);
}
inline void StateMachineProto_CompiledNFAProto_StateProto::SharedDtor(MessageLite& self) {
  StateMachineProto_CompiledNFAProto_StateProto& this_ = static_cast<StateMachineProto_CompiledNFAProto_StateProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* StateMachineProto_CompiledNFAProto_StateProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StateMachineProto_CompiledNFAProto_StateProto(arena);
}
constexpr auto StateMachineProto_CompiledNFAProto_StateProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_StateProto, _impl_.edges_) +
          decltype(StateMachineProto_CompiledNFAProto_StateProto::_impl_.edges_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(StateMachineProto_CompiledNFAProto_StateProto), alignof(StateMachineProto_CompiledNFAProto_StateProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&StateMachineProto_CompiledNFAProto_StateProto::PlacementNew_,
                                 sizeof(StateMachineProto_CompiledNFAProto_StateProto),
                                 alignof(StateMachineProto_CompiledNFAProto_StateProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StateMachineProto_CompiledNFAProto_StateProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StateMachineProto_CompiledNFAProto_StateProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StateMachineProto_CompiledNFAProto_StateProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StateMachineProto_CompiledNFAProto_StateProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StateMachineProto_CompiledNFAProto_StateProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StateMachineProto_CompiledNFAProto_StateProto>(), &StateMachineProto_CompiledNFAProto_StateProto::ByteSizeLong,
            &StateMachineProto_CompiledNFAProto_StateProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_StateProto, _impl_._cached_size_),
        false,
    },
    &StateMachineProto_CompiledNFAProto_StateProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StateMachineProto_CompiledNFAProto_StateProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> StateMachineProto_CompiledNFAProto_StateProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_StateProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto edges = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_StateProto, _impl_.edges_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto edges = 1;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto_StateProto, _impl_.edges_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_EdgeProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void StateMachineProto_CompiledNFAProto_StateProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.edges_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StateMachineProto_CompiledNFAProto_StateProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StateMachineProto_CompiledNFAProto_StateProto& this_ = static_cast<const StateMachineProto_CompiledNFAProto_StateProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StateMachineProto_CompiledNFAProto_StateProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StateMachineProto_CompiledNFAProto_StateProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto edges = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_edges_size());
               i < n; i++) {
            const auto& repfield = this_._internal_edges().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StateMachineProto_CompiledNFAProto_StateProto::ByteSizeLong(const MessageLite& base) {
          const StateMachineProto_CompiledNFAProto_StateProto& this_ = static_cast<const StateMachineProto_CompiledNFAProto_StateProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StateMachineProto_CompiledNFAProto_StateProto::ByteSizeLong() const {
          const StateMachineProto_CompiledNFAProto_StateProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.EdgeProto edges = 1;
            {
              total_size += 1UL * this_._internal_edges_size();
              for (const auto& msg : this_._internal_edges()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StateMachineProto_CompiledNFAProto_StateProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StateMachineProto_CompiledNFAProto_StateProto*>(&to_msg);
  auto& from = static_cast<const StateMachineProto_CompiledNFAProto_StateProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_edges()->MergeFrom(
      from._internal_edges());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StateMachineProto_CompiledNFAProto_StateProto::CopyFrom(const StateMachineProto_CompiledNFAProto_StateProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StateMachineProto_CompiledNFAProto_StateProto::InternalSwap(StateMachineProto_CompiledNFAProto_StateProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.edges_.InternalSwap(&other->_impl_.edges_);
}

::google::protobuf::Metadata StateMachineProto_CompiledNFAProto_StateProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StateMachineProto_CompiledNFAProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<StateMachineProto_CompiledNFAProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_._has_bits_);
};

StateMachineProto_CompiledNFAProto::StateMachineProto_CompiledNFAProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto_CompiledNFAProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        states_{visibility, arena, from.states_} {}

StateMachineProto_CompiledNFAProto::StateMachineProto_CompiledNFAProto(
    ::google::protobuf::Arena* arena,
    const StateMachineProto_CompiledNFAProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StateMachineProto_CompiledNFAProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_state_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, start_state_),
           offsetof(Impl_, num_pattern_variables_) -
               offsetof(Impl_, start_state_) +
               sizeof(Impl_::num_pattern_variables_));

  // @@protoc_insertion_point(copy_constructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto_CompiledNFAProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        states_{visibility, arena} {}

inline void StateMachineProto_CompiledNFAProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, start_state_),
           0,
           offsetof(Impl_, num_pattern_variables_) -
               offsetof(Impl_, start_state_) +
               sizeof(Impl_::num_pattern_variables_));
}
StateMachineProto_CompiledNFAProto::~StateMachineProto_CompiledNFAProto() {
  // @@protoc_insertion_point(destructor:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
  SharedDtor(*this);
}
inline void StateMachineProto_CompiledNFAProto::SharedDtor(MessageLite& self) {
  StateMachineProto_CompiledNFAProto& this_ = static_cast<StateMachineProto_CompiledNFAProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* StateMachineProto_CompiledNFAProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StateMachineProto_CompiledNFAProto(arena);
}
constexpr auto StateMachineProto_CompiledNFAProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.states_) +
          decltype(StateMachineProto_CompiledNFAProto::_impl_.states_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(StateMachineProto_CompiledNFAProto), alignof(StateMachineProto_CompiledNFAProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&StateMachineProto_CompiledNFAProto::PlacementNew_,
                                 sizeof(StateMachineProto_CompiledNFAProto),
                                 alignof(StateMachineProto_CompiledNFAProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StateMachineProto_CompiledNFAProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StateMachineProto_CompiledNFAProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StateMachineProto_CompiledNFAProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StateMachineProto_CompiledNFAProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StateMachineProto_CompiledNFAProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StateMachineProto_CompiledNFAProto>(), &StateMachineProto_CompiledNFAProto::ByteSizeLong,
            &StateMachineProto_CompiledNFAProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_._cached_size_),
        false,
    },
    &StateMachineProto_CompiledNFAProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StateMachineProto_CompiledNFAProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> StateMachineProto_CompiledNFAProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 num_pattern_variables = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StateMachineProto_CompiledNFAProto, _impl_.num_pattern_variables_), 2>(),
     {32, 2, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.num_pattern_variables_)}},
    // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto states = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.states_)}},
    // optional int32 start_state = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StateMachineProto_CompiledNFAProto, _impl_.start_state_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.start_state_)}},
    // optional int32 final_state = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StateMachineProto_CompiledNFAProto, _impl_.final_state_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.final_state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto states = 1;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.states_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 start_state = 2;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.start_state_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 final_state = 3;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.final_state_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 num_pattern_variables = 4;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.num_pattern_variables_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto_StateProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void StateMachineProto_CompiledNFAProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.states_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.start_state_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.num_pattern_variables_) -
        reinterpret_cast<char*>(&_impl_.start_state_)) + sizeof(_impl_.num_pattern_variables_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StateMachineProto_CompiledNFAProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StateMachineProto_CompiledNFAProto& this_ = static_cast<const StateMachineProto_CompiledNFAProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StateMachineProto_CompiledNFAProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StateMachineProto_CompiledNFAProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto states = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_states_size());
               i < n; i++) {
            const auto& repfield = this_._internal_states().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 start_state = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_start_state(), target);
          }

          // optional int32 final_state = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_final_state(), target);
          }

          // optional int32 num_pattern_variables = 4;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_num_pattern_variables(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StateMachineProto_CompiledNFAProto::ByteSizeLong(const MessageLite& base) {
          const StateMachineProto_CompiledNFAProto& this_ = static_cast<const StateMachineProto_CompiledNFAProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StateMachineProto_CompiledNFAProto::ByteSizeLong() const {
          const StateMachineProto_CompiledNFAProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto.StateProto states = 1;
            {
              total_size += 1UL * this_._internal_states_size();
              for (const auto& msg : this_._internal_states()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // optional int32 start_state = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_start_state());
            }
            // optional int32 final_state = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_final_state());
            }
            // optional int32 num_pattern_variables = 4;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_num_pattern_variables());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StateMachineProto_CompiledNFAProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StateMachineProto_CompiledNFAProto*>(&to_msg);
  auto& from = static_cast<const StateMachineProto_CompiledNFAProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_states()->MergeFrom(
      from._internal_states());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.start_state_ = from._impl_.start_state_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.final_state_ = from._impl_.final_state_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.num_pattern_variables_ = from._impl_.num_pattern_variables_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StateMachineProto_CompiledNFAProto::CopyFrom(const StateMachineProto_CompiledNFAProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StateMachineProto_CompiledNFAProto::InternalSwap(StateMachineProto_CompiledNFAProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.states_.InternalSwap(&other->_impl_.states_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.num_pattern_variables_)
      + sizeof(StateMachineProto_CompiledNFAProto::_impl_.num_pattern_variables_)
      - PROTOBUF_FIELD_OFFSET(StateMachineProto_CompiledNFAProto, _impl_.start_state_)>(
          reinterpret_cast<char*>(&_impl_.start_state_),
          reinterpret_cast<char*>(&other->_impl_.start_state_));
}

::google::protobuf::Metadata StateMachineProto_CompiledNFAProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StateMachineProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<StateMachineProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_._has_bits_);
};

StateMachineProto::StateMachineProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.match_recognize.StateMachineProto)
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::functions::match_recognize::StateMachineProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

StateMachineProto::StateMachineProto(
    ::google::protobuf::Arena* arena,
    const StateMachineProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StateMachineProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.nfa_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto>(
                              arena, *from._impl_.nfa_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, after_match_skip_mode_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, after_match_skip_mode_),
           offsetof(Impl_, longest_match_mode_) -
               offsetof(Impl_, after_match_skip_mode_) +
               sizeof(Impl_::longest_match_mode_));

  // @@protoc_insertion_point(copy_constructor:googlesql.functions.match_recognize.StateMachineProto)
}
inline PROTOBUF_NDEBUG_INLINE StateMachineProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void StateMachineProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, nfa_),
           0,
           offsetof(Impl_, longest_match_mode_) -
               offsetof(Impl_, nfa_) +
               sizeof(Impl_::longest_match_mode_));
}
StateMachineProto::~StateMachineProto() {
  // @@protoc_insertion_point(destructor:googlesql.functions.match_recognize.StateMachineProto)
  SharedDtor(*this);
}
inline void StateMachineProto::SharedDtor(MessageLite& self) {
  StateMachineProto& this_ = static_cast<StateMachineProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.nfa_;
  this_._impl_.~Impl_();
}

inline void* StateMachineProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StateMachineProto(arena);
}
constexpr auto StateMachineProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StateMachineProto),
                                            alignof(StateMachineProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StateMachineProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StateMachineProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StateMachineProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StateMachineProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StateMachineProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StateMachineProto>(), &StateMachineProto::ByteSizeLong,
            &StateMachineProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_._cached_size_),
        false,
    },
    &StateMachineProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StateMachineProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> StateMachineProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto nfa = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.nfa_)}},
    // optional .googlesql.ResolvedMatchRecognizeScanEnums.AfterMatchSkipMode after_match_skip_mode = 2;
    {::_pbi::TcParser::FastEr0S1,
     {16, 1, 2, PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.after_match_skip_mode_)}},
    // optional bool longest_match_mode = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(StateMachineProto, _impl_.longest_match_mode_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.longest_match_mode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto nfa = 1;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.nfa_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .googlesql.ResolvedMatchRecognizeScanEnums.AfterMatchSkipMode after_match_skip_mode = 2;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.after_match_skip_mode_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional bool longest_match_mode = 3;
    {PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.longest_match_mode_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto>()},
    {0, 3},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void StateMachineProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.functions.match_recognize.StateMachineProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.nfa_ != nullptr);
    _impl_.nfa_->Clear();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.after_match_skip_mode_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.longest_match_mode_) -
        reinterpret_cast<char*>(&_impl_.after_match_skip_mode_)) + sizeof(_impl_.longest_match_mode_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StateMachineProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StateMachineProto& this_ = static_cast<const StateMachineProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StateMachineProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StateMachineProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.functions.match_recognize.StateMachineProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto nfa = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.nfa_, this_._impl_.nfa_->GetCachedSize(), target,
                stream);
          }

          // optional .googlesql.ResolvedMatchRecognizeScanEnums.AfterMatchSkipMode after_match_skip_mode = 2;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_after_match_skip_mode(), target);
          }

          // optional bool longest_match_mode = 3;
          if (cached_has_bits & 0x00000004u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_longest_match_mode(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.functions.match_recognize.StateMachineProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StateMachineProto::ByteSizeLong(const MessageLite& base) {
          const StateMachineProto& this_ = static_cast<const StateMachineProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StateMachineProto::ByteSizeLong() const {
          const StateMachineProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.functions.match_recognize.StateMachineProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // optional .googlesql.functions.match_recognize.StateMachineProto.CompiledNFAProto nfa = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.nfa_);
            }
            // optional .googlesql.ResolvedMatchRecognizeScanEnums.AfterMatchSkipMode after_match_skip_mode = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_after_match_skip_mode());
            }
            // optional bool longest_match_mode = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StateMachineProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StateMachineProto*>(&to_msg);
  auto& from = static_cast<const StateMachineProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.functions.match_recognize.StateMachineProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.nfa_ != nullptr);
      if (_this->_impl_.nfa_ == nullptr) {
        _this->_impl_.nfa_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::functions::match_recognize::StateMachineProto_CompiledNFAProto>(arena, *from._impl_.nfa_);
      } else {
        _this->_impl_.nfa_->MergeFrom(*from._impl_.nfa_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.after_match_skip_mode_ = from._impl_.after_match_skip_mode_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.longest_match_mode_ = from._impl_.longest_match_mode_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StateMachineProto::CopyFrom(const StateMachineProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.functions.match_recognize.StateMachineProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StateMachineProto::InternalSwap(StateMachineProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.longest_match_mode_)
      + sizeof(StateMachineProto::_impl_.longest_match_mode_)
      - PROTOBUF_FIELD_OFFSET(StateMachineProto, _impl_.nfa_)>(
          reinterpret_cast<char*>(&_impl_.nfa_),
          reinterpret_cast<char*>(&other->_impl_.nfa_));
}

::google::protobuf::Metadata StateMachineProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CompiledPatternProto::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::googlesql::functions::match_recognize::CompiledPatternProto, _impl_._oneof_case_);
};

void CompiledPatternProto::set_allocated_state_machine(::googlesql::functions::match_recognize::StateMachineProto* state_machine) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_variant();
  if (state_machine) {
    ::google::protobuf::Arena* submessage_arena = state_machine->GetArena();
    if (message_arena != submessage_arena) {
      state_machine = ::google::protobuf::internal::GetOwnedMessage(message_arena, state_machine, submessage_arena);
    }
    set_has_state_machine();
    _impl_.variant_.state_machine_ = state_machine;
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql.functions.match_recognize.CompiledPatternProto.state_machine)
}
CompiledPatternProto::CompiledPatternProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.functions.match_recognize.CompiledPatternProto)
}
inline PROTOBUF_NDEBUG_INLINE CompiledPatternProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::functions::match_recognize::CompiledPatternProto& from_msg)
      : variant_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

CompiledPatternProto::CompiledPatternProto(
    ::google::protobuf::Arena* arena,
    const CompiledPatternProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CompiledPatternProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (variant_case()) {
    case VARIANT_NOT_SET:
      break;
      case kStateMachine:
        _impl_.variant_.state_machine_ = ::google::protobuf::Message::CopyConstruct<::googlesql::functions::match_recognize::StateMachineProto>(arena, *from._impl_.variant_.state_machine_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:googlesql.functions.match_recognize.CompiledPatternProto)
}
inline PROTOBUF_NDEBUG_INLINE CompiledPatternProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : variant_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void CompiledPatternProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CompiledPatternProto::~CompiledPatternProto() {
  // @@protoc_insertion_point(destructor:googlesql.functions.match_recognize.CompiledPatternProto)
  SharedDtor(*this);
}
inline void CompiledPatternProto::SharedDtor(MessageLite& self) {
  CompiledPatternProto& this_ = static_cast<CompiledPatternProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_variant()) {
    this_.clear_variant();
  }
  this_._impl_.~Impl_();
}

void CompiledPatternProto::clear_variant() {
// @@protoc_insertion_point(one_of_clear_start:googlesql.functions.match_recognize.CompiledPatternProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (variant_case()) {
    case kStateMachine: {
      if (GetArena() == nullptr) {
        delete _impl_.variant_.state_machine_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.variant_.state_machine_);
      }
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VARIANT_NOT_SET;
}


inline void* CompiledPatternProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CompiledPatternProto(arena);
}
constexpr auto CompiledPatternProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CompiledPatternProto),
                                            alignof(CompiledPatternProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CompiledPatternProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CompiledPatternProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CompiledPatternProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CompiledPatternProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CompiledPatternProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CompiledPatternProto>(), &CompiledPatternProto::ByteSizeLong,
            &CompiledPatternProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CompiledPatternProto, _impl_._cached_size_),
        false,
    },
    &CompiledPatternProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CompiledPatternProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> CompiledPatternProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::CompiledPatternProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .googlesql.functions.match_recognize.StateMachineProto state_machine = 1;
    {PROTOBUF_FIELD_OFFSET(CompiledPatternProto, _impl_.variant_.state_machine_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::functions::match_recognize::StateMachineProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CompiledPatternProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.functions.match_recognize.CompiledPatternProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_variant();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CompiledPatternProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CompiledPatternProto& this_ = static_cast<const CompiledPatternProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CompiledPatternProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CompiledPatternProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.functions.match_recognize.CompiledPatternProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .googlesql.functions.match_recognize.StateMachineProto state_machine = 1;
          if (this_.variant_case() == kStateMachine) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.variant_.state_machine_, this_._impl_.variant_.state_machine_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.functions.match_recognize.CompiledPatternProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CompiledPatternProto::ByteSizeLong(const MessageLite& base) {
          const CompiledPatternProto& this_ = static_cast<const CompiledPatternProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CompiledPatternProto::ByteSizeLong() const {
          const CompiledPatternProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.functions.match_recognize.CompiledPatternProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.variant_case()) {
            // .googlesql.functions.match_recognize.StateMachineProto state_machine = 1;
            case kStateMachine: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.variant_.state_machine_);
              break;
            }
            case VARIANT_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CompiledPatternProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CompiledPatternProto*>(&to_msg);
  auto& from = static_cast<const CompiledPatternProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.functions.match_recognize.CompiledPatternProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_variant();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kStateMachine: {
        if (oneof_needs_init) {
          _this->_impl_.variant_.state_machine_ =
              ::google::protobuf::Message::CopyConstruct<::googlesql::functions::match_recognize::StateMachineProto>(arena, *from._impl_.variant_.state_machine_);
        } else {
          _this->_impl_.variant_.state_machine_->MergeFrom(from._internal_state_machine());
        }
        break;
      }
      case VARIANT_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CompiledPatternProto::CopyFrom(const CompiledPatternProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.functions.match_recognize.CompiledPatternProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CompiledPatternProto::InternalSwap(CompiledPatternProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.variant_, other->_impl_.variant_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata CompiledPatternProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace match_recognize
}  // namespace functions
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init_googlesql_public_functions_match_recognize_compiled_pattern_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
