#ifndef INTERNAL_CCALL_GO_ABSL_NUMERIC_INT128_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_NUMERIC_INT128_EXPORT_H

#include "absl/numeric/int128.h"
// include sources
#include "absl/numeric/int128.cc"
// include dependencies
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/types/compare/export.inc"

#endif
