#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_FLOAT_MARGIN_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_FLOAT_MARGIN_EXPORT_H

#include "zetasql/common/float_margin.h"
// include sources
// include dependencies
#include "go-zetasql/common/string_util/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/mathutil/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
