#ifndef googlesql_parser_parser_bind_cc
#define googlesql_parser_parser_bind_cc

#if !defined(GOOGLESQL_LINK_ONLY_BIND) && !defined(GOOGLESQL_UNIFIED_PREBUILT_THIN_BIND_CC)

// switch namespace
#define differential_privacy googlesql_parser_parser_differential_privacy
#define googlesql googlesql_public_analyzer_googlesql
#define googlesql_base googlesql_public_analyzer_googlesql_base
#define googlesql_bison_parser googlesql_public_analyzer_googlesql_bison_parser
#define re2 googlesql_parser_parser_re2
#define AbslInternalSleepFor googlesql_parser_parser_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_parser_parser_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_parser_parser_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_parser_parser_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_parser_parser_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_parser_parser_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_parser_parser_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_parser_parser_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_parser_parser_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_parser_parser_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_parser_parser_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_parser_parser_GoogleSqlalloc
#define GoogleSqlfree googlesql_parser_parser_GoogleSqlfree
#define GoogleSqlrealloc googlesql_parser_parser_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_parser_parser_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_parser_parser_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_parser_parser_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_parser_parser_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_parser_parser_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_parser_parser_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_parser_parser_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_parser_parser_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_parser_parser_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_parser_parser_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_parser_parser_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_parser_parser_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_parser_parser_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_parser_parser_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_parser_parser_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_parser_parser_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_parser_parser_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_parser_parser_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_idstring_allow_unicode_characters googlesql_parser_parser_FLAGS_googlesql_idstring_allow_unicode_characters
#define FLAGS_nogooglesql_idstring_allow_unicode_characters googlesql_parser_parser_FLAGS_nogooglesql_idstring_allow_unicode_characters
#define FLAGS_googlesql_default_error_message_stability googlesql_parser_parser_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_parser_parser_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_parser_parser_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_parser_parser_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_parser_parser_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_parser_parser_GoogleSqlFlexLexer
#define UCaseMap googlesql_parser_parser_UCaseMap

#define GO_EXPORT(def) export_googlesql_parser_parser_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// flex_tokenizer.flex.cc defines yyFlexLexer::{yylex,yywrap}; suppress flex_tokenizer.h inline stubs.
#define GOOGLESQL_PARSER_FLEX_TOKENIZER_SUPPRESS_FLEXLEXER_STUBS
// flex_prelude uses distinct Legacyalloc symbols from root analyzer (see flex_prelude in add_sources).
#define GOOGLESQL_GO_FLEX_LEGACY_IN_PARSER_PKG 1
// Link-only parser bridge helpers construct ParseResumeLocation directly.
#include "googlesql/public/parse_resume_location.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/parser/ast_node.h"
#include "googlesql/parser/ast_node_kind.h"
#include "googlesql/parser/parse_tree.h"
#include "googlesql/parser/parse_tree_decls.h"
#include "googlesql/parser/parse_tree_errors.h"
#include "googlesql/parser/parse_tree_visitor.h"
#include "googlesql/parser/parser.h"
#include "googlesql/parser/parser_internal.h"
#include "googlesql/parser/parser_runtime_info.h"
#include "googlesql/parser/statement_properties.h"
#include "googlesql/parser/unparser.h"
#include "googlesql/parser/visit_result.h"
//#undef private

// include sources
#include "googlesql/parser/ast_node_internal.h"
#include "googlesql/parser/parser.cc"
#include "googlesql/parser/parser_internal.cc"
#include "googlesql/parser/textmapper_lexer_adapter.cc"

#include "googlesql/parser/tm_parser.cc"

#include "googlesql/parser/join_processor.cc"

#include "googlesql/parser/unparser.cc"

// include dependencies
#include "go-googlesql/parser/ast_enums_cc_proto/export.inc"
#include "go-googlesql/parser/ast_node_factory/export.inc"
#include "go-googlesql/parser/bison_parser_generated_lib/export.inc"
#include "go-googlesql/parser/keywords/export.inc"
#include "go-googlesql/parser/lookahead_transformer/export.inc"
#include "go-googlesql/parser/parse_tree/export.inc"
#include "go-googlesql/parser/parser_mode/export.inc"
#include "go-googlesql/parser/token/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-googlesql/parser/tokenizer/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/arena_allocator/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/strings/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/status_payload_utils/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/common/timer_util/export.inc"
#include "go-googlesql/common/utf_util/export.inc"
#include "go-googlesql/common/warning_sink/export.inc"
#include "go-googlesql/parser/macros/macro_catalog/export.inc"
#include "go-googlesql/parser/macros/macro_expander/export.inc"
#include "go-googlesql/proto/internal_error_location_cc_proto/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/error_location_cc_proto/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/parse_resume_location/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/proto/logging_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-absl/types/variant/export.inc"
#include "go-re2/re2/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#else /* GOOGLESQL_LINK_ONLY_BIND || GOOGLESQL_UNIFIED_PREBUILT_THIN_BIND_CC */

// Link-only bind.cc (no amalgamated .cc includes). Native implementations must come from prebuilt
// archives (e.g. libgooglesql.a) and match this package's exported bridge symbols.
// Enable per package via cclib.link_only_bind_packages in internal/cmd/generator/config.yaml.
// See docs/link-only-cgo-migration.md.
#define AbslInternalSleepFor googlesql_parser_parser_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_parser_parser_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_parser_parser_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_parser_parser_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_parser_parser_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_parser_parser_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_parser_parser_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_parser_parser_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_parser_parser_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_parser_parser_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_parser_parser_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_parser_parser_GoogleSqlalloc
#define GoogleSqlfree googlesql_parser_parser_GoogleSqlfree
#define GoogleSqlrealloc googlesql_parser_parser_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_parser_parser_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_parser_parser_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_parser_parser_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_parser_parser_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_parser_parser_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_parser_parser_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_parser_parser_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_parser_parser_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_parser_parser_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_parser_parser_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_parser_parser_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_parser_parser_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_parser_parser_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_parser_parser_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_parser_parser_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_parser_parser_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_parser_parser_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_parser_parser_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_idstring_allow_unicode_characters googlesql_parser_parser_FLAGS_googlesql_idstring_allow_unicode_characters
#define FLAGS_nogooglesql_idstring_allow_unicode_characters googlesql_parser_parser_FLAGS_nogooglesql_idstring_allow_unicode_characters
#define FLAGS_googlesql_default_error_message_stability googlesql_parser_parser_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_parser_parser_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_parser_parser_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_parser_parser_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_parser_parser_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_parser_parser_GoogleSqlFlexLexer
#define UCaseMap googlesql_parser_parser_UCaseMap

#define GO_EXPORT(def) export_googlesql_parser_parser_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

#include "_cgo_export.h"

// flex_tokenizer.flex.cc defines yyFlexLexer::{yylex,yywrap}; suppress flex_tokenizer.h inline stubs.
#define GOOGLESQL_PARSER_FLEX_TOKENIZER_SUPPRESS_FLEXLEXER_STUBS
// flex_prelude uses distinct Legacyalloc symbols from root analyzer (see flex_prelude in add_sources).
#define GOOGLESQL_GO_FLEX_LEGACY_IN_PARSER_PKG 1
// Link-only parser bridge helpers construct ParseResumeLocation directly.
#include "googlesql/public/parse_resume_location.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers (types only; no .cc bodies)
#include "googlesql/parser/ast_node.h"
#include "googlesql/parser/ast_node_kind.h"
#include "googlesql/parser/parse_tree.h"
#include "googlesql/parser/parse_tree_decls.h"
#include "googlesql/parser/parse_tree_errors.h"
#include "googlesql/parser/parse_tree_visitor.h"
#include "googlesql/parser/parser.h"
#include "googlesql/parser/parser_internal.h"
#include "googlesql/parser/parser_runtime_info.h"
#include "googlesql/parser/statement_properties.h"
#include "googlesql/parser/unparser.h"
#include "googlesql/parser/visit_result.h"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* fat vs thin bind.cc */

#endif /* googlesql_parser_parser_bind_cc */
