// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/function.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fpublic_2ffunction_2eproto_2epb_2eh
#define googlesql_2fpublic_2ffunction_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fpublic_2ffunction_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fpublic_2ffunction_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fpublic_2ffunction_2eproto;
namespace googlesql {
class FunctionEnums;
struct FunctionEnumsDefaultTypeInternal;
extern FunctionEnumsDefaultTypeInternal _FunctionEnums_default_instance_;
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql {
enum FunctionEnums_ArgumentCardinality : int {
  FunctionEnums_ArgumentCardinality_REQUIRED = 0,
  FunctionEnums_ArgumentCardinality_REPEATED = 1,
  FunctionEnums_ArgumentCardinality_OPTIONAL = 2,
};

bool FunctionEnums_ArgumentCardinality_IsValid(int value);
extern const uint32_t FunctionEnums_ArgumentCardinality_internal_data_[];
constexpr FunctionEnums_ArgumentCardinality FunctionEnums_ArgumentCardinality_ArgumentCardinality_MIN = static_cast<FunctionEnums_ArgumentCardinality>(0);
constexpr FunctionEnums_ArgumentCardinality FunctionEnums_ArgumentCardinality_ArgumentCardinality_MAX = static_cast<FunctionEnums_ArgumentCardinality>(2);
constexpr int FunctionEnums_ArgumentCardinality_ArgumentCardinality_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_ArgumentCardinality_descriptor();
template <typename T>
const std::string& FunctionEnums_ArgumentCardinality_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_ArgumentCardinality>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ArgumentCardinality_Name().");
  return FunctionEnums_ArgumentCardinality_Name(static_cast<FunctionEnums_ArgumentCardinality>(value));
}
template <>
inline const std::string& FunctionEnums_ArgumentCardinality_Name(FunctionEnums_ArgumentCardinality value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_ArgumentCardinality_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool FunctionEnums_ArgumentCardinality_Parse(absl::string_view name, FunctionEnums_ArgumentCardinality* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_ArgumentCardinality>(
      FunctionEnums_ArgumentCardinality_descriptor(), name, value);
}
enum FunctionEnums_ProcedureArgumentMode : int {
  FunctionEnums_ProcedureArgumentMode_NOT_SET = 0,
  FunctionEnums_ProcedureArgumentMode_IN = 1,
  FunctionEnums_ProcedureArgumentMode_OUT = 2,
  FunctionEnums_ProcedureArgumentMode_INOUT = 3,
};

bool FunctionEnums_ProcedureArgumentMode_IsValid(int value);
extern const uint32_t FunctionEnums_ProcedureArgumentMode_internal_data_[];
constexpr FunctionEnums_ProcedureArgumentMode FunctionEnums_ProcedureArgumentMode_ProcedureArgumentMode_MIN = static_cast<FunctionEnums_ProcedureArgumentMode>(0);
constexpr FunctionEnums_ProcedureArgumentMode FunctionEnums_ProcedureArgumentMode_ProcedureArgumentMode_MAX = static_cast<FunctionEnums_ProcedureArgumentMode>(3);
constexpr int FunctionEnums_ProcedureArgumentMode_ProcedureArgumentMode_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_ProcedureArgumentMode_descriptor();
template <typename T>
const std::string& FunctionEnums_ProcedureArgumentMode_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_ProcedureArgumentMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ProcedureArgumentMode_Name().");
  return FunctionEnums_ProcedureArgumentMode_Name(static_cast<FunctionEnums_ProcedureArgumentMode>(value));
}
template <>
inline const std::string& FunctionEnums_ProcedureArgumentMode_Name(FunctionEnums_ProcedureArgumentMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_ProcedureArgumentMode_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool FunctionEnums_ProcedureArgumentMode_Parse(absl::string_view name, FunctionEnums_ProcedureArgumentMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_ProcedureArgumentMode>(
      FunctionEnums_ProcedureArgumentMode_descriptor(), name, value);
}
enum FunctionEnums_WindowOrderSupport : int {
  FunctionEnums_WindowOrderSupport_ORDER_UNSUPPORTED = 0,
  FunctionEnums_WindowOrderSupport_ORDER_OPTIONAL = 1,
  FunctionEnums_WindowOrderSupport_ORDER_REQUIRED = 2,
};

bool FunctionEnums_WindowOrderSupport_IsValid(int value);
extern const uint32_t FunctionEnums_WindowOrderSupport_internal_data_[];
constexpr FunctionEnums_WindowOrderSupport FunctionEnums_WindowOrderSupport_WindowOrderSupport_MIN = static_cast<FunctionEnums_WindowOrderSupport>(0);
constexpr FunctionEnums_WindowOrderSupport FunctionEnums_WindowOrderSupport_WindowOrderSupport_MAX = static_cast<FunctionEnums_WindowOrderSupport>(2);
constexpr int FunctionEnums_WindowOrderSupport_WindowOrderSupport_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_WindowOrderSupport_descriptor();
template <typename T>
const std::string& FunctionEnums_WindowOrderSupport_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_WindowOrderSupport>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to WindowOrderSupport_Name().");
  return FunctionEnums_WindowOrderSupport_Name(static_cast<FunctionEnums_WindowOrderSupport>(value));
}
template <>
inline const std::string& FunctionEnums_WindowOrderSupport_Name(FunctionEnums_WindowOrderSupport value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_WindowOrderSupport_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool FunctionEnums_WindowOrderSupport_Parse(absl::string_view name, FunctionEnums_WindowOrderSupport* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_WindowOrderSupport>(
      FunctionEnums_WindowOrderSupport_descriptor(), name, value);
}
enum FunctionEnums_Mode : int {
  FunctionEnums_Mode_SCALAR = 1,
  FunctionEnums_Mode_AGGREGATE = 2,
  FunctionEnums_Mode_ANALYTIC = 3,
};

bool FunctionEnums_Mode_IsValid(int value);
extern const uint32_t FunctionEnums_Mode_internal_data_[];
constexpr FunctionEnums_Mode FunctionEnums_Mode_Mode_MIN = static_cast<FunctionEnums_Mode>(1);
constexpr FunctionEnums_Mode FunctionEnums_Mode_Mode_MAX = static_cast<FunctionEnums_Mode>(3);
constexpr int FunctionEnums_Mode_Mode_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_Mode_descriptor();
template <typename T>
const std::string& FunctionEnums_Mode_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_Mode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Mode_Name().");
  return FunctionEnums_Mode_Name(static_cast<FunctionEnums_Mode>(value));
}
template <>
inline const std::string& FunctionEnums_Mode_Name(FunctionEnums_Mode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_Mode_descriptor,
                                                 1, 3>(
      static_cast<int>(value));
}
inline bool FunctionEnums_Mode_Parse(absl::string_view name, FunctionEnums_Mode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_Mode>(
      FunctionEnums_Mode_descriptor(), name, value);
}
enum FunctionEnums_Volatility : int {
  FunctionEnums_Volatility_IMMUTABLE = 0,
  FunctionEnums_Volatility_STABLE = 1,
  FunctionEnums_Volatility_VOLATILE = 2,
};

bool FunctionEnums_Volatility_IsValid(int value);
extern const uint32_t FunctionEnums_Volatility_internal_data_[];
constexpr FunctionEnums_Volatility FunctionEnums_Volatility_Volatility_MIN = static_cast<FunctionEnums_Volatility>(0);
constexpr FunctionEnums_Volatility FunctionEnums_Volatility_Volatility_MAX = static_cast<FunctionEnums_Volatility>(2);
constexpr int FunctionEnums_Volatility_Volatility_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_Volatility_descriptor();
template <typename T>
const std::string& FunctionEnums_Volatility_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_Volatility>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Volatility_Name().");
  return FunctionEnums_Volatility_Name(static_cast<FunctionEnums_Volatility>(value));
}
template <>
inline const std::string& FunctionEnums_Volatility_Name(FunctionEnums_Volatility value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_Volatility_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool FunctionEnums_Volatility_Parse(absl::string_view name, FunctionEnums_Volatility* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_Volatility>(
      FunctionEnums_Volatility_descriptor(), name, value);
}
enum FunctionEnums_TableValuedFunctionType : int {
  FunctionEnums_TableValuedFunctionType_INVALID = 0,
  FunctionEnums_TableValuedFunctionType_FIXED_OUTPUT_SCHEMA_TVF = 1,
  FunctionEnums_TableValuedFunctionType_FORWARD_INPUT_SCHEMA_TO_OUTPUT_SCHEMA_TVF = 2,
  FunctionEnums_TableValuedFunctionType_TEMPLATED_SQL_TVF = 3,
  FunctionEnums_TableValuedFunctionType_FORWARD_INPUT_SCHEMA_TO_OUTPUT_SCHEMA_WITH_APPENDED_COLUMNS = 7,
  FunctionEnums_TableValuedFunctionType_BASIS_TVF = 8,
};

bool FunctionEnums_TableValuedFunctionType_IsValid(int value);
extern const uint32_t FunctionEnums_TableValuedFunctionType_internal_data_[];
constexpr FunctionEnums_TableValuedFunctionType FunctionEnums_TableValuedFunctionType_TableValuedFunctionType_MIN = static_cast<FunctionEnums_TableValuedFunctionType>(0);
constexpr FunctionEnums_TableValuedFunctionType FunctionEnums_TableValuedFunctionType_TableValuedFunctionType_MAX = static_cast<FunctionEnums_TableValuedFunctionType>(8);
constexpr int FunctionEnums_TableValuedFunctionType_TableValuedFunctionType_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_TableValuedFunctionType_descriptor();
template <typename T>
const std::string& FunctionEnums_TableValuedFunctionType_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_TableValuedFunctionType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to TableValuedFunctionType_Name().");
  return FunctionEnums_TableValuedFunctionType_Name(static_cast<FunctionEnums_TableValuedFunctionType>(value));
}
template <>
inline const std::string& FunctionEnums_TableValuedFunctionType_Name(FunctionEnums_TableValuedFunctionType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_TableValuedFunctionType_descriptor,
                                                 0, 8>(
      static_cast<int>(value));
}
inline bool FunctionEnums_TableValuedFunctionType_Parse(absl::string_view name, FunctionEnums_TableValuedFunctionType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_TableValuedFunctionType>(
      FunctionEnums_TableValuedFunctionType_descriptor(), name, value);
}
enum FunctionEnums_ArgumentCollationMode : int {
  FunctionEnums_ArgumentCollationMode_AFFECTS_NONE = 0,
  FunctionEnums_ArgumentCollationMode_AFFECTS_OPERATION = 1,
  FunctionEnums_ArgumentCollationMode_AFFECTS_PROPAGATION = 2,
  FunctionEnums_ArgumentCollationMode_AFFECTS_OPERATION_AND_PROPAGATION = 3,
};

bool FunctionEnums_ArgumentCollationMode_IsValid(int value);
extern const uint32_t FunctionEnums_ArgumentCollationMode_internal_data_[];
constexpr FunctionEnums_ArgumentCollationMode FunctionEnums_ArgumentCollationMode_ArgumentCollationMode_MIN = static_cast<FunctionEnums_ArgumentCollationMode>(0);
constexpr FunctionEnums_ArgumentCollationMode FunctionEnums_ArgumentCollationMode_ArgumentCollationMode_MAX = static_cast<FunctionEnums_ArgumentCollationMode>(3);
constexpr int FunctionEnums_ArgumentCollationMode_ArgumentCollationMode_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_ArgumentCollationMode_descriptor();
template <typename T>
const std::string& FunctionEnums_ArgumentCollationMode_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_ArgumentCollationMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ArgumentCollationMode_Name().");
  return FunctionEnums_ArgumentCollationMode_Name(static_cast<FunctionEnums_ArgumentCollationMode>(value));
}
template <>
inline const std::string& FunctionEnums_ArgumentCollationMode_Name(FunctionEnums_ArgumentCollationMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_ArgumentCollationMode_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool FunctionEnums_ArgumentCollationMode_Parse(absl::string_view name, FunctionEnums_ArgumentCollationMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_ArgumentCollationMode>(
      FunctionEnums_ArgumentCollationMode_descriptor(), name, value);
}
enum FunctionEnums_NamedArgumentKind : int {
  FunctionEnums_NamedArgumentKind_NAMED_ARGUMENT_KIND_UNSPECIFIED = 0,
  FunctionEnums_NamedArgumentKind_POSITIONAL_ONLY = 1,
  FunctionEnums_NamedArgumentKind_POSITIONAL_OR_NAMED = 2,
  FunctionEnums_NamedArgumentKind_NAMED_ONLY = 3,
};

bool FunctionEnums_NamedArgumentKind_IsValid(int value);
extern const uint32_t FunctionEnums_NamedArgumentKind_internal_data_[];
constexpr FunctionEnums_NamedArgumentKind FunctionEnums_NamedArgumentKind_NamedArgumentKind_MIN = static_cast<FunctionEnums_NamedArgumentKind>(0);
constexpr FunctionEnums_NamedArgumentKind FunctionEnums_NamedArgumentKind_NamedArgumentKind_MAX = static_cast<FunctionEnums_NamedArgumentKind>(3);
constexpr int FunctionEnums_NamedArgumentKind_NamedArgumentKind_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_NamedArgumentKind_descriptor();
template <typename T>
const std::string& FunctionEnums_NamedArgumentKind_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_NamedArgumentKind>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to NamedArgumentKind_Name().");
  return FunctionEnums_NamedArgumentKind_Name(static_cast<FunctionEnums_NamedArgumentKind>(value));
}
template <>
inline const std::string& FunctionEnums_NamedArgumentKind_Name(FunctionEnums_NamedArgumentKind value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_NamedArgumentKind_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool FunctionEnums_NamedArgumentKind_Parse(absl::string_view name, FunctionEnums_NamedArgumentKind* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_NamedArgumentKind>(
      FunctionEnums_NamedArgumentKind_descriptor(), name, value);
}
enum FunctionEnums_ArgumentAliasKind : int {
  FunctionEnums_ArgumentAliasKind_ARGUMENT_ALIAS_KIND_UNSPECIFIED = 0,
  FunctionEnums_ArgumentAliasKind_ARGUMENT_NON_ALIASED = 1,
  FunctionEnums_ArgumentAliasKind_ARGUMENT_ALIASED = 2,
};

bool FunctionEnums_ArgumentAliasKind_IsValid(int value);
extern const uint32_t FunctionEnums_ArgumentAliasKind_internal_data_[];
constexpr FunctionEnums_ArgumentAliasKind FunctionEnums_ArgumentAliasKind_ArgumentAliasKind_MIN = static_cast<FunctionEnums_ArgumentAliasKind>(0);
constexpr FunctionEnums_ArgumentAliasKind FunctionEnums_ArgumentAliasKind_ArgumentAliasKind_MAX = static_cast<FunctionEnums_ArgumentAliasKind>(2);
constexpr int FunctionEnums_ArgumentAliasKind_ArgumentAliasKind_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_ArgumentAliasKind_descriptor();
template <typename T>
const std::string& FunctionEnums_ArgumentAliasKind_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_ArgumentAliasKind>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ArgumentAliasKind_Name().");
  return FunctionEnums_ArgumentAliasKind_Name(static_cast<FunctionEnums_ArgumentAliasKind>(value));
}
template <>
inline const std::string& FunctionEnums_ArgumentAliasKind_Name(FunctionEnums_ArgumentAliasKind value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_ArgumentAliasKind_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool FunctionEnums_ArgumentAliasKind_Parse(absl::string_view name, FunctionEnums_ArgumentAliasKind* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_ArgumentAliasKind>(
      FunctionEnums_ArgumentAliasKind_descriptor(), name, value);
}
enum FunctionEnums_DefaultNullHandling : int {
  FunctionEnums_DefaultNullHandling_DEFAULT_NULL_HANDLING_UNSPECIFIED = 0,
  FunctionEnums_DefaultNullHandling_DEFAULT_NULL_HANDLING_IGNORE_NULLS = 1,
  FunctionEnums_DefaultNullHandling_DEFAULT_NULL_HANDLING_RESPECT_NULLS = 2,
};

bool FunctionEnums_DefaultNullHandling_IsValid(int value);
extern const uint32_t FunctionEnums_DefaultNullHandling_internal_data_[];
constexpr FunctionEnums_DefaultNullHandling FunctionEnums_DefaultNullHandling_DefaultNullHandling_MIN = static_cast<FunctionEnums_DefaultNullHandling>(0);
constexpr FunctionEnums_DefaultNullHandling FunctionEnums_DefaultNullHandling_DefaultNullHandling_MAX = static_cast<FunctionEnums_DefaultNullHandling>(2);
constexpr int FunctionEnums_DefaultNullHandling_DefaultNullHandling_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
FunctionEnums_DefaultNullHandling_descriptor();
template <typename T>
const std::string& FunctionEnums_DefaultNullHandling_Name(T value) {
  static_assert(std::is_same<T, FunctionEnums_DefaultNullHandling>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DefaultNullHandling_Name().");
  return FunctionEnums_DefaultNullHandling_Name(static_cast<FunctionEnums_DefaultNullHandling>(value));
}
template <>
inline const std::string& FunctionEnums_DefaultNullHandling_Name(FunctionEnums_DefaultNullHandling value) {
  return ::google::protobuf::internal::NameOfDenseEnum<FunctionEnums_DefaultNullHandling_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool FunctionEnums_DefaultNullHandling_Parse(absl::string_view name, FunctionEnums_DefaultNullHandling* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FunctionEnums_DefaultNullHandling>(
      FunctionEnums_DefaultNullHandling_descriptor(), name, value);
}
enum SignatureArgumentKind : int {
  ARG_TYPE_FIXED = 0,
  ARG_TYPE_ANY_1 = 1,
  ARG_TYPE_ANY_2 = 2,
  ARG_TYPE_ANY_3 = 23,
  ARG_TYPE_ANY_4 = 25,
  ARG_TYPE_ANY_5 = 27,
  ARG_ARRAY_TYPE_ANY_1 = 3,
  ARG_ARRAY_TYPE_ANY_2 = 4,
  ARG_ARRAY_TYPE_ANY_3 = 24,
  ARG_ARRAY_TYPE_ANY_4 = 26,
  ARG_ARRAY_TYPE_ANY_5 = 28,
  ARG_PROTO_MAP_ANY = 14,
  ARG_PROTO_MAP_KEY_ANY = 15,
  ARG_PROTO_MAP_VALUE_ANY = 16,
  ARG_PROTO_ANY = 5,
  ARG_STRUCT_ANY = 6,
  ARG_ENUM_ANY = 7,
  ARG_TYPE_ARBITRARY = 8,
  ARG_TYPE_RELATION = 9,
  ARG_TYPE_VOID = 10,
  ARG_TYPE_MODEL = 11,
  ARG_TYPE_CONNECTION = 12,
  ARG_TYPE_DESCRIPTOR = 13,
  ARG_TYPE_LAMBDA = 17,
  ARG_RANGE_TYPE_ANY_1 = 18,
  ARG_TYPE_GRAPH_NODE = 19,
  ARG_TYPE_GRAPH_EDGE = 20,
  ARG_TYPE_GRAPH_ELEMENT = 21,
  ARG_TYPE_GRAPH_PATH = 30,
  ARG_TYPE_GRAPH = 32,
  ARG_TYPE_SEQUENCE = 22,
  ARG_MEASURE_TYPE_ANY_1 = 31,
  ARG_MAP_TYPE_ANY_1_2 = 29,
  __SignatureArgumentKind__switch_must_have_a_default__ = -1,
};

bool SignatureArgumentKind_IsValid(int value);
extern const uint32_t SignatureArgumentKind_internal_data_[];
constexpr SignatureArgumentKind SignatureArgumentKind_MIN = static_cast<SignatureArgumentKind>(-1);
constexpr SignatureArgumentKind SignatureArgumentKind_MAX = static_cast<SignatureArgumentKind>(32);
constexpr int SignatureArgumentKind_ARRAYSIZE = 32 + 1;
const ::google::protobuf::EnumDescriptor*
SignatureArgumentKind_descriptor();
template <typename T>
const std::string& SignatureArgumentKind_Name(T value) {
  static_assert(std::is_same<T, SignatureArgumentKind>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SignatureArgumentKind_Name().");
  return SignatureArgumentKind_Name(static_cast<SignatureArgumentKind>(value));
}
template <>
inline const std::string& SignatureArgumentKind_Name(SignatureArgumentKind value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SignatureArgumentKind_descriptor,
                                                 -1, 32>(
      static_cast<int>(value));
}
inline bool SignatureArgumentKind_Parse(absl::string_view name, SignatureArgumentKind* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SignatureArgumentKind>(
      SignatureArgumentKind_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class FunctionEnums final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:googlesql.FunctionEnums) */ {
 public:
  inline FunctionEnums() : FunctionEnums(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FunctionEnums* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FunctionEnums));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FunctionEnums(
      ::google::protobuf::internal::ConstantInitialized);

  inline FunctionEnums(const FunctionEnums& from) : FunctionEnums(nullptr, from) {}
  inline FunctionEnums(FunctionEnums&& from) noexcept
      : FunctionEnums(nullptr, std::move(from)) {}
  inline FunctionEnums& operator=(const FunctionEnums& from) {
    CopyFrom(from);
    return *this;
  }
  inline FunctionEnums& operator=(FunctionEnums&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FunctionEnums& default_instance() {
    return *internal_default_instance();
  }
  static inline const FunctionEnums* internal_default_instance() {
    return reinterpret_cast<const FunctionEnums*>(
        &_FunctionEnums_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FunctionEnums& a, FunctionEnums& b) { a.Swap(&b); }
  inline void Swap(FunctionEnums* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FunctionEnums* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FunctionEnums* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<FunctionEnums>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const FunctionEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const FunctionEnums& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql.FunctionEnums"; }

 protected:
  explicit FunctionEnums(::google::protobuf::Arena* arena);
  FunctionEnums(::google::protobuf::Arena* arena, const FunctionEnums& from);
  FunctionEnums(::google::protobuf::Arena* arena, FunctionEnums&& from) noexcept
      : FunctionEnums(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ArgumentCardinality = FunctionEnums_ArgumentCardinality;
  static constexpr ArgumentCardinality REQUIRED = FunctionEnums_ArgumentCardinality_REQUIRED;
  static constexpr ArgumentCardinality REPEATED = FunctionEnums_ArgumentCardinality_REPEATED;
  static constexpr ArgumentCardinality OPTIONAL = FunctionEnums_ArgumentCardinality_OPTIONAL;
  static inline bool ArgumentCardinality_IsValid(int value) {
    return FunctionEnums_ArgumentCardinality_IsValid(value);
  }
  static constexpr ArgumentCardinality ArgumentCardinality_MIN = FunctionEnums_ArgumentCardinality_ArgumentCardinality_MIN;
  static constexpr ArgumentCardinality ArgumentCardinality_MAX = FunctionEnums_ArgumentCardinality_ArgumentCardinality_MAX;
  static constexpr int ArgumentCardinality_ARRAYSIZE = FunctionEnums_ArgumentCardinality_ArgumentCardinality_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* ArgumentCardinality_descriptor() {
    return FunctionEnums_ArgumentCardinality_descriptor();
  }
  template <typename T>
  static inline const std::string& ArgumentCardinality_Name(T value) {
    return FunctionEnums_ArgumentCardinality_Name(value);
  }
  static inline bool ArgumentCardinality_Parse(absl::string_view name, ArgumentCardinality* value) {
    return FunctionEnums_ArgumentCardinality_Parse(name, value);
  }
  using ProcedureArgumentMode = FunctionEnums_ProcedureArgumentMode;
  static constexpr ProcedureArgumentMode NOT_SET = FunctionEnums_ProcedureArgumentMode_NOT_SET;
  static constexpr ProcedureArgumentMode IN = FunctionEnums_ProcedureArgumentMode_IN;
  static constexpr ProcedureArgumentMode OUT = FunctionEnums_ProcedureArgumentMode_OUT;
  static constexpr ProcedureArgumentMode INOUT = FunctionEnums_ProcedureArgumentMode_INOUT;
  static inline bool ProcedureArgumentMode_IsValid(int value) {
    return FunctionEnums_ProcedureArgumentMode_IsValid(value);
  }
  static constexpr ProcedureArgumentMode ProcedureArgumentMode_MIN = FunctionEnums_ProcedureArgumentMode_ProcedureArgumentMode_MIN;
  static constexpr ProcedureArgumentMode ProcedureArgumentMode_MAX = FunctionEnums_ProcedureArgumentMode_ProcedureArgumentMode_MAX;
  static constexpr int ProcedureArgumentMode_ARRAYSIZE = FunctionEnums_ProcedureArgumentMode_ProcedureArgumentMode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* ProcedureArgumentMode_descriptor() {
    return FunctionEnums_ProcedureArgumentMode_descriptor();
  }
  template <typename T>
  static inline const std::string& ProcedureArgumentMode_Name(T value) {
    return FunctionEnums_ProcedureArgumentMode_Name(value);
  }
  static inline bool ProcedureArgumentMode_Parse(absl::string_view name, ProcedureArgumentMode* value) {
    return FunctionEnums_ProcedureArgumentMode_Parse(name, value);
  }
  using WindowOrderSupport = FunctionEnums_WindowOrderSupport;
  static constexpr WindowOrderSupport ORDER_UNSUPPORTED = FunctionEnums_WindowOrderSupport_ORDER_UNSUPPORTED;
  static constexpr WindowOrderSupport ORDER_OPTIONAL = FunctionEnums_WindowOrderSupport_ORDER_OPTIONAL;
  static constexpr WindowOrderSupport ORDER_REQUIRED = FunctionEnums_WindowOrderSupport_ORDER_REQUIRED;
  static inline bool WindowOrderSupport_IsValid(int value) {
    return FunctionEnums_WindowOrderSupport_IsValid(value);
  }
  static constexpr WindowOrderSupport WindowOrderSupport_MIN = FunctionEnums_WindowOrderSupport_WindowOrderSupport_MIN;
  static constexpr WindowOrderSupport WindowOrderSupport_MAX = FunctionEnums_WindowOrderSupport_WindowOrderSupport_MAX;
  static constexpr int WindowOrderSupport_ARRAYSIZE = FunctionEnums_WindowOrderSupport_WindowOrderSupport_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* WindowOrderSupport_descriptor() {
    return FunctionEnums_WindowOrderSupport_descriptor();
  }
  template <typename T>
  static inline const std::string& WindowOrderSupport_Name(T value) {
    return FunctionEnums_WindowOrderSupport_Name(value);
  }
  static inline bool WindowOrderSupport_Parse(absl::string_view name, WindowOrderSupport* value) {
    return FunctionEnums_WindowOrderSupport_Parse(name, value);
  }
  using Mode = FunctionEnums_Mode;
  static constexpr Mode SCALAR = FunctionEnums_Mode_SCALAR;
  static constexpr Mode AGGREGATE = FunctionEnums_Mode_AGGREGATE;
  static constexpr Mode ANALYTIC = FunctionEnums_Mode_ANALYTIC;
  static inline bool Mode_IsValid(int value) {
    return FunctionEnums_Mode_IsValid(value);
  }
  static constexpr Mode Mode_MIN = FunctionEnums_Mode_Mode_MIN;
  static constexpr Mode Mode_MAX = FunctionEnums_Mode_Mode_MAX;
  static constexpr int Mode_ARRAYSIZE = FunctionEnums_Mode_Mode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Mode_descriptor() {
    return FunctionEnums_Mode_descriptor();
  }
  template <typename T>
  static inline const std::string& Mode_Name(T value) {
    return FunctionEnums_Mode_Name(value);
  }
  static inline bool Mode_Parse(absl::string_view name, Mode* value) {
    return FunctionEnums_Mode_Parse(name, value);
  }
  using Volatility = FunctionEnums_Volatility;
  static constexpr Volatility IMMUTABLE = FunctionEnums_Volatility_IMMUTABLE;
  static constexpr Volatility STABLE = FunctionEnums_Volatility_STABLE;
  static constexpr Volatility VOLATILE = FunctionEnums_Volatility_VOLATILE;
  static inline bool Volatility_IsValid(int value) {
    return FunctionEnums_Volatility_IsValid(value);
  }
  static constexpr Volatility Volatility_MIN = FunctionEnums_Volatility_Volatility_MIN;
  static constexpr Volatility Volatility_MAX = FunctionEnums_Volatility_Volatility_MAX;
  static constexpr int Volatility_ARRAYSIZE = FunctionEnums_Volatility_Volatility_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Volatility_descriptor() {
    return FunctionEnums_Volatility_descriptor();
  }
  template <typename T>
  static inline const std::string& Volatility_Name(T value) {
    return FunctionEnums_Volatility_Name(value);
  }
  static inline bool Volatility_Parse(absl::string_view name, Volatility* value) {
    return FunctionEnums_Volatility_Parse(name, value);
  }
  using TableValuedFunctionType = FunctionEnums_TableValuedFunctionType;
  static constexpr TableValuedFunctionType INVALID = FunctionEnums_TableValuedFunctionType_INVALID;
  static constexpr TableValuedFunctionType FIXED_OUTPUT_SCHEMA_TVF = FunctionEnums_TableValuedFunctionType_FIXED_OUTPUT_SCHEMA_TVF;
  static constexpr TableValuedFunctionType FORWARD_INPUT_SCHEMA_TO_OUTPUT_SCHEMA_TVF = FunctionEnums_TableValuedFunctionType_FORWARD_INPUT_SCHEMA_TO_OUTPUT_SCHEMA_TVF;
  static constexpr TableValuedFunctionType TEMPLATED_SQL_TVF = FunctionEnums_TableValuedFunctionType_TEMPLATED_SQL_TVF;
  static constexpr TableValuedFunctionType FORWARD_INPUT_SCHEMA_TO_OUTPUT_SCHEMA_WITH_APPENDED_COLUMNS = FunctionEnums_TableValuedFunctionType_FORWARD_INPUT_SCHEMA_TO_OUTPUT_SCHEMA_WITH_APPENDED_COLUMNS;
  static constexpr TableValuedFunctionType BASIS_TVF = FunctionEnums_TableValuedFunctionType_BASIS_TVF;
  static inline bool TableValuedFunctionType_IsValid(int value) {
    return FunctionEnums_TableValuedFunctionType_IsValid(value);
  }
  static constexpr TableValuedFunctionType TableValuedFunctionType_MIN = FunctionEnums_TableValuedFunctionType_TableValuedFunctionType_MIN;
  static constexpr TableValuedFunctionType TableValuedFunctionType_MAX = FunctionEnums_TableValuedFunctionType_TableValuedFunctionType_MAX;
  static constexpr int TableValuedFunctionType_ARRAYSIZE = FunctionEnums_TableValuedFunctionType_TableValuedFunctionType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* TableValuedFunctionType_descriptor() {
    return FunctionEnums_TableValuedFunctionType_descriptor();
  }
  template <typename T>
  static inline const std::string& TableValuedFunctionType_Name(T value) {
    return FunctionEnums_TableValuedFunctionType_Name(value);
  }
  static inline bool TableValuedFunctionType_Parse(absl::string_view name, TableValuedFunctionType* value) {
    return FunctionEnums_TableValuedFunctionType_Parse(name, value);
  }
  using ArgumentCollationMode = FunctionEnums_ArgumentCollationMode;
  static constexpr ArgumentCollationMode AFFECTS_NONE = FunctionEnums_ArgumentCollationMode_AFFECTS_NONE;
  static constexpr ArgumentCollationMode AFFECTS_OPERATION = FunctionEnums_ArgumentCollationMode_AFFECTS_OPERATION;
  static constexpr ArgumentCollationMode AFFECTS_PROPAGATION = FunctionEnums_ArgumentCollationMode_AFFECTS_PROPAGATION;
  static constexpr ArgumentCollationMode AFFECTS_OPERATION_AND_PROPAGATION = FunctionEnums_ArgumentCollationMode_AFFECTS_OPERATION_AND_PROPAGATION;
  static inline bool ArgumentCollationMode_IsValid(int value) {
    return FunctionEnums_ArgumentCollationMode_IsValid(value);
  }
  static constexpr ArgumentCollationMode ArgumentCollationMode_MIN = FunctionEnums_ArgumentCollationMode_ArgumentCollationMode_MIN;
  static constexpr ArgumentCollationMode ArgumentCollationMode_MAX = FunctionEnums_ArgumentCollationMode_ArgumentCollationMode_MAX;
  static constexpr int ArgumentCollationMode_ARRAYSIZE = FunctionEnums_ArgumentCollationMode_ArgumentCollationMode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* ArgumentCollationMode_descriptor() {
    return FunctionEnums_ArgumentCollationMode_descriptor();
  }
  template <typename T>
  static inline const std::string& ArgumentCollationMode_Name(T value) {
    return FunctionEnums_ArgumentCollationMode_Name(value);
  }
  static inline bool ArgumentCollationMode_Parse(absl::string_view name, ArgumentCollationMode* value) {
    return FunctionEnums_ArgumentCollationMode_Parse(name, value);
  }
  using NamedArgumentKind = FunctionEnums_NamedArgumentKind;
  static constexpr NamedArgumentKind NAMED_ARGUMENT_KIND_UNSPECIFIED = FunctionEnums_NamedArgumentKind_NAMED_ARGUMENT_KIND_UNSPECIFIED;
  static constexpr NamedArgumentKind POSITIONAL_ONLY = FunctionEnums_NamedArgumentKind_POSITIONAL_ONLY;
  static constexpr NamedArgumentKind POSITIONAL_OR_NAMED = FunctionEnums_NamedArgumentKind_POSITIONAL_OR_NAMED;
  static constexpr NamedArgumentKind NAMED_ONLY = FunctionEnums_NamedArgumentKind_NAMED_ONLY;
  static inline bool NamedArgumentKind_IsValid(int value) {
    return FunctionEnums_NamedArgumentKind_IsValid(value);
  }
  static constexpr NamedArgumentKind NamedArgumentKind_MIN = FunctionEnums_NamedArgumentKind_NamedArgumentKind_MIN;
  static constexpr NamedArgumentKind NamedArgumentKind_MAX = FunctionEnums_NamedArgumentKind_NamedArgumentKind_MAX;
  static constexpr int NamedArgumentKind_ARRAYSIZE = FunctionEnums_NamedArgumentKind_NamedArgumentKind_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* NamedArgumentKind_descriptor() {
    return FunctionEnums_NamedArgumentKind_descriptor();
  }
  template <typename T>
  static inline const std::string& NamedArgumentKind_Name(T value) {
    return FunctionEnums_NamedArgumentKind_Name(value);
  }
  static inline bool NamedArgumentKind_Parse(absl::string_view name, NamedArgumentKind* value) {
    return FunctionEnums_NamedArgumentKind_Parse(name, value);
  }
  using ArgumentAliasKind = FunctionEnums_ArgumentAliasKind;
  static constexpr ArgumentAliasKind ARGUMENT_ALIAS_KIND_UNSPECIFIED = FunctionEnums_ArgumentAliasKind_ARGUMENT_ALIAS_KIND_UNSPECIFIED;
  static constexpr ArgumentAliasKind ARGUMENT_NON_ALIASED = FunctionEnums_ArgumentAliasKind_ARGUMENT_NON_ALIASED;
  static constexpr ArgumentAliasKind ARGUMENT_ALIASED = FunctionEnums_ArgumentAliasKind_ARGUMENT_ALIASED;
  static inline bool ArgumentAliasKind_IsValid(int value) {
    return FunctionEnums_ArgumentAliasKind_IsValid(value);
  }
  static constexpr ArgumentAliasKind ArgumentAliasKind_MIN = FunctionEnums_ArgumentAliasKind_ArgumentAliasKind_MIN;
  static constexpr ArgumentAliasKind ArgumentAliasKind_MAX = FunctionEnums_ArgumentAliasKind_ArgumentAliasKind_MAX;
  static constexpr int ArgumentAliasKind_ARRAYSIZE = FunctionEnums_ArgumentAliasKind_ArgumentAliasKind_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* ArgumentAliasKind_descriptor() {
    return FunctionEnums_ArgumentAliasKind_descriptor();
  }
  template <typename T>
  static inline const std::string& ArgumentAliasKind_Name(T value) {
    return FunctionEnums_ArgumentAliasKind_Name(value);
  }
  static inline bool ArgumentAliasKind_Parse(absl::string_view name, ArgumentAliasKind* value) {
    return FunctionEnums_ArgumentAliasKind_Parse(name, value);
  }
  using DefaultNullHandling = FunctionEnums_DefaultNullHandling;
  static constexpr DefaultNullHandling DEFAULT_NULL_HANDLING_UNSPECIFIED = FunctionEnums_DefaultNullHandling_DEFAULT_NULL_HANDLING_UNSPECIFIED;
  static constexpr DefaultNullHandling DEFAULT_NULL_HANDLING_IGNORE_NULLS = FunctionEnums_DefaultNullHandling_DEFAULT_NULL_HANDLING_IGNORE_NULLS;
  static constexpr DefaultNullHandling DEFAULT_NULL_HANDLING_RESPECT_NULLS = FunctionEnums_DefaultNullHandling_DEFAULT_NULL_HANDLING_RESPECT_NULLS;
  static inline bool DefaultNullHandling_IsValid(int value) {
    return FunctionEnums_DefaultNullHandling_IsValid(value);
  }
  static constexpr DefaultNullHandling DefaultNullHandling_MIN = FunctionEnums_DefaultNullHandling_DefaultNullHandling_MIN;
  static constexpr DefaultNullHandling DefaultNullHandling_MAX = FunctionEnums_DefaultNullHandling_DefaultNullHandling_MAX;
  static constexpr int DefaultNullHandling_ARRAYSIZE = FunctionEnums_DefaultNullHandling_DefaultNullHandling_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* DefaultNullHandling_descriptor() {
    return FunctionEnums_DefaultNullHandling_descriptor();
  }
  template <typename T>
  static inline const std::string& DefaultNullHandling_Name(T value) {
    return FunctionEnums_DefaultNullHandling_Name(value);
  }
  static inline bool DefaultNullHandling_Parse(absl::string_view name, DefaultNullHandling* value) {
    return FunctionEnums_DefaultNullHandling_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:googlesql.FunctionEnums)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const FunctionEnums& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_googlesql_2fpublic_2ffunction_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FunctionEnums

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql::FunctionEnums_ArgumentCardinality> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_ArgumentCardinality>() {
  return ::googlesql::FunctionEnums_ArgumentCardinality_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_ProcedureArgumentMode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_ProcedureArgumentMode>() {
  return ::googlesql::FunctionEnums_ProcedureArgumentMode_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_WindowOrderSupport> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_WindowOrderSupport>() {
  return ::googlesql::FunctionEnums_WindowOrderSupport_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_Mode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_Mode>() {
  return ::googlesql::FunctionEnums_Mode_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_Volatility> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_Volatility>() {
  return ::googlesql::FunctionEnums_Volatility_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_TableValuedFunctionType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_TableValuedFunctionType>() {
  return ::googlesql::FunctionEnums_TableValuedFunctionType_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_ArgumentCollationMode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_ArgumentCollationMode>() {
  return ::googlesql::FunctionEnums_ArgumentCollationMode_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_NamedArgumentKind> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_NamedArgumentKind>() {
  return ::googlesql::FunctionEnums_NamedArgumentKind_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_ArgumentAliasKind> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_ArgumentAliasKind>() {
  return ::googlesql::FunctionEnums_ArgumentAliasKind_descriptor();
}
template <>
struct is_proto_enum<::googlesql::FunctionEnums_DefaultNullHandling> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::FunctionEnums_DefaultNullHandling>() {
  return ::googlesql::FunctionEnums_DefaultNullHandling_descriptor();
}
template <>
struct is_proto_enum<::googlesql::SignatureArgumentKind> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql::SignatureArgumentKind>() {
  return ::googlesql::SignatureArgumentKind_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fpublic_2ffunction_2eproto_2epb_2eh
