// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/public/simple_table.proto
// Protobuf C++ Version: 5.29.0

#include "googlesql/public/simple_table.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace googlesql {

inline constexpr SimpleAnonymizationInfoProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_column_name_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SimpleAnonymizationInfoProto::SimpleAnonymizationInfoProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SimpleAnonymizationInfoProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimpleAnonymizationInfoProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimpleAnonymizationInfoProtoDefaultTypeInternal() {}
  union {
    SimpleAnonymizationInfoProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimpleAnonymizationInfoProtoDefaultTypeInternal _SimpleAnonymizationInfoProto_default_instance_;

inline constexpr ExpressionAttributeProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        row_identity_column_index_{},
        _row_identity_column_index_cached_byte_size_{0},
        expression_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expression_kind_{static_cast< ::googlesql::ExpressionAttributeProto_ExpressionKind >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ExpressionAttributeProto::ExpressionAttributeProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ExpressionAttributeProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExpressionAttributeProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExpressionAttributeProtoDefaultTypeInternal() {}
  union {
    ExpressionAttributeProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExpressionAttributeProtoDefaultTypeInternal _ExpressionAttributeProto_default_instance_;

inline constexpr SimpleColumnProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{nullptr},
        annotation_map_{nullptr},
        column_expression_{nullptr},
        is_pseudo_column_{false},
        can_update_unwritable_to_default_{false},
        has_default_value_{false},
        is_writable_column_{true} {}

template <typename>
PROTOBUF_CONSTEXPR SimpleColumnProto::SimpleColumnProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SimpleColumnProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimpleColumnProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimpleColumnProtoDefaultTypeInternal() {}
  union {
    SimpleColumnProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimpleColumnProtoDefaultTypeInternal _SimpleColumnProto_default_instance_;

inline constexpr SimpleTableProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        column_{},
        primary_key_column_index_{},
        row_identity_column_index_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_in_catalog_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        full_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        anonymization_info_{nullptr},
        serialization_id_{::int64_t{0}},
        is_value_table_{false},
        allow_anonymous_column_name_{false},
        allow_duplicate_column_names_{false} {}

template <typename>
PROTOBUF_CONSTEXPR SimpleTableProto::SimpleTableProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SimpleTableProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimpleTableProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimpleTableProtoDefaultTypeInternal() {}
  union {
    SimpleTableProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimpleTableProtoDefaultTypeInternal _SimpleTableProto_default_instance_;
}  // namespace googlesql
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_googlesql_2fpublic_2fsimple_5ftable_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_googlesql_2fpublic_2fsimple_5ftable_2eproto = nullptr;
const ::uint32_t
    TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleAnonymizationInfoProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleAnonymizationInfoProto, _impl_.userid_column_name_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.serialization_id_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.is_value_table_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.column_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.primary_key_column_index_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.row_identity_column_index_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.name_in_catalog_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.allow_anonymous_column_name_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.allow_duplicate_column_names_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.anonymization_info_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleTableProto, _impl_.full_name_),
        0,
        4,
        5,
        ~0u,
        ~0u,
        ~0u,
        1,
        6,
        7,
        3,
        2,
        PROTOBUF_FIELD_OFFSET(::googlesql::ExpressionAttributeProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ExpressionAttributeProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::ExpressionAttributeProto, _impl_.expression_string_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ExpressionAttributeProto, _impl_.expression_kind_),
        PROTOBUF_FIELD_OFFSET(::googlesql::ExpressionAttributeProto, _impl_.row_identity_column_index_),
        0,
        1,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.is_pseudo_column_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.is_writable_column_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.can_update_unwritable_to_default_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.annotation_map_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.has_default_value_),
        PROTOBUF_FIELD_OFFSET(::googlesql::SimpleColumnProto, _impl_.column_expression_),
        0,
        1,
        4,
        7,
        5,
        2,
        6,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::googlesql::SimpleAnonymizationInfoProto)},
        {9, 28, -1, sizeof(::googlesql::SimpleTableProto)},
        {39, 50, -1, sizeof(::googlesql::ExpressionAttributeProto)},
        {53, 69, -1, sizeof(::googlesql::SimpleColumnProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::googlesql::_SimpleAnonymizationInfoProto_default_instance_._instance,
    &::googlesql::_SimpleTableProto_default_instance_._instance,
    &::googlesql::_ExpressionAttributeProto_default_instance_._instance,
    &::googlesql::_SimpleColumnProto_default_instance_._instance,
};
const char descriptor_table_protodef_googlesql_2fpublic_2fsimple_5ftable_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#googlesql/public/simple_table.proto\022\tg"
    "ooglesql\032!googlesql/public/annotation.pr"
    "oto\032\033googlesql/public/type.proto\":\n\034Simp"
    "leAnonymizationInfoProto\022\032\n\022userid_colum"
    "n_name\030\001 \003(\t\"\201\003\n\020SimpleTableProto\022\014\n\004nam"
    "e\030\001 \001(\t\022\030\n\020serialization_id\030\002 \001(\003\022\026\n\016is_"
    "value_table\030\003 \001(\010\022,\n\006column\030\004 \003(\0132\034.goog"
    "lesql.SimpleColumnProto\022 \n\030primary_key_c"
    "olumn_index\030\t \003(\005\022!\n\031row_identity_column"
    "_index\030\013 \003(\005\022\027\n\017name_in_catalog\030\005 \001(\t\022#\n"
    "\033allow_anonymous_column_name\030\006 \001(\010\022$\n\034al"
    "low_duplicate_column_names\030\007 \001(\010\022C\n\022anon"
    "ymization_info\030\010 \001(\0132\'.googlesql.SimpleA"
    "nonymizationInfoProto\022\021\n\tfull_name\030\n \001(\t"
    "\"\357\001\n\030ExpressionAttributeProto\022\031\n\021express"
    "ion_string\030\010 \001(\t\022K\n\017expression_kind\030\t \001("
    "\01622.googlesql.ExpressionAttributeProto.E"
    "xpressionKind\022%\n\031row_identity_column_ind"
    "ex\030\n \003(\005B\002\020\001\"D\n\016ExpressionKind\022\013\n\007DEFAUL"
    "T\020\000\022\r\n\tGENERATED\020\001\022\026\n\022MEASURE_EXPRESSION"
    "\020\002\"\304\002\n\021SimpleColumnProto\022\014\n\004name\030\001 \001(\t\022\""
    "\n\004type\030\002 \001(\0132\024.googlesql.TypeProto\022\030\n\020is"
    "_pseudo_column\030\003 \001(\010\022 \n\022is_writable_colu"
    "mn\030\004 \001(\010:\004true\022(\n can_update_unwritable_"
    "to_default\030\006 \001(\010\0225\n\016annotation_map\030\005 \001(\013"
    "2\035.googlesql.AnnotationMapProto\022 \n\021has_d"
    "efault_value\030\007 \001(\010:\005false\022>\n\021column_expr"
    "ession\030\010 \001(\0132#.googlesql.ExpressionAttri"
    "buteProtoB)\n\024com.google.googlesqlB\021Simpl"
    "eTableProtos"
};
static const ::_pbi::DescriptorTable* const descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto_deps[2] =
    {
        &::descriptor_table_googlesql_2fpublic_2fannotation_2eproto,
        &::descriptor_table_googlesql_2fpublic_2ftype_2eproto,
};
static ::absl::once_flag descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto = {
    false,
    false,
    1172,
    descriptor_table_protodef_googlesql_2fpublic_2fsimple_5ftable_2eproto,
    "googlesql/public/simple_table.proto",
    &descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto_once,
    descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto_deps,
    2,
    4,
    schemas,
    file_default_instances,
    TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto::offsets,
    file_level_enum_descriptors_googlesql_2fpublic_2fsimple_5ftable_2eproto,
    file_level_service_descriptors_googlesql_2fpublic_2fsimple_5ftable_2eproto,
};
namespace googlesql {
const ::google::protobuf::EnumDescriptor* ExpressionAttributeProto_ExpressionKind_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto);
  return file_level_enum_descriptors_googlesql_2fpublic_2fsimple_5ftable_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ExpressionAttributeProto_ExpressionKind_internal_data_[] = {
    196608u, 0u, };
bool ExpressionAttributeProto_ExpressionKind_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr ExpressionAttributeProto_ExpressionKind ExpressionAttributeProto::DEFAULT;
constexpr ExpressionAttributeProto_ExpressionKind ExpressionAttributeProto::GENERATED;
constexpr ExpressionAttributeProto_ExpressionKind ExpressionAttributeProto::MEASURE_EXPRESSION;
constexpr ExpressionAttributeProto_ExpressionKind ExpressionAttributeProto::ExpressionKind_MIN;
constexpr ExpressionAttributeProto_ExpressionKind ExpressionAttributeProto::ExpressionKind_MAX;
constexpr int ExpressionAttributeProto::ExpressionKind_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class SimpleAnonymizationInfoProto::_Internal {
 public:
};

SimpleAnonymizationInfoProto::SimpleAnonymizationInfoProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.SimpleAnonymizationInfoProto)
}
inline PROTOBUF_NDEBUG_INLINE SimpleAnonymizationInfoProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::SimpleAnonymizationInfoProto& from_msg)
      : userid_column_name_{visibility, arena, from.userid_column_name_},
        _cached_size_{0} {}

SimpleAnonymizationInfoProto::SimpleAnonymizationInfoProto(
    ::google::protobuf::Arena* arena,
    const SimpleAnonymizationInfoProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SimpleAnonymizationInfoProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:googlesql.SimpleAnonymizationInfoProto)
}
inline PROTOBUF_NDEBUG_INLINE SimpleAnonymizationInfoProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_column_name_{visibility, arena},
        _cached_size_{0} {}

inline void SimpleAnonymizationInfoProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SimpleAnonymizationInfoProto::~SimpleAnonymizationInfoProto() {
  // @@protoc_insertion_point(destructor:googlesql.SimpleAnonymizationInfoProto)
  SharedDtor(*this);
}
inline void SimpleAnonymizationInfoProto::SharedDtor(MessageLite& self) {
  SimpleAnonymizationInfoProto& this_ = static_cast<SimpleAnonymizationInfoProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SimpleAnonymizationInfoProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SimpleAnonymizationInfoProto(arena);
}
constexpr auto SimpleAnonymizationInfoProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SimpleAnonymizationInfoProto, _impl_.userid_column_name_) +
          decltype(SimpleAnonymizationInfoProto::_impl_.userid_column_name_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SimpleAnonymizationInfoProto), alignof(SimpleAnonymizationInfoProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SimpleAnonymizationInfoProto::PlacementNew_,
                                 sizeof(SimpleAnonymizationInfoProto),
                                 alignof(SimpleAnonymizationInfoProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SimpleAnonymizationInfoProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SimpleAnonymizationInfoProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SimpleAnonymizationInfoProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SimpleAnonymizationInfoProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SimpleAnonymizationInfoProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SimpleAnonymizationInfoProto>(), &SimpleAnonymizationInfoProto::ByteSizeLong,
            &SimpleAnonymizationInfoProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SimpleAnonymizationInfoProto, _impl_._cached_size_),
        false,
    },
    &SimpleAnonymizationInfoProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SimpleAnonymizationInfoProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 65, 2> SimpleAnonymizationInfoProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::SimpleAnonymizationInfoProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string userid_column_name = 1;
    {::_pbi::TcParser::FastSR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SimpleAnonymizationInfoProto, _impl_.userid_column_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string userid_column_name = 1;
    {PROTOBUF_FIELD_OFFSET(SimpleAnonymizationInfoProto, _impl_.userid_column_name_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\46\22\0\0\0\0\0\0"
    "googlesql.SimpleAnonymizationInfoProto"
    "userid_column_name"
  }},
};

PROTOBUF_NOINLINE void SimpleAnonymizationInfoProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.SimpleAnonymizationInfoProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_column_name_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SimpleAnonymizationInfoProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SimpleAnonymizationInfoProto& this_ = static_cast<const SimpleAnonymizationInfoProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SimpleAnonymizationInfoProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SimpleAnonymizationInfoProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.SimpleAnonymizationInfoProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string userid_column_name = 1;
          for (int i = 0, n = this_._internal_userid_column_name_size(); i < n; ++i) {
            const auto& s = this_._internal_userid_column_name().Get(i);
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.SimpleAnonymizationInfoProto.userid_column_name");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.SimpleAnonymizationInfoProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SimpleAnonymizationInfoProto::ByteSizeLong(const MessageLite& base) {
          const SimpleAnonymizationInfoProto& this_ = static_cast<const SimpleAnonymizationInfoProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SimpleAnonymizationInfoProto::ByteSizeLong() const {
          const SimpleAnonymizationInfoProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.SimpleAnonymizationInfoProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string userid_column_name = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_userid_column_name().size());
              for (int i = 0, n = this_._internal_userid_column_name().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_userid_column_name().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SimpleAnonymizationInfoProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SimpleAnonymizationInfoProto*>(&to_msg);
  auto& from = static_cast<const SimpleAnonymizationInfoProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.SimpleAnonymizationInfoProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_userid_column_name()->MergeFrom(from._internal_userid_column_name());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleAnonymizationInfoProto::CopyFrom(const SimpleAnonymizationInfoProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.SimpleAnonymizationInfoProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SimpleAnonymizationInfoProto::InternalSwap(SimpleAnonymizationInfoProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.userid_column_name_.InternalSwap(&other->_impl_.userid_column_name_);
}

::google::protobuf::Metadata SimpleAnonymizationInfoProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SimpleTableProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SimpleTableProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_._has_bits_);
};

SimpleTableProto::SimpleTableProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.SimpleTableProto)
}
inline PROTOBUF_NDEBUG_INLINE SimpleTableProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::SimpleTableProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        column_{visibility, arena, from.column_},
        primary_key_column_index_{visibility, arena, from.primary_key_column_index_},
        row_identity_column_index_{visibility, arena, from.row_identity_column_index_},
        name_(arena, from.name_),
        name_in_catalog_(arena, from.name_in_catalog_),
        full_name_(arena, from.full_name_) {}

SimpleTableProto::SimpleTableProto(
    ::google::protobuf::Arena* arena,
    const SimpleTableProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SimpleTableProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.anonymization_info_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::SimpleAnonymizationInfoProto>(
                              arena, *from._impl_.anonymization_info_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, serialization_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, serialization_id_),
           offsetof(Impl_, allow_duplicate_column_names_) -
               offsetof(Impl_, serialization_id_) +
               sizeof(Impl_::allow_duplicate_column_names_));

  // @@protoc_insertion_point(copy_constructor:googlesql.SimpleTableProto)
}
inline PROTOBUF_NDEBUG_INLINE SimpleTableProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        column_{visibility, arena},
        primary_key_column_index_{visibility, arena},
        row_identity_column_index_{visibility, arena},
        name_(arena),
        name_in_catalog_(arena),
        full_name_(arena) {}

inline void SimpleTableProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, anonymization_info_),
           0,
           offsetof(Impl_, allow_duplicate_column_names_) -
               offsetof(Impl_, anonymization_info_) +
               sizeof(Impl_::allow_duplicate_column_names_));
}
SimpleTableProto::~SimpleTableProto() {
  // @@protoc_insertion_point(destructor:googlesql.SimpleTableProto)
  SharedDtor(*this);
}
inline void SimpleTableProto::SharedDtor(MessageLite& self) {
  SimpleTableProto& this_ = static_cast<SimpleTableProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.name_in_catalog_.Destroy();
  this_._impl_.full_name_.Destroy();
  delete this_._impl_.anonymization_info_;
  this_._impl_.~Impl_();
}

inline void* SimpleTableProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SimpleTableProto(arena);
}
constexpr auto SimpleTableProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.column_) +
          decltype(SimpleTableProto::_impl_.column_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.primary_key_column_index_) +
          decltype(SimpleTableProto::_impl_.primary_key_column_index_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.row_identity_column_index_) +
          decltype(SimpleTableProto::_impl_.row_identity_column_index_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SimpleTableProto), alignof(SimpleTableProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SimpleTableProto::PlacementNew_,
                                 sizeof(SimpleTableProto),
                                 alignof(SimpleTableProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SimpleTableProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SimpleTableProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        SimpleTableProto::IsInitializedImpl,
        &SimpleTableProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SimpleTableProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SimpleTableProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SimpleTableProto>(), &SimpleTableProto::ByteSizeLong,
            &SimpleTableProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_._cached_size_),
        false,
    },
    &SimpleTableProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SimpleTableProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 2, 71, 2> SimpleTableProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::SimpleTableProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.name_)}},
    // optional int64 serialization_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SimpleTableProto, _impl_.serialization_id_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.serialization_id_)}},
    // optional bool is_value_table = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleTableProto, _impl_.is_value_table_), 5>(),
     {24, 5, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.is_value_table_)}},
    // repeated .googlesql.SimpleColumnProto column = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.column_)}},
    // optional string name_in_catalog = 5;
    {::_pbi::TcParser::FastSS1,
     {42, 1, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.name_in_catalog_)}},
    // optional bool allow_anonymous_column_name = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleTableProto, _impl_.allow_anonymous_column_name_), 6>(),
     {48, 6, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.allow_anonymous_column_name_)}},
    // optional bool allow_duplicate_column_names = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleTableProto, _impl_.allow_duplicate_column_names_), 7>(),
     {56, 7, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.allow_duplicate_column_names_)}},
    // optional .googlesql.SimpleAnonymizationInfoProto anonymization_info = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 3, 1, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.anonymization_info_)}},
    // repeated int32 primary_key_column_index = 9;
    {::_pbi::TcParser::FastV32R1,
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.primary_key_column_index_)}},
    // optional string full_name = 10;
    {::_pbi::TcParser::FastSS1,
     {82, 2, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.full_name_)}},
    // repeated int32 row_identity_column_index = 11;
    {::_pbi::TcParser::FastV32R1,
     {88, 63, 0, PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.row_identity_column_index_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string name = 1;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int64 serialization_id = 2;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.serialization_id_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional bool is_value_table = 3;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.is_value_table_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // repeated .googlesql.SimpleColumnProto column = 4;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.column_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string name_in_catalog = 5;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.name_in_catalog_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional bool allow_anonymous_column_name = 6;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.allow_anonymous_column_name_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool allow_duplicate_column_names = 7;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.allow_duplicate_column_names_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .googlesql.SimpleAnonymizationInfoProto anonymization_info = 8;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.anonymization_info_), _Internal::kHasBitsOffset + 3, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated int32 primary_key_column_index = 9;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.primary_key_column_index_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kInt32)},
    // optional string full_name = 10;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.full_name_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated int32 row_identity_column_index = 11;
    {PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.row_identity_column_index_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::SimpleColumnProto>()},
    {::_pbi::TcParser::GetTable<::googlesql::SimpleAnonymizationInfoProto>()},
  }}, {{
    "\32\4\0\0\0\17\0\0\0\0\11\0\0\0\0\0"
    "googlesql.SimpleTableProto"
    "name"
    "name_in_catalog"
    "full_name"
  }},
};

PROTOBUF_NOINLINE void SimpleTableProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.SimpleTableProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.column_.Clear();
  _impl_.primary_key_column_index_.Clear();
  _impl_.row_identity_column_index_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.name_in_catalog_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.full_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.anonymization_info_ != nullptr);
      _impl_.anonymization_info_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f0u) {
    ::memset(&_impl_.serialization_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.allow_duplicate_column_names_) -
        reinterpret_cast<char*>(&_impl_.serialization_id_)) + sizeof(_impl_.allow_duplicate_column_names_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SimpleTableProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SimpleTableProto& this_ = static_cast<const SimpleTableProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SimpleTableProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SimpleTableProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.SimpleTableProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.SimpleTableProto.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional int64 serialization_id = 2;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_serialization_id(), target);
          }

          // optional bool is_value_table = 3;
          if (cached_has_bits & 0x00000020u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_is_value_table(), target);
          }

          // repeated .googlesql.SimpleColumnProto column = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_column_size());
               i < n; i++) {
            const auto& repfield = this_._internal_column().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // optional string name_in_catalog = 5;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_name_in_catalog();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.SimpleTableProto.name_in_catalog");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // optional bool allow_anonymous_column_name = 6;
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_allow_anonymous_column_name(), target);
          }

          // optional bool allow_duplicate_column_names = 7;
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_allow_duplicate_column_names(), target);
          }

          // optional .googlesql.SimpleAnonymizationInfoProto anonymization_info = 8;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                8, *this_._impl_.anonymization_info_, this_._impl_.anonymization_info_->GetCachedSize(), target,
                stream);
          }

          // repeated int32 primary_key_column_index = 9;
          for (int i = 0, n = this_._internal_primary_key_column_index_size(); i < n; ++i) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                9, this_._internal_primary_key_column_index().Get(i), target);
          }

          // optional string full_name = 10;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_full_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.SimpleTableProto.full_name");
            target = stream->WriteStringMaybeAliased(10, _s, target);
          }

          // repeated int32 row_identity_column_index = 11;
          for (int i = 0, n = this_._internal_row_identity_column_index_size(); i < n; ++i) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                11, this_._internal_row_identity_column_index().Get(i), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.SimpleTableProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SimpleTableProto::ByteSizeLong(const MessageLite& base) {
          const SimpleTableProto& this_ = static_cast<const SimpleTableProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SimpleTableProto::ByteSizeLong() const {
          const SimpleTableProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.SimpleTableProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .googlesql.SimpleColumnProto column = 4;
            {
              total_size += 1UL * this_._internal_column_size();
              for (const auto& msg : this_._internal_column()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated int32 primary_key_column_index = 9;
            {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_primary_key_column_index());
              std::size_t tag_size = std::size_t{1} *
                  ::_pbi::FromIntSize(this_._internal_primary_key_column_index_size());
              total_size += tag_size + data_size;
            }
            // repeated int32 row_identity_column_index = 11;
            {
              std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
                  this_._internal_row_identity_column_index());
              std::size_t tag_size = std::size_t{1} *
                  ::_pbi::FromIntSize(this_._internal_row_identity_column_index_size());
              total_size += tag_size + data_size;
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string name = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // optional string name_in_catalog = 5;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name_in_catalog());
            }
            // optional string full_name = 10;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_full_name());
            }
            // optional .googlesql.SimpleAnonymizationInfoProto anonymization_info = 8;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.anonymization_info_);
            }
            // optional int64 serialization_id = 2;
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_serialization_id());
            }
            // optional bool is_value_table = 3;
            if (cached_has_bits & 0x00000020u) {
              total_size += 2;
            }
            // optional bool allow_anonymous_column_name = 6;
            if (cached_has_bits & 0x00000040u) {
              total_size += 2;
            }
            // optional bool allow_duplicate_column_names = 7;
            if (cached_has_bits & 0x00000080u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SimpleTableProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SimpleTableProto*>(&to_msg);
  auto& from = static_cast<const SimpleTableProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.SimpleTableProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_column()->MergeFrom(
      from._internal_column());
  _this->_internal_mutable_primary_key_column_index()->MergeFrom(from._internal_primary_key_column_index());
  _this->_internal_mutable_row_identity_column_index()->MergeFrom(from._internal_row_identity_column_index());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_name_in_catalog(from._internal_name_in_catalog());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_full_name(from._internal_full_name());
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.anonymization_info_ != nullptr);
      if (_this->_impl_.anonymization_info_ == nullptr) {
        _this->_impl_.anonymization_info_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::SimpleAnonymizationInfoProto>(arena, *from._impl_.anonymization_info_);
      } else {
        _this->_impl_.anonymization_info_->MergeFrom(*from._impl_.anonymization_info_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.serialization_id_ = from._impl_.serialization_id_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.is_value_table_ = from._impl_.is_value_table_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.allow_anonymous_column_name_ = from._impl_.allow_anonymous_column_name_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.allow_duplicate_column_names_ = from._impl_.allow_duplicate_column_names_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleTableProto::CopyFrom(const SimpleTableProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.SimpleTableProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SimpleTableProto::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const SimpleTableProto&>(msg);
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_column()))
    return false;
  return true;
}

void SimpleTableProto::InternalSwap(SimpleTableProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.column_.InternalSwap(&other->_impl_.column_);
  _impl_.primary_key_column_index_.InternalSwap(&other->_impl_.primary_key_column_index_);
  _impl_.row_identity_column_index_.InternalSwap(&other->_impl_.row_identity_column_index_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_in_catalog_, &other->_impl_.name_in_catalog_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.full_name_, &other->_impl_.full_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.allow_duplicate_column_names_)
      + sizeof(SimpleTableProto::_impl_.allow_duplicate_column_names_)
      - PROTOBUF_FIELD_OFFSET(SimpleTableProto, _impl_.anonymization_info_)>(
          reinterpret_cast<char*>(&_impl_.anonymization_info_),
          reinterpret_cast<char*>(&other->_impl_.anonymization_info_));
}

::google::protobuf::Metadata SimpleTableProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ExpressionAttributeProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExpressionAttributeProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_._has_bits_);
};

ExpressionAttributeProto::ExpressionAttributeProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.ExpressionAttributeProto)
}
inline PROTOBUF_NDEBUG_INLINE ExpressionAttributeProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::ExpressionAttributeProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        row_identity_column_index_{visibility, arena, from.row_identity_column_index_},
        _row_identity_column_index_cached_byte_size_{0},
        expression_string_(arena, from.expression_string_) {}

ExpressionAttributeProto::ExpressionAttributeProto(
    ::google::protobuf::Arena* arena,
    const ExpressionAttributeProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ExpressionAttributeProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.expression_kind_ = from._impl_.expression_kind_;

  // @@protoc_insertion_point(copy_constructor:googlesql.ExpressionAttributeProto)
}
inline PROTOBUF_NDEBUG_INLINE ExpressionAttributeProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        row_identity_column_index_{visibility, arena},
        _row_identity_column_index_cached_byte_size_{0},
        expression_string_(arena) {}

inline void ExpressionAttributeProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.expression_kind_ = {};
}
ExpressionAttributeProto::~ExpressionAttributeProto() {
  // @@protoc_insertion_point(destructor:googlesql.ExpressionAttributeProto)
  SharedDtor(*this);
}
inline void ExpressionAttributeProto::SharedDtor(MessageLite& self) {
  ExpressionAttributeProto& this_ = static_cast<ExpressionAttributeProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.expression_string_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ExpressionAttributeProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ExpressionAttributeProto(arena);
}
constexpr auto ExpressionAttributeProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.row_identity_column_index_) +
          decltype(ExpressionAttributeProto::_impl_.row_identity_column_index_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ExpressionAttributeProto), alignof(ExpressionAttributeProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ExpressionAttributeProto::PlacementNew_,
                                 sizeof(ExpressionAttributeProto),
                                 alignof(ExpressionAttributeProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ExpressionAttributeProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ExpressionAttributeProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ExpressionAttributeProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ExpressionAttributeProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ExpressionAttributeProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ExpressionAttributeProto>(), &ExpressionAttributeProto::ByteSizeLong,
            &ExpressionAttributeProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_._cached_size_),
        false,
    },
    &ExpressionAttributeProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ExpressionAttributeProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 60, 2> ExpressionAttributeProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_._has_bits_),
    0, // no _extensions_
    10, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966399,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::ExpressionAttributeProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string expression_string = 8;
    {::_pbi::TcParser::FastSS1,
     {66, 0, 0, PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.expression_string_)}},
    // optional .googlesql.ExpressionAttributeProto.ExpressionKind expression_kind = 9;
    {::_pbi::TcParser::FastEr0S1,
     {72, 1, 2, PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.expression_kind_)}},
    // repeated int32 row_identity_column_index = 10 [packed = true];
    {::_pbi::TcParser::FastV32P1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.row_identity_column_index_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string expression_string = 8;
    {PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.expression_string_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional .googlesql.ExpressionAttributeProto.ExpressionKind expression_kind = 9;
    {PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.expression_kind_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // repeated int32 row_identity_column_index = 10 [packed = true];
    {PROTOBUF_FIELD_OFFSET(ExpressionAttributeProto, _impl_.row_identity_column_index_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }}, {{
    {0, 3},
  }}, {{
    "\42\21\0\0\0\0\0\0"
    "googlesql.ExpressionAttributeProto"
    "expression_string"
  }},
};

PROTOBUF_NOINLINE void ExpressionAttributeProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.ExpressionAttributeProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.row_identity_column_index_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.expression_string_.ClearNonDefaultToEmpty();
  }
  _impl_.expression_kind_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ExpressionAttributeProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ExpressionAttributeProto& this_ = static_cast<const ExpressionAttributeProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ExpressionAttributeProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ExpressionAttributeProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.ExpressionAttributeProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string expression_string = 8;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_expression_string();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.ExpressionAttributeProto.expression_string");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          // optional .googlesql.ExpressionAttributeProto.ExpressionKind expression_kind = 9;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                9, this_._internal_expression_kind(), target);
          }

          // repeated int32 row_identity_column_index = 10 [packed = true];
          {
            int byte_size = this_._impl_._row_identity_column_index_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  10, this_._internal_row_identity_column_index(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.ExpressionAttributeProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ExpressionAttributeProto::ByteSizeLong(const MessageLite& base) {
          const ExpressionAttributeProto& this_ = static_cast<const ExpressionAttributeProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ExpressionAttributeProto::ByteSizeLong() const {
          const ExpressionAttributeProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.ExpressionAttributeProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 row_identity_column_index = 10 [packed = true];
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_row_identity_column_index(), 1,
                      this_._impl_._row_identity_column_index_cached_byte_size_);
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string expression_string = 8;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_expression_string());
            }
            // optional .googlesql.ExpressionAttributeProto.ExpressionKind expression_kind = 9;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_expression_kind());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ExpressionAttributeProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExpressionAttributeProto*>(&to_msg);
  auto& from = static_cast<const ExpressionAttributeProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.ExpressionAttributeProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_row_identity_column_index()->MergeFrom(from._internal_row_identity_column_index());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_expression_string(from._internal_expression_string());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.expression_kind_ = from._impl_.expression_kind_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExpressionAttributeProto::CopyFrom(const ExpressionAttributeProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.ExpressionAttributeProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExpressionAttributeProto::InternalSwap(ExpressionAttributeProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.row_identity_column_index_.InternalSwap(&other->_impl_.row_identity_column_index_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.expression_string_, &other->_impl_.expression_string_, arena);
  swap(_impl_.expression_kind_, other->_impl_.expression_kind_);
}

::google::protobuf::Metadata ExpressionAttributeProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SimpleColumnProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SimpleColumnProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_._has_bits_);
};

void SimpleColumnProto::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.type_ != nullptr) _impl_.type_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void SimpleColumnProto::clear_annotation_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.annotation_map_ != nullptr) _impl_.annotation_map_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
SimpleColumnProto::SimpleColumnProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:googlesql.SimpleColumnProto)
}
inline PROTOBUF_NDEBUG_INLINE SimpleColumnProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::googlesql::SimpleColumnProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

SimpleColumnProto::SimpleColumnProto(
    ::google::protobuf::Arena* arena,
    const SimpleColumnProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SimpleColumnProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.type_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::TypeProto>(
                              arena, *from._impl_.type_)
                        : nullptr;
  _impl_.annotation_map_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::AnnotationMapProto>(
                              arena, *from._impl_.annotation_map_)
                        : nullptr;
  _impl_.column_expression_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::googlesql::ExpressionAttributeProto>(
                              arena, *from._impl_.column_expression_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, is_pseudo_column_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, is_pseudo_column_),
           offsetof(Impl_, is_writable_column_) -
               offsetof(Impl_, is_pseudo_column_) +
               sizeof(Impl_::is_writable_column_));

  // @@protoc_insertion_point(copy_constructor:googlesql.SimpleColumnProto)
}
inline PROTOBUF_NDEBUG_INLINE SimpleColumnProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena),
        is_writable_column_{true} {}

inline void SimpleColumnProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, has_default_value_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::has_default_value_));
}
SimpleColumnProto::~SimpleColumnProto() {
  // @@protoc_insertion_point(destructor:googlesql.SimpleColumnProto)
  SharedDtor(*this);
}
inline void SimpleColumnProto::SharedDtor(MessageLite& self) {
  SimpleColumnProto& this_ = static_cast<SimpleColumnProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.type_;
  delete this_._impl_.annotation_map_;
  delete this_._impl_.column_expression_;
  this_._impl_.~Impl_();
}

inline void* SimpleColumnProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SimpleColumnProto(arena);
}
constexpr auto SimpleColumnProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SimpleColumnProto),
                                            alignof(SimpleColumnProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SimpleColumnProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SimpleColumnProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        SimpleColumnProto::IsInitializedImpl,
        &SimpleColumnProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SimpleColumnProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SimpleColumnProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SimpleColumnProto>(), &SimpleColumnProto::ByteSizeLong,
            &SimpleColumnProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_._cached_size_),
        false,
    },
    &SimpleColumnProto::kDescriptorMethods,
    &descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SimpleColumnProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 3, 48, 2> SimpleColumnProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::googlesql::SimpleColumnProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .googlesql.ExpressionAttributeProto column_expression = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 3, 2, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.column_expression_)}},
    // optional string name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.name_)}},
    // optional .googlesql.TypeProto type = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.type_)}},
    // optional bool is_pseudo_column = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleColumnProto, _impl_.is_pseudo_column_), 4>(),
     {24, 4, 0, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.is_pseudo_column_)}},
    // optional bool is_writable_column = 4 [default = true];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleColumnProto, _impl_.is_writable_column_), 7>(),
     {32, 7, 0, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.is_writable_column_)}},
    // optional .googlesql.AnnotationMapProto annotation_map = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 1, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.annotation_map_)}},
    // optional bool can_update_unwritable_to_default = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleColumnProto, _impl_.can_update_unwritable_to_default_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.can_update_unwritable_to_default_)}},
    // optional bool has_default_value = 7 [default = false];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimpleColumnProto, _impl_.has_default_value_), 6>(),
     {56, 6, 0, PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.has_default_value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string name = 1;
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional .googlesql.TypeProto type = 2;
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.type_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bool is_pseudo_column = 3;
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.is_pseudo_column_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool is_writable_column = 4 [default = true];
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.is_writable_column_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .googlesql.AnnotationMapProto annotation_map = 5;
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.annotation_map_), _Internal::kHasBitsOffset + 2, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bool can_update_unwritable_to_default = 6;
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.can_update_unwritable_to_default_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool has_default_value = 7 [default = false];
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.has_default_value_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .googlesql.ExpressionAttributeProto column_expression = 8;
    {PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.column_expression_), _Internal::kHasBitsOffset + 3, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::googlesql::TypeProto>()},
    {::_pbi::TcParser::GetTable<::googlesql::AnnotationMapProto>()},
    {::_pbi::TcParser::GetTable<::googlesql::ExpressionAttributeProto>()},
  }}, {{
    "\33\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "googlesql.SimpleColumnProto"
    "name"
  }},
};

PROTOBUF_NOINLINE void SimpleColumnProto::Clear() {
// @@protoc_insertion_point(message_clear_start:googlesql.SimpleColumnProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.type_ != nullptr);
      _impl_.type_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.annotation_map_ != nullptr);
      _impl_.annotation_map_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.column_expression_ != nullptr);
      _impl_.column_expression_->Clear();
    }
  }
  ::memset(&_impl_.is_pseudo_column_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.has_default_value_) -
      reinterpret_cast<char*>(&_impl_.is_pseudo_column_)) + sizeof(_impl_.has_default_value_));
  _impl_.is_writable_column_ = true;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SimpleColumnProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SimpleColumnProto& this_ = static_cast<const SimpleColumnProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SimpleColumnProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SimpleColumnProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:googlesql.SimpleColumnProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "googlesql.SimpleColumnProto.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional .googlesql.TypeProto type = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.type_, this_._impl_.type_->GetCachedSize(), target,
                stream);
          }

          // optional bool is_pseudo_column = 3;
          if (cached_has_bits & 0x00000010u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_is_pseudo_column(), target);
          }

          // optional bool is_writable_column = 4 [default = true];
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_is_writable_column(), target);
          }

          // optional .googlesql.AnnotationMapProto annotation_map = 5;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                5, *this_._impl_.annotation_map_, this_._impl_.annotation_map_->GetCachedSize(), target,
                stream);
          }

          // optional bool can_update_unwritable_to_default = 6;
          if (cached_has_bits & 0x00000020u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_can_update_unwritable_to_default(), target);
          }

          // optional bool has_default_value = 7 [default = false];
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_has_default_value(), target);
          }

          // optional .googlesql.ExpressionAttributeProto column_expression = 8;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                8, *this_._impl_.column_expression_, this_._impl_.column_expression_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:googlesql.SimpleColumnProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SimpleColumnProto::ByteSizeLong(const MessageLite& base) {
          const SimpleColumnProto& this_ = static_cast<const SimpleColumnProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SimpleColumnProto::ByteSizeLong() const {
          const SimpleColumnProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:googlesql.SimpleColumnProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string name = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // optional .googlesql.TypeProto type = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.type_);
            }
            // optional .googlesql.AnnotationMapProto annotation_map = 5;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.annotation_map_);
            }
            // optional .googlesql.ExpressionAttributeProto column_expression = 8;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.column_expression_);
            }
            // optional bool is_pseudo_column = 3;
            if (cached_has_bits & 0x00000010u) {
              total_size += 2;
            }
            // optional bool can_update_unwritable_to_default = 6;
            if (cached_has_bits & 0x00000020u) {
              total_size += 2;
            }
            // optional bool has_default_value = 7 [default = false];
            if (cached_has_bits & 0x00000040u) {
              total_size += 2;
            }
            // optional bool is_writable_column = 4 [default = true];
            if (cached_has_bits & 0x00000080u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SimpleColumnProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SimpleColumnProto*>(&to_msg);
  auto& from = static_cast<const SimpleColumnProto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:googlesql.SimpleColumnProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.type_ != nullptr);
      if (_this->_impl_.type_ == nullptr) {
        _this->_impl_.type_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::TypeProto>(arena, *from._impl_.type_);
      } else {
        _this->_impl_.type_->MergeFrom(*from._impl_.type_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.annotation_map_ != nullptr);
      if (_this->_impl_.annotation_map_ == nullptr) {
        _this->_impl_.annotation_map_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::AnnotationMapProto>(arena, *from._impl_.annotation_map_);
      } else {
        _this->_impl_.annotation_map_->MergeFrom(*from._impl_.annotation_map_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.column_expression_ != nullptr);
      if (_this->_impl_.column_expression_ == nullptr) {
        _this->_impl_.column_expression_ =
            ::google::protobuf::Message::CopyConstruct<::googlesql::ExpressionAttributeProto>(arena, *from._impl_.column_expression_);
      } else {
        _this->_impl_.column_expression_->MergeFrom(*from._impl_.column_expression_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.is_pseudo_column_ = from._impl_.is_pseudo_column_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.can_update_unwritable_to_default_ = from._impl_.can_update_unwritable_to_default_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.has_default_value_ = from._impl_.has_default_value_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.is_writable_column_ = from._impl_.is_writable_column_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleColumnProto::CopyFrom(const SimpleColumnProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:googlesql.SimpleColumnProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SimpleColumnProto::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const SimpleColumnProto&>(msg);
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._impl_.type_->IsInitialized()) return false;
  }
  return true;
}

void SimpleColumnProto::InternalSwap(SimpleColumnProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.is_writable_column_)
      + sizeof(SimpleColumnProto::_impl_.is_writable_column_)
      - PROTOBUF_FIELD_OFFSET(SimpleColumnProto, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata SimpleColumnProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init_googlesql_public_simple_table_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
