#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_NON_SQL_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_NON_SQL_FUNCTION_EXPORT_H

#include "googlesql/legacy_zetasql/public/non_sql_function.h"
// include sources
#include "googlesql/legacy_zetasql/public/non_sql_function.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/public/error_helpers/export.inc"
#include "go-zetasql/legacy_zetasql/public/function/export.inc"
#include "go-zetasql/legacy_zetasql/public/parse_resume_location/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
