#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_JSON_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_JSON_INTERNAL_EXPORT_H

#include "googlesql/public/functions/json_internal.h"
// include sources
#include "googlesql/public/functions/json_internal.cc"
// include dependencies
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/json_parser/export.inc"
#include "go-zetasql/common/json_util/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-re2/re2/export.inc"

#endif
