#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_FLEX_TOKEN_PROVIDER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_FLEX_TOKEN_PROVIDER_EXPORT_H

#include "googlesql/legacy_zetasql/parser/macros/flex_token_provider.h"
// include sources
#include "googlesql/legacy_zetasql/parser/macros/flex_token_provider.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/parser/macros/token_provider_base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/parser/flex_tokenizer/export.inc"
#include "go-googlesql/parser/token/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
