#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_PRIVACY_PRIVACY_UTILITY_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_PRIVACY_PRIVACY_UTILITY_EXPORT_H

#include "zetasql/analyzer/rewriters/privacy/privacy_utility.h"
// include sources
#include "zetasql/analyzer/rewriters/privacy/privacy_utility.cc"
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"

#endif
