#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ANALYZER_OUTPUT_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ANALYZER_OUTPUT_EXPORT_H

#include "googlesql/legacy_zetasql/public/analyzer_output.h"
// include sources
#include "googlesql/legacy_zetasql/public/analyzer_output.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/analyzer_options/export.inc"
#include "go-googlesql/legacy_zetasql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/legacy_zetasql/public/id_string/export.inc"
#include "go-googlesql/legacy_zetasql/public/language_options/export.inc"
#include "go-googlesql/legacy_zetasql/public/options_cc_proto/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/enum_utils/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/common/timer_util/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/proto/logging_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"

#endif
