#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_FUNCTION_SIGNATURE_MATCHER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_FUNCTION_SIGNATURE_MATCHER_EXPORT_H

#include "zetasql/analyzer/function_signature_matcher.h"
// include sources
#include "zetasql/analyzer/function_signature_matcher.cc"
// include dependencies
#include "go-zetasql/analyzer/lambda_util/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/signature_match_result/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/span/export.inc"

#endif
