#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_MATH_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_MATH_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/math.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/math.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/public/functions/arithmetics/export.inc"
#include "go-zetasql/legacy_zetasql/public/functions/rounding_mode_cc_proto/export.inc"
#include "go-zetasql/legacy_zetasql/public/functions/util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/multiprecision_int/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
