#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GLOBALS_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GLOBALS_EXPORT_H

#include "absl/log/globals.h"
// include sources
// include dependencies
#include "go-absl/base/atomic_hook/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/log/go_internal/vlog_config/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
