#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_EPSILON_REMOVER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_EPSILON_REMOVER_EXPORT_H

#include "googlesql/legacy_zetasql/common/match_recognize/epsilon_remover.h"
// include sources
#include "googlesql/legacy_zetasql/common/match_recognize/epsilon_remover.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/common/match_recognize/nfa/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
