#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_MAP_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_MAP_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/functions/map.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/functions/map.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/optional_ref/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/internal_value/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/reference_impl/evaluation/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
