#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_UUID_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_UUID_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/functions/uuid.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/functions/uuid.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/uuid/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
