#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_TOKEN_PROVIDER_BASE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_TOKEN_PROVIDER_BASE_EXPORT_H

#include "googlesql/parser/macros/token_provider_base.h"
// include sources
// include dependencies
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
