#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANALYZER_OUTPUT_PROPERTIES_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANALYZER_OUTPUT_PROPERTIES_EXPORT_H

#include "googlesql/public/analyzer_output_properties.h"
// include sources
// include dependencies
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/target_syntax/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
