#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_SIMPLE_CATALOG_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_SIMPLE_CATALOG_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/public/simple_catalog_util.h"
// include sources
#include "googlesql/legacy_zetasql/public/simple_catalog_util.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/public/analyzer/export.inc"
#include "go-zetasql/legacy_zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/legacy_zetasql/public/analyzer_output/export.inc"
#include "go-zetasql/legacy_zetasql/public/catalog/export.inc"
#include "go-zetasql/legacy_zetasql/public/function/export.inc"
#include "go-zetasql/legacy_zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/legacy_zetasql/public/function_headers/export.inc"
#include "go-zetasql/legacy_zetasql/public/simple_catalog/export.inc"
#include "go-zetasql/legacy_zetasql/public/sql_constant/export.inc"
#include "go-zetasql/legacy_zetasql/public/sql_function/export.inc"
#include "go-zetasql/legacy_zetasql/public/sql_tvf/export.inc"
#include "go-zetasql/legacy_zetasql/public/sql_view/export.inc"
#include "go-zetasql/legacy_zetasql/public/templated_sql_function/export.inc"
#include "go-zetasql/legacy_zetasql/public/templated_sql_tvf/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/internal_property_graph/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
