#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_FILTER_FIELDS_PATH_VALIDATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_FILTER_FIELDS_PATH_VALIDATOR_EXPORT_H

#include "googlesql/analyzer/filter_fields_path_validator.h"
// include sources
#include "googlesql/analyzer/filter_fields_path_validator.cc"
// include dependencies
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
