#ifndef INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_PARSED_SCRIPT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_PARSED_SCRIPT_EXPORT_H

#include "zetasql/scripting/parsed_script.h"
// include sources
#include "zetasql/scripting/parsed_script.cc"
// include dependencies
#include "go-zetasql/scripting/control_flow_graph/export.inc"
#include "go-zetasql/scripting/error_helpers/export.inc"
#include "go-zetasql/scripting/type_aliases/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/variant/export.inc"

#endif
