#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_NUMERIC_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_NUMERIC_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/numeric.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/numeric.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/functions/util/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
