#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_INTERNAL_ANALYZER_OUTPUT_PROPERTIES_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_INTERNAL_ANALYZER_OUTPUT_PROPERTIES_EXPORT_H

#include "zetasql/common/internal_analyzer_output_properties.h"
// include sources
// include dependencies
#include "go-zetasql/public/analyzer_output_properties/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/target_syntax/export.inc"

#endif
