#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_TYPES_INTERNAL_PROTO_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_TYPES_INTERNAL_PROTO_UTILS_EXPORT_H

#include "googlesql/public/types/internal_proto_utils.h"
// include sources
#include "googlesql/public/types/internal_proto_utils.cc"
// include dependencies
#include "go-googlesql/public/types/type/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/proto_helper/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-absl/status/status/export.inc"

#endif
