#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_GENERALIZED_QUERY_STMT_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_GENERALIZED_QUERY_STMT_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/generalized_query_stmt_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/generalized_query_stmt_rewriter.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
