#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_TEMPLATED_SQL_TVF_NO_RESOLVER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_TEMPLATED_SQL_TVF_NO_RESOLVER_EXPORT_H

#include "googlesql/public/templated_sql_tvf.h"
// include sources
// include dependencies
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_resume_location/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
