#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_RANGE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_RANGE_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/range.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/range.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/functions/date_time_util/export.inc"
#include "go-googlesql/legacy_zetasql/public/functions/datetime_cc_proto/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/endian/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/civil_time/export.inc"
#include "go-googlesql/public/interval_value/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"

#endif
