#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_BITS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_BITS_EXPORT_H

#include "googlesql/base/bits.h"
// include sources
#include "googlesql/base/bits.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/endian/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
