#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_SET_OPERATION_RESOLVER_BASE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_SET_OPERATION_RESOLVER_BASE_EXPORT_H

#include "googlesql/analyzer/set_operation_resolver_base.h"
// include sources
#include "googlesql/analyzer/set_operation_resolver_base.cc"
// include dependencies
#include "go-zetasql/analyzer/input_argument_type_resolver_helper/export.inc"
#include "go-zetasql/analyzer/resolver_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/stl_util/export.inc"
#include "go-zetasql/parser/parse_tree/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/function_headers/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/column_factory/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
