
#ifndef googlesql_reference_impl_statement_evaluator_bind_cc
#define googlesql_reference_impl_statement_evaluator_bind_cc

// switch namespace
#define differential_privacy googlesql_reference_impl_statement_evaluator_differential_privacy
#define googlesql googlesql_reference_impl_statement_evaluator_googlesql
#define googlesql_base googlesql_reference_impl_statement_evaluator_googlesql_base
#define googlesql_bison_parser googlesql_reference_impl_statement_evaluator_googlesql_bison_parser
#define re2 googlesql_reference_impl_statement_evaluator_re2
#define AbslInternalSleepFor googlesql_reference_impl_statement_evaluator_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_reference_impl_statement_evaluator_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_reference_impl_statement_evaluator_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_reference_impl_statement_evaluator_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_reference_impl_statement_evaluator_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_reference_impl_statement_evaluator_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_reference_impl_statement_evaluator_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_reference_impl_statement_evaluator_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_reference_impl_statement_evaluator_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_reference_impl_statement_evaluator_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_reference_impl_statement_evaluator_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_reference_impl_statement_evaluator_GoogleSqlalloc
#define GoogleSqlfree googlesql_reference_impl_statement_evaluator_GoogleSqlfree
#define GoogleSqlrealloc googlesql_reference_impl_statement_evaluator_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_reference_impl_statement_evaluator_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_reference_impl_statement_evaluator_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_reference_impl_statement_evaluator_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_reference_impl_statement_evaluator_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_reference_impl_statement_evaluator_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_reference_impl_statement_evaluator_GoogleSqlFlexLexer
#define UCaseMap googlesql_reference_impl_statement_evaluator_UCaseMap

#define GO_EXPORT(def) export_googlesql_reference_impl_statement_evaluator_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/reference_impl/statement_evaluator.h"
//#undef private

// include sources
#include "googlesql/reference_impl/statement_evaluator.cc"

// include dependencies
#include "go-googlesql/reference_impl/evaluator_table_iterator_cc_proto/export.inc"
#include "go-googlesql/reference_impl/type_helpers/export.inc"
#include "go-googlesql/reference_impl/type_parameter_constraints/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/status_payload_utils/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/proto/script_exception_cc_proto/export.inc"
#include "go-googlesql/public/analyzer/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/evaluator/export.inc"
#include "go-googlesql/public/evaluator_table_iterator/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/multi_catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/simple_catalog/export.inc"
#include "go-googlesql/public/simple_catalog_util/export.inc"
#include "go-googlesql/public/sql_procedure/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-googlesql/scripting/error_helpers/export.inc"
#include "go-googlesql/scripting/parsed_script/export.inc"
#include "go-googlesql/scripting/script_executor/export.inc"
#include "go-googlesql/scripting/script_segment/export.inc"
#include "go-googlesql/scripting/type_aliases/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_reference_impl_statement_evaluator_bind_cc */
