
#ifndef algorithms_binary_search_bind_cc
#define algorithms_binary_search_bind_cc

// switch namespace
#define differential_privacy algorithms_binary_search_differential_privacy
#define googlesql algorithms_binary_search_googlesql
#define googlesql_base algorithms_binary_search_googlesql_base
#define googlesql_bison_parser algorithms_binary_search_googlesql_bison_parser
#define re2 algorithms_binary_search_re2
#define AbslInternalSleepFor algorithms_binary_search_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_binary_search_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_binary_search_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_binary_search_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_binary_search_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_binary_search_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_binary_search_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_binary_search_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_binary_search_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_binary_search_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_binary_search_AbslInternalGetFileMappingHint
#define GoogleSqlalloc algorithms_binary_search_GoogleSqlalloc
#define GoogleSqlfree algorithms_binary_search_GoogleSqlfree
#define GoogleSqlrealloc algorithms_binary_search_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_binary_search_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream algorithms_binary_search_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_binary_search_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream algorithms_binary_search_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit algorithms_binary_search_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path algorithms_binary_search_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width algorithms_binary_search_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance algorithms_binary_search_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period algorithms_binary_search_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit algorithms_binary_search_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path algorithms_binary_search_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width algorithms_binary_search_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance algorithms_binary_search_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period algorithms_binary_search_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes algorithms_binary_search_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes algorithms_binary_search_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string algorithms_binary_search_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string algorithms_binary_search_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability algorithms_binary_search_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability algorithms_binary_search_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests algorithms_binary_search_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests algorithms_binary_search_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase algorithms_binary_search_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer algorithms_binary_search_GoogleSqlFlexLexer
#define UCaseMap algorithms_binary_search_UCaseMap

#define GO_EXPORT(def) export_algorithms_binary_search_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "algorithms/binary-search.h"
//#undef private

// include sources

// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/numerical-mechanisms/export.inc"
#include "go-base/percentile/export.inc"
#include "go-proto/util-lib/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-base/status/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_binary_search_bind_cc */
