#ifndef INTERNAL_CCALL_GO_ALGORITHMS_BINARY_SEARCH_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_BINARY_SEARCH_EXPORT_H

#include "algorithms/binary-search.h"
// include sources
// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/numerical-mechanisms/export.inc"
#include "go-base/percentile/export.inc"
#include "go-proto/util-lib/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-base/status/export.inc"

#endif
