#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_NULLSTREAM_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_NULLSTREAM_EXPORT_H

#include "absl/log/internal/nullstream.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
