
#ifndef absl_types_variant_bind_cc
#define absl_types_variant_bind_cc

// switch namespace
#define differential_privacy absl_types_variant_differential_privacy
#define googlesql absl_types_variant_googlesql
#define googlesql_base absl_types_variant_googlesql_base
#define googlesql_bison_parser absl_types_variant_googlesql_bison_parser
#define re2 absl_types_variant_re2
#define AbslInternalSleepFor absl_types_variant_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_types_variant_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_types_variant_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_types_variant_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_types_variant_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_types_variant_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_types_variant_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_types_variant_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_types_variant_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_types_variant_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_types_variant_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_types_variant_GoogleSqlalloc
#define GoogleSqlfree absl_types_variant_GoogleSqlfree
#define GoogleSqlrealloc absl_types_variant_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_types_variant_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_types_variant_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_types_variant_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_types_variant_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_types_variant_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_types_variant_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_types_variant_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_types_variant_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_types_variant_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_types_variant_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_types_variant_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_types_variant_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_types_variant_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_types_variant_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_types_variant_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_types_variant_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_types_variant_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_types_variant_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_types_variant_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_types_variant_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_types_variant_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_types_variant_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_types_variant_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_types_variant_GoogleSqlFlexLexer
#define UCaseMap absl_types_variant_UCaseMap

#define GO_EXPORT(def) export_absl_types_variant_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/types/variant.h"
//#undef private

// include sources
#include "absl/types/internal/variant.h"

// include dependencies
#include "go-absl/types/bad_variant_access/export.inc"
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/utility/utility/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_types_variant_bind_cc */
