#ifndef INTERNAL_CCALL_GO_ABSL_TYPES_VARIANT_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_TYPES_VARIANT_EXPORT_H

// include dependencies
#include "go-absl/types/bad_variant_access/export.inc"
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
