#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_ROW_EDGE_LIST_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_ROW_EDGE_LIST_EXPORT_H

#include "googlesql/legacy_zetasql/common/match_recognize/row_edge_list.h"
// include sources
#include "googlesql/legacy_zetasql/common/match_recognize/row_edge_list.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/common/match_recognize/compiled_nfa/export.inc"
#include "go-zetasql/legacy_zetasql/common/match_recognize/nfa/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
