#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_TYPES_INTERNAL_PROTO_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_TYPES_INTERNAL_PROTO_UTILS_EXPORT_H

#include "googlesql/public/types/internal_proto_utils.h"
// include sources
#include "googlesql/public/types/internal_proto_utils.cc"
// include dependencies
#include "go-zetasql/public/types/type/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/proto_helper/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
