#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FILE_MODULE_CONTENTS_FETCHER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FILE_MODULE_CONTENTS_FETCHER_EXPORT_H

#include "googlesql/public/file_module_contents_fetcher.h"
// include sources
#include "googlesql/public/file_module_contents_fetcher.cc"
// include dependencies
#include "go-zetasql/public/module_contents_fetcher/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/base/file_util/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/path/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/proto_helper/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/proto/module_options_cc_proto/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
