#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_EVALUATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_EVALUATOR_EXPORT_H

#include "googlesql/legacy_zetasql/public/evaluator.h"
// include sources
#include "googlesql/legacy_zetasql/public/evaluator.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/evaluator_base/export.inc"
#include "go-googlesql/common/evaluator_registration_utils/export.inc"

#endif
