#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_TEMPLATED_SQL_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_TEMPLATED_SQL_FUNCTION_EXPORT_H

#include "googlesql/legacy_zetasql/public/templated_sql_function.h"
// include sources
#include "googlesql/legacy_zetasql/public/templated_sql_function.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/error_location_cc_proto/export.inc"
#include "go-googlesql/legacy_zetasql/public/function/export.inc"
#include "go-googlesql/legacy_zetasql/public/id_string/export.inc"
#include "go-googlesql/legacy_zetasql/public/parse_location/export.inc"
#include "go-googlesql/legacy_zetasql/public/parse_resume_location/export.inc"
#include "go-googlesql/legacy_zetasql/public/strings/export.inc"
#include "go-googlesql/legacy_zetasql/public/type/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/proto/function_cc_proto/export.inc"
#include "go-googlesql/proto/internal_error_location_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
