#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_GROUPING_SET_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_GROUPING_SET_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/grouping_set_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/grouping_set_rewriter.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
