#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_CYCLE_DETECTOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_CYCLE_DETECTOR_EXPORT_H

#include "googlesql/public/cycle_detector.h"
// include sources
#include "googlesql/public/cycle_detector.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
