#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_DATE_TIME_UTIL_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_DATE_TIME_UTIL_INTERNAL_EXPORT_H

#include "googlesql/public/functions/date_time_util_internal.h"
// include sources
#include "googlesql/public/functions/date_time_util_internal.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-absl/time/time/export.inc"

#endif
