
#ifndef googlesql_public_types_type_factory_bind_cc
#define googlesql_public_types_type_factory_bind_cc

// switch namespace
#define differential_privacy googlesql_public_types_type_factory_differential_privacy
#define googlesql googlesql_public_types_type_factory_googlesql
#define googlesql_base googlesql_public_types_type_factory_googlesql_base
#define googlesql_bison_parser googlesql_public_types_type_factory_googlesql_bison_parser
#define re2 googlesql_public_types_type_factory_re2
#define AbslInternalSleepFor googlesql_public_types_type_factory_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_public_types_type_factory_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_public_types_type_factory_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_public_types_type_factory_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_public_types_type_factory_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_public_types_type_factory_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_public_types_type_factory_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_public_types_type_factory_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_public_types_type_factory_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_public_types_type_factory_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_public_types_type_factory_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_public_types_type_factory_GoogleSqlalloc
#define GoogleSqlfree googlesql_public_types_type_factory_GoogleSqlfree
#define GoogleSqlrealloc googlesql_public_types_type_factory_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_public_types_type_factory_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_public_types_type_factory_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_public_types_type_factory_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_public_types_type_factory_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_public_types_type_factory_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_public_types_type_factory_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_public_types_type_factory_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_public_types_type_factory_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_public_types_type_factory_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_public_types_type_factory_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_public_types_type_factory_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_public_types_type_factory_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_public_types_type_factory_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_public_types_type_factory_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_public_types_type_factory_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_public_types_type_factory_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_public_types_type_factory_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_public_types_type_factory_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_public_types_type_factory_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_public_types_type_factory_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_public_types_type_factory_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_public_types_type_factory_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_public_types_type_factory_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_public_types_type_factory_GoogleSqlFlexLexer
#define UCaseMap googlesql_public_types_type_factory_UCaseMap

#define GO_EXPORT(def) export_googlesql_public_types_type_factory_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/public/types/enum_type.h"
#include "googlesql/public/types/graph_element_type.h"
#include "googlesql/public/types/graph_path_type.h"
#include "googlesql/public/types/internal_proto_utils.h"
#include "googlesql/public/types/proto_type.h"
#include "googlesql/public/types/type_deserializer.h"
#include "googlesql/public/types/type_factory.h"
//#undef private

// include sources
#include "googlesql/public/types/enum_type.cc"
#include "googlesql/public/types/graph_element_type.cc"
#include "googlesql/public/types/graph_path_type.cc"
#include "googlesql/public/types/internal_utils.h"
#include "googlesql/public/types/proto_type.cc"
#include "googlesql/public/types/type_deserializer.cc"
#include "googlesql/public/types/type_factory.cc"

// include dependencies
#include "go-googlesql/public/types/internal_proto_utils/export.inc"
#include "go-googlesql/public/types/type/export.inc"
#include "go-googlesql/public/types/value_representations/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/float_margin/export.inc"
#include "go-googlesql/common/proto_helper/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/public/annotation_cc_proto/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value_cc_proto/export.inc"
#include "go-googlesql/public/value_content/export.inc"
#include "go-googlesql/public/functions/array_find_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/array_zip_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/bitwise_agg_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/convert_proto/export.inc"
#include "go-googlesql/public/functions/datetime_cc_proto/export.inc"
#include "go-googlesql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-googlesql/public/functions/normalize_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/range_sessionize_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/rank_type_cc_proto/export.inc"
#include "go-googlesql/public/functions/rounding_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/container/node_hash_set/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_public_types_type_factory_bind_cc */
