#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PARSE_LOCATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PARSE_LOCATION_EXPORT_H

#include "zetasql/public/parse_location.h"
// include sources
#include "zetasql/public/parse_location.cc"
// include dependencies
#include "go-zetasql/public/parse_location_range_cc_proto/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/mathutil/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/proto/internal_error_location_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-icu/icu/export.inc"

#endif
