#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_RESOLVED_AST_TARGET_SYNTAX_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_RESOLVED_AST_TARGET_SYNTAX_EXPORT_H

#include "googlesql/legacy_zetasql/resolved_ast/target_syntax.h"
// include sources
// include dependencies
#include "go-zetasql/legacy_zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"

#endif
