#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_FLEX_TOKENIZER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_FLEX_TOKENIZER_EXPORT_H

#include "googlesql/legacy_zetasql/parser/flex_tokenizer.h"
// include sources
// flex_tokenizer.cc / flex_tokenizer.flex.cc are amalgamated in parser/bind.cc (parser prelude).
// include dependencies
#include "go-googlesql/parser/flex_istream/export.inc"
#include "go-googlesql/parser/tm_lexer/export.inc"
#include "go-googlesql/parser/token_codes/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
