
#ifndef algorithms_internal_gaussian_stddev_calculator_bind_cc
#define algorithms_internal_gaussian_stddev_calculator_bind_cc

// Link-only bind.cc (no amalgamated .cc includes). Native implementations must come from prebuilt
// archives (e.g. libgooglesql.a) and match this package's exported bridge symbols.
// Enable per package via cclib.link_only_bind_packages in internal/cmd/generator/config.yaml.
// See docs/link-only-cgo-migration.md.
#define differential_privacy algorithms_internal_gaussian_stddev_calculator_differential_privacy
#define googlesql algorithms_internal_gaussian_stddev_calculator_googlesql
#define googlesql_base algorithms_internal_gaussian_stddev_calculator_googlesql_base
#define googlesql_bison_parser algorithms_internal_gaussian_stddev_calculator_googlesql_bison_parser
#define re2 algorithms_internal_gaussian_stddev_calculator_re2
#define AbslInternalSleepFor algorithms_internal_gaussian_stddev_calculator_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_internal_gaussian_stddev_calculator_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_internal_gaussian_stddev_calculator_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_internal_gaussian_stddev_calculator_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_internal_gaussian_stddev_calculator_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_internal_gaussian_stddev_calculator_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_internal_gaussian_stddev_calculator_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_internal_gaussian_stddev_calculator_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_internal_gaussian_stddev_calculator_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_internal_gaussian_stddev_calculator_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_internal_gaussian_stddev_calculator_AbslInternalGetFileMappingHint
#define GoogleSqlalloc algorithms_internal_gaussian_stddev_calculator_GoogleSqlalloc
#define GoogleSqlfree algorithms_internal_gaussian_stddev_calculator_GoogleSqlfree
#define GoogleSqlrealloc algorithms_internal_gaussian_stddev_calculator_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_internal_gaussian_stddev_calculator_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_internal_gaussian_stddev_calculator_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests algorithms_internal_gaussian_stddev_calculator_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests algorithms_internal_gaussian_stddev_calculator_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase algorithms_internal_gaussian_stddev_calculator_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer algorithms_internal_gaussian_stddev_calculator_GoogleSqlFlexLexer
#define UCaseMap algorithms_internal_gaussian_stddev_calculator_UCaseMap

#define GO_EXPORT(def) export_algorithms_internal_gaussian_stddev_calculator_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

#include "_cgo_export.h"

// include headers (types only; no .cc bodies)
#include "algorithms/internal/gaussian-stddev-calculator.h"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_internal_gaussian_stddev_calculator_bind_cc */
