#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_REWRITER_INTERFACE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_REWRITER_INTERFACE_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/rewriter_interface.h"
// include sources
// include dependencies
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
