#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_PATH_EXPRESSION_SPAN_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_PATH_EXPRESSION_SPAN_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/path_expression_span.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/path_expression_span.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/parser/parse_tree/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
