#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_PERCENTILE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_PERCENTILE_EXPORT_H

#include "googlesql/public/functions/percentile.h"
// include sources
#include "googlesql/public/functions/percentile.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/mathutil/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/multiprecision_int/export.inc"
#include "go-googlesql/public/collator/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
