#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_UUID_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_UUID_EXPORT_H

#include "googlesql/reference_impl/functions/uuid.h"
// include sources
#include "googlesql/reference_impl/functions/uuid.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/uuid/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/reference_impl/evaluation/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
