#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_CLOCK_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_CLOCK_EXPORT_H

#include "zetasql/base/clock.h"
// include sources
#include "zetasql/base/clock.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"

#endif
