#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_VALUE_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_VALUE_CC_PROTO_EXPORT_H

#include "googlesql/public/value.pb.h"
// include sources
#define schemas googlesql_public_value_cc_proto_googlesql_public_value_pb_schemas
#define file_default_instances googlesql_public_value_cc_proto_googlesql_public_value_pb_file_default_instances
#include "googlesql/public/value.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies

#endif
