#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_UNICODE_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_UNICODE_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/common/unicode_utils.h"
// include sources
#include "googlesql/legacy_zetasql/common/unicode_utils.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-icu/icu/export.inc"

#endif
