#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_EVALUATOR_TABLE_ITERATOR_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_EVALUATOR_TABLE_ITERATOR_CC_PROTO_EXPORT_H

#include "zetasql/reference_impl/evaluator_table_iterator.pb.h"
// include sources
#include "zetasql/reference_impl/evaluator_table_iterator.pb.cc"
// include dependencies
#include "go-protobuf/protobuf/export.inc"

#endif
