#ifndef INTERNAL_CCALL_GO_ABSL_FUNCTIONAL_BIND_FRONT_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FUNCTIONAL_BIND_FRONT_EXPORT_H

#include "absl/functional/bind_front.h"
// include sources
#include "absl/functional/internal/front_binder.h"
// include dependencies
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/container/compressed_tuple/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
