#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_AGGREGATE_NULL_HANDLING_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_AGGREGATE_NULL_HANDLING_EXPORT_H

#include "googlesql/common/aggregate_null_handling.h"
// include sources
#include "googlesql/common/aggregate_null_handling.cc"
// include dependencies
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"

#endif
