#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_RESOLUTION_SCOPE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_RESOLUTION_SCOPE_EXPORT_H

#include "googlesql/common/resolution_scope.h"
// include sources
#include "googlesql/common/resolution_scope.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/parser/parse_tree/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
