#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_ANALYZER_OUTPUT_MUTATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_ANALYZER_OUTPUT_MUTATOR_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/analyzer_output_mutator.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/analyzer_output_mutator.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/common/timer_util/export.inc"
#include "go-zetasql/public/analyzer_output/export.inc"
#include "go-zetasql/public/analyzer_output_properties/export.inc"
#include "go-zetasql/public/proto/logging_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
