#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_DIFFERENTIAL_PRIVACY_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_DIFFERENTIAL_PRIVACY_CC_PROTO_EXPORT_H

// anon_output must precede differential_privacy.pb.{h,cc} (embedded messages).
#include "go-zetasql/proto/anon_output_with_report_cc_proto/export.inc"
#include "zetasql/public/functions/differential_privacy.pb.h"
// include sources
#include "zetasql/public/functions/differential_privacy.pb.cc"
// include dependencies
#include "go-protobuf/protobuf/export.inc"

#endif
