#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_NAME_SCOPE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_NAME_SCOPE_EXPORT_H

#include "googlesql/analyzer/name_scope.h"
// include sources
#include "googlesql/analyzer/name_scope.cc"
// include dependencies
#include "go-googlesql/analyzer/path_expression_span/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/strings/export.inc"
#include "go-googlesql/common/reflection_cc_proto/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/types/type_with_catalog_impl/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
