#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_MULTI_CATALOG_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_MULTI_CATALOG_EXPORT_H

#include "googlesql/legacy_zetasql/public/multi_catalog.h"
// include sources
#include "googlesql/legacy_zetasql/public/multi_catalog.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/catalog/export.inc"
#include "go-googlesql/legacy_zetasql/public/constant/export.inc"
#include "go-googlesql/legacy_zetasql/public/function/export.inc"
#include "go-googlesql/legacy_zetasql/public/type/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
