#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_TIME_ZONE_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_TIME_ZONE_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/public/time_zone_util.h"
// include sources
#include "googlesql/legacy_zetasql/public/time_zone_util.cc"
// include dependencies
#include "go-zetasql/common/errors/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"

#endif
