#ifndef INTERNAL_CCALL_GO_ZETASQL_PROTO_FUNCTION_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PROTO_FUNCTION_CC_PROTO_EXPORT_H

#include "zetasql/proto/function.pb.h"
// include sources
#include "zetasql/proto/function.pb.cc"
// include dependencies
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value_cc_proto/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/simple_table_cc_proto/export.inc"
#include "go-zetasql/public/simple_value_cc_proto/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/parse_resume_location_cc_proto/export.inc"
#include "go-zetasql/public/annotation_cc_proto/export.inc"
#include "go-zetasql/public/deprecation_warning_cc_proto/export.inc"
#include "go-zetasql/public/error_location_cc_proto/export.inc"
#include "go-zetasql/public/parse_location_range_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/serialization_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
