#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_MACRO_EXPANDER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_MACRO_EXPANDER_EXPORT_H

#include "zetasql/parser/macros/macro_expander.h"
// include sources
#include "zetasql/parser/macros/macro_expander.cc"
// include dependencies
#include "go-zetasql/parser/macros/macro_catalog/export.inc"
#include "go-zetasql/parser/macros/quoting/export.inc"
#include "go-zetasql/parser/macros/standalone_macro_expansion/export.inc"
#include "go-zetasql/parser/macros/token_provider_base/export.inc"
#include "go-zetasql/parser/macros/token_splicing_utils/export.inc"
#include "go-zetasql/parser/macros/token_with_location/export.inc"
#include "go-zetasql/base/arena/export.inc"
#include "go-zetasql/base/arena_allocator/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-zetasql/parser/bison_token_codes/export.inc"
#include "go-zetasql/proto/internal_error_location_cc_proto/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/error_location_cc_proto/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
