
#ifndef googlesql_reference_impl_reference_driver_bind_cc
#define googlesql_reference_impl_reference_driver_bind_cc

// switch namespace
#define differential_privacy googlesql_reference_impl_reference_driver_differential_privacy
#define googlesql googlesql_reference_impl_reference_driver_googlesql
#define googlesql_base googlesql_reference_impl_reference_driver_googlesql_base
#define googlesql_bison_parser googlesql_reference_impl_reference_driver_googlesql_bison_parser
#define re2 googlesql_reference_impl_reference_driver_re2
#define AbslInternalSleepFor googlesql_reference_impl_reference_driver_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_reference_impl_reference_driver_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_reference_impl_reference_driver_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_reference_impl_reference_driver_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_reference_impl_reference_driver_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_reference_impl_reference_driver_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_reference_impl_reference_driver_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_reference_impl_reference_driver_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_reference_impl_reference_driver_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_reference_impl_reference_driver_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_reference_impl_reference_driver_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_reference_impl_reference_driver_GoogleSqlalloc
#define GoogleSqlfree googlesql_reference_impl_reference_driver_GoogleSqlfree
#define GoogleSqlrealloc googlesql_reference_impl_reference_driver_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_reference_impl_reference_driver_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_reference_impl_reference_driver_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_reference_impl_reference_driver_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_reference_impl_reference_driver_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_reference_impl_reference_driver_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_reference_impl_reference_driver_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_reference_impl_reference_driver_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_reference_impl_reference_driver_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_reference_impl_reference_driver_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_reference_impl_reference_driver_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_reference_impl_reference_driver_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_reference_impl_reference_driver_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_reference_impl_reference_driver_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_reference_impl_reference_driver_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_reference_impl_reference_driver_GoogleSqlFlexLexer
#define UCaseMap googlesql_reference_impl_reference_driver_UCaseMap

#define GO_EXPORT(def) export_googlesql_reference_impl_reference_driver_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/reference_impl/reference_driver.h"
//#undef private

// include sources
#include "googlesql/reference_impl/reference_driver.cc"

// include dependencies
#include "go-googlesql/reference_impl/algebrizer/export.inc"
#include "go-googlesql/reference_impl/common/export.inc"
#include "go-googlesql/reference_impl/evaluation/export.inc"
#include "go-googlesql/reference_impl/parameters/export.inc"
#include "go-googlesql/reference_impl/rewrite_flags/export.inc"
#include "go-googlesql/reference_impl/statement_evaluator/export.inc"
#include "go-googlesql/reference_impl/type_helpers/export.inc"
#include "go-googlesql/reference_impl/variable_generator/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/clock/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/evaluator_registration_utils/export.inc"
#include "go-googlesql/common/measure_analysis_utils/export.inc"
#include "go-googlesql/common/status_payload_utils/export.inc"
#include "go-googlesql/compliance/test_database_catalog/export.inc"
#include "go-googlesql/compliance/test_driver/export.inc"
#include "go-googlesql/compliance/test_driver_cc_proto/export.inc"
#include "go-googlesql/proto/script_exception_cc_proto/export.inc"
#include "go-googlesql/public/analyzer/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/evaluator/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/multi_catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/prepared_expression_constant_evaluator/export.inc"
#include "go-googlesql/public/simple_catalog/export.inc"
#include "go-googlesql/public/simple_catalog_util/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/annotation/collation/export.inc"
#include "go-googlesql/public/functions/date_time_util/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-googlesql/scripting/error_helpers/export.inc"
#include "go-googlesql/scripting/script_executor/export.inc"
#include "go-googlesql/scripting/script_segment/export.inc"
#include "go-googlesql/scripting/type_aliases/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_reference_impl_reference_driver_bind_cc */
