#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_JSON_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_JSON_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/common/json_util.h"
// include sources
#include "googlesql/legacy_zetasql/common/json_util.cc"
// include dependencies
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
