#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_TYPE_VISITORS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_TYPE_VISITORS_EXPORT_H

#include "googlesql/common/type_visitors.h"
// include sources
#include "googlesql/common/type_visitors.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
