#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_RESOLVED_AST_COMPARATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_RESOLVED_AST_COMPARATOR_EXPORT_H

#include "googlesql/legacy_zetasql/resolved_ast/resolved_ast_comparator.h"
// include sources
#include "googlesql/legacy_zetasql/resolved_ast/resolved_ast_comparator.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
