#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_EXPORT_H

#include "googlesql/legacy_zetasql/common/match_recognize/nfa.h"
// include sources
#include "googlesql/legacy_zetasql/common/match_recognize/nfa.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/span/export.inc"

#endif
