#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_UTIL_EXPORT_H

#include "googlesql/public/functions/util.h"
// include sources
#include "googlesql/public/functions/util.cc"
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/utf_util/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
