
#ifndef algorithms_distributions_bind_cc
#define algorithms_distributions_bind_cc

// switch namespace
#define differential_privacy algorithms_distributions_differential_privacy
#define googlesql algorithms_distributions_googlesql
#define googlesql_base algorithms_distributions_googlesql_base
#define googlesql_bison_parser algorithms_distributions_googlesql_bison_parser
#define re2 algorithms_distributions_re2
#define AbslInternalSleepFor algorithms_distributions_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_distributions_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_distributions_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_distributions_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_distributions_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_distributions_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_distributions_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_distributions_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_distributions_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_distributions_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_distributions_AbslInternalGetFileMappingHint
#define GoogleSqlalloc algorithms_distributions_GoogleSqlalloc
#define GoogleSqlfree algorithms_distributions_GoogleSqlfree
#define GoogleSqlrealloc algorithms_distributions_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_distributions_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream algorithms_distributions_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_distributions_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream algorithms_distributions_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit algorithms_distributions_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path algorithms_distributions_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width algorithms_distributions_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance algorithms_distributions_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period algorithms_distributions_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit algorithms_distributions_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path algorithms_distributions_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width algorithms_distributions_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance algorithms_distributions_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period algorithms_distributions_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes algorithms_distributions_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes algorithms_distributions_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string algorithms_distributions_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string algorithms_distributions_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability algorithms_distributions_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability algorithms_distributions_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests algorithms_distributions_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests algorithms_distributions_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase algorithms_distributions_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer algorithms_distributions_GoogleSqlFlexLexer
#define UCaseMap algorithms_distributions_UCaseMap

#define GO_EXPORT(def) export_algorithms_distributions_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "algorithms/distributions.h"
//#undef private

// include sources
#include "algorithms/distributions.cc"

// include dependencies
#include "go-algorithms/rand/export.inc"
#include "go-algorithms/util/export.inc"
#include "go-base/logging/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/random/random/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-base/status/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_distributions_bind_cc */
