// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/public/simple_token_list.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto;
namespace zetasql {
class SimpleTokenListProto;
struct SimpleTokenListProtoDefaultTypeInternal;
extern SimpleTokenListProtoDefaultTypeInternal _SimpleTokenListProto_default_instance_;
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
template <>
::zetasql::SimpleTokenListProto* Arena::CreateMaybeMessage<::zetasql::SimpleTokenListProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace zetasql {

// ===================================================================


// -------------------------------------------------------------------

class SimpleTokenListProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zetasql.SimpleTokenListProto) */ {
 public:
  inline SimpleTokenListProto() : SimpleTokenListProto(nullptr) {}
  ~SimpleTokenListProto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SimpleTokenListProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SimpleTokenListProto(const SimpleTokenListProto& from);
  SimpleTokenListProto(SimpleTokenListProto&& from) noexcept
    : SimpleTokenListProto() {
    *this = ::std::move(from);
  }

  inline SimpleTokenListProto& operator=(const SimpleTokenListProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimpleTokenListProto& operator=(SimpleTokenListProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SimpleTokenListProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimpleTokenListProto* internal_default_instance() {
    return reinterpret_cast<const SimpleTokenListProto*>(
               &_SimpleTokenListProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SimpleTokenListProto& a, SimpleTokenListProto& b) {
    a.Swap(&b);
  }
  inline void Swap(SimpleTokenListProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimpleTokenListProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SimpleTokenListProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SimpleTokenListProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SimpleTokenListProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SimpleTokenListProto& from) {
    SimpleTokenListProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimpleTokenListProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "zetasql.SimpleTokenListProto";
  }
  protected:
  explicit SimpleTokenListProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 1,
  };
  // repeated string token = 1;
  int token_size() const;
  private:
  int _internal_token_size() const;

  public:
  void clear_token() ;
  const std::string& token(int index) const;
  std::string* mutable_token(int index);
  void set_token(int index, const std::string& value);
  void set_token(int index, std::string&& value);
  void set_token(int index, const char* value);
  void set_token(int index, const char* value, std::size_t size);
  void set_token(int index, absl::string_view value);
  std::string* add_token();
  void add_token(const std::string& value);
  void add_token(std::string&& value);
  void add_token(const char* value);
  void add_token(const char* value, std::size_t size);
  void add_token(absl::string_view value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& token() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_token();

  private:
  const std::string& _internal_token(int index) const;
  std::string* _internal_add_token();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& _internal_token() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* _internal_mutable_token();

  public:
  // @@protoc_insertion_point(class_scope:zetasql.SimpleTokenListProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> token_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SimpleTokenListProto

// repeated string token = 1;
inline int SimpleTokenListProto::_internal_token_size() const {
  return _impl_.token_.size();
}
inline int SimpleTokenListProto::token_size() const {
  return _internal_token_size();
}
inline void SimpleTokenListProto::clear_token() {
  _internal_mutable_token()->Clear();
}
inline std::string* SimpleTokenListProto::add_token() {
  std::string* _s = _internal_add_token();
  // @@protoc_insertion_point(field_add_mutable:zetasql.SimpleTokenListProto.token)
  return _s;
}
inline const std::string& SimpleTokenListProto::token(int index) const {
  // @@protoc_insertion_point(field_get:zetasql.SimpleTokenListProto.token)
  return _internal_token(index);
}
inline std::string* SimpleTokenListProto::mutable_token(int index) {
  // @@protoc_insertion_point(field_mutable:zetasql.SimpleTokenListProto.token)
  return _internal_mutable_token()->Mutable(index);
}
inline void SimpleTokenListProto::set_token(int index, const std::string& value) {
  _internal_mutable_token()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::set_token(int index, std::string&& value) {
  _internal_mutable_token()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::set_token(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_token()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::set_token(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_token()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::set_token(int index, absl::string_view value) {
  _internal_mutable_token()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::add_token(const std::string& value) {
  _internal_mutable_token()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::add_token(std::string&& value) {
  _internal_mutable_token()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::add_token(const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_token()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::add_token(const char* value, std::size_t size) {
  _internal_mutable_token()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:zetasql.SimpleTokenListProto.token)
}
inline void SimpleTokenListProto::add_token(absl::string_view value) {
  _internal_mutable_token()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:zetasql.SimpleTokenListProto.token)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SimpleTokenListProto::token() const {
  // @@protoc_insertion_point(field_list:zetasql.SimpleTokenListProto.token)
  return _internal_token();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* SimpleTokenListProto::mutable_token() {
  // @@protoc_insertion_point(field_mutable_list:zetasql.SimpleTokenListProto.token)
  return _internal_mutable_token();
}
inline const std::string& SimpleTokenListProto::_internal_token(int index) const {
  return _internal_token().Get(index);
}
inline std::string* SimpleTokenListProto::_internal_add_token() {
  return _internal_mutable_token()->Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SimpleTokenListProto::_internal_token() const {
  return _impl_.token_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SimpleTokenListProto::_internal_mutable_token() {
  return &_impl_.token_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace zetasql


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_zetasql_2fpublic_2fsimple_5ftoken_5flist_2eproto_2epb_2eh
