#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_ANONYMIZATION_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_ANONYMIZATION_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/anonymization_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/anonymization_rewriter.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/analyzer/rewriters/anonymization_helper/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
