#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_DATETIME_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_DATETIME_CC_PROTO_EXPORT_H

#include "googlesql/public/functions/datetime.pb.h"
// include sources
#define schemas googlesql_public_functions_datetime_cc_proto_schemas
#define file_default_instances googlesql_public_functions_datetime_cc_proto_file_default_instances
#include "googlesql/public/functions/datetime.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies

#endif
