
#ifndef googlesql_scripting_script_executor_bind_cc
#define googlesql_scripting_script_executor_bind_cc

// switch namespace
#define differential_privacy googlesql_scripting_script_executor_differential_privacy
#define googlesql googlesql_scripting_script_executor_googlesql
#define googlesql_base googlesql_scripting_script_executor_googlesql_base
#define googlesql_bison_parser googlesql_scripting_script_executor_googlesql_bison_parser
#define re2 googlesql_scripting_script_executor_re2
#define AbslInternalSleepFor googlesql_scripting_script_executor_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_scripting_script_executor_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_scripting_script_executor_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_scripting_script_executor_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_scripting_script_executor_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_scripting_script_executor_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_scripting_script_executor_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_scripting_script_executor_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_scripting_script_executor_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_scripting_script_executor_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_scripting_script_executor_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_scripting_script_executor_GoogleSqlalloc
#define GoogleSqlfree googlesql_scripting_script_executor_GoogleSqlfree
#define GoogleSqlrealloc googlesql_scripting_script_executor_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_scripting_script_executor_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_scripting_script_executor_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_scripting_script_executor_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_scripting_script_executor_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_scripting_script_executor_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_scripting_script_executor_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_scripting_script_executor_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_scripting_script_executor_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_scripting_script_executor_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_scripting_script_executor_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_scripting_script_executor_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_scripting_script_executor_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_scripting_script_executor_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_scripting_script_executor_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_scripting_script_executor_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_scripting_script_executor_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_scripting_script_executor_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_scripting_script_executor_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_scripting_script_executor_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_scripting_script_executor_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_scripting_script_executor_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_scripting_script_executor_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_scripting_script_executor_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_scripting_script_executor_GoogleSqlFlexLexer
#define UCaseMap googlesql_scripting_script_executor_UCaseMap

#define GO_EXPORT(def) export_googlesql_scripting_script_executor_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/scripting/script_executor.h"
//#undef private

// include sources
#include "googlesql/scripting/script_executor.cc"
#include "googlesql/scripting/script_executor_impl.cc"
#include "googlesql/scripting/script_executor_impl.h"
#include "googlesql/scripting/serialization_helpers.cc"
#include "googlesql/scripting/serialization_helpers.h"

// include dependencies
#include "go-zetasql/scripting/control_flow_graph/export.inc"
#include "go-zetasql/scripting/error_helpers/export.inc"
#include "go-zetasql/scripting/parsed_script/export.inc"
#include "go-zetasql/scripting/procedure_extension_cc_proto/export.inc"
#include "go-zetasql/scripting/script_executor_state_cc_proto/export.inc"
#include "go-zetasql/scripting/script_segment/export.inc"
#include "go-zetasql/scripting/stack_frame/export.inc"
#include "go-zetasql/scripting/type_aliases/export.inc"
#include "go-zetasql/scripting/variable_cc_proto/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/flat_set/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/proto/script_exception_cc_proto/export.inc"
#include "go-zetasql/public/analyzer/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/evaluator/export.inc"
#include "go-zetasql/public/evaluator_table_iterator/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/signature_match_result/export.inc"
#include "go-zetasql/public/time_zone_util/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_scripting_script_executor_bind_cc */
