#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_BUILDER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_NFA_BUILDER_EXPORT_H

#include "googlesql/legacy_zetasql/common/match_recognize/nfa_builder.h"
// include sources
#include "googlesql/legacy_zetasql/common/match_recognize/nfa_builder.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/common/match_recognize/epsilon_remover/export.inc"
#include "go-googlesql/legacy_zetasql/common/match_recognize/nfa/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/coercer/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"

#endif
