#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_INPUT_ARGUMENT_TYPE_RESOLVER_HELPER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_INPUT_ARGUMENT_TYPE_RESOLVER_HELPER_EXPORT_H

#include "googlesql/analyzer/input_argument_type_resolver_helper.h"
// include sources
#include "googlesql/analyzer/input_argument_type_resolver_helper.cc"
// include dependencies
#include "go-googlesql/analyzer/constant_resolver_helper/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
