#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_TOKENIZER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_TOKENIZER_EXPORT_H

#include "googlesql/parser/tokenizer.h"
// include sources
#include "googlesql/parser/tokenizer.cc"
// include dependencies
#include "go-zetasql/parser/tm_lexer/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
