#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_RESOLVED_AST_REWRITE_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_RESOLVED_AST_REWRITE_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/resolved_ast/rewrite_utils.h"
// include sources
#include "googlesql/legacy_zetasql/resolved_ast/rewrite_utils.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/legacy_zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/legacy_zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/legacy_zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-googlesql/legacy_zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/analyzer/annotation_propagator/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/coercer/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/annotation/collation/export.inc"
#include "go-googlesql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
