#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_SQL_VIEW_INLINER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_SQL_VIEW_INLINER_EXPORT_H

#include "zetasql/analyzer/rewriters/sql_view_inliner.h"
// include sources
#include "zetasql/analyzer/rewriters/sql_view_inliner.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output_properties/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/sql_view/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
