#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_ARENA_ALLOCATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_ARENA_ALLOCATOR_EXPORT_H

#include "googlesql/legacy_zetasql/base/arena_allocator.h"
// include sources
#include "googlesql/legacy_zetasql/base/arena_allocator.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/base/arena/export.inc"
#include "go-googlesql/legacy_zetasql/base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
