#ifndef INTERNAL_CCALL_GO_ABSL_PROFILING_PERIODIC_SAMPLER_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_PROFILING_PERIODIC_SAMPLER_EXPORT_H

#include "absl/profiling/internal/periodic_sampler.h"
// include sources
#include "absl/profiling/internal/periodic_sampler.cc"
// include dependencies
#include "go-absl/profiling/exponential_biased/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
