
#ifndef absl_crc_crc32c_bind_cc
#define absl_crc_crc32c_bind_cc

// switch namespace
#define differential_privacy absl_crc_crc32c_differential_privacy
#define googlesql absl_crc_crc32c_googlesql
#define googlesql_base absl_crc_crc32c_googlesql_base
#define googlesql_bison_parser absl_crc_crc32c_googlesql_bison_parser
#define re2 absl_crc_crc32c_re2
#define AbslInternalSleepFor absl_crc_crc32c_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_crc_crc32c_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_crc_crc32c_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_crc_crc32c_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_crc_crc32c_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_crc_crc32c_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_crc_crc32c_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_crc_crc32c_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_crc_crc32c_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_crc_crc32c_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_crc_crc32c_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_crc_crc32c_GoogleSqlalloc
#define GoogleSqlfree absl_crc_crc32c_GoogleSqlfree
#define GoogleSqlrealloc absl_crc_crc32c_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_crc_crc32c_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_crc_crc32c_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_crc_crc32c_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_crc_crc32c_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_crc_crc32c_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_crc_crc32c_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_crc_crc32c_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_crc_crc32c_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_crc_crc32c_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_crc_crc32c_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_crc_crc32c_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_crc_crc32c_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_crc_crc32c_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_crc_crc32c_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_crc_crc32c_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_crc_crc32c_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_crc_crc32c_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_crc_crc32c_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_crc_crc32c_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_crc_crc32c_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_crc_crc32c_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_crc_crc32c_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_crc_crc32c_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_crc_crc32c_GoogleSqlFlexLexer
#define UCaseMap absl_crc_crc32c_UCaseMap

#define GO_EXPORT(def) export_absl_crc_crc32c_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/crc/crc32c.h"
#include "absl/crc/internal/crc32c.h"
#include "absl/crc/internal/crc_memcpy.h"
//#undef private

// include sources
#include "absl/crc/internal/crc32c_inline.h"

// include dependencies
#include "go-absl/crc/cpu_detect/export.inc"
#include "go-absl/crc/crc_internal/export.inc"
#include "go-absl/crc/non_temporal_memcpy/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/endian/export.inc"
#include "go-absl/base/prefetch/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_crc_crc32c_bind_cc */
