#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_INPUT_FORMAT_STRING_MAX_WIDTH_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_INPUT_FORMAT_STRING_MAX_WIDTH_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/input_format_string_max_width.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/input_format_string_max_width.cc"
// include dependencies
#include "go-absl/flags/flag/export.inc"

#endif
