// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/public/functions/array_zip_mode.proto

#include "zetasql/public/functions/array_zip_mode.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace zetasql {
namespace functions {
template <typename>
PROTOBUF_CONSTEXPR ArrayZipEnums::ArrayZipEnums(
    ::_pbi::ConstantInitialized) {}
struct ArrayZipEnumsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArrayZipEnumsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArrayZipEnumsDefaultTypeInternal() {}
  union {
    ArrayZipEnums _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArrayZipEnumsDefaultTypeInternal _ArrayZipEnums_default_instance_;
}  // namespace functions
}  // namespace zetasql
static ::_pb::Metadata file_level_metadata_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto = nullptr;
const ::uint32_t TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::zetasql::functions::ArrayZipEnums, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::zetasql::functions::ArrayZipEnums)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::zetasql::functions::_ArrayZipEnums_default_instance_._instance,
};
const char descriptor_table_protodef_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n-zetasql/public/functions/array_zip_mod"
    "e.proto\022\021zetasql.functions\032\031zetasql/publ"
    "ic/type.proto\"\200\001\n\rArrayZipEnums\"o\n\014Array"
    "ZipMode\022$\n\026ARRAY_ZIP_MODE_INVALID\020\000\032\010\262\362\260"
    "\222\016\002\010\001\022\007\n\003PAD\020\001\022\014\n\010TRUNCATE\020\002\022\n\n\006STRICT\020\003"
    "\032\026\262\320\257\372\r\020\n\016ARRAY_ZIP_MODEB3\n\034com.google.z"
    "etasql.functionsB\023ZetaSQLArrayZipMode"
};
static const ::_pbi::DescriptorTable* const descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_deps[1] =
    {
        &::descriptor_table_zetasql_2fpublic_2ftype_2eproto,
};
static ::absl::once_flag descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto = {
    false,
    false,
    277,
    descriptor_table_protodef_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto,
    "zetasql/public/functions/array_zip_mode.proto",
    &descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_once,
    descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto::offsets,
    file_level_metadata_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto,
    file_level_enum_descriptors_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto,
    file_level_service_descriptors_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_getter() {
  return &descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto(&descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto);
namespace zetasql {
namespace functions {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ArrayZipEnums_ArrayZipMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto);
  return file_level_enum_descriptors_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto[0];
}
bool ArrayZipEnums_ArrayZipMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr ArrayZipEnums_ArrayZipMode ArrayZipEnums::ARRAY_ZIP_MODE_INVALID;
constexpr ArrayZipEnums_ArrayZipMode ArrayZipEnums::PAD;
constexpr ArrayZipEnums_ArrayZipMode ArrayZipEnums::TRUNCATE;
constexpr ArrayZipEnums_ArrayZipMode ArrayZipEnums::STRICT;
constexpr ArrayZipEnums_ArrayZipMode ArrayZipEnums::ArrayZipMode_MIN;
constexpr ArrayZipEnums_ArrayZipMode ArrayZipEnums::ArrayZipMode_MAX;
constexpr int ArrayZipEnums::ArrayZipMode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class ArrayZipEnums::_Internal {
 public:
};

ArrayZipEnums::ArrayZipEnums(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:zetasql.functions.ArrayZipEnums)
}
ArrayZipEnums::ArrayZipEnums(const ArrayZipEnums& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ArrayZipEnums* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:zetasql.functions.ArrayZipEnums)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArrayZipEnums::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArrayZipEnums::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ArrayZipEnums::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_getter, &descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto_once,
      file_level_metadata_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zetasql::functions::ArrayZipEnums*
Arena::CreateMaybeMessage< ::zetasql::functions::ArrayZipEnums >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zetasql::functions::ArrayZipEnums >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
