// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/public/functions/rounding_mode.proto

#include "zetasql/public/functions/rounding_mode.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace zetasql {
namespace functions {
}  // namespace functions
}  // namespace zetasql
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto = nullptr;
const uint32_t TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,zetasql/public/functions/rounding_mode"
  ".proto\022\021zetasql.functions\032\031zetasql/publi"
  "c/type.proto*\202\001\n\014RoundingMode\022\'\n\031ROUNDIN"
  "G_MODE_UNSPECIFIED\020\000\032\010\262\362\260\222\016\002\010\001\022\035\n\031ROUND_"
  "HALF_AWAY_FROM_ZERO\020\001\022\023\n\017ROUND_HALF_EVEN"
  "\020\002\032\025\262\320\257\372\r\017\n\rROUNDING_MODEB3\n\034com.google."
  "zetasql.functionsB\023ZetaSQLRoundingMode"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_deps[1] = {
  &::descriptor_table_zetasql_2fpublic_2ftype_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto = {
  false, false, 278, descriptor_table_protodef_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto, "zetasql/public/functions/rounding_mode.proto", 
  &descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_once, descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto::offsets,
  nullptr, file_level_enum_descriptors_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto, file_level_service_descriptors_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto_getter() {
  return &descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto(&descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto);
namespace zetasql {
namespace functions {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RoundingMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto);
  return file_level_enum_descriptors_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto[0];
}
bool RoundingMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace functions
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
