#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_PROTO_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_PROTO_UTIL_EXPORT_H

#include "googlesql/reference_impl/proto_util.h"
// include sources
#include "googlesql/reference_impl/proto_util.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/internal_value/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/arithmetics/export.inc"
#include "go-googlesql/public/functions/date_time_util/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"

#endif
