#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FIX_SUGGESTION_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FIX_SUGGESTION_CC_PROTO_EXPORT_H

#include "googlesql/public/fix_suggestion.pb.h"
// include sources
#define schemas googlesql_public_fix_suggestion_schemas
#define file_default_instances googlesql_public_fix_suggestion_file_default_instances
#include "googlesql/public/fix_suggestion.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies

#endif
