#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_AGGREGATE_NULL_HANDLING_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_AGGREGATE_NULL_HANDLING_EXPORT_H

#include "zetasql/common/aggregate_null_handling.h"
// include sources
#include "zetasql/common/aggregate_null_handling.cc"
// include dependencies
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"

#endif
