#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_CONSTANT_RESOLVER_HELPER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_CONSTANT_RESOLVER_HELPER_EXPORT_H

#include "googlesql/analyzer/constant_resolver_helper.h"
// include sources
#include "googlesql/analyzer/constant_resolver_helper.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/sql_constant/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
