#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_COMMON_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_COMMON_PROTO_EXPORT_H

#include "googlesql/public/functions/common_proto.h"
// include sources
#include "googlesql/public/functions/common_proto.cc"
// include dependencies
#include "go-googlesql/public/functions/date_time_util/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/utf_util/export.inc"
#include "go-googlesql/public/civil_time/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-google/type/latlng_cc_proto/export.inc"
#include "go-google/type/timeofday_cc_proto/export.inc"

#endif
