
#ifndef googlesql_public_types_type_factory_bind_cc
#define googlesql_public_types_type_factory_bind_cc

// switch namespace
#define absl googlesql_public_types_type_factory_absl
#define differential_privacy googlesql_public_types_type_factory_differential_privacy
#define google googlesql_public_types_type_factory_google
#define googlesql googlesql_public_types_type_factory_googlesql
#define googlesql_base googlesql_public_types_type_factory_googlesql_base
#define googlesql_bison_parser googlesql_public_types_type_factory_googlesql_bison_parser
#define re2 googlesql_public_types_type_factory_re2
#define AbslInternalSleepFor googlesql_public_types_type_factory_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_public_types_type_factory_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_public_types_type_factory_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_public_types_type_factory_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_public_types_type_factory_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_public_types_type_factory_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_public_types_type_factory_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_public_types_type_factory_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_public_types_type_factory_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_public_types_type_factory_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_public_types_type_factory_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_public_types_type_factory_GoogleSqlalloc
#define GoogleSqlfree googlesql_public_types_type_factory_GoogleSqlfree
#define GoogleSqlrealloc googlesql_public_types_type_factory_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_public_types_type_factory_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_public_types_type_factory_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_public_types_type_factory_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_public_types_type_factory_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_public_types_type_factory_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_public_types_type_factory_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_public_types_type_factory_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_public_types_type_factory_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_public_types_type_factory_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_public_types_type_factory_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_public_types_type_factory_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_public_types_type_factory_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_public_types_type_factory_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_public_types_type_factory_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_public_types_type_factory_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_public_types_type_factory_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_public_types_type_factory_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_public_types_type_factory_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_public_types_type_factory_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_public_types_type_factory_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_public_types_type_factory_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_public_types_type_factory_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_public_types_type_factory_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_public_types_type_factory_GoogleSqlFlexLexer
#define UCaseMap googlesql_public_types_type_factory_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto googlesql_public_types_type_factory_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto googlesql_public_types_type_factory_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto googlesql_public_types_type_factory_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto googlesql_public_types_type_factory_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto googlesql_public_types_type_factory_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto googlesql_public_types_type_factory_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto googlesql_public_types_type_factory_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto googlesql_public_types_type_factory_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto googlesql_public_types_type_factory_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto googlesql_public_types_type_factory_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto googlesql_public_types_type_factory_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto googlesql_public_types_type_factory_TableStruct_google_2ftype_2ftimeofday_2eproto
#define google_2frpc_2fstatus_2eproto googlesql_public_types_type_factory_google_2frpc_2fstatus_2eproto
#define descriptor_table_google_2frpc_2fstatus_2eproto googlesql_public_types_type_factory_descriptor_table_google_2frpc_2fstatus_2eproto
#define TableStruct_google_2frpc_2fstatus_2eproto googlesql_public_types_type_factory_TableStruct_google_2frpc_2fstatus_2eproto
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define googlesql_2fcommon_2freflection_2eproto googlesql_public_types_type_factory_googlesql_2fcommon_2freflection_2eproto
#define descriptor_table_googlesql_2fcommon_2freflection_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fcommon_2freflection_2eproto
#define TableStruct_googlesql_2fcommon_2freflection_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fcommon_2freflection_2eproto
#define googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto googlesql_public_types_type_factory_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define descriptor_table_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define TableStruct_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define googlesql_2fparser_2fparse_5ftree_2eproto googlesql_public_types_type_factory_googlesql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_googlesql_2fparser_2fparse_5ftree_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_googlesql_2fparser_2fparse_5ftree_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fparser_2fparse_5ftree_2eproto
#define googlesql_2fparser_2fast_5fenums_2eproto googlesql_public_types_type_factory_googlesql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_googlesql_2fparser_2fast_5fenums_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fparser_2fast_5fenums_2eproto
#define TableStruct_googlesql_2fparser_2fast_5fenums_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fparser_2fast_5fenums_2eproto
#define googlesql_2fproto_2foptions_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2foptions_2eproto
#define descriptor_table_googlesql_2fproto_2foptions_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2foptions_2eproto
#define TableStruct_googlesql_2fproto_2foptions_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2foptions_2eproto
#define googlesql_2fproto_2fsimple_5fcatalog_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_googlesql_2fproto_2fsimple_5fcatalog_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_googlesql_2fproto_2fsimple_5fcatalog_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define googlesql_2fproto_2ffunction_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2ffunction_2eproto
#define descriptor_table_googlesql_2fproto_2ffunction_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2ffunction_2eproto
#define TableStruct_googlesql_2fproto_2ffunction_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2ffunction_2eproto
#define googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define googlesql_2fproto_2fmodule_5foptions_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2fmodule_5foptions_2eproto
#define descriptor_table_googlesql_2fproto_2fmodule_5foptions_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2fmodule_5foptions_2eproto
#define TableStruct_googlesql_2fproto_2fmodule_5foptions_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2fmodule_5foptions_2eproto
#define googlesql_2fproto_2finternal_5ferror_5flocation_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define googlesql_2fproto_2fscript_5fexception_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2fscript_5fexception_2eproto
#define descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto
#define TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto
#define googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto googlesql_public_types_type_factory_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define descriptor_table_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define TableStruct_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define googlesql_2fpublic_2fconstness_5flevel_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define descriptor_table_googlesql_2fpublic_2fconstness_5flevel_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define TableStruct_googlesql_2fpublic_2fconstness_5flevel_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define googlesql_2fpublic_2fbuiltin_5ffunction_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define googlesql_2fpublic_2fdeprecation_5fwarning_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define googlesql_2fpublic_2ffunction_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunction_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunction_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunction_2eproto
#define TableStruct_googlesql_2fpublic_2ffunction_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunction_2eproto
#define googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2foptions_2eproto
#define googlesql_2fpublic_2fsimple_5ftable_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define googlesql_2fpublic_2fsimple_5fconstant_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fconstant_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fconstant_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define googlesql_2fpublic_2fsimple_5fconnection_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fconnection_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fconnection_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define googlesql_2fpublic_2fsimple_5fmodel_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fmodel_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fmodel_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define googlesql_2fpublic_2fsimple_5fsequence_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fsequence_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fsequence_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define googlesql_2fpublic_2fparse_5flocation_5frange_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ftype_2eproto
#define googlesql_2fpublic_2ftype_5fannotation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define googlesql_2fpublic_2fvalue_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fvalue_2eproto
#define descriptor_table_googlesql_2fpublic_2fvalue_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fvalue_2eproto
#define TableStruct_googlesql_2fpublic_2fvalue_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fvalue_2eproto
#define googlesql_2fpublic_2ftype_5fparameters_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fparameters_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fparameters_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define googlesql_2fpublic_2fcollation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fcollation_2eproto
#define descriptor_table_googlesql_2fpublic_2fcollation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fcollation_2eproto
#define TableStruct_googlesql_2fpublic_2fcollation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fcollation_2eproto
#define googlesql_2fpublic_2ftype_5fmodifiers_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define googlesql_2fpublic_2fformatter_5foptions_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2fformatter_5foptions_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_googlesql_2fpublic_2fformatter_5foptions_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define googlesql_2fpublic_2ferror_5flocation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto
#define googlesql_2fpublic_2fannotation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fannotation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fannotation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fannotation_2eproto
#define googlesql_2fpublic_2fsimple_5fvalue_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fvalue_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define descriptor_table_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define TableStruct_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define googlesql_2fpublic_2ffix_5fsuggestion_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define descriptor_table_googlesql_2fpublic_2ffix_5fsuggestion_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define TableStruct_googlesql_2fpublic_2ffix_5fsuggestion_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define googlesql_2fpublic_2ffunctions_2fdatetime_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define descriptor_table_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define TableStruct_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define googlesql_2fpublic_2fproto_2flogging_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2flogging_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2flogging_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fproto_2flogging_2eproto
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_types_type_factory_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto googlesql_public_types_type_factory_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto googlesql_public_types_type_factory_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto googlesql_public_types_type_factory_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fast_2eproto googlesql_public_types_type_factory_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define googlesql_2fresolved_5fast_2fserialization_2eproto googlesql_public_types_type_factory_googlesql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fserialization_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fserialization_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fresolved_5fast_2fserialization_2eproto
#define googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto googlesql_public_types_type_factory_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define googlesql_2fscripting_2fprocedure_5fextension_2eproto googlesql_public_types_type_factory_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_googlesql_2fscripting_2fprocedure_5fextension_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_googlesql_2fscripting_2fprocedure_5fextension_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define googlesql_2fscripting_2fvariable_2eproto googlesql_public_types_type_factory_googlesql_2fscripting_2fvariable_2eproto
#define descriptor_table_googlesql_2fscripting_2fvariable_2eproto googlesql_public_types_type_factory_descriptor_table_googlesql_2fscripting_2fvariable_2eproto
#define TableStruct_googlesql_2fscripting_2fvariable_2eproto googlesql_public_types_type_factory_TableStruct_googlesql_2fscripting_2fvariable_2eproto
#define proto_2fconfidence_2dinterval_2eproto googlesql_public_types_type_factory_proto_2fconfidence_2dinterval_2eproto
#define descriptor_table_proto_2fconfidence_2dinterval_2eproto googlesql_public_types_type_factory_descriptor_table_proto_2fconfidence_2dinterval_2eproto
#define TableStruct_proto_2fconfidence_2dinterval_2eproto googlesql_public_types_type_factory_TableStruct_proto_2fconfidence_2dinterval_2eproto
#define proto_2fdata_2eproto googlesql_public_types_type_factory_proto_2fdata_2eproto
#define descriptor_table_proto_2fdata_2eproto googlesql_public_types_type_factory_descriptor_table_proto_2fdata_2eproto
#define TableStruct_proto_2fdata_2eproto googlesql_public_types_type_factory_TableStruct_proto_2fdata_2eproto
#define proto_2fnumerical_2dmechanism_2eproto googlesql_public_types_type_factory_proto_2fnumerical_2dmechanism_2eproto
#define descriptor_table_proto_2fnumerical_2dmechanism_2eproto googlesql_public_types_type_factory_descriptor_table_proto_2fnumerical_2dmechanism_2eproto
#define TableStruct_proto_2fnumerical_2dmechanism_2eproto googlesql_public_types_type_factory_TableStruct_proto_2fnumerical_2dmechanism_2eproto
#define proto_2fsummary_2eproto googlesql_public_types_type_factory_proto_2fsummary_2eproto
#define descriptor_table_proto_2fsummary_2eproto googlesql_public_types_type_factory_descriptor_table_proto_2fsummary_2eproto
#define TableStruct_proto_2fsummary_2eproto googlesql_public_types_type_factory_TableStruct_proto_2fsummary_2eproto

#define GO_EXPORT(def) export_googlesql_public_types_type_factory_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "googlesql/public/types/enum_type.h"
#include "googlesql/public/types/graph_element_type.h"
#include "googlesql/public/types/graph_path_type.h"
#include "googlesql/public/types/internal_proto_utils.h"
#include "googlesql/public/types/proto_type.h"
#include "googlesql/public/types/type_deserializer.h"
#include "googlesql/public/types/type_factory.h"
//#undef private

// include sources
#include "googlesql/public/types/enum_type.cc"
#include "googlesql/public/types/graph_element_type.cc"
#include "googlesql/public/types/graph_path_type.cc"
#include "googlesql/public/types/internal_utils.h"
#include "googlesql/public/types/proto_type.cc"
#include "googlesql/public/types/type_deserializer.cc"
#include "googlesql/public/types/type_factory.cc"

// include dependencies
#include "go-zetasql/public/types/internal_proto_utils/export.inc"
#include "go-zetasql/public/types/type/export.inc"
#include "go-zetasql/public/types/value_representations/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/float_margin/export.inc"
#include "go-zetasql/common/proto_helper/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-zetasql/public/annotation_cc_proto/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type_annotation_cc_proto/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value_cc_proto/export.inc"
#include "go-zetasql/public/value_content/export.inc"
#include "go-zetasql/public/functions/array_find_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/array_zip_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/bitwise_agg_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/convert_proto/export.inc"
#include "go-zetasql/public/functions/datetime_cc_proto/export.inc"
#include "go-zetasql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-zetasql/public/functions/normalize_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/range_sessionize_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/rank_type_cc_proto/export.inc"
#include "go-zetasql/public/functions/rounding_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-zetasql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/container/node_hash_set/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/meta/type_traits/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-protobuf/protobuf/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_public_types_type_factory_bind_cc */
