#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_MACRO_CATALOG_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_MACRO_CATALOG_EXPORT_H

#include "googlesql/legacy_zetasql/parser/macros/macro_catalog.h"
// include sources
#include "googlesql/legacy_zetasql/parser/macros/macro_catalog.cc"
// include dependencies
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
