#ifndef INTERNAL_CCALL_GO_ABSL_LOG_SCOPED_MOCK_LOG_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_SCOPED_MOCK_LOG_EXPORT_H

#include "absl/log/scoped_mock_log.h"
// include sources
#include "absl/log/scoped_mock_log.cc"
// include dependencies
#include "go-absl/log/log_entry/export.inc"
#include "go-absl/log/log_sink/export.inc"
#include "go-absl/log/log_sink_registry/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
