#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_TOKEN_WITH_LOCATION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_TOKEN_WITH_LOCATION_EXPORT_H

#include "googlesql/parser/macros/token_with_location.h"
// include sources
#include "googlesql/parser/macros/token_with_location.cc"
// include dependencies
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
