#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_TYPE_AND_ARGUMENT_KIND_VISITOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_TYPE_AND_ARGUMENT_KIND_VISITOR_EXPORT_H

#include "googlesql/common/type_and_argument_kind_visitor.h"
// include sources
#include "googlesql/common/type_and_argument_kind_visitor.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/types/type/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/span/export.inc"

#endif
