#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_COMMANDLINEFLAG_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_COMMANDLINEFLAG_EXPORT_H

#include "absl/flags/commandlineflag.h"
// include sources
// include dependencies
#include "go-absl/flags/commandlineflag_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/fast_type_id/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
