#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_FLOAT_MARGIN_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_FLOAT_MARGIN_EXPORT_H

#include "googlesql/common/float_margin.h"
// include sources
// include dependencies
#include "go-googlesql/common/string_util/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/mathutil/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
