#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_LENIENT_FORMATTER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_LENIENT_FORMATTER_EXPORT_H

#include "googlesql/public/lenient_formatter.h"
// include sources
#include "googlesql/public/lenient_formatter.cc"
// include dependencies
#include "go-zetasql/public/formatter_options/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/tools/formatter/go_internal/layout/export.inc"
#include "go-zetasql/tools/formatter/go_internal/parsed_file/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
