
#ifndef googlesql_public_coercer_bind_cc
#define googlesql_public_coercer_bind_cc

// switch namespace
#define differential_privacy googlesql_public_coercer_differential_privacy
#define googlesql googlesql_public_coercer_googlesql
#define googlesql_base googlesql_public_coercer_googlesql_base
#define googlesql_bison_parser googlesql_public_coercer_googlesql_bison_parser
#define re2 googlesql_public_coercer_re2
#define AbslInternalSleepFor googlesql_public_coercer_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_public_coercer_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_public_coercer_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_public_coercer_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_public_coercer_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_public_coercer_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_public_coercer_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_public_coercer_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_public_coercer_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_public_coercer_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_public_coercer_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_public_coercer_GoogleSqlalloc
#define GoogleSqlfree googlesql_public_coercer_GoogleSqlfree
#define GoogleSqlrealloc googlesql_public_coercer_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_public_coercer_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_public_coercer_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_public_coercer_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_public_coercer_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_public_coercer_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_public_coercer_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_public_coercer_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_public_coercer_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_public_coercer_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_public_coercer_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_public_coercer_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_public_coercer_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_public_coercer_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_public_coercer_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_public_coercer_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_public_coercer_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_public_coercer_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_public_coercer_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_public_coercer_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_public_coercer_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_public_coercer_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_public_coercer_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_public_coercer_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_public_coercer_GoogleSqlFlexLexer
#define UCaseMap googlesql_public_coercer_UCaseMap

#define GO_EXPORT(def) export_googlesql_public_coercer_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/public/cast.h"
#include "googlesql/public/coercer.h"
//#undef private

// include sources
#include "googlesql/public/cast.cc"
#include "googlesql/public/coercer.cc"

// include dependencies
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/civil_time/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/interval_value/export.inc"
#include "go-googlesql/public/json_value/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/pico_time/export.inc"
#include "go-googlesql/public/proto_value_conversion/export.inc"
#include "go-googlesql/public/signature_match_result/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/timestamp_picos_value/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/uuid_value/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/graph_element_utils/export.inc"
#include "go-googlesql/common/internal_value/export.inc"
#include "go-googlesql/common/utf_util/export.inc"
#include "go-googlesql/public/functions/cast_date_time/export.inc"
#include "go-googlesql/public/functions/convert/export.inc"
#include "go-googlesql/public/functions/convert_proto/export.inc"
#include "go-googlesql/public/functions/convert_string/export.inc"
#include "go-googlesql/public/functions/convert_string_with_format/export.inc"
#include "go-googlesql/public/functions/date_time_util/export.inc"
#include "go-googlesql/public/functions/datetime_cc_proto/export.inc"
#include "go-googlesql/public/functions/range/export.inc"
#include "go-googlesql/public/functions/string/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_public_coercer_bind_cc */
