#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_TEMPLATED_SQL_TVF_NO_RESOLVER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_TEMPLATED_SQL_TVF_NO_RESOLVER_EXPORT_H

#include "zetasql/public/templated_sql_tvf.h"
// include sources
// include dependencies
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_resume_location/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"

#endif
