#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_REFLECTION_HELPER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_REFLECTION_HELPER_EXPORT_H

#include "googlesql/common/reflection_helper.h"
// include sources
#include "googlesql/common/reflection_helper.cc"
// include dependencies
#include "go-googlesql/common/reflection_cc_proto/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/span/export.inc"

#endif
