#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_STATEMENT_EVALUATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_STATEMENT_EVALUATOR_EXPORT_H

#include "zetasql/reference_impl/statement_evaluator.h"
// include sources
#include "zetasql/reference_impl/statement_evaluator.cc"
// include dependencies
#include "go-zetasql/reference_impl/evaluator_table_iterator_cc_proto/export.inc"
#include "go-zetasql/reference_impl/type_helpers/export.inc"
#include "go-zetasql/reference_impl/type_parameter_constraints/export.inc"
#include "go-zetasql/analyzer/resolver/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/analyzer/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/evaluator/export.inc"
#include "go-zetasql/public/evaluator_table_iterator/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/multi_catalog/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/parse_resume_location/export.inc"
#include "go-zetasql/public/simple_catalog/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-zetasql/scripting/error_helpers/export.inc"
#include "go-zetasql/scripting/parsed_script/export.inc"
#include "go-zetasql/scripting/script_exception_cc_proto/export.inc"
#include "go-zetasql/scripting/script_executor/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
