#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TOKEN_WITH_LOCATION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TOKEN_WITH_LOCATION_EXPORT_H

#include "googlesql/parser/token_with_location.h"
// include sources
#include "googlesql/parser/token_with_location.cc"
// include dependencies
#include "go-googlesql/parser/token/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/error_location_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
