#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_CIVIL_TIME_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_CIVIL_TIME_EXPORT_H

#include "zetasql/public/civil_time.h"
// include sources
#include "zetasql/public/civil_time.cc"
// include dependencies
#include "go-zetasql/base/mathutil/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/compare/export.inc"

#endif
