#ifndef INTERNAL_CCALL_GO_GOOGLESQL_RESOLVED_AST_RESOLVED_AST_REWRITE_VISITOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_RESOLVED_AST_RESOLVED_AST_REWRITE_VISITOR_EXPORT_H

#include "googlesql/resolved_ast/resolved_ast_rewrite_visitor.h"
// include sources
#include "googlesql/resolved_ast/resolved_ast_rewrite_visitor_1.cc"
#include "googlesql/resolved_ast/resolved_ast_rewrite_visitor_2.cc"
#include "googlesql/resolved_ast/resolved_ast_rewrite_visitor_3.cc"
#include "googlesql/resolved_ast/resolved_ast_rewrite_visitor_4.cc"
// include dependencies
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
