#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_PARSE_TREE_SERIALIZER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_PARSE_TREE_SERIALIZER_EXPORT_H

#include "zetasql/parser/parse_tree_serializer.h"
#include "zetasql/parser/parser.h"
#include "zetasql/parser/statement_properties.h"
// include sources
#include "zetasql/parser/parse_tree_serializer.cc"
// include dependencies
#include "go-zetasql/parser/bison_parser_generated_lib/export.inc"
#include "go-zetasql/parser/parse_tree/export.inc"
#include "go-zetasql/parser/parse_tree_cc_proto/export.inc"
#include "go-zetasql/base/arena/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/parser/macros/macro_catalog/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/proto/logging_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/variant/export.inc"

#endif
