#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_ANALYZER_IMPL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_ANALYZER_IMPL_EXPORT_H

#include "zetasql/analyzer/analyzer_impl.h"
// include sources
#include "zetasql/analyzer/analyzer_impl.cc"
// include dependencies
#include "go-zetasql/analyzer/analyzer_output_mutator/export.inc"
#include "go-zetasql/analyzer/resolver/export.inc"
#include "go-zetasql/analyzer/rewrite_resolved_ast/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/internal_analyzer_options/export.inc"
#include "go-zetasql/common/timer_util/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/validator/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
