
#ifndef algorithms_quantiles_bind_cc
#define algorithms_quantiles_bind_cc

// switch namespace
#define differential_privacy algorithms_quantiles_differential_privacy
#define googlesql algorithms_quantiles_googlesql
#define googlesql_base algorithms_quantiles_googlesql_base
#define googlesql_bison_parser algorithms_quantiles_googlesql_bison_parser
#define re2 algorithms_quantiles_re2
#define AbslInternalSleepFor algorithms_quantiles_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError algorithms_quantiles_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield algorithms_quantiles_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost algorithms_quantiles_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait algorithms_quantiles_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything algorithms_quantiles_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay algorithms_quantiles_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake algorithms_quantiles_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin algorithms_quantiles_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd algorithms_quantiles_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint algorithms_quantiles_AbslInternalGetFileMappingHint
#define GoogleSqlalloc algorithms_quantiles_GoogleSqlalloc
#define GoogleSqlfree algorithms_quantiles_GoogleSqlfree
#define GoogleSqlrealloc algorithms_quantiles_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly algorithms_quantiles_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream algorithms_quantiles_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly algorithms_quantiles_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream algorithms_quantiles_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit algorithms_quantiles_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path algorithms_quantiles_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width algorithms_quantiles_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance algorithms_quantiles_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period algorithms_quantiles_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit algorithms_quantiles_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path algorithms_quantiles_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width algorithms_quantiles_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance algorithms_quantiles_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period algorithms_quantiles_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes algorithms_quantiles_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes algorithms_quantiles_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string algorithms_quantiles_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string algorithms_quantiles_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability algorithms_quantiles_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability algorithms_quantiles_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests algorithms_quantiles_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests algorithms_quantiles_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase algorithms_quantiles_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer algorithms_quantiles_GoogleSqlFlexLexer
#define UCaseMap algorithms_quantiles_UCaseMap

#define GO_EXPORT(def) export_algorithms_quantiles_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "algorithms/quantiles.h"
//#undef private

// include sources

// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/bounded-algorithm/export.inc"
#include "go-algorithms/quantile-tree/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* algorithms_quantiles_bind_cc */
