#ifndef INTERNAL_CCALL_GO_ALGORITHMS_QUANTILES_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_QUANTILES_EXPORT_H

#include "algorithms/quantiles.h"
// include sources
// include dependencies
#include "go-algorithms/algorithm/export.inc"
#include "go-algorithms/bounded-algorithm/export.inc"
#include "go-algorithms/quantile-tree/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
