
#ifndef googlesql_common_builtin_function_internal_bind_cc
#define googlesql_common_builtin_function_internal_bind_cc

// switch namespace
#define differential_privacy googlesql_common_builtin_function_internal_differential_privacy
#define googlesql googlesql_common_builtin_function_internal_googlesql
#define googlesql_base googlesql_common_builtin_function_internal_googlesql_base
#define googlesql_bison_parser googlesql_common_builtin_function_internal_googlesql_bison_parser
#define re2 googlesql_common_builtin_function_internal_re2
#define AbslInternalSleepFor googlesql_common_builtin_function_internal_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_common_builtin_function_internal_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_common_builtin_function_internal_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_common_builtin_function_internal_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_common_builtin_function_internal_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_common_builtin_function_internal_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_common_builtin_function_internal_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_common_builtin_function_internal_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_common_builtin_function_internal_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_common_builtin_function_internal_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_common_builtin_function_internal_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_common_builtin_function_internal_GoogleSqlalloc
#define GoogleSqlfree googlesql_common_builtin_function_internal_GoogleSqlfree
#define GoogleSqlrealloc googlesql_common_builtin_function_internal_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_common_builtin_function_internal_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_common_builtin_function_internal_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_common_builtin_function_internal_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_common_builtin_function_internal_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_common_builtin_function_internal_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_common_builtin_function_internal_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_common_builtin_function_internal_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_common_builtin_function_internal_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_common_builtin_function_internal_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_common_builtin_function_internal_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_common_builtin_function_internal_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_common_builtin_function_internal_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_common_builtin_function_internal_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_common_builtin_function_internal_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_common_builtin_function_internal_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_common_builtin_function_internal_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_common_builtin_function_internal_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_common_builtin_function_internal_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_common_builtin_function_internal_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_common_builtin_function_internal_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_common_builtin_function_internal_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_common_builtin_function_internal_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_common_builtin_function_internal_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_common_builtin_function_internal_GoogleSqlFlexLexer
#define UCaseMap googlesql_common_builtin_function_internal_UCaseMap

#define GO_EXPORT(def) export_googlesql_common_builtin_function_internal_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/common/builtin_function_internal.h"
//#undef private

// include sources
#include "googlesql/common/builtin_enum_type.cc"
#include "googlesql/common/builtin_function_array.cc"
#include "googlesql/common/builtin_function_comparison.cc"
#include "googlesql/common/builtin_function_differential_privacy.cc"
#include "googlesql/common/builtin_function_distance.cc"
#include "googlesql/common/builtin_function_graph.cc"
#include "googlesql/common/builtin_function_internal_1.cc"
#include "googlesql/common/builtin_function_internal_2.cc"
#include "googlesql/common/builtin_function_internal_3.cc"
#include "googlesql/common/builtin_function_map.cc"
#include "googlesql/common/builtin_function_match_recognize.cc"
#include "googlesql/common/builtin_function_measure.cc"
#include "googlesql/common/builtin_function_range.cc"
#include "googlesql/common/builtin_function_sketches.cc"
#include "googlesql/common/builtin_function_time_series.cc"
#include "googlesql/common/builtin_tvfs.cc"

// include dependencies
#include "go-googlesql/common/builtins_output_properties/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/no_destructor/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/proto/anon_output_with_report_cc_proto/export.inc"
#include "go-googlesql/proto/options_cc_proto/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/anon_function/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/builtin_function_options/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/coercer/export.inc"
#include "go-googlesql/public/cycle_detector/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/annotation/collation/export.inc"
#include "go-googlesql/public/functions/array_zip_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/bitwise_agg_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/date_time_util/export.inc"
#include "go-googlesql/public/functions/datetime_cc_proto/export.inc"
#include "go-googlesql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-googlesql/public/functions/rank_type_cc_proto/export.inc"
#include "go-googlesql/public/functions/regexp/export.inc"
#include "go-googlesql/public/functions/string_format/export.inc"
#include "go-googlesql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/functional/bind_front/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-google/type/date_cc_proto/export.inc"
#include "go-google/type/timeofday_cc_proto/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_common_builtin_function_internal_bind_cc */
