#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_DATE_TIME_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_DATE_TIME_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/date_time_util.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/date_time_util.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/functions/arithmetics/export.inc"
#include "go-googlesql/legacy_zetasql/public/functions/date_time_util_internal/export.inc"
#include "go-googlesql/legacy_zetasql/public/functions/datetime_cc_proto/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/mathutil/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/time_proto_util/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/civil_time/export.inc"
#include "go-googlesql/public/interval_value/export.inc"
#include "go-googlesql/public/pico_time/export.inc"
#include "go-googlesql/public/time_zone_util/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/types/timestamp_util/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-google/type/date_cc_proto/export.inc"

#endif
