#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_BUILTIN_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_BUILTIN_FUNCTION_EXPORT_H

#include "googlesql/legacy_zetasql/public/builtin_function.h"
// include sources
#include "googlesql/legacy_zetasql/public/builtin_function.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/legacy_zetasql/public/builtin_function_options/export.inc"
#include "go-googlesql/legacy_zetasql/public/function/export.inc"
#include "go-googlesql/legacy_zetasql/public/language_options/export.inc"
#include "go-googlesql/legacy_zetasql/public/options_cc_proto/export.inc"
#include "go-googlesql/legacy_zetasql/public/type/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/builtin_function_internal/export.inc"
#include "go-googlesql/common/builtins_output_properties/export.inc"
#include "go-googlesql/proto/options_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/public/types/type/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
