#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_COMPRESSION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_COMPRESSION_EXPORT_H

#include "googlesql/public/functions/compression.h"
// include sources
#include "googlesql/public/functions/compression.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/utf_util/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
