#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_FLAG_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_FLAG_EXPORT_H

#include "absl/flags/declare.h"
#include "absl/flags/flag.h"
// include sources
// include dependencies
#include "go-absl/flags/commandlineflag/export.inc"
#include "go-absl/flags/config/export.inc"
#include "go-absl/flags/flag_internal/export.inc"
#include "go-absl/flags/reflection/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
