#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_STACKTRACE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_STACKTRACE_EXPORT_H

#include "absl/debugging/stacktrace.h"
// include sources
#include "absl/debugging/internal/stacktrace_config.h"
// include dependencies
#include "go-absl/debugging/debugging_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/dynamic_annotations/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#endif
