#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_GENERAL_TRIE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_GENERAL_TRIE_EXPORT_H

#include "googlesql/legacy_zetasql/base/general_trie.h"
// include sources
// include dependencies
#include "go-googlesql/legacy_zetasql/base/base/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
