
#ifndef absl_base_core_headers_bind_cc
#define absl_base_core_headers_bind_cc

// switch namespace
#define absl absl_base_core_headers_absl
#define differential_privacy absl_base_core_headers_differential_privacy
#define google absl_base_core_headers_google
#define googlesql absl_base_core_headers_googlesql
#define googlesql_base absl_base_core_headers_googlesql_base
#define googlesql_bison_parser absl_base_core_headers_googlesql_bison_parser
#define re2 absl_base_core_headers_re2
#define AbslInternalSleepFor absl_base_core_headers_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_base_core_headers_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_base_core_headers_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_base_core_headers_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_base_core_headers_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_base_core_headers_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_base_core_headers_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_base_core_headers_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_base_core_headers_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_base_core_headers_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_base_core_headers_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_base_core_headers_GoogleSqlalloc
#define GoogleSqlfree absl_base_core_headers_GoogleSqlfree
#define GoogleSqlrealloc absl_base_core_headers_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_base_core_headers_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_base_core_headers_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_base_core_headers_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_base_core_headers_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_base_core_headers_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_base_core_headers_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_base_core_headers_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_base_core_headers_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_base_core_headers_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_base_core_headers_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_base_core_headers_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_base_core_headers_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_base_core_headers_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_base_core_headers_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_base_core_headers_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_base_core_headers_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_base_core_headers_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_base_core_headers_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_base_core_headers_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_base_core_headers_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_base_core_headers_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_base_core_headers_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_base_core_headers_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_base_core_headers_GoogleSqlFlexLexer
#define UCaseMap absl_base_core_headers_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto absl_base_core_headers_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto absl_base_core_headers_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto absl_base_core_headers_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto absl_base_core_headers_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto absl_base_core_headers_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto absl_base_core_headers_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto absl_base_core_headers_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto absl_base_core_headers_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto absl_base_core_headers_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto absl_base_core_headers_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto absl_base_core_headers_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto absl_base_core_headers_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto absl_base_core_headers_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto absl_base_core_headers_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto absl_base_core_headers_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto absl_base_core_headers_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto absl_base_core_headers_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto absl_base_core_headers_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto absl_base_core_headers_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto absl_base_core_headers_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto absl_base_core_headers_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto absl_base_core_headers_TableStruct_google_2ftype_2ftimeofday_2eproto
#define google_2frpc_2fstatus_2eproto absl_base_core_headers_google_2frpc_2fstatus_2eproto
#define descriptor_table_google_2frpc_2fstatus_2eproto absl_base_core_headers_descriptor_table_google_2frpc_2fstatus_2eproto
#define TableStruct_google_2frpc_2fstatus_2eproto absl_base_core_headers_TableStruct_google_2frpc_2fstatus_2eproto
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto absl_base_core_headers_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define googlesql_2fcommon_2freflection_2eproto absl_base_core_headers_googlesql_2fcommon_2freflection_2eproto
#define descriptor_table_googlesql_2fcommon_2freflection_2eproto absl_base_core_headers_descriptor_table_googlesql_2fcommon_2freflection_2eproto
#define TableStruct_googlesql_2fcommon_2freflection_2eproto absl_base_core_headers_TableStruct_googlesql_2fcommon_2freflection_2eproto
#define googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto absl_base_core_headers_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define descriptor_table_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto absl_base_core_headers_descriptor_table_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define TableStruct_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto absl_base_core_headers_TableStruct_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define googlesql_2fparser_2fparse_5ftree_2eproto absl_base_core_headers_googlesql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_googlesql_2fparser_2fparse_5ftree_2eproto absl_base_core_headers_descriptor_table_googlesql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_googlesql_2fparser_2fparse_5ftree_2eproto absl_base_core_headers_TableStruct_googlesql_2fparser_2fparse_5ftree_2eproto
#define googlesql_2fparser_2fast_5fenums_2eproto absl_base_core_headers_googlesql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_googlesql_2fparser_2fast_5fenums_2eproto absl_base_core_headers_descriptor_table_googlesql_2fparser_2fast_5fenums_2eproto
#define TableStruct_googlesql_2fparser_2fast_5fenums_2eproto absl_base_core_headers_TableStruct_googlesql_2fparser_2fast_5fenums_2eproto
#define googlesql_2fproto_2foptions_2eproto absl_base_core_headers_googlesql_2fproto_2foptions_2eproto
#define descriptor_table_googlesql_2fproto_2foptions_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2foptions_2eproto
#define TableStruct_googlesql_2fproto_2foptions_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2foptions_2eproto
#define googlesql_2fproto_2fsimple_5fcatalog_2eproto absl_base_core_headers_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_googlesql_2fproto_2fsimple_5fcatalog_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_googlesql_2fproto_2fsimple_5fcatalog_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define googlesql_2fproto_2ffunction_2eproto absl_base_core_headers_googlesql_2fproto_2ffunction_2eproto
#define descriptor_table_googlesql_2fproto_2ffunction_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2ffunction_2eproto
#define TableStruct_googlesql_2fproto_2ffunction_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2ffunction_2eproto
#define googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto absl_base_core_headers_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define googlesql_2fproto_2fmodule_5foptions_2eproto absl_base_core_headers_googlesql_2fproto_2fmodule_5foptions_2eproto
#define descriptor_table_googlesql_2fproto_2fmodule_5foptions_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2fmodule_5foptions_2eproto
#define TableStruct_googlesql_2fproto_2fmodule_5foptions_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2fmodule_5foptions_2eproto
#define googlesql_2fproto_2finternal_5ferror_5flocation_2eproto absl_base_core_headers_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto absl_base_core_headers_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto absl_base_core_headers_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define googlesql_2fproto_2fscript_5fexception_2eproto absl_base_core_headers_googlesql_2fproto_2fscript_5fexception_2eproto
#define descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto
#define TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto
#define googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto absl_base_core_headers_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define descriptor_table_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto absl_base_core_headers_descriptor_table_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define TableStruct_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto absl_base_core_headers_TableStruct_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define googlesql_2fpublic_2fconstness_5flevel_2eproto absl_base_core_headers_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define descriptor_table_googlesql_2fpublic_2fconstness_5flevel_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define TableStruct_googlesql_2fpublic_2fconstness_5flevel_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define googlesql_2fpublic_2fbuiltin_5ffunction_2eproto absl_base_core_headers_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define googlesql_2fpublic_2fdeprecation_5fwarning_2eproto absl_base_core_headers_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define googlesql_2fpublic_2ffunction_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunction_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunction_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunction_2eproto
#define TableStruct_googlesql_2fpublic_2ffunction_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunction_2eproto
#define googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto absl_base_core_headers_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define googlesql_2fpublic_2foptions_2eproto absl_base_core_headers_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2foptions_2eproto
#define googlesql_2fpublic_2fsimple_5ftable_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define googlesql_2fpublic_2fsimple_5fconstant_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fconstant_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fconstant_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define googlesql_2fpublic_2fsimple_5fconnection_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fconnection_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fconnection_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define googlesql_2fpublic_2fsimple_5fmodel_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fmodel_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fmodel_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define googlesql_2fpublic_2fsimple_5fsequence_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fsequence_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fsequence_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define googlesql_2fpublic_2fparse_5flocation_5frange_2eproto absl_base_core_headers_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define googlesql_2fpublic_2ftype_2eproto absl_base_core_headers_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ftype_2eproto
#define googlesql_2fpublic_2ftype_5fannotation_2eproto absl_base_core_headers_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define googlesql_2fpublic_2fvalue_2eproto absl_base_core_headers_googlesql_2fpublic_2fvalue_2eproto
#define descriptor_table_googlesql_2fpublic_2fvalue_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fvalue_2eproto
#define TableStruct_googlesql_2fpublic_2fvalue_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fvalue_2eproto
#define googlesql_2fpublic_2ftype_5fparameters_2eproto absl_base_core_headers_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fparameters_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fparameters_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define googlesql_2fpublic_2fcollation_2eproto absl_base_core_headers_googlesql_2fpublic_2fcollation_2eproto
#define descriptor_table_googlesql_2fpublic_2fcollation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fcollation_2eproto
#define TableStruct_googlesql_2fpublic_2fcollation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fcollation_2eproto
#define googlesql_2fpublic_2ftype_5fmodifiers_2eproto absl_base_core_headers_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define googlesql_2fpublic_2fformatter_5foptions_2eproto absl_base_core_headers_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2fformatter_5foptions_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_googlesql_2fpublic_2fformatter_5foptions_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define googlesql_2fpublic_2ferror_5flocation_2eproto absl_base_core_headers_googlesql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto
#define googlesql_2fpublic_2fannotation_2eproto absl_base_core_headers_googlesql_2fpublic_2fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fannotation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fannotation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fannotation_2eproto
#define googlesql_2fpublic_2fsimple_5fvalue_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fvalue_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto absl_base_core_headers_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define descriptor_table_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define TableStruct_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto absl_base_core_headers_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define googlesql_2fpublic_2ffix_5fsuggestion_2eproto absl_base_core_headers_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define descriptor_table_googlesql_2fpublic_2ffix_5fsuggestion_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define TableStruct_googlesql_2fpublic_2ffix_5fsuggestion_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define googlesql_2fpublic_2ffunctions_2fdatetime_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto absl_base_core_headers_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto absl_base_core_headers_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define descriptor_table_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define TableStruct_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define googlesql_2fpublic_2fproto_2flogging_2eproto absl_base_core_headers_googlesql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2flogging_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2flogging_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fproto_2flogging_2eproto
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto absl_base_core_headers_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto absl_base_core_headers_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto absl_base_core_headers_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto absl_base_core_headers_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto absl_base_core_headers_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto absl_base_core_headers_descriptor_table_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto absl_base_core_headers_TableStruct_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto absl_base_core_headers_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto absl_base_core_headers_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto absl_base_core_headers_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto absl_base_core_headers_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto absl_base_core_headers_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto absl_base_core_headers_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fast_2eproto absl_base_core_headers_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto absl_base_core_headers_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto absl_base_core_headers_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define googlesql_2fresolved_5fast_2fserialization_2eproto absl_base_core_headers_googlesql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fserialization_2eproto absl_base_core_headers_descriptor_table_googlesql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fserialization_2eproto absl_base_core_headers_TableStruct_googlesql_2fresolved_5fast_2fserialization_2eproto
#define googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto absl_base_core_headers_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto absl_base_core_headers_descriptor_table_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto absl_base_core_headers_TableStruct_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define googlesql_2fscripting_2fprocedure_5fextension_2eproto absl_base_core_headers_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_googlesql_2fscripting_2fprocedure_5fextension_2eproto absl_base_core_headers_descriptor_table_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_googlesql_2fscripting_2fprocedure_5fextension_2eproto absl_base_core_headers_TableStruct_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define googlesql_2fscripting_2fvariable_2eproto absl_base_core_headers_googlesql_2fscripting_2fvariable_2eproto
#define descriptor_table_googlesql_2fscripting_2fvariable_2eproto absl_base_core_headers_descriptor_table_googlesql_2fscripting_2fvariable_2eproto
#define TableStruct_googlesql_2fscripting_2fvariable_2eproto absl_base_core_headers_TableStruct_googlesql_2fscripting_2fvariable_2eproto
#define proto_2fconfidence_2dinterval_2eproto absl_base_core_headers_proto_2fconfidence_2dinterval_2eproto
#define descriptor_table_proto_2fconfidence_2dinterval_2eproto absl_base_core_headers_descriptor_table_proto_2fconfidence_2dinterval_2eproto
#define TableStruct_proto_2fconfidence_2dinterval_2eproto absl_base_core_headers_TableStruct_proto_2fconfidence_2dinterval_2eproto
#define proto_2fdata_2eproto absl_base_core_headers_proto_2fdata_2eproto
#define descriptor_table_proto_2fdata_2eproto absl_base_core_headers_descriptor_table_proto_2fdata_2eproto
#define TableStruct_proto_2fdata_2eproto absl_base_core_headers_TableStruct_proto_2fdata_2eproto
#define proto_2fnumerical_2dmechanism_2eproto absl_base_core_headers_proto_2fnumerical_2dmechanism_2eproto
#define descriptor_table_proto_2fnumerical_2dmechanism_2eproto absl_base_core_headers_descriptor_table_proto_2fnumerical_2dmechanism_2eproto
#define TableStruct_proto_2fnumerical_2dmechanism_2eproto absl_base_core_headers_TableStruct_proto_2fnumerical_2dmechanism_2eproto
#define proto_2fsummary_2eproto absl_base_core_headers_proto_2fsummary_2eproto
#define descriptor_table_proto_2fsummary_2eproto absl_base_core_headers_descriptor_table_proto_2fsummary_2eproto
#define TableStruct_proto_2fsummary_2eproto absl_base_core_headers_TableStruct_proto_2fsummary_2eproto

#define GO_EXPORT(def) export_absl_base_core_headers_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "absl/base/attributes.h"
#include "absl/base/const_init.h"
#include "absl/base/macros.h"
#include "absl/base/optimization.h"
#include "absl/base/port.h"
#include "absl/base/thread_annotations.h"
//#undef private

// include sources
#include "absl/base/internal/thread_annotations.h"

// include dependencies
#include "go-absl/base/config/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_base_core_headers_bind_cc */
