#ifndef INTERNAL_CCALL_GO_ABSL_BASE_CORE_HEADERS_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_BASE_CORE_HEADERS_EXPORT_H

#include "absl/base/attributes.h"
#include "absl/base/const_init.h"
#include "absl/base/macros.h"
#include "absl/base/optimization.h"
#include "absl/base/port.h"
#include "absl/base/thread_annotations.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"

#endif
