#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_RET_CHECK_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_RET_CHECK_EXPORT_H

#include "googlesql/legacy_zetasql/base/ret_check.h"
// include sources
#include "googlesql/legacy_zetasql/base/ret_check.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/base/logging/export.inc"
#include "go-zetasql/legacy_zetasql/base/source_location/export.inc"
#include "go-zetasql/legacy_zetasql/base/status/export.inc"
#include "go-absl/status/status/export.inc"

#endif
