#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_RESOLVED_AST_RESOLVED_AST_BUILDER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_RESOLVED_AST_RESOLVED_AST_BUILDER_EXPORT_H

#include "googlesql/legacy_zetasql/resolved_ast/resolved_ast_builder.h"
// include sources
// include dependencies
#include "go-zetasql/legacy_zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
