#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_EXACTFLOAT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_EXACTFLOAT_EXPORT_H

#include "zetasql/base/exactfloat.h"
// include sources
#include "zetasql/base/exactfloat.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-boringssl/boringssl/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/fixed_array/export.inc"

#endif
