#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_EXACTFLOAT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_EXACTFLOAT_EXPORT_H

#include "googlesql/base/exactfloat.h"
// include sources
#include "googlesql/base/exactfloat.cc"
// include dependencies
#include "go-boringssl/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/fixed_array/export.inc"
#include "go-absl/log/absl_check/export.inc"
#include "go-absl/log/absl_log/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
