#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_RANGE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_FUNCTIONS_RANGE_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/functions/range.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/functions/range.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/civil_time/export.inc"
#include "go-googlesql/public/interval_value/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/range/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/reference_impl/evaluation/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
