#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_BUILTIN_ONLY_CATALOG_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_BUILTIN_ONLY_CATALOG_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/builtin_only_catalog.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/builtin_only_catalog.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function_headers/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
