#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_ARRAY_FIND_MODE_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_ARRAY_FIND_MODE_CC_PROTO_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/array_find_mode.pb.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/array_find_mode.pb.cc"
// include dependencies

#endif
