#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SIMPLE_CATALOG_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SIMPLE_CATALOG_UTIL_EXPORT_H

#include "zetasql/public/simple_catalog_util.h"
// include sources
#include "zetasql/public/simple_catalog_util.cc"
// include dependencies
#include "go-zetasql/public/analyzer/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output/export.inc"
#include "go-zetasql/public/simple_catalog/export.inc"
#include "go-zetasql/public/sql_function/export.inc"
#include "go-zetasql/public/templated_sql_function/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"

#endif
