#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_TYPE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_TYPE_EXPORT_H

#include "googlesql/public/convert_type_to_proto.h"
#include "googlesql/public/type.h"
// include sources
#include "googlesql/public/convert_type_to_proto.cc"
// include dependencies
#include "go-googlesql/public/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value_cc_proto/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
