#ifndef ZETASQL_PUBLIC_ERROR_LOCATION_CC_PROTO_EXPORT_H
#define ZETASQL_PUBLIC_ERROR_LOCATION_CC_PROTO_EXPORT_H

#include "zetasql/public/error_location.pb.h"
#define schemas go_zetasql_public_error_location_cc_proto_error_location_schemas
#define file_default_instances go_zetasql_public_error_location_cc_proto_error_location_file_default_instances
#include "zetasql/public/error_location.pb.cc"
#undef file_default_instances
#undef schemas

#include "go-protobuf/protobuf/export.inc"

#endif
