#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_PIVOT_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_PIVOT_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/pivot_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/pivot_rewriter.cc"
// include dependencies
#include "go-googlesql/analyzer/resolver/export.inc"
#include "go-googlesql/analyzer/substitute/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/aggregate_null_handling/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/annotation/collation/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
