#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_STANDALONE_MACRO_EXPANSION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_STANDALONE_MACRO_EXPANSION_EXPORT_H

#include "zetasql/parser/macros/standalone_macro_expansion.h"
// include sources
#include "zetasql/parser/macros/standalone_macro_expansion.cc"
// include dependencies
#include "go-zetasql/parser/macros/token_splicing_utils/export.inc"
#include "go-zetasql/parser/macros/token_with_location/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/parser/bison_token_codes/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
