
#ifndef absl_utility_utility_bind_cc
#define absl_utility_utility_bind_cc

// switch namespace
#define differential_privacy absl_utility_utility_differential_privacy
#define googlesql absl_utility_utility_googlesql
#define googlesql_base absl_utility_utility_googlesql_base
#define googlesql_bison_parser absl_utility_utility_googlesql_bison_parser
#define re2 absl_utility_utility_re2
#define AbslInternalSleepFor absl_utility_utility_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_utility_utility_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_utility_utility_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_utility_utility_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_utility_utility_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_utility_utility_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_utility_utility_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_utility_utility_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_utility_utility_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_utility_utility_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_utility_utility_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_utility_utility_GoogleSqlalloc
#define GoogleSqlfree absl_utility_utility_GoogleSqlfree
#define GoogleSqlrealloc absl_utility_utility_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_utility_utility_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_utility_utility_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_utility_utility_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_utility_utility_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_utility_utility_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_utility_utility_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_utility_utility_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_utility_utility_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_utility_utility_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_utility_utility_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_utility_utility_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_utility_utility_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_utility_utility_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_utility_utility_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_utility_utility_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_utility_utility_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_utility_utility_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_utility_utility_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_utility_utility_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_utility_utility_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_utility_utility_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_utility_utility_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_utility_utility_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_utility_utility_GoogleSqlFlexLexer
#define UCaseMap absl_utility_utility_UCaseMap

#define GO_EXPORT(def) export_absl_utility_utility_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/utility/utility.h"
//#undef private

// include sources

// include dependencies
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_utility_utility_bind_cc */
