#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_STANDALONE_MACRO_EXPANSION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_STANDALONE_MACRO_EXPANSION_EXPORT_H

#include "googlesql/parser/macros/standalone_macro_expansion.h"
// include sources
#include "googlesql/parser/macros/standalone_macro_expansion.cc"
// include dependencies
#include "go-googlesql/parser/macros/token_splicing_utils/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/parser/token/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
