#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_EXAMINE_STACK_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_EXAMINE_STACK_EXPORT_H

#include "absl/debugging/internal/examine_stack.h"
// include sources
#include "absl/debugging/internal/examine_stack.cc"
// include dependencies
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/debugging/symbolize/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#endif
