#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PROTO_VALUE_CONVERSION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_PROTO_VALUE_CONVERSION_EXPORT_H

#include "zetasql/public/proto_value_conversion.h"
// include sources
#include "zetasql/public/proto_value_conversion.cc"
// include dependencies
#include "go-zetasql/public/json_value/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/uuid_value/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/value_cc_proto/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/functions/date_time_util/export.inc"
#include "go-zetasql/public/functions/range/export.inc"
#include "go-zetasql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-protobuf/protobuf/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
