#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TOKEN_DISAMBIGUATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TOKEN_DISAMBIGUATOR_EXPORT_H

#include "googlesql/parser/token_disambiguator.h"
// include sources
#include "googlesql/parser/token_disambiguator.cc"
// include dependencies
#include "go-googlesql/parser/bison_parser_mode/export.inc"
#include "go-googlesql/parser/bison_token_codes/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/parser/macros/flex_token_provider/export.inc"
#include "go-googlesql/parser/macros/macro_catalog/export.inc"
#include "go-googlesql/parser/macros/macro_expander/export.inc"
#include "go-googlesql/parser/macros/token_with_location/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
