
#ifndef absl_status_status_matchers_bind_cc
#define absl_status_status_matchers_bind_cc

// switch namespace
#define differential_privacy absl_status_status_matchers_differential_privacy
#define googlesql absl_status_status_matchers_googlesql
#define googlesql_base absl_status_status_matchers_googlesql_base
#define googlesql_bison_parser absl_status_status_matchers_googlesql_bison_parser
#define re2 absl_status_status_matchers_re2
#define AbslInternalSleepFor absl_status_status_matchers_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_status_status_matchers_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_status_status_matchers_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_status_status_matchers_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_status_status_matchers_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_status_status_matchers_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_status_status_matchers_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_status_status_matchers_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_status_status_matchers_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_status_status_matchers_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_status_status_matchers_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_status_status_matchers_GoogleSqlalloc
#define GoogleSqlfree absl_status_status_matchers_GoogleSqlfree
#define GoogleSqlrealloc absl_status_status_matchers_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_status_status_matchers_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_status_status_matchers_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_status_status_matchers_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_status_status_matchers_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_status_status_matchers_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_status_status_matchers_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_status_status_matchers_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_status_status_matchers_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_status_status_matchers_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_status_status_matchers_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_status_status_matchers_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_status_status_matchers_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_status_status_matchers_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_status_status_matchers_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_status_status_matchers_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_status_status_matchers_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_status_status_matchers_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_status_status_matchers_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_status_status_matchers_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_status_status_matchers_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_status_status_matchers_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_status_status_matchers_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_status_status_matchers_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_status_status_matchers_GoogleSqlFlexLexer
#define UCaseMap absl_status_status_matchers_UCaseMap

#define GO_EXPORT(def) export_absl_status_status_matchers_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/status/status_matchers.h"
//#undef private

// include sources
#include "absl/status/internal/status_matchers.cc"
#include "absl/status/internal/status_matchers.h"

// include dependencies
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-googletest/googletest/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_status_status_matchers_bind_cc */
