#ifndef INTERNAL_CCALL_GO_ABSL_STATUS_STATUS_MATCHERS_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STATUS_STATUS_MATCHERS_EXPORT_H

#include "absl/status/status_matchers.h"
// include sources
#include "absl/status/internal/status_matchers.cc"
#include "absl/status/internal/status_matchers.h"
// include dependencies
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
