#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_DEBUGGING_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_DEBUGGING_INTERNAL_EXPORT_H

#include "absl/debugging/internal/address_is_readable.h"
#include "absl/debugging/internal/elf_mem_image.h"
#include "absl/debugging/internal/vdso_support.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/dynamic_annotations/export.inc"
#include "go-absl/base/errno_saver/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#endif
