#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_AGGREGATION_THRESHOLD_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_AGGREGATION_THRESHOLD_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/public/aggregation_threshold_utils.h"
// include sources
#include "googlesql/legacy_zetasql/public/aggregation_threshold_utils.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/analyzer_options/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/no_destructor/export.inc"
#include "go-googlesql/proto/options_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"

#endif
