#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_TYPE_PARAMETER_CONSTRAINTS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_TYPE_PARAMETER_CONSTRAINTS_EXPORT_H

#include "googlesql/reference_impl/type_parameter_constraints.h"
// include sources
#include "googlesql/reference_impl/type_parameter_constraints.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/internal_value/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/timestamp_picos_value/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/string/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
