#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_FUNCTION_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_FUNCTION_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/common/function_utils.h"
// include sources
#include "googlesql/legacy_zetasql/common/function_utils.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/public/function_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
