#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_SQL_CONSTANT_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_SQL_CONSTANT_EXPORT_H

#include "googlesql/legacy_zetasql/public/sql_constant.h"
// include sources
#include "googlesql/legacy_zetasql/public/sql_constant.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/constant/export.inc"
#include "go-googlesql/legacy_zetasql/public/parse_location/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
