#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_MACRO_EXPANDER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_MACROS_MACRO_EXPANDER_EXPORT_H

#include "googlesql/parser/macros/macro_expander.h"
// include sources
#include "googlesql/parser/macros/macro_expander.cc"
// include dependencies
#include "go-googlesql/parser/macros/diagnostic/export.inc"
#include "go-googlesql/parser/macros/macro_catalog/export.inc"
#include "go-googlesql/parser/macros/quoting/export.inc"
#include "go-googlesql/parser/macros/standalone_macro_expansion/export.inc"
#include "go-googlesql/parser/macros/token_provider_base/export.inc"
#include "go-googlesql/parser/macros/token_splicing_utils/export.inc"
#include "go-googlesql/base/arena/export.inc"
#include "go-googlesql/base/arena_allocator/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/strings/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/parser/token/export.inc"
#include "go-googlesql/parser/token_with_location/export.inc"
#include "go-googlesql/proto/internal_error_location_cc_proto/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/error_location_cc_proto/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"

#endif
