#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_PATH_EXPRESSION_SPAN_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_PATH_EXPRESSION_SPAN_EXPORT_H

#include "googlesql/analyzer/path_expression_span.h"
// include sources
#include "googlesql/analyzer/path_expression_span.cc"
// include dependencies
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/parser/parse_tree/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
