
#ifndef absl_time_time_bind_cc
#define absl_time_time_bind_cc

// switch namespace
#define differential_privacy absl_time_time_differential_privacy
#define googlesql absl_time_time_googlesql
#define googlesql_base absl_time_time_googlesql_base
#define googlesql_bison_parser absl_time_time_googlesql_bison_parser
#define re2 absl_time_time_re2
#define AbslInternalSleepFor absl_time_time_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_time_time_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_time_time_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_time_time_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_time_time_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_time_time_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_time_time_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_time_time_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_time_time_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_time_time_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_time_time_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_time_time_GoogleSqlalloc
#define GoogleSqlfree absl_time_time_GoogleSqlfree
#define GoogleSqlrealloc absl_time_time_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_time_time_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_time_time_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_time_time_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_time_time_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_time_time_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_time_time_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_time_time_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_time_time_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_time_time_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_time_time_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_time_time_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_time_time_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_time_time_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_time_time_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_time_time_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_time_time_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_time_time_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_time_time_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_time_time_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_time_time_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_time_time_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_time_time_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_time_time_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_time_time_GoogleSqlFlexLexer
#define UCaseMap absl_time_time_UCaseMap

#define GO_EXPORT(def) export_absl_time_time_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/time/civil_time.h"
#include "absl/time/clock.h"
#include "absl/time/time.h"
//#undef private

// include sources
#include "absl/time/civil_time.cc"
#include "absl/time/clock.cc"
#include "absl/time/duration.cc"
#include "absl/time/format.cc"
#define unix_epoch absl_time_time_unix_epoch
#include "absl/time/time.cc"
#undef unix_epoch


// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/go_internal/cctz/civil_time/export.inc"
#include "go-absl/time/go_internal/cctz/time_zone/export.inc"
#include "go-absl/types/optional/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_time_time_bind_cc */
