#ifndef INTERNAL_CCALL_GO_ABSL_TIME_TIME_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_TIME_TIME_EXPORT_H

#include "absl/time/civil_time.h"
#include "absl/time/clock.h"
#include "absl/time/time.h"
// include sources
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/go_internal/cctz/civil_time/export.inc"
#include "go-absl/time/go_internal/cctz/time_zone/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
