#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_STANDALONE_MACRO_EXPANSION_IMPL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PARSER_MACROS_STANDALONE_MACRO_EXPANSION_IMPL_EXPORT_H

#include "googlesql/legacy_zetasql/parser/macros/standalone_macro_expansion_impl.h"
// include sources
// include dependencies
#include "go-googlesql/legacy_zetasql/parser/macros/flex_token_provider/export.inc"
#include "go-googlesql/legacy_zetasql/parser/macros/macro_catalog/export.inc"
#include "go-googlesql/legacy_zetasql/parser/macros/macro_expander/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
