// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/tools/execute_query/execute_query.proto

#include "googlesql/legacy_zetasql/tools/execute_query/execute_query.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace zetasql {
namespace execute_query {
template <typename>
PROTOBUF_CONSTEXPR ParserErrorContext::ParserErrorContext(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.text_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }
} {}
struct ParserErrorContextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParserErrorContextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParserErrorContextDefaultTypeInternal() {}
  union {
    ParserErrorContext _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParserErrorContextDefaultTypeInternal _ParserErrorContext_default_instance_;
}  // namespace execute_query
}  // namespace zetasql
static ::_pb::Metadata file_level_metadata_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto = nullptr;
const ::uint32_t TableStruct_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::zetasql::execute_query::ParserErrorContext, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::zetasql::execute_query::ParserErrorContext, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::zetasql::execute_query::ParserErrorContext, _impl_.text_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 9, -1, sizeof(::zetasql::execute_query::ParserErrorContext)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::zetasql::execute_query::_ParserErrorContext_default_instance_._instance,
};
const char descriptor_table_protodef_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n/zetasql/tools/execute_query/execute_qu"
    "ery.proto\022\025zetasql.execute_query\"\"\n\022Pars"
    "erErrorContext\022\014\n\004text\030\001 \001(\t"
};
static ::absl::once_flag descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto = {
    false,
    false,
    108,
    descriptor_table_protodef_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto,
    "zetasql/tools/execute_query/execute_query.proto",
    &descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto::offsets,
    file_level_metadata_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto,
    file_level_enum_descriptors_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto,
    file_level_service_descriptors_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto_getter() {
  return &descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto(&descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto);
namespace zetasql {
namespace execute_query {
// ===================================================================

class ParserErrorContext::_Internal {
 public:
  using HasBits = decltype(std::declval<ParserErrorContext>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ParserErrorContext, _impl_._has_bits_);
  static void set_has_text(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ParserErrorContext::ParserErrorContext(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:zetasql.execute_query.ParserErrorContext)
}
ParserErrorContext::ParserErrorContext(const ParserErrorContext& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ParserErrorContext* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.text_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.text_.Set(from._internal_text(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:zetasql.execute_query.ParserErrorContext)
}

inline void ParserErrorContext::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.text_) {}

  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.text_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ParserErrorContext::~ParserErrorContext() {
  // @@protoc_insertion_point(destructor:zetasql.execute_query.ParserErrorContext)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ParserErrorContext::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.text_.Destroy();
}

void ParserErrorContext::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ParserErrorContext::Clear() {
// @@protoc_insertion_point(message_clear_start:zetasql.execute_query.ParserErrorContext)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.text_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParserErrorContext::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string text = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "zetasql.execute_query.ParserErrorContext.text");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* ParserErrorContext::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zetasql.execute_query.ParserErrorContext)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string text = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_text();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "zetasql.execute_query.ParserErrorContext.text");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zetasql.execute_query.ParserErrorContext)
  return target;
}

::size_t ParserErrorContext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zetasql.execute_query.ParserErrorContext)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string text = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_text());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ParserErrorContext::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ParserErrorContext::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ParserErrorContext::GetClassData() const { return &_class_data_; }


void ParserErrorContext::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ParserErrorContext*>(&to_msg);
  auto& from = static_cast<const ParserErrorContext&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:zetasql.execute_query.ParserErrorContext)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_text(from._internal_text());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ParserErrorContext::CopyFrom(const ParserErrorContext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zetasql.execute_query.ParserErrorContext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParserErrorContext::IsInitialized() const {
  return true;
}

void ParserErrorContext::InternalSwap(ParserErrorContext* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, lhs_arena,
                                       &other->_impl_.text_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata ParserErrorContext::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto_getter, &descriptor_table_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto_once,
      file_level_metadata_zetasql_2ftools_2fexecute_5fquery_2fexecute_5fquery_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace execute_query
}  // namespace zetasql
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zetasql::execute_query::ParserErrorContext*
Arena::CreateMaybeMessage< ::zetasql::execute_query::ParserErrorContext >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zetasql::execute_query::ParserErrorContext >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
