#ifndef INTERNAL_CCALL_GO_ABSL_LOG_LOG_STREAMER_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_LOG_STREAMER_EXPORT_H

#include "absl/log/log_streamer.h"
// include sources
// include dependencies
#include "go-absl/log/absl_log/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/internal/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-absl/utility/utility/export.inc"

#endif
