#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANON_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANON_FUNCTION_EXPORT_H

#include "googlesql/public/anon_function.h"
// include sources
#include "googlesql/public/anon_function.cc"
// include dependencies
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-absl/functional/bind_front/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
