#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_BITWISE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_BITWISE_EXPORT_H

#include "googlesql/public/functions/bitwise.h"
// include sources
#include "googlesql/public/functions/bitwise.cc"
// include dependencies
#include "go-googlesql/public/functions/bitwise_agg_mode_cc_proto/export.inc"
#include "go-googlesql/public/functions/util/export.inc"
#include "go-googlesql/base/bits/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
