#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_BASE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_BASE_EXPORT_H

#include "googlesql/legacy_zetasql/base/atomic_sequence_num.h"
#include "googlesql/legacy_zetasql/base/logging.h"
#include "googlesql/legacy_zetasql/base/varsetter.h"
// include sources
// include dependencies
#include "go-googlesql/legacy_zetasql/base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/log/absl_check/export.inc"
#include "go-absl/log/absl_log/export.inc"

#endif
