#ifndef INTERNAL_CCALL_GO_ABSL_LOG_ABSL_VLOG_IS_ON_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_ABSL_VLOG_IS_ON_EXPORT_H

#include "absl/log/absl_vlog_is_on.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/log/go_internal/vlog_config/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
