#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_MATCH_RECOGNIZE_EDGE_MATCHERS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_MATCH_RECOGNIZE_EDGE_MATCHERS_EXPORT_H

#include "googlesql/common/match_recognize/edge_matchers.h"
// include sources
#include "googlesql/common/match_recognize/edge_matchers.cc"
// include dependencies
#include "go-googlesql/common/match_recognize/compiled_nfa/export.inc"
#include "go-googlesql/common/match_recognize/nfa/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-googletest/googletest/export.inc"

#endif
