#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_SAMPLE_TOKEN_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_SAMPLE_TOKEN_EXPORT_H

#include "absl/strings/internal/cordz_sample_token.h"
// include sources
#include "absl/strings/internal/cordz_sample_token.cc"
// include dependencies
#include "go-absl/strings/cordz_handle/export.inc"
#include "go-absl/strings/cordz_info/export.inc"
#include "go-absl/base/config/export.inc"

#endif
