#ifndef INTERNAL_CCALL_GO_ALGORITHMS_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_UTIL_EXPORT_H

#include "algorithms/util.h"
// include sources
#include "algorithms/util.cc"
// include dependencies
#include "go-base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-base/status/export.inc"

#endif
