#ifndef INTERNAL_CCALL_GO_ABSL_FUNCTIONAL_FUNCTION_REF_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FUNCTIONAL_FUNCTION_REF_EXPORT_H

#include "absl/functional/function_ref.h"
// include sources
#include "absl/functional/internal/function_ref.h"
// include dependencies
#include "go-absl/functional/any_invocable/export.inc"
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#endif
