#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_NUMERIC_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_NUMERIC_VALUE_EXPORT_H

#include "googlesql/legacy_zetasql/public/numeric_value.h"
// include sources
#include "googlesql/legacy_zetasql/public/numeric_value.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/numeric_constants/export.inc"
#include "go-googlesql/legacy_zetasql/public/numeric_parser/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/endian/export.inc"
#include "go-googlesql/base/mathutil/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/stl_util/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/multiprecision_int/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/compare/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
