#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_NET_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_NET_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/net.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/net.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/functions/util/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/net/idn/export.inc"
#include "go-googlesql/base/net/ipaddress/export.inc"
#include "go-googlesql/base/net/public_suffix/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
