#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_EVALUATOR_TABLE_ITERATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_EVALUATOR_TABLE_ITERATOR_EXPORT_H

#include "googlesql/legacy_zetasql/public/evaluator_table_iterator.h"
// include sources
// include dependencies
#include "go-zetasql/legacy_zetasql/public/value/export.inc"
#include "go-zetasql/base/status/export.inc"

#endif
