#ifndef INTERNAL_CCALL_GO_ABSL_LOG_LOG_ENTRY_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_LOG_ENTRY_EXPORT_H

#include "absl/log/log_entry.h"
// include sources
#include "absl/log/log_entry.cc"
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/log/go_internal/config/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
