#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_FILE_UTIL_OSS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_FILE_UTIL_OSS_EXPORT_H

#include "googlesql/legacy_zetasql/base/file_util_oss.h"
// include sources
// include dependencies
#include "go-zetasql/legacy_zetasql/base/logging/export.inc"
#include "go-zetasql/legacy_zetasql/base/path/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-re2/re2/export.inc"

#endif
