#ifndef INTERNAL_CCALL_GO_ABSL_LOG_INITIALIZE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_INITIALIZE_EXPORT_H

#include "absl/log/initialize.h"
// include sources
#include "absl/log/initialize.cc"
// include dependencies
#include "go-absl/log/globals/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/log/go_internal/globals/export.inc"
#include "go-absl/time/time/export.inc"

#endif
