#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_FUNCTION_SIGNATURE_MATCHER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_FUNCTION_SIGNATURE_MATCHER_EXPORT_H

#include "googlesql/analyzer/function_signature_matcher.h"
// include sources
#include "googlesql/analyzer/function_signature_matcher.cc"
// include dependencies
#include "go-googlesql/analyzer/lambda_util/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/base/strings/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/coercer/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/id_string/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/signature_match_result/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/span/export.inc"

#endif
