#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_ARENA_ALLOCATOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_ARENA_ALLOCATOR_EXPORT_H

#include "zetasql/base/arena_allocator.h"
// include sources
#include "zetasql/base/arena_allocator.cc"
// include dependencies
#include "go-zetasql/base/arena/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
