#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_MODULE_CONTENTS_FETCHER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_MODULE_CONTENTS_FETCHER_EXPORT_H

#include "googlesql/public/module_contents_fetcher.h"
// include sources
#include "googlesql/public/module_contents_fetcher.cc"
// include dependencies
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_resume_location/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/proto/module_options_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/types/span/export.inc"

#endif
