#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_SCRIPTING_SCRIPT_SEGMENT_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_SCRIPTING_SCRIPT_SEGMENT_EXPORT_H

#include "googlesql/legacy_zetasql/scripting/script_segment.h"
// include sources
#include "googlesql/legacy_zetasql/scripting/script_segment.cc"
// include dependencies
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-googlesql/public/parse_resume_location/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
