#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_REWRITE_SUBPIPELINE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_REWRITE_SUBPIPELINE_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/rewrite_subpipeline.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/rewrite_subpipeline.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
