#ifndef INTERNAL_CCALL_GO_ABSL_LOG_FLAGS_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_FLAGS_EXPORT_H

#include "absl/log/flags.h"
// include sources
#include "absl/log/flags.cc"
// include dependencies
#include "go-absl/log/globals/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/flags/marshalling/export.inc"
#include "go-absl/log/go_internal/config/export.inc"
#include "go-absl/log/go_internal/flags/export.inc"
#include "go-absl/log/go_internal/vlog_config/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
