#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_STRING_WITH_COLLATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_STRING_WITH_COLLATION_EXPORT_H

#include "zetasql/reference_impl/functions/string_with_collation.h"
// include sources
#include "zetasql/reference_impl/functions/string_with_collation.cc"
// include dependencies
#include "go-zetasql/public/collator/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/string_with_collation/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
