#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_STRING_WITH_COLLATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_STRING_WITH_COLLATION_EXPORT_H

#include "googlesql/reference_impl/functions/string_with_collation.h"
// include sources
#include "googlesql/reference_impl/functions/string_with_collation.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/collator/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/string_with_collation/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#endif
