#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_MULTIPRECISION_INT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_MULTIPRECISION_INT_EXPORT_H

#include "zetasql/common/multiprecision_int.h"
#include "zetasql/common/multiprecision_int_impl.h"
// include sources
#include "zetasql/common/multiprecision_int.cc"
#include "zetasql/common/multiprecision_int_impl.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/bits/export.inc"
#include "go-zetasql/base/endian/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/compare/export.inc"
#include "go-absl/types/span/export.inc"

#endif
