#ifndef INTERNAL_CCALL_GO_ABSL_FLAGS_CONFIG_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_FLAGS_CONFIG_EXPORT_H

#include "absl/flags/config.h"
#include "absl/flags/usage_config.h"
// include sources
// include dependencies
#include "go-absl/flags/path_util/export.inc"
#include "go-absl/flags/program_name/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
