
#ifndef base_percentile_bind_cc
#define base_percentile_bind_cc

// switch namespace
#define differential_privacy base_percentile_differential_privacy
#define googlesql base_percentile_googlesql
#define googlesql_base base_percentile_googlesql_base
#define googlesql_bison_parser base_percentile_googlesql_bison_parser
#define re2 base_percentile_re2
#define AbslInternalSleepFor base_percentile_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError base_percentile_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield base_percentile_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost base_percentile_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait base_percentile_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything base_percentile_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay base_percentile_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake base_percentile_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin base_percentile_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd base_percentile_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint base_percentile_AbslInternalGetFileMappingHint
#define GoogleSqlalloc base_percentile_GoogleSqlalloc
#define GoogleSqlfree base_percentile_GoogleSqlfree
#define GoogleSqlrealloc base_percentile_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly base_percentile_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream base_percentile_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly base_percentile_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream base_percentile_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit base_percentile_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path base_percentile_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width base_percentile_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance base_percentile_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period base_percentile_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit base_percentile_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path base_percentile_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width base_percentile_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance base_percentile_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period base_percentile_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes base_percentile_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes base_percentile_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string base_percentile_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string base_percentile_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability base_percentile_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability base_percentile_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests base_percentile_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests base_percentile_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase base_percentile_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer base_percentile_GoogleSqlFlexLexer
#define UCaseMap base_percentile_UCaseMap

#define GO_EXPORT(def) export_base_percentile_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "base/percentile.h"
//#undef private

// include sources

// include dependencies
#include "go-proto/util-lib/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* base_percentile_bind_cc */
