#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_STATUS_PAYLOAD_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_STATUS_PAYLOAD_UTILS_EXPORT_H

#include "zetasql/common/status_payload_utils.h"
// include sources
#include "zetasql/common/status_payload_utils.cc"
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"
#include "go-google/rpc/status_cc_proto/export.inc"

#endif
