#ifndef ZETASQL_PUBLIC_TYPE_MODIFIERS_CC_PROTO_EXPORT_H
#define ZETASQL_PUBLIC_TYPE_MODIFIERS_CC_PROTO_EXPORT_H

#include "zetasql/public/type_modifiers.pb.h"
#define schemas go_zetasql_public_type_modifiers_cc_proto_type_modifiers_schemas
#define file_default_instances go_zetasql_public_type_modifiers_cc_proto_type_modifiers_file_default_instances
#include "zetasql/public/type_modifiers.pb.cc"
#undef file_default_instances
#undef schemas

#include "go-protobuf/protobuf/export.inc"

#endif
