#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_NUMERIC_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_NUMERIC_VALUE_EXPORT_H

#include "zetasql/public/numeric_value.h"
// include sources
#include "zetasql/public/numeric_value.cc"
// include dependencies
#include "go-zetasql/public/numeric_constants/export.inc"
#include "go-zetasql/public/numeric_parser/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/endian/export.inc"
#include "go-zetasql/base/mathutil/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/stl_util/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/multiprecision_int/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
