#ifndef INTERNAL_CCALL_GO_ZETASQL_BASE_MATHUTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_BASE_MATHUTIL_EXPORT_H

#include "zetasql/base/mathutil.h"
// include sources
#include "zetasql/base/mathutil.cc"
// include dependencies
#include "go-zetasql/base/bits/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/mathlimits/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
