#ifndef INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_WIDE_MULTIPLY_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_WIDE_MULTIPLY_EXPORT_H

#include "absl/random/internal/wide_multiply.h"
// include sources
// include dependencies
#include "go-absl/random/go_internal/traits/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/numeric/int128/export.inc"

#endif
