#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_JSON_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_JSON_EXPORT_H

#include "zetasql/public/functions/json.h"
// include sources
#include "zetasql/public/functions/json.cc"
// include dependencies
#include "go-zetasql/public/functions/convert/export.inc"
#include "go-zetasql/public/functions/convert_string/export.inc"
#include "go-zetasql/public/functions/json_format/export.inc"
#include "go-zetasql/public/functions/json_internal/export.inc"
#include "go-zetasql/public/functions/to_json/export.inc"
#include "go-zetasql/base/lossless_convert/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/public/json_value/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-re2/re2/export.inc"

#endif
