#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_CONVERT_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_CONVERT_PROTO_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/convert_proto.h"
// include sources
#include "googlesql/legacy_zetasql/public/functions/convert_proto.cc"
// include dependencies
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"

#endif
