#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANONYMIZATION_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANONYMIZATION_UTILS_EXPORT_H

#include "zetasql/public/anonymization_utils.h"
// include sources
#include "zetasql/public/anonymization_utils.cc"
// include dependencies
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
