#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_LITERAL_REMOVER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_LITERAL_REMOVER_EXPORT_H

#include "googlesql/legacy_zetasql/public/literal_remover.h"
// include sources
#include "googlesql/legacy_zetasql/public/literal_remover.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/legacy_zetasql/public/language_options/export.inc"
#include "go-zetasql/legacy_zetasql/public/parse_location/export.inc"
#include "go-zetasql/legacy_zetasql/public/type/export.inc"
#include "go-zetasql/legacy_zetasql/public/value/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/container/node_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
