#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_DEMANGLE_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_DEMANGLE_INTERNAL_EXPORT_H

#include "absl/debugging/internal/demangle.h"
// include sources
// include dependencies
#include "go-absl/debugging/demangle_rust/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/numeric/bits/export.inc"

#endif
