#ifndef INTERNAL_CCALL_GO_ABSL_DEBUGGING_DEMANGLE_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_DEBUGGING_DEMANGLE_INTERNAL_EXPORT_H

#include "absl/debugging/internal/demangle.h"
// include sources
#include "absl/debugging/internal/demangle.cc"
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
