#ifndef INTERNAL_CCALL_GO_ABSL_PROFILING_SAMPLE_RECORDER_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_PROFILING_SAMPLE_RECORDER_EXPORT_H

#include "absl/profiling/internal/sample_recorder.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"

#endif
