#ifndef INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_POOL_URBG_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_POOL_URBG_EXPORT_H

#include "absl/random/internal/pool_urbg.h"
// include sources
#include "absl/random/internal/pool_urbg.cc"
// include dependencies
#include "go-absl/random/go_internal/randen/export.inc"
#include "go-absl/random/go_internal/seed_material/export.inc"
#include "go-absl/random/go_internal/traits/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/endian/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/random/seed_gen_exception/export.inc"
#include "go-absl/types/span/export.inc"

#endif
