#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_INTERNAL_ANALYZER_OUTPUT_PROPERTIES_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_INTERNAL_ANALYZER_OUTPUT_PROPERTIES_EXPORT_H

#include "googlesql/common/internal_analyzer_output_properties.h"
// include sources
// include dependencies
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/target_syntax/export.inc"

#endif
