#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_PROTO_EXPORT_H

#include "absl/log/internal/proto.h"
// include sources
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
