#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SIMPLE_SEQUENCE_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SIMPLE_SEQUENCE_CC_PROTO_EXPORT_H

#include "googlesql/public/simple_sequence.pb.h"
// include sources
#define schemas googlesql_public_simple_sequence_schemas
#define file_default_instances googlesql_public_simple_sequence_file_default_instances
#include "googlesql/public/simple_sequence.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies

#endif
