#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITE_RESOLVED_AST_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITE_RESOLVED_AST_EXPORT_H

#include "zetasql/analyzer/rewrite_resolved_ast.h"
// include sources
#include "zetasql/analyzer/rewrite_resolved_ast.cc"
// include dependencies
#include "go-zetasql/analyzer/analyzer_output_mutator/export.inc"
#include "go-zetasql/analyzer/rewriters/registration/export.inc"
#include "go-zetasql/analyzer/rewriters/rewriter_relevance_checker/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/internal_analyzer_options/export.inc"
#include "go-zetasql/common/timer_util/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/validator/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
