#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_TO_JSON_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_TO_JSON_EXPORT_H

#include "zetasql/public/functions/to_json.h"
// include sources
#include "zetasql/public/functions/to_json.cc"
// include dependencies
#include "go-zetasql/public/functions/json_format/export.inc"
#include "go-zetasql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/thread_stack/export.inc"
#include "go-zetasql/public/interval_value/export.inc"
#include "go-zetasql/public/json_value/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/uuid_value/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
