#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANNOTATION_COLLATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ANNOTATION_COLLATION_EXPORT_H

#include "zetasql/public/annotation/collation.h"
// include sources
#include "zetasql/public/annotation/collation.cc"
// include dependencies
#include "go-zetasql/public/annotation/default_annotation/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/parser/parse_tree/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
