#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_INTERVAL_VALUE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_INTERVAL_VALUE_EXPORT_H

#include "googlesql/legacy_zetasql/public/interval_value.h"
// include sources
#include "googlesql/legacy_zetasql/public/interval_value.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/endian/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/multiprecision_int/export.inc"
#include "go-googlesql/public/functions/datetime_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/numeric/int128/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-re2/re2/export.inc"

#endif
