#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_RANGE_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_FUNCTIONS_RANGE_EXPORT_H

#include "zetasql/reference_impl/functions/range.h"
// include sources
#include "zetasql/reference_impl/functions/range.cc"
// include dependencies
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/civil_time/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/range/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
