#ifndef INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_SCRIPT_SEGMENT_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_SCRIPT_SEGMENT_EXPORT_H

#include "zetasql/scripting/script_segment.h"
// include sources
#include "zetasql/scripting/script_segment.cc"
// include dependencies
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/parse_resume_location/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
