
#ifndef googlesql_common_builtin_function_internal_bind_cc
#define googlesql_common_builtin_function_internal_bind_cc

// switch namespace
#define absl googlesql_common_builtin_function_internal_absl
#define differential_privacy googlesql_common_builtin_function_internal_differential_privacy
#define google googlesql_common_builtin_function_internal_google
#define googlesql googlesql_common_builtin_function_internal_googlesql
#define googlesql_base googlesql_common_builtin_function_internal_googlesql_base
#define googlesql_bison_parser googlesql_common_builtin_function_internal_googlesql_bison_parser
#define re2 googlesql_common_builtin_function_internal_re2
#define AbslInternalSleepFor googlesql_common_builtin_function_internal_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_common_builtin_function_internal_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_common_builtin_function_internal_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_common_builtin_function_internal_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_common_builtin_function_internal_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_common_builtin_function_internal_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_common_builtin_function_internal_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_common_builtin_function_internal_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_common_builtin_function_internal_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_common_builtin_function_internal_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_common_builtin_function_internal_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_common_builtin_function_internal_GoogleSqlalloc
#define GoogleSqlfree googlesql_common_builtin_function_internal_GoogleSqlfree
#define GoogleSqlrealloc googlesql_common_builtin_function_internal_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_common_builtin_function_internal_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_common_builtin_function_internal_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_common_builtin_function_internal_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_common_builtin_function_internal_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_common_builtin_function_internal_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_common_builtin_function_internal_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_common_builtin_function_internal_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_common_builtin_function_internal_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_common_builtin_function_internal_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_common_builtin_function_internal_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_common_builtin_function_internal_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_common_builtin_function_internal_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_common_builtin_function_internal_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_common_builtin_function_internal_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_common_builtin_function_internal_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_common_builtin_function_internal_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_common_builtin_function_internal_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_common_builtin_function_internal_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_common_builtin_function_internal_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_common_builtin_function_internal_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_common_builtin_function_internal_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_common_builtin_function_internal_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_common_builtin_function_internal_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_common_builtin_function_internal_GoogleSqlFlexLexer
#define UCaseMap googlesql_common_builtin_function_internal_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto googlesql_common_builtin_function_internal_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto googlesql_common_builtin_function_internal_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto googlesql_common_builtin_function_internal_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto googlesql_common_builtin_function_internal_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2ftype_2ftimeofday_2eproto
#define google_2frpc_2fstatus_2eproto googlesql_common_builtin_function_internal_google_2frpc_2fstatus_2eproto
#define descriptor_table_google_2frpc_2fstatus_2eproto googlesql_common_builtin_function_internal_descriptor_table_google_2frpc_2fstatus_2eproto
#define TableStruct_google_2frpc_2fstatus_2eproto googlesql_common_builtin_function_internal_TableStruct_google_2frpc_2fstatus_2eproto
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define googlesql_2fcommon_2freflection_2eproto googlesql_common_builtin_function_internal_googlesql_2fcommon_2freflection_2eproto
#define descriptor_table_googlesql_2fcommon_2freflection_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fcommon_2freflection_2eproto
#define TableStruct_googlesql_2fcommon_2freflection_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fcommon_2freflection_2eproto
#define googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto googlesql_common_builtin_function_internal_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define descriptor_table_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define TableStruct_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fcommon_2fmatch_5frecognize_2fmatch_5ftest_5fresult_2eproto
#define googlesql_2fparser_2fparse_5ftree_2eproto googlesql_common_builtin_function_internal_googlesql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_googlesql_2fparser_2fparse_5ftree_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_googlesql_2fparser_2fparse_5ftree_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fparser_2fparse_5ftree_2eproto
#define googlesql_2fparser_2fast_5fenums_2eproto googlesql_common_builtin_function_internal_googlesql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_googlesql_2fparser_2fast_5fenums_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fparser_2fast_5fenums_2eproto
#define TableStruct_googlesql_2fparser_2fast_5fenums_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fparser_2fast_5fenums_2eproto
#define googlesql_2fproto_2foptions_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2foptions_2eproto
#define descriptor_table_googlesql_2fproto_2foptions_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2foptions_2eproto
#define TableStruct_googlesql_2fproto_2foptions_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2foptions_2eproto
#define googlesql_2fproto_2fsimple_5fcatalog_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_googlesql_2fproto_2fsimple_5fcatalog_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_googlesql_2fproto_2fsimple_5fcatalog_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2fsimple_5fcatalog_2eproto
#define googlesql_2fproto_2ffunction_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2ffunction_2eproto
#define descriptor_table_googlesql_2fproto_2ffunction_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2ffunction_2eproto
#define TableStruct_googlesql_2fproto_2ffunction_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2ffunction_2eproto
#define googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2finternal_5ffix_5fsuggestion_2eproto
#define googlesql_2fproto_2fmodule_5foptions_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2fmodule_5foptions_2eproto
#define descriptor_table_googlesql_2fproto_2fmodule_5foptions_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2fmodule_5foptions_2eproto
#define TableStruct_googlesql_2fproto_2fmodule_5foptions_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2fmodule_5foptions_2eproto
#define googlesql_2fproto_2finternal_5ferror_5flocation_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2finternal_5ferror_5flocation_2eproto
#define googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define googlesql_2fproto_2fscript_5fexception_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2fscript_5fexception_2eproto
#define descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2fscript_5fexception_2eproto
#define TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2fscript_5fexception_2eproto
#define googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto googlesql_common_builtin_function_internal_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define descriptor_table_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define TableStruct_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fproto_2fsimple_5fproperty_5fgraph_2eproto
#define googlesql_2fpublic_2fconstness_5flevel_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define descriptor_table_googlesql_2fpublic_2fconstness_5flevel_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define TableStruct_googlesql_2fpublic_2fconstness_5flevel_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fconstness_5flevel_2eproto
#define googlesql_2fpublic_2fbuiltin_5ffunction_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fbuiltin_5ffunction_2eproto
#define googlesql_2fpublic_2fdeprecation_5fwarning_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fdeprecation_5fwarning_2eproto
#define googlesql_2fpublic_2ffunction_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunction_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunction_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunction_2eproto
#define TableStruct_googlesql_2fpublic_2ffunction_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunction_2eproto
#define googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define googlesql_2fpublic_2foptions_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2foptions_2eproto
#define googlesql_2fpublic_2fsimple_5ftable_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5ftable_2eproto
#define googlesql_2fpublic_2fsimple_5fconstant_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fconstant_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fconstant_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5fconstant_2eproto
#define googlesql_2fpublic_2fsimple_5fconnection_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fconnection_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fconnection_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5fconnection_2eproto
#define googlesql_2fpublic_2fsimple_5fmodel_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fmodel_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fmodel_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5fmodel_2eproto
#define googlesql_2fpublic_2fsimple_5fsequence_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fsequence_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fsequence_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5fsequence_2eproto
#define googlesql_2fpublic_2fparse_5flocation_5frange_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fparse_5flocation_5frange_2eproto
#define googlesql_2fpublic_2ftype_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ftype_2eproto
#define googlesql_2fpublic_2ftype_5fannotation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ftype_5fannotation_2eproto
#define googlesql_2fpublic_2fvalue_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fvalue_2eproto
#define descriptor_table_googlesql_2fpublic_2fvalue_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fvalue_2eproto
#define TableStruct_googlesql_2fpublic_2fvalue_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fvalue_2eproto
#define googlesql_2fpublic_2ftype_5fparameters_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fparameters_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fparameters_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ftype_5fparameters_2eproto
#define googlesql_2fpublic_2fcollation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fcollation_2eproto
#define descriptor_table_googlesql_2fpublic_2fcollation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fcollation_2eproto
#define TableStruct_googlesql_2fpublic_2fcollation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fcollation_2eproto
#define googlesql_2fpublic_2ftype_5fmodifiers_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ftype_5fmodifiers_2eproto
#define googlesql_2fpublic_2fformatter_5foptions_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2fformatter_5foptions_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_googlesql_2fpublic_2fformatter_5foptions_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fformatter_5foptions_2eproto
#define googlesql_2fpublic_2ferror_5flocation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ferror_5flocation_2eproto
#define googlesql_2fpublic_2fannotation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fannotation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fannotation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fannotation_2eproto
#define googlesql_2fpublic_2fsimple_5fvalue_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5fvalue_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5fvalue_2eproto
#define googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define descriptor_table_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define TableStruct_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffeature_5flabel_5fdictionary_2eproto
#define googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define descriptor_table_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define TableStruct_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fsimple_5ftoken_5flist_2eproto
#define googlesql_2fpublic_2ffix_5fsuggestion_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define descriptor_table_googlesql_2fpublic_2ffix_5fsuggestion_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define TableStruct_googlesql_2fpublic_2ffix_5fsuggestion_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffix_5fsuggestion_2eproto
#define googlesql_2fpublic_2ffunctions_2fdatetime_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2fdatetime_2eproto
#define googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2fbitwise_5fagg_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2funsupported_5ffields_2eproto
#define googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2frank_5ftype_2eproto
#define googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2ffunctions_2fmatch_5frecognize_2fcompiled_5fpattern_2eproto
#define googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define descriptor_table_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define TableStruct_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2finformation_5fschema_2fproperty_5fgraph_2eproto
#define googlesql_2fpublic_2fproto_2flogging_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2flogging_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2flogging_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fproto_2flogging_2eproto
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_common_builtin_function_internal_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto googlesql_common_builtin_function_internal_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto googlesql_common_builtin_function_internal_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto googlesql_common_builtin_function_internal_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define googlesql_2fresolved_5fast_2fresolved_5fast_2eproto googlesql_common_builtin_function_internal_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fresolved_5fast_2fresolved_5fast_2eproto
#define googlesql_2fresolved_5fast_2fserialization_2eproto googlesql_common_builtin_function_internal_googlesql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_googlesql_2fresolved_5fast_2fserialization_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_googlesql_2fresolved_5fast_2fserialization_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fresolved_5fast_2fserialization_2eproto
#define googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto googlesql_common_builtin_function_internal_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define googlesql_2fscripting_2fprocedure_5fextension_2eproto googlesql_common_builtin_function_internal_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_googlesql_2fscripting_2fprocedure_5fextension_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_googlesql_2fscripting_2fprocedure_5fextension_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fscripting_2fprocedure_5fextension_2eproto
#define googlesql_2fscripting_2fvariable_2eproto googlesql_common_builtin_function_internal_googlesql_2fscripting_2fvariable_2eproto
#define descriptor_table_googlesql_2fscripting_2fvariable_2eproto googlesql_common_builtin_function_internal_descriptor_table_googlesql_2fscripting_2fvariable_2eproto
#define TableStruct_googlesql_2fscripting_2fvariable_2eproto googlesql_common_builtin_function_internal_TableStruct_googlesql_2fscripting_2fvariable_2eproto
#define proto_2fconfidence_2dinterval_2eproto googlesql_common_builtin_function_internal_proto_2fconfidence_2dinterval_2eproto
#define descriptor_table_proto_2fconfidence_2dinterval_2eproto googlesql_common_builtin_function_internal_descriptor_table_proto_2fconfidence_2dinterval_2eproto
#define TableStruct_proto_2fconfidence_2dinterval_2eproto googlesql_common_builtin_function_internal_TableStruct_proto_2fconfidence_2dinterval_2eproto
#define proto_2fdata_2eproto googlesql_common_builtin_function_internal_proto_2fdata_2eproto
#define descriptor_table_proto_2fdata_2eproto googlesql_common_builtin_function_internal_descriptor_table_proto_2fdata_2eproto
#define TableStruct_proto_2fdata_2eproto googlesql_common_builtin_function_internal_TableStruct_proto_2fdata_2eproto
#define proto_2fnumerical_2dmechanism_2eproto googlesql_common_builtin_function_internal_proto_2fnumerical_2dmechanism_2eproto
#define descriptor_table_proto_2fnumerical_2dmechanism_2eproto googlesql_common_builtin_function_internal_descriptor_table_proto_2fnumerical_2dmechanism_2eproto
#define TableStruct_proto_2fnumerical_2dmechanism_2eproto googlesql_common_builtin_function_internal_TableStruct_proto_2fnumerical_2dmechanism_2eproto
#define proto_2fsummary_2eproto googlesql_common_builtin_function_internal_proto_2fsummary_2eproto
#define descriptor_table_proto_2fsummary_2eproto googlesql_common_builtin_function_internal_descriptor_table_proto_2fsummary_2eproto
#define TableStruct_proto_2fsummary_2eproto googlesql_common_builtin_function_internal_TableStruct_proto_2fsummary_2eproto

#define GO_EXPORT(def) export_googlesql_common_builtin_function_internal_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "googlesql/common/builtin_function_internal.h"
//#undef private

// include sources
#include "googlesql/common/builtin_enum_type.cc"
#include "googlesql/common/builtin_function_array.cc"
#include "googlesql/common/builtin_function_comparison.cc"
#include "googlesql/common/builtin_function_differential_privacy.cc"
#include "googlesql/common/builtin_function_distance.cc"
#include "googlesql/common/builtin_function_graph.cc"
#include "googlesql/common/builtin_function_internal_1.cc"
#include "googlesql/common/builtin_function_internal_2.cc"
#include "googlesql/common/builtin_function_internal_3.cc"
#include "googlesql/common/builtin_function_map.cc"
#include "googlesql/common/builtin_function_match_recognize.cc"
#include "googlesql/common/builtin_function_measure.cc"
#include "googlesql/common/builtin_function_range.cc"
#include "googlesql/common/builtin_function_sketches.cc"
#include "googlesql/common/builtin_function_time_series.cc"
#include "googlesql/common/builtin_tvfs.cc"

// include dependencies
#include "go-zetasql/common/builtins_output_properties/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/no_destructor/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/proto/anon_output_with_report_cc_proto/export.inc"
#include "go-zetasql/proto/options_cc_proto/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/anon_function/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/builtin_function_options/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/cycle_detector/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/annotation/collation/export.inc"
#include "go-zetasql/public/functions/array_zip_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/bitwise_agg_mode_cc_proto/export.inc"
#include "go-zetasql/public/functions/date_time_util/export.inc"
#include "go-zetasql/public/functions/datetime_cc_proto/export.inc"
#include "go-zetasql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-zetasql/public/functions/rank_type_cc_proto/export.inc"
#include "go-zetasql/public/functions/regexp/export.inc"
#include "go-zetasql/public/functions/string_format/export.inc"
#include "go-zetasql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/functional/bind_front/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-google/type/date_cc_proto/export.inc"
#include "go-google/type/timeofday_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_common_builtin_function_internal_bind_cc */
