#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_SET_OPERATION_CORRESPONDING_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_SET_OPERATION_CORRESPONDING_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/set_operation_corresponding_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/set_operation_corresponding_rewriter.cc"
// include dependencies
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"

#endif
