#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_GENERATE_ARRAY_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_FUNCTIONS_GENERATE_ARRAY_EXPORT_H

#include "googlesql/legacy_zetasql/public/functions/generate_array.h"
// include sources
// include dependencies
#include "go-googlesql/legacy_zetasql/public/functions/arithmetics/export.inc"
#include "go-googlesql/legacy_zetasql/public/functions/date_time_util/export.inc"
#include "go-googlesql/legacy_zetasql/public/functions/datetime_cc_proto/export.inc"
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/numeric_value/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/time/time/export.inc"

#endif
