#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_PROTO_FROM_ITERATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_PROTO_FROM_ITERATOR_EXPORT_H

#include "googlesql/legacy_zetasql/common/proto_from_iterator.h"
// include sources
#include "googlesql/legacy_zetasql/common/proto_from_iterator.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/evaluator_table_iterator/export.inc"
#include "go-googlesql/public/proto_value_conversion/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
