#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_REGISTER_ALL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_REGISTER_ALL_EXPORT_H

#include "googlesql/reference_impl/functions/register_all.h"
// include sources
#include "googlesql/reference_impl/functions/register_all.cc"
// include dependencies
#include "go-googlesql/reference_impl/functions/compression/export.inc"
#include "go-googlesql/reference_impl/functions/graph/export.inc"
#include "go-googlesql/reference_impl/functions/hash/export.inc"
#include "go-googlesql/reference_impl/functions/json/export.inc"
#include "go-googlesql/reference_impl/functions/map/export.inc"
#include "go-googlesql/reference_impl/functions/range/export.inc"
#include "go-googlesql/reference_impl/functions/string_with_collation/export.inc"
#include "go-googlesql/reference_impl/functions/uuid/export.inc"

#endif
