#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FEATURE_LABEL_EXTRACTOR_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FEATURE_LABEL_EXTRACTOR_EXPORT_H

#include "googlesql/public/feature_label_extractor.h"
// include sources
#include "googlesql/public/feature_label_extractor.cc"
// include dependencies
#include "go-zetasql/public/analyzer/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output_properties/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/feature_label_dictionary_proto_cc_proto/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/internal_analyzer_output_properties/export.inc"
#include "go-zetasql/compliance/compliance_label_cc_proto/export.inc"
#include "go-zetasql/compliance/compliance_label_extractor/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/target_syntax/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
