#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_COMPRESSION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_COMPRESSION_EXPORT_H

#include "googlesql/reference_impl/functions/compression.h"
// include sources
#include "googlesql/reference_impl/functions/compression.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/compression/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/reference_impl/evaluation/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#endif
