#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_UPDATE_CONSTRUCTOR_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_UPDATE_CONSTRUCTOR_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/update_constructor_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/update_constructor_rewriter.cc"
// include dependencies
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
