#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_BUILTIN_FUNCTION_OPTIONS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_BUILTIN_FUNCTION_OPTIONS_EXPORT_H

#include "zetasql/public/builtin_function_options.h"
// include sources
#include "zetasql/public/builtin_function_options.cc"
// include dependencies
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/proto/options_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/functional/bind_front/export.inc"

#endif
