#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_ORDER_BY_AND_LIMIT_IN_AGGREGATE_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_ORDER_BY_AND_LIMIT_IN_AGGREGATE_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/order_by_and_limit_in_aggregate_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/order_by_and_limit_in_aggregate_rewriter.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output_properties/export.inc"
#include "go-googlesql/public/builtin_function_cc_proto/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
