#ifndef googlesql_public_simple_catalog_bind_cc
#define googlesql_public_simple_catalog_bind_cc

#ifndef GOOGLESQL_LINK_ONLY_BIND

// switch namespace
#define differential_privacy googlesql_public_simple_catalog_differential_privacy
#define googlesql googlesql_public_simple_catalog_googlesql
#define googlesql_base googlesql_public_simple_catalog_googlesql_base
#define googlesql_bison_parser googlesql_public_simple_catalog_googlesql_bison_parser
#define re2 googlesql_public_simple_catalog_re2
#define AbslInternalSleepFor googlesql_public_simple_catalog_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_public_simple_catalog_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_public_simple_catalog_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_public_simple_catalog_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_public_simple_catalog_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_public_simple_catalog_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_public_simple_catalog_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_public_simple_catalog_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_public_simple_catalog_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_public_simple_catalog_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_public_simple_catalog_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_public_simple_catalog_GoogleSqlalloc
#define GoogleSqlfree googlesql_public_simple_catalog_GoogleSqlfree
#define GoogleSqlrealloc googlesql_public_simple_catalog_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_public_simple_catalog_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_public_simple_catalog_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_public_simple_catalog_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_public_simple_catalog_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_public_simple_catalog_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_public_simple_catalog_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_public_simple_catalog_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_public_simple_catalog_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_public_simple_catalog_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_public_simple_catalog_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_public_simple_catalog_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_public_simple_catalog_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_public_simple_catalog_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_public_simple_catalog_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_public_simple_catalog_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_public_simple_catalog_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_public_simple_catalog_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_public_simple_catalog_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_public_simple_catalog_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_public_simple_catalog_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_public_simple_catalog_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_public_simple_catalog_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_public_simple_catalog_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_public_simple_catalog_GoogleSqlFlexLexer
#define UCaseMap googlesql_public_simple_catalog_UCaseMap

#define GO_EXPORT(def) export_googlesql_public_simple_catalog_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/public/simple_catalog.h"
#include "googlesql/public/simple_property_graph.h"
#include "googlesql/public/table_from_proto.h"
//#undef private

// include sources
#include "googlesql/public/simple_catalog.cc"
#include "googlesql/public/simple_property_graph.cc"
#include "googlesql/public/table_from_proto.cc"

// include dependencies
#include "go-googlesql/public/builtin_function/export.inc"
#include "go-googlesql/public/builtin_function_options/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/constant/export.inc"
#include "go-googlesql/public/evaluator_table_iterator/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/simple_connection_cc_proto/export.inc"
#include "go-googlesql/public/simple_constant_cc_proto/export.inc"
#include "go-googlesql/public/simple_model_cc_proto/export.inc"
#include "go-googlesql/public/simple_sequence_cc_proto/export.inc"
#include "go-googlesql/public/simple_table_cc_proto/export.inc"
#include "go-googlesql/public/sql_view/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/case/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/clock/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/simple_evaluator_table_iterator/export.inc"
#include "go-googlesql/proto/simple_catalog_cc_proto/export.inc"
#include "go-googlesql/proto/simple_property_graph_cc_proto/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/public/sql_tvf/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#else /* GOOGLESQL_LINK_ONLY_BIND */

// Link-only bind.cc (no amalgamated .cc includes). Native implementations must come from prebuilt
// archives (e.g. libgooglesql.a) and match this package's exported bridge symbols.
// Enable per package via cclib.link_only_bind_packages in internal/cmd/generator/config.yaml.
// See docs/link-only-cgo-migration.md.
#define AbslInternalSleepFor googlesql_public_simple_catalog_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_public_simple_catalog_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_public_simple_catalog_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_public_simple_catalog_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_public_simple_catalog_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_public_simple_catalog_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_public_simple_catalog_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_public_simple_catalog_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_public_simple_catalog_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_public_simple_catalog_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_public_simple_catalog_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_public_simple_catalog_GoogleSqlalloc
#define GoogleSqlfree googlesql_public_simple_catalog_GoogleSqlfree
#define GoogleSqlrealloc googlesql_public_simple_catalog_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_public_simple_catalog_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_public_simple_catalog_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_public_simple_catalog_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_public_simple_catalog_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_public_simple_catalog_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_public_simple_catalog_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_public_simple_catalog_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_public_simple_catalog_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_public_simple_catalog_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_public_simple_catalog_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_public_simple_catalog_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_public_simple_catalog_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_public_simple_catalog_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_public_simple_catalog_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_public_simple_catalog_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_public_simple_catalog_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_public_simple_catalog_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_public_simple_catalog_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_public_simple_catalog_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_public_simple_catalog_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_public_simple_catalog_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_public_simple_catalog_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_public_simple_catalog_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_public_simple_catalog_GoogleSqlFlexLexer
#define UCaseMap googlesql_public_simple_catalog_UCaseMap

#define GO_EXPORT(def) export_googlesql_public_simple_catalog_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers (types only; no .cc bodies)
#include "googlesql/public/simple_catalog.h"
#include "googlesql/public/simple_property_graph.h"
#include "googlesql/public/table_from_proto.h"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* GOOGLESQL_LINK_ONLY_BIND */

#endif /* googlesql_public_simple_catalog_bind_cc */
