#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_LOG_MESSAGE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_LOG_MESSAGE_EXPORT_H

#include "absl/log/internal/log_message.h"
// include sources
#include "absl/log/internal/log_message.cc"
// include dependencies
#include "go-absl/log/go_internal/append_truncated/export.inc"
#include "go-absl/log/go_internal/format/export.inc"
#include "go-absl/log/go_internal/globals/export.inc"
#include "go-absl/log/go_internal/log_sink_set/export.inc"
#include "go-absl/log/go_internal/nullguard/export.inc"
#include "go-absl/log/go_internal/proto/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/errno_saver/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/base/strerror/export.inc"
#include "go-absl/container/inlined_vector/export.inc"
#include "go-absl/debugging/examine_stack/export.inc"
#include "go-absl/log/globals/export.inc"
#include "go-absl/log/log_entry/export.inc"
#include "go-absl/log/log_sink/export.inc"
#include "go-absl/log/log_sink_registry/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"

#endif
