#ifndef INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_DIAGNOSTIC_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PARSER_MACROS_DIAGNOSTIC_EXPORT_H

#include "googlesql/parser/macros/diagnostic.h"
// include sources
#include "googlesql/parser/macros/diagnostic.cc"
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/parser/token_with_location/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
