#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_REFERENCE_IMPL_REWRITE_FLAGS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_REFERENCE_IMPL_REWRITE_FLAGS_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/rewrite_flags.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/rewrite_flags.cc"
// include dependencies
#include "go-zetasql/common/options_utils/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
