
#ifndef absl_container_hash_container_defaults_bind_cc
#define absl_container_hash_container_defaults_bind_cc

// switch namespace
#define differential_privacy absl_container_hash_container_defaults_differential_privacy
#define googlesql absl_container_hash_container_defaults_googlesql
#define googlesql_base absl_container_hash_container_defaults_googlesql_base
#define googlesql_bison_parser absl_container_hash_container_defaults_googlesql_bison_parser
#define re2 absl_container_hash_container_defaults_re2
#define AbslInternalSleepFor absl_container_hash_container_defaults_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_container_hash_container_defaults_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_container_hash_container_defaults_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_container_hash_container_defaults_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_container_hash_container_defaults_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_container_hash_container_defaults_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_container_hash_container_defaults_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_container_hash_container_defaults_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_container_hash_container_defaults_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_container_hash_container_defaults_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_container_hash_container_defaults_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_container_hash_container_defaults_GoogleSqlalloc
#define GoogleSqlfree absl_container_hash_container_defaults_GoogleSqlfree
#define GoogleSqlrealloc absl_container_hash_container_defaults_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_container_hash_container_defaults_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_container_hash_container_defaults_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_container_hash_container_defaults_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_container_hash_container_defaults_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_container_hash_container_defaults_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_container_hash_container_defaults_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_container_hash_container_defaults_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_container_hash_container_defaults_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_container_hash_container_defaults_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_container_hash_container_defaults_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_container_hash_container_defaults_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_container_hash_container_defaults_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_container_hash_container_defaults_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_container_hash_container_defaults_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_container_hash_container_defaults_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_container_hash_container_defaults_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_container_hash_container_defaults_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_container_hash_container_defaults_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_container_hash_container_defaults_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_container_hash_container_defaults_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_container_hash_container_defaults_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_container_hash_container_defaults_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_container_hash_container_defaults_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_container_hash_container_defaults_GoogleSqlFlexLexer
#define UCaseMap absl_container_hash_container_defaults_UCaseMap

#define GO_EXPORT(def) export_absl_container_hash_container_defaults_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/container/hash_container_defaults.h"
//#undef private

// include sources

// include dependencies
#include "go-absl/container/hash_function_defaults/export.inc"
#include "go-absl/base/config/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_container_hash_container_defaults_bind_cc */
