#ifndef INTERNAL_CCALL_GO_ABSL_BASE_BASE_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_BASE_BASE_INTERNAL_EXPORT_H

#include "absl/base/internal/hide_ptr.h"
#include "absl/base/internal/identity.h"
#include "absl/base/internal/inline_variable.h"
#include "absl/base/internal/invoke.h"
#include "absl/base/internal/scheduling_mode.h"
// include sources
// include dependencies
#include "go-absl/base/config/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#endif
