#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_UUID_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_UUID_EXPORT_H

#include "zetasql/public/functions/uuid.h"
// include sources
#include "zetasql/public/functions/uuid.cc"
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/uuid_value/export.inc"
#include "go-absl/random/random/export.inc"
#include "go-absl/random/bit_gen_ref/export.inc"

#endif
