#ifndef INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_TYPE_PARAMETER_CONSTRAINTS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_REFERENCE_IMPL_TYPE_PARAMETER_CONSTRAINTS_EXPORT_H

#include "zetasql/reference_impl/type_parameter_constraints.h"
// include sources
#include "zetasql/reference_impl/type_parameter_constraints.cc"
// include dependencies
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/numeric_value/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/string/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
