#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_UTF_UTIL_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_UTF_UTIL_EXPORT_H

#include "googlesql/legacy_zetasql/common/utf_util.h"
// include sources
#include "googlesql/legacy_zetasql/common/utf_util.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"
#include "go-icu/icu/export.inc"

#endif
