#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_FORMATTER_OPTIONS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PUBLIC_FORMATTER_OPTIONS_EXPORT_H

#include "googlesql/legacy_zetasql/public/formatter_options.h"
// include sources
#include "googlesql/legacy_zetasql/public/formatter_options.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/public/formatter_options_cc_proto/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
