
#ifndef googlesql_analyzer_analyzer_impl_bind_cc
#define googlesql_analyzer_analyzer_impl_bind_cc

// switch namespace
#define differential_privacy googlesql_analyzer_analyzer_impl_differential_privacy
#define googlesql googlesql_analyzer_analyzer_impl_googlesql
#define googlesql_base googlesql_analyzer_analyzer_impl_googlesql_base
#define googlesql_bison_parser googlesql_analyzer_analyzer_impl_googlesql_bison_parser
#define re2 googlesql_analyzer_analyzer_impl_re2
#define AbslInternalSleepFor googlesql_analyzer_analyzer_impl_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_analyzer_analyzer_impl_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_analyzer_analyzer_impl_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_analyzer_analyzer_impl_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_analyzer_analyzer_impl_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_analyzer_analyzer_impl_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_analyzer_analyzer_impl_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_analyzer_analyzer_impl_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_analyzer_analyzer_impl_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_analyzer_analyzer_impl_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_analyzer_analyzer_impl_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_analyzer_analyzer_impl_GoogleSqlalloc
#define GoogleSqlfree googlesql_analyzer_analyzer_impl_GoogleSqlfree
#define GoogleSqlrealloc googlesql_analyzer_analyzer_impl_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_analyzer_analyzer_impl_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_analyzer_analyzer_impl_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_analyzer_analyzer_impl_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_analyzer_analyzer_impl_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_analyzer_analyzer_impl_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_analyzer_analyzer_impl_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_analyzer_analyzer_impl_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_analyzer_analyzer_impl_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_analyzer_analyzer_impl_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_analyzer_analyzer_impl_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_analyzer_analyzer_impl_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_analyzer_analyzer_impl_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_analyzer_analyzer_impl_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_analyzer_analyzer_impl_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_analyzer_analyzer_impl_GoogleSqlFlexLexer
#define UCaseMap googlesql_analyzer_analyzer_impl_UCaseMap

#define GO_EXPORT(def) export_googlesql_analyzer_analyzer_impl_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/analyzer/analyzer_impl.h"
//#undef private

// include sources
#include "googlesql/analyzer/analyzer_impl.cc"

// include dependencies
#include "go-googlesql/analyzer/analyzer_output_mutator/export.inc"
#include "go-googlesql/analyzer/resolver/export.inc"
#include "go-googlesql/analyzer/rewrite_resolved_ast/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/internal_analyzer_options/export.inc"
#include "go-googlesql/common/timer_util/export.inc"
#include "go-googlesql/parser/parser/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/analyzer_output/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/error_helpers/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/validator/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_analyzer_analyzer_impl_bind_cc */
