#ifndef INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_ERROR_HELPERS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_SCRIPTING_ERROR_HELPERS_EXPORT_H

#include "zetasql/scripting/error_helpers.h"
// include sources
#include "zetasql/scripting/error_helpers.cc"
// include dependencies
#include "go-zetasql/scripting/script_exception_cc_proto/export.inc"
#include "go-zetasql/scripting/script_segment/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/parser/parser/export.inc"
#include "go-zetasql/public/error_location_cc_proto/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
