#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SQL_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_SQL_FUNCTION_EXPORT_H

#include "zetasql/public/sql_function.h"
// include sources
#include "zetasql/public/sql_function.cc"
// include dependencies
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/parse_resume_location/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
