#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SQL_FUNCTION_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_SQL_FUNCTION_EXPORT_H

#include "googlesql/public/sql_function.h"
// include sources
#include "googlesql/public/sql_function.cc"
// include dependencies
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/function_cc_proto/export.inc"
#include "go-googlesql/public/parse_resume_location/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"

#endif
