#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_HANDLE_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_CORDZ_HANDLE_EXPORT_H

#include "absl/strings/internal/cordz_handle.h"
// include sources
#include "absl/strings/internal/cordz_handle.cc"
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
