
#ifndef zetasql_reference_impl_reference_driver_bind_cc
#define zetasql_reference_impl_reference_driver_bind_cc

// switch namespace
#define absl zetasql_reference_impl_reference_driver_absl
#define differential_privacy zetasql_reference_impl_reference_driver_differential_privacy
#define google zetasql_reference_impl_reference_driver_google
#define zetasql zetasql_reference_impl_reference_driver_zetasql
#define zetasql_base zetasql_reference_impl_reference_driver_zetasql_base
#define zetasql_bison_parser zetasql_reference_impl_reference_driver_zetasql_bison_parser
#define re2 zetasql_reference_impl_reference_driver_re2
#define AbslInternalSleepFor zetasql_reference_impl_reference_driver_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError zetasql_reference_impl_reference_driver_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield zetasql_reference_impl_reference_driver_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost zetasql_reference_impl_reference_driver_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait zetasql_reference_impl_reference_driver_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything zetasql_reference_impl_reference_driver_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay zetasql_reference_impl_reference_driver_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake zetasql_reference_impl_reference_driver_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin zetasql_reference_impl_reference_driver_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd zetasql_reference_impl_reference_driver_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint zetasql_reference_impl_reference_driver_AbslInternalGetFileMappingHint
#define ZetaSqlalloc zetasql_reference_impl_reference_driver_ZetaSqlalloc
#define ZetaSqlfree zetasql_reference_impl_reference_driver_ZetaSqlfree
#define ZetaSqlrealloc zetasql_reference_impl_reference_driver_ZetaSqlrealloc
#define FLAGS_nooutput_asc_explicitly zetasql_reference_impl_reference_driver_FLAGS_nooutput_asc_explicitly
#define FLAGS_nozetasql_use_customized_flex_istream zetasql_reference_impl_reference_driver_FLAGS_nozetasql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly zetasql_reference_impl_reference_driver_FLAGS_output_asc_explicitly
#define FLAGS_zetasql_use_customized_flex_istream zetasql_reference_impl_reference_driver_FLAGS_zetasql_use_customized_flex_istream
#define FLAGS_zetasql_type_factory_nesting_depth_limit zetasql_reference_impl_reference_driver_FLAGS_zetasql_type_factory_nesting_depth_limit
#define FLAGS_zetasql_read_proto_field_optimized_path zetasql_reference_impl_reference_driver_FLAGS_zetasql_read_proto_field_optimized_path
#define FLAGS_zetasql_format_max_output_width zetasql_reference_impl_reference_driver_FLAGS_zetasql_format_max_output_width
#define FLAGS_zetasql_min_length_required_for_edit_distance zetasql_reference_impl_reference_driver_FLAGS_zetasql_min_length_required_for_edit_distance
#define FLAGS_zetasql_simple_iterator_call_time_now_rows_period zetasql_reference_impl_reference_driver_FLAGS_zetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_nozetasql_type_factory_nesting_depth_limit zetasql_reference_impl_reference_driver_FLAGS_nozetasql_type_factory_nesting_depth_limit
#define FLAGS_nozetasql_read_proto_field_optimized_path zetasql_reference_impl_reference_driver_FLAGS_nozetasql_read_proto_field_optimized_path
#define FLAGS_nozetasql_format_max_output_width zetasql_reference_impl_reference_driver_FLAGS_nozetasql_format_max_output_width
#define FLAGS_nozetasql_min_length_required_for_edit_distance zetasql_reference_impl_reference_driver_FLAGS_nozetasql_min_length_required_for_edit_distance
#define FLAGS_nozetasql_simple_iterator_call_time_now_rows_period zetasql_reference_impl_reference_driver_FLAGS_nozetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_zetasql_enough_stack_bytes zetasql_reference_impl_reference_driver_FLAGS_zetasql_enough_stack_bytes
#define FLAGS_nozetasql_enough_stack_bytes zetasql_reference_impl_reference_driver_FLAGS_nozetasql_enough_stack_bytes
#define FLAGS_zetasql_canonicalize_signed_zero_to_string zetasql_reference_impl_reference_driver_FLAGS_zetasql_canonicalize_signed_zero_to_string
#define FLAGS_nozetasql_canonicalize_signed_zero_to_string zetasql_reference_impl_reference_driver_FLAGS_nozetasql_canonicalize_signed_zero_to_string
#define ZetaSqlFlexTokenizerBase zetasql_reference_impl_reference_driver_ZetaSqlFlexTokenizerBase
#define ZetaSqlFlexLexer zetasql_reference_impl_reference_driver_ZetaSqlFlexLexer
#define UCaseMap zetasql_reference_impl_reference_driver_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto zetasql_reference_impl_reference_driver_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto zetasql_reference_impl_reference_driver_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto zetasql_reference_impl_reference_driver_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto zetasql_reference_impl_reference_driver_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto zetasql_reference_impl_reference_driver_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto zetasql_reference_impl_reference_driver_TableStruct_google_2ftype_2ftimeofday_2eproto
#define zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define zetasql_2fparser_2fparse_5ftree_2eproto zetasql_reference_impl_reference_driver_zetasql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto
#define zetasql_2fparser_2fast_5fenums_2eproto zetasql_reference_impl_reference_driver_zetasql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto
#define TableStruct_zetasql_2fparser_2fast_5fenums_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fparser_2fast_5fenums_2eproto
#define zetasql_2fproto_2foptions_2eproto zetasql_reference_impl_reference_driver_zetasql_2fproto_2foptions_2eproto
#define descriptor_table_zetasql_2fproto_2foptions_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fproto_2foptions_2eproto
#define TableStruct_zetasql_2fproto_2foptions_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fproto_2foptions_2eproto
#define zetasql_2fproto_2fsimple_5fcatalog_2eproto zetasql_reference_impl_reference_driver_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define zetasql_2fproto_2ffunction_2eproto zetasql_reference_impl_reference_driver_zetasql_2fproto_2ffunction_2eproto
#define descriptor_table_zetasql_2fproto_2ffunction_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fproto_2ffunction_2eproto
#define TableStruct_zetasql_2fproto_2ffunction_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fproto_2ffunction_2eproto
#define zetasql_2fproto_2finternal_5ferror_5flocation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto zetasql_reference_impl_reference_driver_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto zetasql_reference_impl_reference_driver_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define zetasql_2fpublic_2fbuiltin_5ffunction_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define zetasql_2fpublic_2fdeprecation_5fwarning_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define zetasql_2fpublic_2ffunction_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunction_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2ffunction_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunction_2eproto
#define zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define zetasql_2fpublic_2foptions_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2foptions_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2foptions_2eproto
#define TableStruct_zetasql_2fpublic_2foptions_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2foptions_2eproto
#define zetasql_2fpublic_2fsimple_5ftable_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define zetasql_2fpublic_2fsimple_5fconstant_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define zetasql_2fpublic_2fsimple_5fconnection_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconnection_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconnection_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fsimple_5fconnection_2eproto
#define zetasql_2fpublic_2fsimple_5fmodel_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fmodel_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fmodel_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fsimple_5fmodel_2eproto
#define zetasql_2fpublic_2fparse_5flocation_5frange_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define zetasql_2fpublic_2ftype_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ftype_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ftype_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ftype_2eproto
#define zetasql_2fpublic_2ftype_5fannotation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define zetasql_2fpublic_2fvalue_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fvalue_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fvalue_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fvalue_2eproto
#define zetasql_2fpublic_2ftype_5fparameters_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define zetasql_2fpublic_2fcollation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fcollation_2eproto
#define descriptor_table_zetasql_2fpublic_2fcollation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fcollation_2eproto
#define TableStruct_zetasql_2fpublic_2fcollation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fcollation_2eproto
#define zetasql_2fpublic_2ftype_5fmodifiers_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define zetasql_2fpublic_2fformatter_5foptions_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define zetasql_2fpublic_2ferror_5flocation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto
#define zetasql_2fpublic_2fannotation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fannotation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fannotation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fannotation_2eproto
#define zetasql_2fpublic_2fsimple_5fvalue_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define zetasql_2fpublic_2ffunctions_2fdatetime_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2ffunctions_2frange_5fsessionize_5fmode_2eproto
#define zetasql_2fpublic_2fproto_2flogging_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto
#define zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto zetasql_reference_impl_reference_driver_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto zetasql_reference_impl_reference_driver_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto zetasql_reference_impl_reference_driver_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto zetasql_reference_impl_reference_driver_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_2eproto zetasql_reference_impl_reference_driver_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define zetasql_2fresolved_5fast_2fserialization_2eproto zetasql_reference_impl_reference_driver_zetasql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto
#define zetasql_2fscripting_2fscript_5fexception_2eproto zetasql_reference_impl_reference_driver_zetasql_2fscripting_2fscript_5fexception_2eproto
#define descriptor_table_zetasql_2fscripting_2fscript_5fexception_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fscripting_2fscript_5fexception_2eproto
#define TableStruct_zetasql_2fscripting_2fscript_5fexception_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fscripting_2fscript_5fexception_2eproto
#define zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto zetasql_reference_impl_reference_driver_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define zetasql_2fscripting_2fprocedure_5fextension_2eproto zetasql_reference_impl_reference_driver_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define zetasql_2fscripting_2fvariable_2eproto zetasql_reference_impl_reference_driver_zetasql_2fscripting_2fvariable_2eproto
#define descriptor_table_zetasql_2fscripting_2fvariable_2eproto zetasql_reference_impl_reference_driver_descriptor_table_zetasql_2fscripting_2fvariable_2eproto
#define TableStruct_zetasql_2fscripting_2fvariable_2eproto zetasql_reference_impl_reference_driver_TableStruct_zetasql_2fscripting_2fvariable_2eproto
#define proto_2fconfidence_2dinterval_2eproto zetasql_reference_impl_reference_driver_proto_2fconfidence_2dinterval_2eproto
#define descriptor_table_proto_2fconfidence_2dinterval_2eproto zetasql_reference_impl_reference_driver_descriptor_table_proto_2fconfidence_2dinterval_2eproto
#define TableStruct_proto_2fconfidence_2dinterval_2eproto zetasql_reference_impl_reference_driver_TableStruct_proto_2fconfidence_2dinterval_2eproto
#define proto_2fdata_2eproto zetasql_reference_impl_reference_driver_proto_2fdata_2eproto
#define descriptor_table_proto_2fdata_2eproto zetasql_reference_impl_reference_driver_descriptor_table_proto_2fdata_2eproto
#define TableStruct_proto_2fdata_2eproto zetasql_reference_impl_reference_driver_TableStruct_proto_2fdata_2eproto
#define proto_2fnumerical_2dmechanism_2eproto zetasql_reference_impl_reference_driver_proto_2fnumerical_2dmechanism_2eproto
#define descriptor_table_proto_2fnumerical_2dmechanism_2eproto zetasql_reference_impl_reference_driver_descriptor_table_proto_2fnumerical_2dmechanism_2eproto
#define TableStruct_proto_2fnumerical_2dmechanism_2eproto zetasql_reference_impl_reference_driver_TableStruct_proto_2fnumerical_2dmechanism_2eproto
#define proto_2fsummary_2eproto zetasql_reference_impl_reference_driver_proto_2fsummary_2eproto
#define descriptor_table_proto_2fsummary_2eproto zetasql_reference_impl_reference_driver_descriptor_table_proto_2fsummary_2eproto
#define TableStruct_proto_2fsummary_2eproto zetasql_reference_impl_reference_driver_TableStruct_proto_2fsummary_2eproto

#define GO_EXPORT(def) export_zetasql_reference_impl_reference_driver_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "zetasql/reference_impl/reference_driver.h"
//#undef private

// include sources
#include "zetasql/reference_impl/reference_driver.cc"

// include dependencies
#include "go-zetasql/reference_impl/algebrizer/export.inc"
#include "go-zetasql/reference_impl/common/export.inc"
#include "go-zetasql/reference_impl/evaluation/export.inc"
#include "go-zetasql/reference_impl/parameters/export.inc"
#include "go-zetasql/reference_impl/rewrite_flags/export.inc"
#include "go-zetasql/reference_impl/statement_evaluator/export.inc"
#include "go-zetasql/reference_impl/type_helpers/export.inc"
#include "go-zetasql/analyzer/resolver/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/evaluator_registration_utils/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/compliance/test_database_catalog/export.inc"
#include "go-zetasql/compliance/test_driver/export.inc"
#include "go-zetasql/public/analyzer/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/analyzer_output/export.inc"
#include "go-zetasql/public/error_helpers/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/multi_catalog/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/simple_catalog/export.inc"
#include "go-zetasql/public/simple_catalog_util/export.inc"
#include "go-zetasql/public/sql_function/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/annotation/collation/export.inc"
#include "go-zetasql/public/functions/date_time_util/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-zetasql/scripting/error_helpers/export.inc"
#include "go-zetasql/scripting/script_executor/export.inc"
#include "go-zetasql/scripting/type_aliases/export.inc"
#include "go-zetasql/testing/test_value/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-protobuf/protobuf/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* zetasql_reference_impl_reference_driver_bind_cc */
