#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_SCOPE_ERROR_CATALOG_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_SCOPE_ERROR_CATALOG_EXPORT_H

#include "googlesql/common/scope_error_catalog.h"
// include sources
#include "googlesql/common/scope_error_catalog.cc"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/types/span/export.inc"

#endif
