#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_MATCH_RECOGNIZE_COMPILED_NFA_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_MATCH_RECOGNIZE_COMPILED_NFA_EXPORT_H

#include "googlesql/common/match_recognize/compiled_nfa.h"
// include sources
#include "googlesql/common/match_recognize/compiled_nfa.cc"
// include dependencies
#include "go-googlesql/common/match_recognize/nfa/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/functions/match_recognize/compiled_pattern_cc_proto/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
