
#ifndef googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_bind_cc
#define googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_bind_cc

// switch namespace
#define differential_privacy googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_differential_privacy
#define googlesql googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_googlesql
#define googlesql_base googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_googlesql_base
#define googlesql_bison_parser googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_googlesql_bison_parser
#define re2 googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_re2
#define AbslInternalSleepFor googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_GoogleSqlalloc
#define GoogleSqlfree googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_GoogleSqlfree
#define GoogleSqlrealloc googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_GoogleSqlFlexLexer
#define UCaseMap googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_UCaseMap

#define GO_EXPORT(def) export_googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/legacy_zetasql/analyzer/rewriters/anonymization_helper.h"
//#undef private

// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/anonymization_helper.cc"

// include dependencies
#include "go-zetasql/analyzer/expr_matching_helpers/export.inc"
#include "go-zetasql/analyzer/resolver/export.inc"
#include "go-zetasql/analyzer/rewriters/privacy/approx_count_distinct_utility/export.inc"
#include "go-zetasql/analyzer/rewriters/privacy/privacy_utility/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/proto/anon_output_with_report_cc_proto/export.inc"
#include "go-zetasql/proto/internal_error_location_cc_proto/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/anon_function/export.inc"
#include "go-zetasql/public/anonymization_utils/export.inc"
#include "go-zetasql/public/builtin_function/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/language_options/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/column_factory/export.inc"
#include "go-zetasql/resolved_ast/make_node_vector/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-zetasql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/str_format/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_legacy_zetasql_analyzer_rewriters_anonymization_helper_bind_cc */
