
#ifndef absl_random_internal_randen_bind_cc
#define absl_random_internal_randen_bind_cc

// switch namespace
#define differential_privacy absl_random_internal_randen_differential_privacy
#define googlesql absl_random_internal_randen_googlesql
#define googlesql_base absl_random_internal_randen_googlesql_base
#define googlesql_bison_parser absl_random_internal_randen_googlesql_bison_parser
#define re2 absl_random_internal_randen_re2
#define AbslInternalSleepFor absl_random_internal_randen_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_random_internal_randen_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_random_internal_randen_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_random_internal_randen_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_random_internal_randen_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_random_internal_randen_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_random_internal_randen_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_random_internal_randen_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_random_internal_randen_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_random_internal_randen_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_random_internal_randen_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_random_internal_randen_GoogleSqlalloc
#define GoogleSqlfree absl_random_internal_randen_GoogleSqlfree
#define GoogleSqlrealloc absl_random_internal_randen_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_random_internal_randen_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_random_internal_randen_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_random_internal_randen_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_random_internal_randen_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_random_internal_randen_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_random_internal_randen_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_random_internal_randen_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_random_internal_randen_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_random_internal_randen_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_random_internal_randen_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_random_internal_randen_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_random_internal_randen_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_random_internal_randen_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_random_internal_randen_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_random_internal_randen_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_random_internal_randen_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_random_internal_randen_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_random_internal_randen_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_random_internal_randen_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_random_internal_randen_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_random_internal_randen_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_random_internal_randen_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_random_internal_randen_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_random_internal_randen_GoogleSqlFlexLexer
#define UCaseMap absl_random_internal_randen_UCaseMap

#define GO_EXPORT(def) export_absl_random_internal_randen_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/random/internal/randen.h"
//#undef private

// include sources
#include "absl/random/internal/randen.cc"

// include dependencies
#include "go-absl/random/go_internal/platform/export.inc"
#include "go-absl/random/go_internal/randen_hwaes/export.inc"
#include "go-absl/random/go_internal/randen_slow/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_random_internal_randen_bind_cc */
