#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_SET_OPERATION_CORRESPONDING_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_SET_OPERATION_CORRESPONDING_REWRITER_EXPORT_H

#include "zetasql/analyzer/rewriters/set_operation_corresponding_rewriter.h"
// include sources
#include "zetasql/analyzer/rewriters/set_operation_corresponding_rewriter.cc"
// include dependencies
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-zetasql/resolved_ast/rewrite_utils/export.inc"

#endif
