#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_CATALOG_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_CATALOG_EXPORT_H

#include "zetasql/public/catalog.h"
#include "zetasql/public/catalog_helper.h"
// include sources
#include "zetasql/public/catalog.cc"
#include "zetasql/public/catalog_helper.cc"
// include dependencies
#include "go-zetasql/public/evaluator_table_iterator/export.inc"
#include "go-zetasql/public/strings/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/edit_distance/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/source_location/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/functional/function_ref/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-absl/types/variant/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
