#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ID_STRING_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_ID_STRING_EXPORT_H

#include "zetasql/public/id_string.h"
// include sources
#include "zetasql/public/id_string.cc"
// include dependencies
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/arena/export.inc"
#include "go-zetasql/base/case/export.inc"
#include "go-zetasql/base/endian/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
