#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_MEASURE_TYPE_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_REWRITERS_MEASURE_TYPE_REWRITER_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/rewriters/measure_type_rewriter.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/rewriters/measure_type_rewriter.cc"
#include "googlesql/legacy_zetasql/analyzer/rewriters/measure_type_rewriter_util.cc"
#include "googlesql/legacy_zetasql/analyzer/rewriters/measure_type_rewriter_util.h"
// include dependencies
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/function_headers/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/column_factory/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-zetasql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
