
#ifndef base_status_bind_cc
#define base_status_bind_cc

// switch namespace
#define absl base_status_absl
#define differential_privacy base_status_differential_privacy
#define google base_status_google
#define zetasql base_status_zetasql
#define zetasql_base base_status_zetasql_base
#define zetasql_bison_parser base_status_zetasql_bison_parser
#define re2 base_status_re2
#define AbslInternalSleepFor base_status_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError base_status_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield base_status_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost base_status_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait base_status_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything base_status_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay base_status_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake base_status_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin base_status_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd base_status_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint base_status_AbslInternalGetFileMappingHint
#define ZetaSqlalloc base_status_ZetaSqlalloc
#define ZetaSqlfree base_status_ZetaSqlfree
#define ZetaSqlrealloc base_status_ZetaSqlrealloc
#define FLAGS_nooutput_asc_explicitly base_status_FLAGS_nooutput_asc_explicitly
#define FLAGS_nozetasql_use_customized_flex_istream base_status_FLAGS_nozetasql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly base_status_FLAGS_output_asc_explicitly
#define FLAGS_zetasql_use_customized_flex_istream base_status_FLAGS_zetasql_use_customized_flex_istream
#define FLAGS_zetasql_type_factory_nesting_depth_limit base_status_FLAGS_zetasql_type_factory_nesting_depth_limit
#define FLAGS_zetasql_read_proto_field_optimized_path base_status_FLAGS_zetasql_read_proto_field_optimized_path
#define FLAGS_zetasql_format_max_output_width base_status_FLAGS_zetasql_format_max_output_width
#define FLAGS_zetasql_min_length_required_for_edit_distance base_status_FLAGS_zetasql_min_length_required_for_edit_distance
#define FLAGS_zetasql_simple_iterator_call_time_now_rows_period base_status_FLAGS_zetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_nozetasql_type_factory_nesting_depth_limit base_status_FLAGS_nozetasql_type_factory_nesting_depth_limit
#define FLAGS_nozetasql_read_proto_field_optimized_path base_status_FLAGS_nozetasql_read_proto_field_optimized_path
#define FLAGS_nozetasql_format_max_output_width base_status_FLAGS_nozetasql_format_max_output_width
#define FLAGS_nozetasql_min_length_required_for_edit_distance base_status_FLAGS_nozetasql_min_length_required_for_edit_distance
#define FLAGS_nozetasql_simple_iterator_call_time_now_rows_period base_status_FLAGS_nozetasql_simple_iterator_call_time_now_rows_period
#define FLAGS_zetasql_enough_stack_bytes base_status_FLAGS_zetasql_enough_stack_bytes
#define FLAGS_nozetasql_enough_stack_bytes base_status_FLAGS_nozetasql_enough_stack_bytes
#define FLAGS_zetasql_canonicalize_signed_zero_to_string base_status_FLAGS_zetasql_canonicalize_signed_zero_to_string
#define FLAGS_nozetasql_canonicalize_signed_zero_to_string base_status_FLAGS_nozetasql_canonicalize_signed_zero_to_string
#define ZetaSqlFlexTokenizerBase base_status_ZetaSqlFlexTokenizerBase
#define ZetaSqlFlexLexer base_status_ZetaSqlFlexLexer
#define UCaseMap base_status_UCaseMap
#define google_2fprotobuf_2fdescriptor_2eproto base_status_google_2fprotobuf_2fdescriptor_2eproto
#define descriptor_table_google_2fprotobuf_2fdescriptor_2eproto base_status_descriptor_table_google_2fprotobuf_2fdescriptor_2eproto
#define TableStruct_google_2fprotobuf_2fdescriptor_2eproto base_status_TableStruct_google_2fprotobuf_2fdescriptor_2eproto
#define google_2fprotobuf_2ftimestamp_2eproto base_status_google_2fprotobuf_2ftimestamp_2eproto
#define descriptor_table_google_2fprotobuf_2ftimestamp_2eproto base_status_descriptor_table_google_2fprotobuf_2ftimestamp_2eproto
#define TableStruct_google_2fprotobuf_2ftimestamp_2eproto base_status_TableStruct_google_2fprotobuf_2ftimestamp_2eproto
#define google_2fprotobuf_2fany_2eproto base_status_google_2fprotobuf_2fany_2eproto
#define descriptor_table_google_2fprotobuf_2fany_2eproto base_status_descriptor_table_google_2fprotobuf_2fany_2eproto
#define TableStruct_google_2fprotobuf_2fany_2eproto base_status_TableStruct_google_2fprotobuf_2fany_2eproto
#define google_2fprotobuf_2fapi_2eproto base_status_google_2fprotobuf_2fapi_2eproto
#define descriptor_table_google_2fprotobuf_2fapi_2eproto base_status_descriptor_table_google_2fprotobuf_2fapi_2eproto
#define TableStruct_google_2fprotobuf_2fapi_2eproto base_status_TableStruct_google_2fprotobuf_2fapi_2eproto
#define google_2fprotobuf_2fduration_2eproto base_status_google_2fprotobuf_2fduration_2eproto
#define descriptor_table_google_2fprotobuf_2fduration_2eproto base_status_descriptor_table_google_2fprotobuf_2fduration_2eproto
#define TableStruct_google_2fprotobuf_2fduration_2eproto base_status_TableStruct_google_2fprotobuf_2fduration_2eproto
#define google_2fprotobuf_2fempty_2eproto base_status_google_2fprotobuf_2fempty_2eproto
#define descriptor_table_google_2fprotobuf_2fempty_2eproto base_status_descriptor_table_google_2fprotobuf_2fempty_2eproto
#define TableStruct_google_2fprotobuf_2fempty_2eproto base_status_TableStruct_google_2fprotobuf_2fempty_2eproto
#define google_2fprotobuf_2ffield_5fmask_2eproto base_status_google_2fprotobuf_2ffield_5fmask_2eproto
#define descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto base_status_descriptor_table_google_2fprotobuf_2ffield_5fmask_2eproto
#define TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto base_status_TableStruct_google_2fprotobuf_2ffield_5fmask_2eproto
#define google_2fprotobuf_2fsource_5fcontext_2eproto base_status_google_2fprotobuf_2fsource_5fcontext_2eproto
#define descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto base_status_descriptor_table_google_2fprotobuf_2fsource_5fcontext_2eproto
#define TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto base_status_TableStruct_google_2fprotobuf_2fsource_5fcontext_2eproto
#define google_2fprotobuf_2fstruct_2eproto base_status_google_2fprotobuf_2fstruct_2eproto
#define descriptor_table_google_2fprotobuf_2fstruct_2eproto base_status_descriptor_table_google_2fprotobuf_2fstruct_2eproto
#define TableStruct_google_2fprotobuf_2fstruct_2eproto base_status_TableStruct_google_2fprotobuf_2fstruct_2eproto
#define google_2fprotobuf_2ftype_2eproto base_status_google_2fprotobuf_2ftype_2eproto
#define descriptor_table_google_2fprotobuf_2ftype_2eproto base_status_descriptor_table_google_2fprotobuf_2ftype_2eproto
#define TableStruct_google_2fprotobuf_2ftype_2eproto base_status_TableStruct_google_2fprotobuf_2ftype_2eproto
#define google_2fprotobuf_2fwrappers_2eproto base_status_google_2fprotobuf_2fwrappers_2eproto
#define descriptor_table_google_2fprotobuf_2fwrappers_2eproto base_status_descriptor_table_google_2fprotobuf_2fwrappers_2eproto
#define TableStruct_google_2fprotobuf_2fwrappers_2eproto base_status_TableStruct_google_2fprotobuf_2fwrappers_2eproto
#define google_2ftype_2fdate_2eproto base_status_google_2ftype_2fdate_2eproto
#define descriptor_table_google_2ftype_2fdate_2eproto base_status_descriptor_table_google_2ftype_2fdate_2eproto
#define TableStruct_google_2ftype_2fdate_2eproto base_status_TableStruct_google_2ftype_2fdate_2eproto
#define google_2ftype_2flatlng_2eproto base_status_google_2ftype_2flatlng_2eproto
#define descriptor_table_google_2ftype_2flatlng_2eproto base_status_descriptor_table_google_2ftype_2flatlng_2eproto
#define TableStruct_google_2ftype_2flatlng_2eproto base_status_TableStruct_google_2ftype_2flatlng_2eproto
#define google_2ftype_2ftimeofday_2eproto base_status_google_2ftype_2ftimeofday_2eproto
#define descriptor_table_google_2ftype_2ftimeofday_2eproto base_status_descriptor_table_google_2ftype_2ftimeofday_2eproto
#define TableStruct_google_2ftype_2ftimeofday_2eproto base_status_TableStruct_google_2ftype_2ftimeofday_2eproto
#define zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto base_status_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto base_status_descriptor_table_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto base_status_TableStruct_zetasql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define zetasql_2fparser_2fparse_5ftree_2eproto base_status_zetasql_2fparser_2fparse_5ftree_2eproto
#define descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto base_status_descriptor_table_zetasql_2fparser_2fparse_5ftree_2eproto
#define TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto base_status_TableStruct_zetasql_2fparser_2fparse_5ftree_2eproto
#define zetasql_2fparser_2fast_5fenums_2eproto base_status_zetasql_2fparser_2fast_5fenums_2eproto
#define descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto base_status_descriptor_table_zetasql_2fparser_2fast_5fenums_2eproto
#define TableStruct_zetasql_2fparser_2fast_5fenums_2eproto base_status_TableStruct_zetasql_2fparser_2fast_5fenums_2eproto
#define zetasql_2fproto_2foptions_2eproto base_status_zetasql_2fproto_2foptions_2eproto
#define descriptor_table_zetasql_2fproto_2foptions_2eproto base_status_descriptor_table_zetasql_2fproto_2foptions_2eproto
#define TableStruct_zetasql_2fproto_2foptions_2eproto base_status_TableStruct_zetasql_2fproto_2foptions_2eproto
#define zetasql_2fproto_2fsimple_5fcatalog_2eproto base_status_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto base_status_descriptor_table_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto base_status_TableStruct_zetasql_2fproto_2fsimple_5fcatalog_2eproto
#define zetasql_2fproto_2ffunction_2eproto base_status_zetasql_2fproto_2ffunction_2eproto
#define descriptor_table_zetasql_2fproto_2ffunction_2eproto base_status_descriptor_table_zetasql_2fproto_2ffunction_2eproto
#define TableStruct_zetasql_2fproto_2ffunction_2eproto base_status_TableStruct_zetasql_2fproto_2ffunction_2eproto
#define zetasql_2fproto_2finternal_5ferror_5flocation_2eproto base_status_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto base_status_descriptor_table_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto base_status_TableStruct_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto base_status_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto base_status_descriptor_table_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto base_status_TableStruct_zetasql_2fproto_2fanon_5foutput_5fwith_5freport_2eproto
#define zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto base_status_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto base_status_descriptor_table_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto base_status_TableStruct_zetasql_2fproto_2fplaceholder_5fdescriptor_2eproto
#define zetasql_2fpublic_2fbuiltin_5ffunction_2eproto base_status_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto base_status_descriptor_table_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto base_status_TableStruct_zetasql_2fpublic_2fbuiltin_5ffunction_2eproto
#define zetasql_2fpublic_2fdeprecation_5fwarning_2eproto base_status_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto base_status_descriptor_table_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto base_status_TableStruct_zetasql_2fpublic_2fdeprecation_5fwarning_2eproto
#define zetasql_2fpublic_2ffunction_2eproto base_status_zetasql_2fpublic_2ffunction_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunction_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunction_2eproto
#define TableStruct_zetasql_2fpublic_2ffunction_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunction_2eproto
#define zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto base_status_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto base_status_descriptor_table_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto base_status_TableStruct_zetasql_2fpublic_2fparse_5fresume_5flocation_2eproto
#define zetasql_2fpublic_2foptions_2eproto base_status_zetasql_2fpublic_2foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2foptions_2eproto base_status_descriptor_table_zetasql_2fpublic_2foptions_2eproto
#define TableStruct_zetasql_2fpublic_2foptions_2eproto base_status_TableStruct_zetasql_2fpublic_2foptions_2eproto
#define zetasql_2fpublic_2fsimple_5ftable_2eproto base_status_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto base_status_descriptor_table_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto base_status_TableStruct_zetasql_2fpublic_2fsimple_5ftable_2eproto
#define zetasql_2fpublic_2fsimple_5fconstant_2eproto base_status_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto base_status_descriptor_table_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto base_status_TableStruct_zetasql_2fpublic_2fsimple_5fconstant_2eproto
#define zetasql_2fpublic_2fparse_5flocation_5frange_2eproto base_status_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto base_status_descriptor_table_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto base_status_TableStruct_zetasql_2fpublic_2fparse_5flocation_5frange_2eproto
#define zetasql_2fpublic_2ftype_2eproto base_status_zetasql_2fpublic_2ftype_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_2eproto base_status_descriptor_table_zetasql_2fpublic_2ftype_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_2eproto base_status_TableStruct_zetasql_2fpublic_2ftype_2eproto
#define zetasql_2fpublic_2ftype_5fannotation_2eproto base_status_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto base_status_descriptor_table_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto base_status_TableStruct_zetasql_2fpublic_2ftype_5fannotation_2eproto
#define zetasql_2fpublic_2fvalue_2eproto base_status_zetasql_2fpublic_2fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fvalue_2eproto base_status_descriptor_table_zetasql_2fpublic_2fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fvalue_2eproto base_status_TableStruct_zetasql_2fpublic_2fvalue_2eproto
#define zetasql_2fpublic_2ftype_5fparameters_2eproto base_status_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto base_status_descriptor_table_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto base_status_TableStruct_zetasql_2fpublic_2ftype_5fparameters_2eproto
#define zetasql_2fpublic_2fcollation_2eproto base_status_zetasql_2fpublic_2fcollation_2eproto
#define descriptor_table_zetasql_2fpublic_2fcollation_2eproto base_status_descriptor_table_zetasql_2fpublic_2fcollation_2eproto
#define TableStruct_zetasql_2fpublic_2fcollation_2eproto base_status_TableStruct_zetasql_2fpublic_2fcollation_2eproto
#define zetasql_2fpublic_2ftype_5fmodifiers_2eproto base_status_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto base_status_descriptor_table_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto base_status_TableStruct_zetasql_2fpublic_2ftype_5fmodifiers_2eproto
#define zetasql_2fpublic_2fformatter_5foptions_2eproto base_status_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto base_status_descriptor_table_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto base_status_TableStruct_zetasql_2fpublic_2fformatter_5foptions_2eproto
#define zetasql_2fpublic_2ferror_5flocation_2eproto base_status_zetasql_2fpublic_2ferror_5flocation_2eproto
#define descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto base_status_descriptor_table_zetasql_2fpublic_2ferror_5flocation_2eproto
#define TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto base_status_TableStruct_zetasql_2fpublic_2ferror_5flocation_2eproto
#define zetasql_2fpublic_2fannotation_2eproto base_status_zetasql_2fpublic_2fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fannotation_2eproto base_status_descriptor_table_zetasql_2fpublic_2fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fannotation_2eproto base_status_TableStruct_zetasql_2fpublic_2fannotation_2eproto
#define zetasql_2fpublic_2fsimple_5fvalue_2eproto base_status_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto base_status_descriptor_table_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto base_status_TableStruct_zetasql_2fpublic_2fsimple_5fvalue_2eproto
#define zetasql_2fpublic_2ffunctions_2fdatetime_2eproto base_status_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunctions_2fdatetime_2eproto
#define zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto base_status_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunctions_2fnormalize_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto base_status_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunctions_2frounding_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto base_status_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5ffind_5fmode_2eproto
#define zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto base_status_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunctions_2fdifferential_5fprivacy_2eproto
#define zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto base_status_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto base_status_descriptor_table_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto base_status_TableStruct_zetasql_2fpublic_2ffunctions_2farray_5fzip_5fmode_2eproto
#define zetasql_2fpublic_2fproto_2flogging_2eproto base_status_zetasql_2fpublic_2fproto_2flogging_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto base_status_descriptor_table_zetasql_2fpublic_2fproto_2flogging_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto base_status_TableStruct_zetasql_2fpublic_2fproto_2flogging_2eproto
#define zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto base_status_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto base_status_descriptor_table_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto base_status_TableStruct_zetasql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto base_status_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto base_status_descriptor_table_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto base_status_TableStruct_zetasql_2freference_5fimpl_2fevaluator_5ftable_5fiterator_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto base_status_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto base_status_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto base_status_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fnode_5fkind_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto base_status_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto base_status_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto base_status_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_5fenums_2eproto
#define zetasql_2fresolved_5fast_2fresolved_5fast_2eproto base_status_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto base_status_descriptor_table_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto base_status_TableStruct_zetasql_2fresolved_5fast_2fresolved_5fast_2eproto
#define zetasql_2fresolved_5fast_2fserialization_2eproto base_status_zetasql_2fresolved_5fast_2fserialization_2eproto
#define descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto base_status_descriptor_table_zetasql_2fresolved_5fast_2fserialization_2eproto
#define TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto base_status_TableStruct_zetasql_2fresolved_5fast_2fserialization_2eproto
#define zetasql_2fscripting_2fscript_5fexception_2eproto base_status_zetasql_2fscripting_2fscript_5fexception_2eproto
#define descriptor_table_zetasql_2fscripting_2fscript_5fexception_2eproto base_status_descriptor_table_zetasql_2fscripting_2fscript_5fexception_2eproto
#define TableStruct_zetasql_2fscripting_2fscript_5fexception_2eproto base_status_TableStruct_zetasql_2fscripting_2fscript_5fexception_2eproto
#define zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto base_status_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto base_status_descriptor_table_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto base_status_TableStruct_zetasql_2fscripting_2fscript_5fexecutor_5fstate_2eproto
#define zetasql_2fscripting_2fprocedure_5fextension_2eproto base_status_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto base_status_descriptor_table_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto base_status_TableStruct_zetasql_2fscripting_2fprocedure_5fextension_2eproto
#define zetasql_2fscripting_2fvariable_2eproto base_status_zetasql_2fscripting_2fvariable_2eproto
#define descriptor_table_zetasql_2fscripting_2fvariable_2eproto base_status_descriptor_table_zetasql_2fscripting_2fvariable_2eproto
#define TableStruct_zetasql_2fscripting_2fvariable_2eproto base_status_TableStruct_zetasql_2fscripting_2fvariable_2eproto

#define GO_EXPORT(def) export_base_status_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// include headers
//#define private public
#include "base/status.h"
#include "base/status_macros.h"
//#undef private

// include sources

// include dependencies
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* base_status_bind_cc */
