#ifndef INTERNAL_CCALL_GO_BASE_STATUS_EXPORT_H
#define INTERNAL_CCALL_GO_BASE_STATUS_EXPORT_H

#include "base/status.h"
#include "base/status_macros.h"
// include sources
// include dependencies
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/container/node_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
