#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_STRING_VIEW_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_STRING_VIEW_EXPORT_H

#include "absl/strings/string_view.h"
// include sources
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/base/throw_delegate/export.inc"

#endif
