
#ifndef absl_synchronization_synchronization_bind_cc
#define absl_synchronization_synchronization_bind_cc

// switch namespace
#define differential_privacy absl_synchronization_synchronization_differential_privacy
#define googlesql absl_synchronization_synchronization_googlesql
#define googlesql_base absl_synchronization_synchronization_googlesql_base
#define googlesql_bison_parser absl_synchronization_synchronization_googlesql_bison_parser
#define re2 absl_synchronization_synchronization_re2
#define AbslInternalSleepFor absl_synchronization_synchronization_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_synchronization_synchronization_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_synchronization_synchronization_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_synchronization_synchronization_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_synchronization_synchronization_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_synchronization_synchronization_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_synchronization_synchronization_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_synchronization_synchronization_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_synchronization_synchronization_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_synchronization_synchronization_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_synchronization_synchronization_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_synchronization_synchronization_GoogleSqlalloc
#define GoogleSqlfree absl_synchronization_synchronization_GoogleSqlfree
#define GoogleSqlrealloc absl_synchronization_synchronization_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_synchronization_synchronization_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_synchronization_synchronization_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_synchronization_synchronization_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_synchronization_synchronization_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_synchronization_synchronization_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_synchronization_synchronization_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_synchronization_synchronization_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_synchronization_synchronization_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_synchronization_synchronization_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_synchronization_synchronization_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_synchronization_synchronization_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_synchronization_synchronization_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_synchronization_synchronization_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_synchronization_synchronization_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_synchronization_synchronization_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_synchronization_synchronization_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_synchronization_synchronization_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_synchronization_synchronization_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_synchronization_synchronization_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_synchronization_synchronization_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_synchronization_synchronization_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_synchronization_synchronization_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_synchronization_synchronization_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_synchronization_synchronization_GoogleSqlFlexLexer
#define UCaseMap absl_synchronization_synchronization_UCaseMap

#define GO_EXPORT(def) export_absl_synchronization_synchronization_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/synchronization/barrier.h"
#include "absl/synchronization/blocking_counter.h"
#include "absl/synchronization/internal/create_thread_identity.h"
#include "absl/synchronization/internal/futex.h"
#include "absl/synchronization/internal/futex_waiter.h"
#include "absl/synchronization/internal/per_thread_sem.h"
#include "absl/synchronization/internal/pthread_waiter.h"
#include "absl/synchronization/internal/sem_waiter.h"
#include "absl/synchronization/internal/stdcpp_waiter.h"
#include "absl/synchronization/internal/waiter.h"
#include "absl/synchronization/internal/waiter_base.h"
#include "absl/synchronization/internal/win32_waiter.h"
#include "absl/synchronization/mutex.h"
#include "absl/synchronization/notification.h"
//#undef private

// include sources
#include "absl/synchronization/barrier.cc"
#include "absl/synchronization/blocking_counter.cc"
#include "absl/synchronization/internal/create_thread_identity.cc"
#include "absl/synchronization/internal/futex_waiter.cc"
#include "absl/synchronization/internal/per_thread_sem.cc"
#include "absl/synchronization/internal/pthread_waiter.cc"
#include "absl/synchronization/internal/sem_waiter.cc"
#include "absl/synchronization/internal/stdcpp_waiter.cc"
#include "absl/synchronization/internal/waiter_base.cc"
#include "absl/synchronization/internal/win32_waiter.cc"
#include "absl/synchronization/mutex.cc"
#include "absl/synchronization/notification.cc"

// include dependencies
#include "go-absl/synchronization/graphcycles_internal/export.inc"
#include "go-absl/synchronization/kernel_timeout_internal/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/atomic_hook/export.inc"
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/dynamic_annotations/export.inc"
#include "go-absl/base/malloc_internal/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/debugging/stacktrace/export.inc"
#include "go-absl/debugging/symbolize/export.inc"
#include "go-absl/time/time/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_synchronization_synchronization_bind_cc */
