#ifndef INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_LIKE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_REFERENCE_IMPL_FUNCTIONS_LIKE_EXPORT_H

#include "googlesql/reference_impl/functions/like.h"
// include sources
#include "googlesql/reference_impl/functions/like.cc"
// include dependencies
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/collator/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/functions/like/export.inc"
#include "go-googlesql/public/functions/string_with_collation/export.inc"
#include "go-googlesql/public/proto/type_annotation_cc_proto/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-re2/re2/export.inc"

#endif
