#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_ARENA_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_BASE_ARENA_EXPORT_H

#include "googlesql/legacy_zetasql/base/arena.h"
// include sources
#include "googlesql/legacy_zetasql/base/arena.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"

#endif
