#ifndef INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_RANDEN_SLOW_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_RANDEN_SLOW_EXPORT_H

#include "absl/random/internal/randen_slow.h"
// include sources
#include "absl/random/internal/randen_slow.cc"
// include dependencies
#include "go-absl/random/go_internal/platform/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/endian/export.inc"
#include "go-absl/numeric/int128/export.inc"

#endif
