#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_CONSTANT_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_CONSTANT_UTILS_EXPORT_H

#include "googlesql/common/constant_utils.h"
// include sources
#include "googlesql/common/constant_utils.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/types/type/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
