
#ifndef absl_strings_str_format_bind_cc
#define absl_strings_str_format_bind_cc

// switch namespace
#define differential_privacy absl_strings_str_format_differential_privacy
#define googlesql absl_strings_str_format_googlesql
#define googlesql_base absl_strings_str_format_googlesql_base
#define googlesql_bison_parser absl_strings_str_format_googlesql_bison_parser
#define re2 absl_strings_str_format_re2
#define AbslInternalSleepFor absl_strings_str_format_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError absl_strings_str_format_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield absl_strings_str_format_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost absl_strings_str_format_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait absl_strings_str_format_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything absl_strings_str_format_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay absl_strings_str_format_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake absl_strings_str_format_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin absl_strings_str_format_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd absl_strings_str_format_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint absl_strings_str_format_AbslInternalGetFileMappingHint
#define GoogleSqlalloc absl_strings_str_format_GoogleSqlalloc
#define GoogleSqlfree absl_strings_str_format_GoogleSqlfree
#define GoogleSqlrealloc absl_strings_str_format_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly absl_strings_str_format_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream absl_strings_str_format_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly absl_strings_str_format_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream absl_strings_str_format_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit absl_strings_str_format_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path absl_strings_str_format_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width absl_strings_str_format_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance absl_strings_str_format_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period absl_strings_str_format_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit absl_strings_str_format_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path absl_strings_str_format_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width absl_strings_str_format_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance absl_strings_str_format_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period absl_strings_str_format_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes absl_strings_str_format_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes absl_strings_str_format_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string absl_strings_str_format_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string absl_strings_str_format_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability absl_strings_str_format_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability absl_strings_str_format_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests absl_strings_str_format_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests absl_strings_str_format_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase absl_strings_str_format_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer absl_strings_str_format_GoogleSqlFlexLexer
#define UCaseMap absl_strings_str_format_UCaseMap

#define GO_EXPORT(def) export_absl_strings_str_format_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "absl/strings/str_format.h"
//#undef private

// include sources

// include dependencies
#include "go-absl/strings/str_format_internal/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/types/span/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* absl_strings_str_format_bind_cc */
