#ifndef INTERNAL_CCALL_GO_ABSL_STRINGS_STR_FORMAT_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_STRINGS_STR_FORMAT_EXPORT_H

#include "absl/strings/str_format.h"
// include sources
// include dependencies
#include "go-absl/strings/str_format_internal/export.inc"
#include "go-absl/strings/string_view/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/types/span/export.inc"

#endif
