#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ANONYMIZATION_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_PUBLIC_ANONYMIZATION_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/public/anonymization_utils.h"
// include sources
#include "googlesql/legacy_zetasql/public/anonymization_utils.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/public/function_headers/export.inc"
#include "go-googlesql/legacy_zetasql/public/type/export.inc"
#include "go-googlesql/legacy_zetasql/public/value/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/functions/differential_privacy_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"
#include "go-algorithms/partition-selection/export.inc"

#endif
