#ifndef INTERNAL_CCALL_GO_ZETASQL_COMMON_WARNING_SINK_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_COMMON_WARNING_SINK_EXPORT_H

#include "googlesql/common/warning_sink.h"
// include sources
#include "googlesql/common/warning_sink.cc"
// include dependencies
#include "go-zetasql/common/status_payload_utils/export.inc"
#include "go-zetasql/proto/internal_error_location_cc_proto/export.inc"
#include "go-zetasql/public/deprecation_warning_cc_proto/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/types/span/export.inc"

#endif
