#ifndef INTERNAL_CCALL_GO_ABSL_SYNCHRONIZATION_GRAPHCYCLES_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_SYNCHRONIZATION_GRAPHCYCLES_INTERNAL_EXPORT_H

#include "absl/synchronization/internal/graphcycles.h"
// include sources
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/base_internal/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/malloc_internal/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"

#endif
