#ifndef INTERNAL_CCALL_GO_GOOGLESQL_RESOLVED_AST_RESOLVED_AST_BUILDER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_RESOLVED_AST_RESOLVED_AST_BUILDER_EXPORT_H

#include "googlesql/resolved_ast/resolved_ast_builder.h"
// include sources
// include dependencies
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/source_location/export.inc"
#include "go-googlesql/common/status_payload_utils/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
