#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_MATCH_RECOGNIZE_COMPILED_PATTERN_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_MATCH_RECOGNIZE_COMPILED_PATTERN_CC_PROTO_EXPORT_H

#include "googlesql/public/functions/match_recognize/compiled_pattern.pb.h"
// include sources
#include "googlesql/public/functions/match_recognize/compiled_pattern.pb.cc"
// include dependencies

#endif
