#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_TO_JSON_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_TO_JSON_EXPORT_H

#include "googlesql/public/functions/to_json.h"
// include sources
#include "googlesql/public/functions/to_json.cc"
// include dependencies
#include "go-googlesql/public/functions/json_format/export.inc"
#include "go-googlesql/public/functions/unsupported_fields_cc_proto/export.inc"
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/common/errors/export.inc"
#include "go-googlesql/common/thread_stack/export.inc"
#include "go-googlesql/public/interval_value/export.inc"
#include "go-googlesql/public/json_value/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/uuid_value/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/public/types/types/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
