#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_EDGE_TRACKER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_MATCH_RECOGNIZE_EDGE_TRACKER_EXPORT_H

#include "googlesql/legacy_zetasql/common/match_recognize/edge_tracker.h"
// include sources
#include "googlesql/legacy_zetasql/common/match_recognize/edge_tracker.cc"
// include dependencies
#include "go-googlesql/legacy_zetasql/common/match_recognize/compiled_nfa/export.inc"
#include "go-googlesql/legacy_zetasql/common/match_recognize/nfa/export.inc"
#include "go-googlesql/legacy_zetasql/common/match_recognize/row_edge_list/export.inc"
#include "go-absl/functional/any_invocable/export.inc"

#endif
