#ifndef INTERNAL_CCALL_GO_GOOGLESQL_RESOLVED_AST_MAKE_NODE_VECTOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_RESOLVED_AST_MAKE_NODE_VECTOR_EXPORT_H

#include "googlesql/resolved_ast/make_node_vector.h"
// include sources
#include "googlesql/resolved_ast/make_node_vector_internal.h"
// include dependencies
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/meta/type_traits/export.inc"

#endif
