#ifndef INTERNAL_CCALL_GO_ZETASQL_PROTO_INTERNAL_ERROR_LOCATION_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PROTO_INTERNAL_ERROR_LOCATION_CC_PROTO_EXPORT_H

#include "zetasql/proto/internal_error_location.pb.h"
// include sources
#define schemas zetasql_proto_internal_error_location_cc_proto_schemas
#define file_default_instances zetasql_proto_internal_error_location_cc_proto_file_default_instances
#include "zetasql/proto/internal_error_location.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies
#include "go-zetasql/public/error_location_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
