#ifndef INTERNAL_CCALL_GO_ZETASQL_RESOLVED_AST_COLUMN_FACTORY_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_RESOLVED_AST_COLUMN_FACTORY_EXPORT_H

#include "zetasql/resolved_ast/column_factory.h"
// include sources
#include "zetasql/resolved_ast/column_factory.cc"
// include dependencies
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/public/builtin_function_cc_proto/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
