#ifndef INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_RANDEN_HWAES_IMPL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_RANDOM_GO_INTERNAL_RANDEN_HWAES_IMPL_EXPORT_H

// include sources
#include "absl/random/internal/randen_hwaes.cc"
#include "absl/random/internal/randen_hwaes.h"
// include dependencies
#include "go-absl/random/go_internal/platform/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/int128/export.inc"

#endif
