#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_EXPR_MATCHING_HELPERS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_ANALYZER_EXPR_MATCHING_HELPERS_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/expr_matching_helpers.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/expr_matching_helpers.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/analyzer/name_scope/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/function/export.inc"
#include "go-zetasql/public/function_cc_proto/export.inc"
#include "go-zetasql/public/id_string/export.inc"
#include "go-zetasql/public/type/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/hash/hash/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
