// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: googlesql/common/initialize_required_fields_test.proto
// Protobuf C++ Version: 5.29.0

#ifndef googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto_2epb_2eh
#define googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto;
namespace googlesql_test {
class InitializeRequiredFieldsTestMessage;
struct InitializeRequiredFieldsTestMessageDefaultTypeInternal;
extern InitializeRequiredFieldsTestMessageDefaultTypeInternal _InitializeRequiredFieldsTestMessage_default_instance_;
class InitializeRequiredFieldsTestMessage_InnerMessage;
struct InitializeRequiredFieldsTestMessage_InnerMessageDefaultTypeInternal;
extern InitializeRequiredFieldsTestMessage_InnerMessageDefaultTypeInternal _InitializeRequiredFieldsTestMessage_InnerMessage_default_instance_;
}  // namespace googlesql_test
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace googlesql_test {
enum InitializeRequiredFieldsTestMessage_Enum : int {
  InitializeRequiredFieldsTestMessage_Enum_ONE_VAL = 1,
  InitializeRequiredFieldsTestMessage_Enum_TWO_VAL = 2,
};

bool InitializeRequiredFieldsTestMessage_Enum_IsValid(int value);
extern const uint32_t InitializeRequiredFieldsTestMessage_Enum_internal_data_[];
constexpr InitializeRequiredFieldsTestMessage_Enum InitializeRequiredFieldsTestMessage_Enum_Enum_MIN = static_cast<InitializeRequiredFieldsTestMessage_Enum>(1);
constexpr InitializeRequiredFieldsTestMessage_Enum InitializeRequiredFieldsTestMessage_Enum_Enum_MAX = static_cast<InitializeRequiredFieldsTestMessage_Enum>(2);
constexpr int InitializeRequiredFieldsTestMessage_Enum_Enum_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
InitializeRequiredFieldsTestMessage_Enum_descriptor();
template <typename T>
const std::string& InitializeRequiredFieldsTestMessage_Enum_Name(T value) {
  static_assert(std::is_same<T, InitializeRequiredFieldsTestMessage_Enum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return InitializeRequiredFieldsTestMessage_Enum_Name(static_cast<InitializeRequiredFieldsTestMessage_Enum>(value));
}
template <>
inline const std::string& InitializeRequiredFieldsTestMessage_Enum_Name(InitializeRequiredFieldsTestMessage_Enum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<InitializeRequiredFieldsTestMessage_Enum_descriptor,
                                                 1, 2>(
      static_cast<int>(value));
}
inline bool InitializeRequiredFieldsTestMessage_Enum_Parse(absl::string_view name, InitializeRequiredFieldsTestMessage_Enum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<InitializeRequiredFieldsTestMessage_Enum>(
      InitializeRequiredFieldsTestMessage_Enum_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class InitializeRequiredFieldsTestMessage_InnerMessage final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage) */ {
 public:
  inline InitializeRequiredFieldsTestMessage_InnerMessage() : InitializeRequiredFieldsTestMessage_InnerMessage(nullptr) {}
  ~InitializeRequiredFieldsTestMessage_InnerMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InitializeRequiredFieldsTestMessage_InnerMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InitializeRequiredFieldsTestMessage_InnerMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InitializeRequiredFieldsTestMessage_InnerMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline InitializeRequiredFieldsTestMessage_InnerMessage(const InitializeRequiredFieldsTestMessage_InnerMessage& from) : InitializeRequiredFieldsTestMessage_InnerMessage(nullptr, from) {}
  inline InitializeRequiredFieldsTestMessage_InnerMessage(InitializeRequiredFieldsTestMessage_InnerMessage&& from) noexcept
      : InitializeRequiredFieldsTestMessage_InnerMessage(nullptr, std::move(from)) {}
  inline InitializeRequiredFieldsTestMessage_InnerMessage& operator=(const InitializeRequiredFieldsTestMessage_InnerMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitializeRequiredFieldsTestMessage_InnerMessage& operator=(InitializeRequiredFieldsTestMessage_InnerMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitializeRequiredFieldsTestMessage_InnerMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const InitializeRequiredFieldsTestMessage_InnerMessage* internal_default_instance() {
    return reinterpret_cast<const InitializeRequiredFieldsTestMessage_InnerMessage*>(
        &_InitializeRequiredFieldsTestMessage_InnerMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(InitializeRequiredFieldsTestMessage_InnerMessage& a, InitializeRequiredFieldsTestMessage_InnerMessage& b) { a.Swap(&b); }
  inline void Swap(InitializeRequiredFieldsTestMessage_InnerMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitializeRequiredFieldsTestMessage_InnerMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitializeRequiredFieldsTestMessage_InnerMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InitializeRequiredFieldsTestMessage_InnerMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InitializeRequiredFieldsTestMessage_InnerMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InitializeRequiredFieldsTestMessage_InnerMessage& from) { InitializeRequiredFieldsTestMessage_InnerMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InitializeRequiredFieldsTestMessage_InnerMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage"; }

 protected:
  explicit InitializeRequiredFieldsTestMessage_InnerMessage(::google::protobuf::Arena* arena);
  InitializeRequiredFieldsTestMessage_InnerMessage(::google::protobuf::Arena* arena, const InitializeRequiredFieldsTestMessage_InnerMessage& from);
  InitializeRequiredFieldsTestMessage_InnerMessage(::google::protobuf::Arena* arena, InitializeRequiredFieldsTestMessage_InnerMessage&& from) noexcept
      : InitializeRequiredFieldsTestMessage_InnerMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReqFieldNumber = 1,
    kNonReqFieldNumber = 2,
  };
  // required int32 req = 1;
  bool has_req() const;
  void clear_req() ;
  ::int32_t req() const;
  void set_req(::int32_t value);

  private:
  ::int32_t _internal_req() const;
  void _internal_set_req(::int32_t value);

  public:
  // optional int32 non_req = 2;
  bool has_non_req() const;
  void clear_non_req() ;
  ::int32_t non_req() const;
  void set_non_req(::int32_t value);

  private:
  ::int32_t _internal_non_req() const;
  void _internal_set_non_req(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const InitializeRequiredFieldsTestMessage_InnerMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t req_;
    ::int32_t non_req_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto;
};
// -------------------------------------------------------------------

class InitializeRequiredFieldsTestMessage final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:googlesql_test.InitializeRequiredFieldsTestMessage) */ {
 public:
  inline InitializeRequiredFieldsTestMessage() : InitializeRequiredFieldsTestMessage(nullptr) {}
  ~InitializeRequiredFieldsTestMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InitializeRequiredFieldsTestMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InitializeRequiredFieldsTestMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InitializeRequiredFieldsTestMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline InitializeRequiredFieldsTestMessage(const InitializeRequiredFieldsTestMessage& from) : InitializeRequiredFieldsTestMessage(nullptr, from) {}
  inline InitializeRequiredFieldsTestMessage(InitializeRequiredFieldsTestMessage&& from) noexcept
      : InitializeRequiredFieldsTestMessage(nullptr, std::move(from)) {}
  inline InitializeRequiredFieldsTestMessage& operator=(const InitializeRequiredFieldsTestMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline InitializeRequiredFieldsTestMessage& operator=(InitializeRequiredFieldsTestMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InitializeRequiredFieldsTestMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const InitializeRequiredFieldsTestMessage* internal_default_instance() {
    return reinterpret_cast<const InitializeRequiredFieldsTestMessage*>(
        &_InitializeRequiredFieldsTestMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(InitializeRequiredFieldsTestMessage& a, InitializeRequiredFieldsTestMessage& b) { a.Swap(&b); }
  inline void Swap(InitializeRequiredFieldsTestMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InitializeRequiredFieldsTestMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InitializeRequiredFieldsTestMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InitializeRequiredFieldsTestMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InitializeRequiredFieldsTestMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InitializeRequiredFieldsTestMessage& from) { InitializeRequiredFieldsTestMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InitializeRequiredFieldsTestMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "googlesql_test.InitializeRequiredFieldsTestMessage"; }

 protected:
  explicit InitializeRequiredFieldsTestMessage(::google::protobuf::Arena* arena);
  InitializeRequiredFieldsTestMessage(::google::protobuf::Arena* arena, const InitializeRequiredFieldsTestMessage& from);
  InitializeRequiredFieldsTestMessage(::google::protobuf::Arena* arena, InitializeRequiredFieldsTestMessage&& from) noexcept
      : InitializeRequiredFieldsTestMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using InnerMessage = InitializeRequiredFieldsTestMessage_InnerMessage;
  using Enum = InitializeRequiredFieldsTestMessage_Enum;
  static constexpr Enum ONE_VAL = InitializeRequiredFieldsTestMessage_Enum_ONE_VAL;
  static constexpr Enum TWO_VAL = InitializeRequiredFieldsTestMessage_Enum_TWO_VAL;
  static inline bool Enum_IsValid(int value) {
    return InitializeRequiredFieldsTestMessage_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = InitializeRequiredFieldsTestMessage_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = InitializeRequiredFieldsTestMessage_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = InitializeRequiredFieldsTestMessage_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Enum_descriptor() {
    return InitializeRequiredFieldsTestMessage_Enum_descriptor();
  }
  template <typename T>
  static inline const std::string& Enum_Name(T value) {
    return InitializeRequiredFieldsTestMessage_Enum_Name(value);
  }
  static inline bool Enum_Parse(absl::string_view name, Enum* value) {
    return InitializeRequiredFieldsTestMessage_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kRepMsg1FieldNumber = 12,
    kRepMsg2FieldNumber = 15,
    kRepValFieldNumber = 17,
    kSFieldNumber = 8,
    kReqMsg1FieldNumber = 10,
    kOptMsg1FieldNumber = 11,
    kReqMsg2FieldNumber = 13,
    kOptMsg2FieldNumber = 14,
    kDFieldNumber = 1,
    kFFieldNumber = 2,
    kI32FieldNumber = 3,
    kI64FieldNumber = 4,
    kU64FieldNumber = 6,
    kU32FieldNumber = 5,
    kBFieldNumber = 7,
    kOptValFieldNumber = 16,
    kEFieldNumber = 9,
  };
  // repeated .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage rep_msg1 = 12;
  int rep_msg1_size() const;
  private:
  int _internal_rep_msg1_size() const;

  public:
  void clear_rep_msg1() ;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* mutable_rep_msg1(int index);
  ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>* mutable_rep_msg1();

  private:
  const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>& _internal_rep_msg1() const;
  ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>* _internal_mutable_rep_msg1();
  public:
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& rep_msg1(int index) const;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* add_rep_msg1();
  const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>& rep_msg1() const;
  // repeated .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage rep_msg2 = 15;
  int rep_msg2_size() const;
  private:
  int _internal_rep_msg2_size() const;

  public:
  void clear_rep_msg2() ;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* mutable_rep_msg2(int index);
  ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>* mutable_rep_msg2();

  private:
  const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>& _internal_rep_msg2() const;
  ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>* _internal_mutable_rep_msg2();
  public:
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& rep_msg2(int index) const;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* add_rep_msg2();
  const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>& rep_msg2() const;
  // repeated int32 rep_val = 17;
  int rep_val_size() const;
  private:
  int _internal_rep_val_size() const;

  public:
  void clear_rep_val() ;
  ::int32_t rep_val(int index) const;
  void set_rep_val(int index, ::int32_t value);
  void add_rep_val(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& rep_val() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_rep_val();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_rep_val() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_rep_val();

  public:
  // required string s = 8;
  bool has_s() const;
  void clear_s() ;
  const std::string& s() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_s(Arg_&& arg, Args_... args);
  std::string* mutable_s();
  PROTOBUF_NODISCARD std::string* release_s();
  void set_allocated_s(std::string* value);

  private:
  const std::string& _internal_s() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_s(
      const std::string& value);
  std::string* _internal_mutable_s();

  public:
  // required .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage req_msg1 = 10;
  bool has_req_msg1() const;
  void clear_req_msg1() ;
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& req_msg1() const;
  PROTOBUF_NODISCARD ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* release_req_msg1();
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* mutable_req_msg1();
  void set_allocated_req_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  void unsafe_arena_set_allocated_req_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* unsafe_arena_release_req_msg1();

  private:
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& _internal_req_msg1() const;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _internal_mutable_req_msg1();

  public:
  // optional .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage opt_msg1 = 11;
  bool has_opt_msg1() const;
  void clear_opt_msg1() ;
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& opt_msg1() const;
  PROTOBUF_NODISCARD ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* release_opt_msg1();
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* mutable_opt_msg1();
  void set_allocated_opt_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  void unsafe_arena_set_allocated_opt_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* unsafe_arena_release_opt_msg1();

  private:
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& _internal_opt_msg1() const;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _internal_mutable_opt_msg1();

  public:
  // required .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage req_msg2 = 13;
  bool has_req_msg2() const;
  void clear_req_msg2() ;
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& req_msg2() const;
  PROTOBUF_NODISCARD ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* release_req_msg2();
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* mutable_req_msg2();
  void set_allocated_req_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  void unsafe_arena_set_allocated_req_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* unsafe_arena_release_req_msg2();

  private:
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& _internal_req_msg2() const;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _internal_mutable_req_msg2();

  public:
  // optional .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage opt_msg2 = 14;
  bool has_opt_msg2() const;
  void clear_opt_msg2() ;
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& opt_msg2() const;
  PROTOBUF_NODISCARD ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* release_opt_msg2();
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* mutable_opt_msg2();
  void set_allocated_opt_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  void unsafe_arena_set_allocated_opt_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value);
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* unsafe_arena_release_opt_msg2();

  private:
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& _internal_opt_msg2() const;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _internal_mutable_opt_msg2();

  public:
  // required double d = 1;
  bool has_d() const;
  void clear_d() ;
  double d() const;
  void set_d(double value);

  private:
  double _internal_d() const;
  void _internal_set_d(double value);

  public:
  // required float f = 2;
  bool has_f() const;
  void clear_f() ;
  float f() const;
  void set_f(float value);

  private:
  float _internal_f() const;
  void _internal_set_f(float value);

  public:
  // required int32 i32 = 3;
  bool has_i32() const;
  void clear_i32() ;
  ::int32_t i32() const;
  void set_i32(::int32_t value);

  private:
  ::int32_t _internal_i32() const;
  void _internal_set_i32(::int32_t value);

  public:
  // required int64 i64 = 4;
  bool has_i64() const;
  void clear_i64() ;
  ::int64_t i64() const;
  void set_i64(::int64_t value);

  private:
  ::int64_t _internal_i64() const;
  void _internal_set_i64(::int64_t value);

  public:
  // required fixed64 u64 = 6;
  bool has_u64() const;
  void clear_u64() ;
  ::uint64_t u64() const;
  void set_u64(::uint64_t value);

  private:
  ::uint64_t _internal_u64() const;
  void _internal_set_u64(::uint64_t value);

  public:
  // required fixed32 u32 = 5;
  bool has_u32() const;
  void clear_u32() ;
  ::uint32_t u32() const;
  void set_u32(::uint32_t value);

  private:
  ::uint32_t _internal_u32() const;
  void _internal_set_u32(::uint32_t value);

  public:
  // required bool b = 7;
  bool has_b() const;
  void clear_b() ;
  bool b() const;
  void set_b(bool value);

  private:
  bool _internal_b() const;
  void _internal_set_b(bool value);

  public:
  // optional int32 opt_val = 16;
  bool has_opt_val() const;
  void clear_opt_val() ;
  ::int32_t opt_val() const;
  void set_opt_val(::int32_t value);

  private:
  ::int32_t _internal_opt_val() const;
  void _internal_set_opt_val(::int32_t value);

  public:
  // required .googlesql_test.InitializeRequiredFieldsTestMessage.Enum e = 9;
  bool has_e() const;
  void clear_e() ;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_Enum e() const;
  void set_e(::googlesql_test::InitializeRequiredFieldsTestMessage_Enum value);

  private:
  ::googlesql_test::InitializeRequiredFieldsTestMessage_Enum _internal_e() const;
  void _internal_set_e(::googlesql_test::InitializeRequiredFieldsTestMessage_Enum value);

  public:
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            typename = typename _proto_TypeTraits::Singular>
  inline bool HasExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.Has(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void ClearExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    _impl_._extensions_.ClearExtension(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            typename = typename _proto_TypeTraits::Repeated>
  inline int ExtensionSize(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.ExtensionSize(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<!_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Mutable(id.number(), _field_type, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::ConstType value) {
    _proto_TypeTraits::Set(id.number(), _field_type, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::SetAllocated(id.number(), _field_type, value,
                                    &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void UnsafeArenaSetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::UnsafeArenaSetAllocated(id.number(), _field_type,
                                               value, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  PROTOBUF_NODISCARD inline
      typename _proto_TypeTraits::Singular::MutableType
      ReleaseExtension(
          const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                           _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Release(id.number(), _field_type, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType
  UnsafeArenaReleaseExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::UnsafeArenaRelease(id.number(), _field_type,
                                                 &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<!_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed,
            std::enable_if_t<_proto_TypeTraits::kLifetimeBound, int> = 0>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::Mutable(id.number(), index, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index, typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Set(id.number(), index, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    typename _proto_TypeTraits::Repeated::MutableType to_add =
        _proto_TypeTraits::Add(id.number(), _field_type, &_impl_._extensions_);
    return to_add;
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Add(id.number(), _field_type, _is_packed, value,
                           &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline const typename _proto_TypeTraits::Repeated::RepeatedFieldType&
  GetRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::GetRepeated(id.number(), _impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::RepeatedFieldType*
  MutableRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<InitializeRequiredFieldsTestMessage, _proto_TypeTraits,
                                       _field_type, _is_packed>& id)
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _proto_TypeTraits::MutableRepeated(id.number(), _field_type,
                                              _is_packed, &_impl_._extensions_);
  }
  // @@protoc_insertion_point(class_scope:googlesql_test.InitializeRequiredFieldsTestMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      5, 17, 7,
      76, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const InitializeRequiredFieldsTestMessage& from_msg);
    ::google::protobuf::internal::ExtensionSet _extensions_;
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage > rep_msg1_;
    ::google::protobuf::RepeatedPtrField< ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage > rep_msg2_;
    ::google::protobuf::RepeatedField<::int32_t> rep_val_;
    ::google::protobuf::internal::ArenaStringPtr s_;
    ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* req_msg1_;
    ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* opt_msg1_;
    ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* req_msg2_;
    ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* opt_msg2_;
    double d_;
    float f_;
    ::int32_t i32_;
    ::int64_t i64_;
    ::uint64_t u64_;
    ::uint32_t u32_;
    bool b_;
    ::int32_t opt_val_;
    int e_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto;
};

// ===================================================================



static const int kExtensionOptI32FieldNumber = 100;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::googlesql_test::InitializeRequiredFieldsTestMessage, ::google::protobuf::internal::PrimitiveTypeTraits< ::int32_t >, 5,
    false>
    extension_opt_i32;
static const int kExtensionMsgFieldNumber = 103;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::googlesql_test::InitializeRequiredFieldsTestMessage, ::google::protobuf::internal::MessageTypeTraits< ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage >, 11,
    false>
    extension_msg;
static const int kRepeatedExtensionMsgFieldNumber = 104;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::googlesql_test::InitializeRequiredFieldsTestMessage, ::google::protobuf::internal::RepeatedMessageTypeTraits< ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage >, 11,
    false>
    repeated_extension_msg;

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// InitializeRequiredFieldsTestMessage_InnerMessage

// required int32 req = 1;
inline bool InitializeRequiredFieldsTestMessage_InnerMessage::has_req() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage_InnerMessage::clear_req() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.req_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t InitializeRequiredFieldsTestMessage_InnerMessage::req() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage.req)
  return _internal_req();
}
inline void InitializeRequiredFieldsTestMessage_InnerMessage::set_req(::int32_t value) {
  _internal_set_req(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage.req)
}
inline ::int32_t InitializeRequiredFieldsTestMessage_InnerMessage::_internal_req() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.req_;
}
inline void InitializeRequiredFieldsTestMessage_InnerMessage::_internal_set_req(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.req_ = value;
}

// optional int32 non_req = 2;
inline bool InitializeRequiredFieldsTestMessage_InnerMessage::has_non_req() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage_InnerMessage::clear_non_req() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.non_req_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t InitializeRequiredFieldsTestMessage_InnerMessage::non_req() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage.non_req)
  return _internal_non_req();
}
inline void InitializeRequiredFieldsTestMessage_InnerMessage::set_non_req(::int32_t value) {
  _internal_set_non_req(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage.non_req)
}
inline ::int32_t InitializeRequiredFieldsTestMessage_InnerMessage::_internal_non_req() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.non_req_;
}
inline void InitializeRequiredFieldsTestMessage_InnerMessage::_internal_set_non_req(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.non_req_ = value;
}

// -------------------------------------------------------------------

// InitializeRequiredFieldsTestMessage

// required int32 i32 = 3;
inline bool InitializeRequiredFieldsTestMessage::has_i32() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_i32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i32_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t InitializeRequiredFieldsTestMessage::i32() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.i32)
  return _internal_i32();
}
inline void InitializeRequiredFieldsTestMessage::set_i32(::int32_t value) {
  _internal_set_i32(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.i32)
}
inline ::int32_t InitializeRequiredFieldsTestMessage::_internal_i32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i32_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_i32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i32_ = value;
}

// required int64 i64 = 4;
inline bool InitializeRequiredFieldsTestMessage::has_i64() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_i64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i64_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int64_t InitializeRequiredFieldsTestMessage::i64() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.i64)
  return _internal_i64();
}
inline void InitializeRequiredFieldsTestMessage::set_i64(::int64_t value) {
  _internal_set_i64(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.i64)
}
inline ::int64_t InitializeRequiredFieldsTestMessage::_internal_i64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.i64_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_i64(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.i64_ = value;
}

// required fixed32 u32 = 5;
inline bool InitializeRequiredFieldsTestMessage::has_u32() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_u32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u32_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline ::uint32_t InitializeRequiredFieldsTestMessage::u32() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.u32)
  return _internal_u32();
}
inline void InitializeRequiredFieldsTestMessage::set_u32(::uint32_t value) {
  _internal_set_u32(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.u32)
}
inline ::uint32_t InitializeRequiredFieldsTestMessage::_internal_u32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.u32_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_u32(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u32_ = value;
}

// required fixed64 u64 = 6;
inline bool InitializeRequiredFieldsTestMessage::has_u64() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_u64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u64_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::uint64_t InitializeRequiredFieldsTestMessage::u64() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.u64)
  return _internal_u64();
}
inline void InitializeRequiredFieldsTestMessage::set_u64(::uint64_t value) {
  _internal_set_u64(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.u64)
}
inline ::uint64_t InitializeRequiredFieldsTestMessage::_internal_u64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.u64_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_u64(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.u64_ = value;
}

// required double d = 1;
inline bool InitializeRequiredFieldsTestMessage::has_d() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_d() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.d_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline double InitializeRequiredFieldsTestMessage::d() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.d)
  return _internal_d();
}
inline void InitializeRequiredFieldsTestMessage::set_d(double value) {
  _internal_set_d(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.d)
}
inline double InitializeRequiredFieldsTestMessage::_internal_d() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.d_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_d(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.d_ = value;
}

// required float f = 2;
inline bool InitializeRequiredFieldsTestMessage::has_f() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_f() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.f_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline float InitializeRequiredFieldsTestMessage::f() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.f)
  return _internal_f();
}
inline void InitializeRequiredFieldsTestMessage::set_f(float value) {
  _internal_set_f(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.f)
}
inline float InitializeRequiredFieldsTestMessage::_internal_f() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.f_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_f(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.f_ = value;
}

// required bool b = 7;
inline bool InitializeRequiredFieldsTestMessage::has_b() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_ = false;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline bool InitializeRequiredFieldsTestMessage::b() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.b)
  return _internal_b();
}
inline void InitializeRequiredFieldsTestMessage::set_b(bool value) {
  _internal_set_b(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.b)
}
inline bool InitializeRequiredFieldsTestMessage::_internal_b() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.b_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_b(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_ = value;
}

// required string s = 8;
inline bool InitializeRequiredFieldsTestMessage::has_s() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.s_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& InitializeRequiredFieldsTestMessage::s() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.s)
  return _internal_s();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InitializeRequiredFieldsTestMessage::set_s(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.s_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.s)
}
inline std::string* InitializeRequiredFieldsTestMessage::mutable_s() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_s();
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.s)
  return _s;
}
inline const std::string& InitializeRequiredFieldsTestMessage::_internal_s() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.s_.Get();
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_s(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.s_.Set(value, GetArena());
}
inline std::string* InitializeRequiredFieldsTestMessage::_internal_mutable_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.s_.Mutable( GetArena());
}
inline std::string* InitializeRequiredFieldsTestMessage::release_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql_test.InitializeRequiredFieldsTestMessage.s)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.s_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.s_.Set("", GetArena());
  }
  return released;
}
inline void InitializeRequiredFieldsTestMessage::set_allocated_s(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.s_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.s_.IsDefault()) {
    _impl_.s_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.s)
}

// required .googlesql_test.InitializeRequiredFieldsTestMessage.Enum e = 9;
inline bool InitializeRequiredFieldsTestMessage::has_e() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_e() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.e_ = 1;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_Enum InitializeRequiredFieldsTestMessage::e() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.e)
  return _internal_e();
}
inline void InitializeRequiredFieldsTestMessage::set_e(::googlesql_test::InitializeRequiredFieldsTestMessage_Enum value) {
  _internal_set_e(value);
  _impl_._has_bits_[0] |= 0x00002000u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.e)
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_Enum InitializeRequiredFieldsTestMessage::_internal_e() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_Enum>(_impl_.e_);
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_e(::googlesql_test::InitializeRequiredFieldsTestMessage_Enum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::googlesql_test::InitializeRequiredFieldsTestMessage_Enum_IsValid(value));
  _impl_.e_ = value;
}

// required .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage req_msg1 = 10;
inline bool InitializeRequiredFieldsTestMessage::has_req_msg1() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.req_msg1_ != nullptr);
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_req_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.req_msg1_ != nullptr) _impl_.req_msg1_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::_internal_req_msg1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* p = _impl_.req_msg1_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage&>(::googlesql_test::_InitializeRequiredFieldsTestMessage_InnerMessage_default_instance_);
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::req_msg1() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg1)
  return _internal_req_msg1();
}
inline void InitializeRequiredFieldsTestMessage::unsafe_arena_set_allocated_req_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.req_msg1_);
  }
  _impl_.req_msg1_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg1)
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::release_req_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* released = _impl_.req_msg1_;
  _impl_.req_msg1_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::unsafe_arena_release_req_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg1)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* temp = _impl_.req_msg1_;
  _impl_.req_msg1_ = nullptr;
  return temp;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::_internal_mutable_req_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.req_msg1_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>(GetArena());
    _impl_.req_msg1_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(p);
  }
  return _impl_.req_msg1_;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::mutable_req_msg1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _msg = _internal_mutable_req_msg1();
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg1)
  return _msg;
}
inline void InitializeRequiredFieldsTestMessage::set_allocated_req_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.req_msg1_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.req_msg1_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg1)
}

// optional .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage opt_msg1 = 11;
inline bool InitializeRequiredFieldsTestMessage::has_opt_msg1() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.opt_msg1_ != nullptr);
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_opt_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.opt_msg1_ != nullptr) _impl_.opt_msg1_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::_internal_opt_msg1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* p = _impl_.opt_msg1_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage&>(::googlesql_test::_InitializeRequiredFieldsTestMessage_InnerMessage_default_instance_);
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::opt_msg1() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg1)
  return _internal_opt_msg1();
}
inline void InitializeRequiredFieldsTestMessage::unsafe_arena_set_allocated_opt_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.opt_msg1_);
  }
  _impl_.opt_msg1_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg1)
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::release_opt_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* released = _impl_.opt_msg1_;
  _impl_.opt_msg1_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::unsafe_arena_release_opt_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg1)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* temp = _impl_.opt_msg1_;
  _impl_.opt_msg1_ = nullptr;
  return temp;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::_internal_mutable_opt_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.opt_msg1_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>(GetArena());
    _impl_.opt_msg1_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(p);
  }
  return _impl_.opt_msg1_;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::mutable_opt_msg1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _msg = _internal_mutable_opt_msg1();
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg1)
  return _msg;
}
inline void InitializeRequiredFieldsTestMessage::set_allocated_opt_msg1(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.opt_msg1_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.opt_msg1_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg1)
}

// repeated .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage rep_msg1 = 12;
inline int InitializeRequiredFieldsTestMessage::_internal_rep_msg1_size() const {
  return _internal_rep_msg1().size();
}
inline int InitializeRequiredFieldsTestMessage::rep_msg1_size() const {
  return _internal_rep_msg1_size();
}
inline void InitializeRequiredFieldsTestMessage::clear_rep_msg1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rep_msg1_.Clear();
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::mutable_rep_msg1(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg1)
  return _internal_mutable_rep_msg1()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>* InitializeRequiredFieldsTestMessage::mutable_rep_msg1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg1)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rep_msg1();
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::rep_msg1(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg1)
  return _internal_rep_msg1().Get(index);
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::add_rep_msg1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _add = _internal_mutable_rep_msg1()->Add();
  // @@protoc_insertion_point(field_add:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg1)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>& InitializeRequiredFieldsTestMessage::rep_msg1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg1)
  return _internal_rep_msg1();
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>&
InitializeRequiredFieldsTestMessage::_internal_rep_msg1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rep_msg1_;
}
inline ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>*
InitializeRequiredFieldsTestMessage::_internal_mutable_rep_msg1() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rep_msg1_;
}

// required .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage req_msg2 = 13;
inline bool InitializeRequiredFieldsTestMessage::has_req_msg2() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.req_msg2_ != nullptr);
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_req_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.req_msg2_ != nullptr) _impl_.req_msg2_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::_internal_req_msg2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* p = _impl_.req_msg2_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage&>(::googlesql_test::_InitializeRequiredFieldsTestMessage_InnerMessage_default_instance_);
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::req_msg2() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg2)
  return _internal_req_msg2();
}
inline void InitializeRequiredFieldsTestMessage::unsafe_arena_set_allocated_req_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.req_msg2_);
  }
  _impl_.req_msg2_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg2)
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::release_req_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* released = _impl_.req_msg2_;
  _impl_.req_msg2_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::unsafe_arena_release_req_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg2)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* temp = _impl_.req_msg2_;
  _impl_.req_msg2_ = nullptr;
  return temp;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::_internal_mutable_req_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.req_msg2_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>(GetArena());
    _impl_.req_msg2_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(p);
  }
  return _impl_.req_msg2_;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::mutable_req_msg2() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _msg = _internal_mutable_req_msg2();
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg2)
  return _msg;
}
inline void InitializeRequiredFieldsTestMessage::set_allocated_req_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.req_msg2_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.req_msg2_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.req_msg2)
}

// optional .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage opt_msg2 = 14;
inline bool InitializeRequiredFieldsTestMessage::has_opt_msg2() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.opt_msg2_ != nullptr);
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_opt_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.opt_msg2_ != nullptr) _impl_.opt_msg2_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::_internal_opt_msg2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* p = _impl_.opt_msg2_;
  return p != nullptr ? *p : reinterpret_cast<const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage&>(::googlesql_test::_InitializeRequiredFieldsTestMessage_InnerMessage_default_instance_);
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::opt_msg2() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg2)
  return _internal_opt_msg2();
}
inline void InitializeRequiredFieldsTestMessage::unsafe_arena_set_allocated_opt_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.opt_msg2_);
  }
  _impl_.opt_msg2_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg2)
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::release_opt_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* released = _impl_.opt_msg2_;
  _impl_.opt_msg2_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::unsafe_arena_release_opt_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg2)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* temp = _impl_.opt_msg2_;
  _impl_.opt_msg2_ = nullptr;
  return temp;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::_internal_mutable_opt_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.opt_msg2_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>(GetArena());
    _impl_.opt_msg2_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(p);
  }
  return _impl_.opt_msg2_;
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::mutable_opt_msg2() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _msg = _internal_mutable_opt_msg2();
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg2)
  return _msg;
}
inline void InitializeRequiredFieldsTestMessage::set_allocated_opt_msg2(::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.opt_msg2_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.opt_msg2_ = reinterpret_cast<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:googlesql_test.InitializeRequiredFieldsTestMessage.opt_msg2)
}

// repeated .googlesql_test.InitializeRequiredFieldsTestMessage.InnerMessage rep_msg2 = 15;
inline int InitializeRequiredFieldsTestMessage::_internal_rep_msg2_size() const {
  return _internal_rep_msg2().size();
}
inline int InitializeRequiredFieldsTestMessage::rep_msg2_size() const {
  return _internal_rep_msg2_size();
}
inline void InitializeRequiredFieldsTestMessage::clear_rep_msg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rep_msg2_.Clear();
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::mutable_rep_msg2(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg2)
  return _internal_mutable_rep_msg2()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>* InitializeRequiredFieldsTestMessage::mutable_rep_msg2()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rep_msg2();
}
inline const ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage& InitializeRequiredFieldsTestMessage::rep_msg2(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg2)
  return _internal_rep_msg2().Get(index);
}
inline ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* InitializeRequiredFieldsTestMessage::add_rep_msg2() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage* _add = _internal_mutable_rep_msg2()->Add();
  // @@protoc_insertion_point(field_add:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg2)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>& InitializeRequiredFieldsTestMessage::rep_msg2() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql_test.InitializeRequiredFieldsTestMessage.rep_msg2)
  return _internal_rep_msg2();
}
inline const ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>&
InitializeRequiredFieldsTestMessage::_internal_rep_msg2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rep_msg2_;
}
inline ::google::protobuf::RepeatedPtrField<::googlesql_test::InitializeRequiredFieldsTestMessage_InnerMessage>*
InitializeRequiredFieldsTestMessage::_internal_mutable_rep_msg2() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rep_msg2_;
}

// optional int32 opt_val = 16;
inline bool InitializeRequiredFieldsTestMessage::has_opt_val() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void InitializeRequiredFieldsTestMessage::clear_opt_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_val_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline ::int32_t InitializeRequiredFieldsTestMessage::opt_val() const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.opt_val)
  return _internal_opt_val();
}
inline void InitializeRequiredFieldsTestMessage::set_opt_val(::int32_t value) {
  _internal_set_opt_val(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.opt_val)
}
inline ::int32_t InitializeRequiredFieldsTestMessage::_internal_opt_val() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.opt_val_;
}
inline void InitializeRequiredFieldsTestMessage::_internal_set_opt_val(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_val_ = value;
}

// repeated int32 rep_val = 17;
inline int InitializeRequiredFieldsTestMessage::_internal_rep_val_size() const {
  return _internal_rep_val().size();
}
inline int InitializeRequiredFieldsTestMessage::rep_val_size() const {
  return _internal_rep_val_size();
}
inline void InitializeRequiredFieldsTestMessage::clear_rep_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rep_val_.Clear();
}
inline ::int32_t InitializeRequiredFieldsTestMessage::rep_val(int index) const {
  // @@protoc_insertion_point(field_get:googlesql_test.InitializeRequiredFieldsTestMessage.rep_val)
  return _internal_rep_val().Get(index);
}
inline void InitializeRequiredFieldsTestMessage::set_rep_val(int index, ::int32_t value) {
  _internal_mutable_rep_val()->Set(index, value);
  // @@protoc_insertion_point(field_set:googlesql_test.InitializeRequiredFieldsTestMessage.rep_val)
}
inline void InitializeRequiredFieldsTestMessage::add_rep_val(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rep_val()->Add(value);
  // @@protoc_insertion_point(field_add:googlesql_test.InitializeRequiredFieldsTestMessage.rep_val)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& InitializeRequiredFieldsTestMessage::rep_val() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:googlesql_test.InitializeRequiredFieldsTestMessage.rep_val)
  return _internal_rep_val();
}
inline ::google::protobuf::RepeatedField<::int32_t>* InitializeRequiredFieldsTestMessage::mutable_rep_val()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:googlesql_test.InitializeRequiredFieldsTestMessage.rep_val)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rep_val();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
InitializeRequiredFieldsTestMessage::_internal_rep_val() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rep_val_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* InitializeRequiredFieldsTestMessage::_internal_mutable_rep_val() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rep_val_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace googlesql_test


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::googlesql_test::InitializeRequiredFieldsTestMessage_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::googlesql_test::InitializeRequiredFieldsTestMessage_Enum>() {
  return ::googlesql_test::InitializeRequiredFieldsTestMessage_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // googlesql_2fcommon_2finitialize_5frequired_5ffields_5ftest_2eproto_2epb_2eh
