#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_REMOTE_TVF_FACTORY_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_REMOTE_TVF_FACTORY_EXPORT_H

#include "googlesql/public/remote_tvf_factory.h"
// include sources
// include dependencies
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/function/export.inc"
#include "go-googlesql/public/module_details/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
