#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_ASSOCIATIVE_VIEW_INTERNAL_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_BASE_ASSOCIATIVE_VIEW_INTERNAL_EXPORT_H

#include "googlesql/legacy_zetasql/base/associative_view_internal.h"
// include sources
// include dependencies
#include "go-googlesql/legacy_zetasql/base/requires/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/strings/cord/export.inc"

#endif
