#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_PIPE_IF_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_PIPE_IF_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/pipe_if_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/pipe_if_rewriter.cc"
// include dependencies
#include "go-googlesql/analyzer/rewriters/rewrite_subpipeline/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/rewriter_interface/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_builder/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
