#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_FILTER_FIELDS_PATH_VALIDATOR_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_ANALYZER_FILTER_FIELDS_PATH_VALIDATOR_EXPORT_H

#include "googlesql/legacy_zetasql/analyzer/filter_fields_path_validator.h"
// include sources
#include "googlesql/legacy_zetasql/analyzer/filter_fields_path_validator.cc"
// include dependencies
#include "go-googlesql/base/logging/export.inc"
#include "go-googlesql/base/map_util/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
