
#ifndef googlesql_common_match_recognize_nfa_builder_bind_cc
#define googlesql_common_match_recognize_nfa_builder_bind_cc

// switch namespace
#define differential_privacy googlesql_common_match_recognize_nfa_builder_differential_privacy
#define googlesql googlesql_common_match_recognize_nfa_builder_googlesql
#define googlesql_base googlesql_common_match_recognize_nfa_builder_googlesql_base
#define googlesql_bison_parser googlesql_common_match_recognize_nfa_builder_googlesql_bison_parser
#define re2 googlesql_common_match_recognize_nfa_builder_re2
#define AbslInternalSleepFor googlesql_common_match_recognize_nfa_builder_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError googlesql_common_match_recognize_nfa_builder_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield googlesql_common_match_recognize_nfa_builder_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost googlesql_common_match_recognize_nfa_builder_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait googlesql_common_match_recognize_nfa_builder_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything googlesql_common_match_recognize_nfa_builder_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay googlesql_common_match_recognize_nfa_builder_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake googlesql_common_match_recognize_nfa_builder_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin googlesql_common_match_recognize_nfa_builder_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd googlesql_common_match_recognize_nfa_builder_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint googlesql_common_match_recognize_nfa_builder_AbslInternalGetFileMappingHint
#define GoogleSqlalloc googlesql_common_match_recognize_nfa_builder_GoogleSqlalloc
#define GoogleSqlfree googlesql_common_match_recognize_nfa_builder_GoogleSqlfree
#define GoogleSqlrealloc googlesql_common_match_recognize_nfa_builder_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly googlesql_common_match_recognize_nfa_builder_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly googlesql_common_match_recognize_nfa_builder_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests googlesql_common_match_recognize_nfa_builder_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests googlesql_common_match_recognize_nfa_builder_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase googlesql_common_match_recognize_nfa_builder_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer googlesql_common_match_recognize_nfa_builder_GoogleSqlFlexLexer
#define UCaseMap googlesql_common_match_recognize_nfa_builder_UCaseMap

#define GO_EXPORT(def) export_googlesql_common_match_recognize_nfa_builder_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"


// Descriptor table identifiers for googlesql/public/options.proto (see googlesql/public/analyzer amalgamation).
#define googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_googlesql_2fpublic_2foptions_2eproto
#define descriptor_table_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2foptions_2eproto
#define TableStruct_googlesql_2fpublic_2foptions_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2foptions_2eproto
// Descriptor table identifiers for googlesql/public/type.proto (same single-owner TU as options.pb.cc).
#define googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_googlesql_2fpublic_2ftype_2eproto
#define descriptor_table_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2ftype_2eproto
#define TableStruct_googlesql_2fpublic_2ftype_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2ftype_2eproto
// googlesql/public/proto/wire_format_annotation.proto (paired with public/proto/type_annotation in analyzer).
#define googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2fwire_5fformat_5fannotation_2eproto
// googlesql/public/proto/type_annotation.proto (extends google.protobuf.FieldOptions; single-owner TU).
#define googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_descriptor_table_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
#define TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto googlesql_public_analyzer_TableStruct_googlesql_2fpublic_2fproto_2ftype_5fannotation_2eproto
// include headers
//#define private public
#include "googlesql/common/match_recognize/nfa_builder.h"
//#undef private

// include sources
#include "googlesql/common/match_recognize/nfa_builder.cc"

// include dependencies
#include "go-zetasql/common/match_recognize/epsilon_remover/export.inc"
#include "go-zetasql/common/match_recognize/nfa/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/coercer/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast_enums_cc_proto/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/time/time/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* googlesql_common_match_recognize_nfa_builder_bind_cc */
