
#ifndef base_statusor_bind_cc
#define base_statusor_bind_cc

// switch namespace
#define differential_privacy base_statusor_differential_privacy
#define googlesql base_statusor_googlesql
#define googlesql_base base_statusor_googlesql_base
#define googlesql_bison_parser base_statusor_googlesql_bison_parser
#define re2 base_statusor_re2
#define AbslInternalSleepFor base_statusor_AbslInternalSleepFor
#define AbslInternalReportFatalUsageError base_statusor_AbslInternalReportFatalUsageError
#define AbslInternalMutexYield base_statusor_AbslInternalMutexYield
#define AbslInternalPerThreadSemPost base_statusor_AbslInternalPerThreadSemPost
#define AbslInternalPerThreadSemWait base_statusor_AbslInternalPerThreadSemWait
#define AbslContainerInternalSampleEverything base_statusor_AbslContainerInternalSampleEverything
#define AbslInternalSpinLockDelay base_statusor_AbslInternalSpinLockDelay
#define AbslInternalSpinLockWake base_statusor_AbslInternalSpinLockWake
#define AbslInternalAnnotateIgnoreReadsBegin base_statusor_AbslInternalAnnotateIgnoreReadsBegin
#define AbslInternalAnnotateIgnoreReadsEnd base_statusor_AbslInternalAnnotateIgnoreReadsEnd
#define AbslInternalGetFileMappingHint base_statusor_AbslInternalGetFileMappingHint
#define GoogleSqlalloc base_statusor_GoogleSqlalloc
#define GoogleSqlfree base_statusor_GoogleSqlfree
#define GoogleSqlrealloc base_statusor_GoogleSqlrealloc
#define FLAGS_nooutput_asc_explicitly base_statusor_FLAGS_nooutput_asc_explicitly
#define FLAGS_nogooglesql_use_customized_flex_istream base_statusor_FLAGS_nogooglesql_use_customized_flex_istream
#define FLAGS_output_asc_explicitly base_statusor_FLAGS_output_asc_explicitly
#define FLAGS_googlesql_use_customized_flex_istream base_statusor_FLAGS_googlesql_use_customized_flex_istream
#define FLAGS_googlesql_type_factory_nesting_depth_limit base_statusor_FLAGS_googlesql_type_factory_nesting_depth_limit
#define FLAGS_googlesql_read_proto_field_optimized_path base_statusor_FLAGS_googlesql_read_proto_field_optimized_path
#define FLAGS_googlesql_format_max_output_width base_statusor_FLAGS_googlesql_format_max_output_width
#define FLAGS_googlesql_min_length_required_for_edit_distance base_statusor_FLAGS_googlesql_min_length_required_for_edit_distance
#define FLAGS_googlesql_simple_iterator_call_time_now_rows_period base_statusor_FLAGS_googlesql_simple_iterator_call_time_now_rows_period
#define FLAGS_nogooglesql_type_factory_nesting_depth_limit base_statusor_FLAGS_nogooglesql_type_factory_nesting_depth_limit
#define FLAGS_nogooglesql_read_proto_field_optimized_path base_statusor_FLAGS_nogooglesql_read_proto_field_optimized_path
#define FLAGS_nogooglesql_format_max_output_width base_statusor_FLAGS_nogooglesql_format_max_output_width
#define FLAGS_nogooglesql_min_length_required_for_edit_distance base_statusor_FLAGS_nogooglesql_min_length_required_for_edit_distance
#define FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period base_statusor_FLAGS_nogooglesql_simple_iterator_call_time_now_rows_period
#define FLAGS_googlesql_enough_stack_bytes base_statusor_FLAGS_googlesql_enough_stack_bytes
#define FLAGS_nogooglesql_enough_stack_bytes base_statusor_FLAGS_nogooglesql_enough_stack_bytes
#define FLAGS_googlesql_canonicalize_signed_zero_to_string base_statusor_FLAGS_googlesql_canonicalize_signed_zero_to_string
#define FLAGS_nogooglesql_canonicalize_signed_zero_to_string base_statusor_FLAGS_nogooglesql_canonicalize_signed_zero_to_string
#define FLAGS_googlesql_default_error_message_stability base_statusor_FLAGS_googlesql_default_error_message_stability
#define FLAGS_nogooglesql_default_error_message_stability base_statusor_FLAGS_nogooglesql_default_error_message_stability
#define FLAGS_googlesql_redact_error_messages_for_tests base_statusor_FLAGS_googlesql_redact_error_messages_for_tests
#define FLAGS_nogooglesql_redact_error_messages_for_tests base_statusor_FLAGS_nogooglesql_redact_error_messages_for_tests
#define GoogleSqlFlexTokenizerBase base_statusor_GoogleSqlFlexTokenizerBase
#define GoogleSqlFlexLexer base_statusor_GoogleSqlFlexLexer
#define UCaseMap base_statusor_UCaseMap

#define GO_EXPORT(def) export_base_statusor_ ## def
#define U_ICU_ENTRY_POINT_RENAME(x) GO_EXPORT(x)

// bridge_cc.inc uses GoSlice; bridge.inc includes _cgo_export.h again for exported symbols.
#include "_cgo_export.h"

// include headers
//#define private public
#include "base/statusor.h"
//#undef private

// include sources

// include dependencies
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/status/statusor/export.inc"

#include "bridge.h"

#include "bridge_cc.inc"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "bridge.inc"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* base_statusor_bind_cc */
