#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_STRING_WITH_COLLATION_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_FUNCTIONS_STRING_WITH_COLLATION_EXPORT_H

#include "zetasql/public/functions/string_with_collation.h"
// include sources
#include "zetasql/public/functions/string_with_collation.cc"
// include dependencies
#include "go-zetasql/public/functions/like/export.inc"
#include "go-zetasql/public/functions/string/export.inc"
#include "go-zetasql/public/functions/util/export.inc"
#include "go-zetasql/base/check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/common/utf_util/export.inc"
#include "go-zetasql/public/collator_lite/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-re2/re2/export.inc"

#endif
