#ifndef INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_TEMPLATED_FUNCTION_CALL_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_ANALYZER_REWRITERS_TEMPLATED_FUNCTION_CALL_REWRITER_EXPORT_H

#include "googlesql/analyzer/rewriters/templated_function_call_rewriter.h"
// include sources
#include "googlesql/analyzer/rewriters/templated_function_call_rewriter.cc"
// include dependencies
#include "go-googlesql/analyzer/rewriters/rewriter_relevance_checker/export.inc"
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/catalog/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/templated_sql_function/export.inc"
#include "go-googlesql/public/templated_sql_tvf_no_resolver/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/column_factory/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast_rewrite_visitor/export.inc"
#include "go-googlesql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-googlesql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
