#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_MULTIPRECISION_INT_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_MULTIPRECISION_INT_EXPORT_H

#include "googlesql/common/multiprecision_int.h"
#include "googlesql/common/multiprecision_int_impl.h"
// include sources
#include "googlesql/common/multiprecision_int.cc"
#include "googlesql/common/multiprecision_int_impl.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/bits/export.inc"
#include "go-googlesql/base/endian/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/numeric/bits/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/compare/export.inc"
#include "go-absl/types/span/export.inc"

#endif
