#ifndef INTERNAL_CCALL_GO_ALGORITHMS_GO_INTERNAL_BOUNDED_MEAN_CI_EXPORT_H
#define INTERNAL_CCALL_GO_ALGORITHMS_GO_INTERNAL_BOUNDED_MEAN_CI_EXPORT_H

#include "algorithms/internal/bounded-mean-ci.h"
// include sources
// include dependencies
#include "go-algorithms/numerical-mechanisms/export.inc"
#include "go-algorithms/util/export.inc"
#include "go-proto/confidence_interval_cc_proto/export.inc"

#endif
