#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TOKENIZER_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PARSER_TOKENIZER_EXPORT_H

#include "googlesql/parser/tokenizer.h"
// include sources
#include "googlesql/parser/tokenizer.cc"
// include dependencies
#include "go-googlesql/parser/tm_lexer/export.inc"
#include "go-googlesql/base/check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/parse_location/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
