#ifndef INTERNAL_CCALL_GO_GOOGLESQL_COMMON_UNICODE_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_COMMON_UNICODE_UTILS_EXPORT_H

#include "googlesql/common/unicode_utils.h"
// include sources
#ifndef GOOGLESQL_OMIT_UNICODE_UTILS_CC
#include "googlesql/common/unicode_utils.cc"
#endif
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-absl/algorithm/container/export.inc"
#include "go-absl/base/nullability/export.inc"
#include "go-absl/flags/flag/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-icu/icu/export.inc"

#endif
