#ifndef INTERNAL_CCALL_GO_ABSL_SYNCHRONIZATION_THREAD_POOL_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_SYNCHRONIZATION_THREAD_POOL_EXPORT_H

#include "absl/synchronization/internal/thread_pool.h"
// include sources
// include dependencies
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/functional/any_invocable/export.inc"

#endif
