#ifndef INTERNAL_CCALL_GO_ZETASQL_PROTO_PLACEHOLDER_DESCRIPTOR_CC_PROTO_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PROTO_PLACEHOLDER_DESCRIPTOR_CC_PROTO_EXPORT_H

#include "zetasql/proto/placeholder_descriptor.pb.h"
// include sources
#define schemas zetasql_proto_placeholder_descriptor_cc_proto_schemas
#define file_default_instances zetasql_proto_placeholder_descriptor_cc_proto_file_default_instances
#include "zetasql/proto/placeholder_descriptor.pb.cc"
#undef file_default_instances
#undef schemas
// include dependencies
#include "go-protobuf/protobuf/export.inc"

#endif
