#ifndef INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_AGGREGATION_THRESHOLD_REWRITER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_ANALYZER_REWRITERS_AGGREGATION_THRESHOLD_REWRITER_EXPORT_H

#include "zetasql/analyzer/rewriters/aggregation_threshold_rewriter.h"
// include sources
#include "zetasql/analyzer/rewriters/aggregation_threshold_rewriter.cc"
// include dependencies
#include "go-zetasql/analyzer/rewriters/anonymization_helper/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/public/analyzer_options/export.inc"
#include "go-zetasql/public/catalog/export.inc"
#include "go-zetasql/public/rewriter_interface/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/column_factory/export.inc"
#include "go-zetasql/resolved_ast/rewrite_utils/export.inc"
#include "go-absl/status/statusor/export.inc"

#endif
