#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_VLOG_CONFIG_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_VLOG_CONFIG_EXPORT_H

#include "absl/log/internal/vlog_config.h"
// include sources
#include "absl/log/internal/vlog_config.cc"
// include dependencies
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/log/go_internal/fnmatch/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
