#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_COMMON_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_REFERENCE_IMPL_COMMON_EXPORT_H

#include "googlesql/legacy_zetasql/reference_impl/common.h"
#include "googlesql/legacy_zetasql/reference_impl/variable_id.h"
// include sources
#include "googlesql/legacy_zetasql/reference_impl/common.cc"
#include "googlesql/legacy_zetasql/reference_impl/variable_id.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/collator_lite/export.inc"
#include "go-googlesql/public/type/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-googlesql/public/value/export.inc"
#include "go-googlesql/resolved_ast/resolved_ast/export.inc"
#include "go-googlesql/resolved_ast/serialization_cc_proto/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
