#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PARSER_TM_LEXER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_PARSER_TM_LEXER_EXPORT_H

#include "googlesql/legacy_zetasql/parser/tm_lexer.h"
#include "googlesql/legacy_zetasql/parser/tm_token.h"
// include sources
#include "googlesql/legacy_zetasql/parser/tm_lexer.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/parser/bison_parser_mode/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/public/parse_location/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/strings/strings/export.inc"

#endif
