#ifndef INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_PROTO_HELPER_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_LEGACY_ZETASQL_COMMON_PROTO_HELPER_EXPORT_H

#include "googlesql/legacy_zetasql/common/proto_helper.h"
// include sources
#include "googlesql/legacy_zetasql/common/proto_helper.cc"
// include dependencies
#include "go-zetasql/legacy_zetasql/common/errors/export.inc"
#include "go-zetasql/legacy_zetasql/common/thread_stack/export.inc"
#include "go-zetasql/base/base/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/ret_check/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/optional/export.inc"

#endif
