#ifndef INTERNAL_CCALL_GO_ZETASQL_PUBLIC_MODULE_DETAILS_EXPORT_H
#define INTERNAL_CCALL_GO_ZETASQL_PUBLIC_MODULE_DETAILS_EXPORT_H

#include "googlesql/public/module_details.h"
// include sources
#include "googlesql/public/module_details.cc"
// include dependencies
#include "go-zetasql/public/constant_evaluator/export.inc"
#include "go-zetasql/public/options_cc_proto/export.inc"
#include "go-zetasql/public/value/export.inc"
#include "go-zetasql/base/map_util/export.inc"
#include "go-zetasql/base/status/export.inc"
#include "go-zetasql/base/strings/export.inc"
#include "go-zetasql/common/errors/export.inc"
#include "go-zetasql/common/resolution_scope/export.inc"
#include "go-zetasql/proto/module_options_cc_proto/export.inc"
#include "go-zetasql/public/types/types/export.inc"
#include "go-zetasql/resolved_ast/resolved_ast/export.inc"
#include "go-zetasql/resolved_ast/resolved_node_kind_cc_proto/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/log/log/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
