#ifndef INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_LIKE_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_PUBLIC_FUNCTIONS_LIKE_EXPORT_H

#include "googlesql/public/functions/like.h"
// include sources
#include "googlesql/public/functions/like.cc"
// include dependencies
#include "go-googlesql/base/base/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/type_cc_proto/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/memory/memory/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-re2/re2/export.inc"

#endif
