#ifndef INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_OPTIONS_UTILS_EXPORT_H
#define INTERNAL_CCALL_GO_GOOGLESQL_LEGACY_ZETASQL_COMMON_OPTIONS_UTILS_EXPORT_H

#include "googlesql/legacy_zetasql/common/options_utils.h"
// include sources
#include "googlesql/legacy_zetasql/common/options_utils.cc"
// include dependencies
#include "go-googlesql/base/ret_check/export.inc"
#include "go-googlesql/base/status/export.inc"
#include "go-googlesql/public/analyzer_options/export.inc"
#include "go-googlesql/public/evaluator/export.inc"
#include "go-googlesql/public/language_options/export.inc"
#include "go-googlesql/public/options_cc_proto/export.inc"
#include "go-googlesql/public/parse_helpers/export.inc"
#include "go-googlesql/public/strings/export.inc"
#include "go-absl/container/btree/export.inc"
#include "go-absl/container/flat_hash_map/export.inc"
#include "go-absl/container/flat_hash_set/export.inc"
#include "go-absl/status/status/export.inc"
#include "go-absl/status/statusor/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/types/span/export.inc"

#endif
