#ifndef INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_LOG_SINK_SET_EXPORT_H
#define INTERNAL_CCALL_GO_ABSL_LOG_GO_INTERNAL_LOG_SINK_SET_EXPORT_H

#include "absl/log/internal/log_sink_set.h"
// include sources
// include dependencies
#include "go-absl/log/go_internal/config/export.inc"
#include "go-absl/log/go_internal/globals/export.inc"
#include "go-absl/base/base/export.inc"
#include "go-absl/base/config/export.inc"
#include "go-absl/base/core_headers/export.inc"
#include "go-absl/base/log_severity/export.inc"
#include "go-absl/base/no_destructor/export.inc"
#include "go-absl/base/raw_logging_internal/export.inc"
#include "go-absl/cleanup/cleanup/export.inc"
#include "go-absl/log/globals/export.inc"
#include "go-absl/log/log_entry/export.inc"
#include "go-absl/log/log_sink/export.inc"
#include "go-absl/strings/strings/export.inc"
#include "go-absl/synchronization/synchronization/export.inc"
#include "go-absl/types/span/export.inc"

#endif
